module.exports = [{q:'OSI模型共分为几层？', level:'基础', options:['5层','6层','7层','8层'], answer:2, explain:'OSI模型分为7层：物理层到应用层'},
{q:'TCP建立连接需要几次握手？', level:'基础', options:['1次','2次','3次','4次'], answer:2, explain:'TCP通过三次握手建立可靠连接'},
{q:'HTTP状态码200表示什么？', level:'基础', options:['重定向','请求成功','客户端错误','服务器错误'], answer:1, explain:'200 OK表示请求已成功处理'},
{q:'DNS的主要作用是什么？', level:'基础', options:['加密传输','域名解析','路由选择','负载均衡'], answer:1, explain:'DNS将域名解析为IP地址'},
{q:'DHCP协议用于什么？', level:'基础', options:['动态分配IP','远程登录','文件传输','邮件发送'], answer:0, explain:'DHCP动态为主机分配IP地址等参数'},
{q:'VLAN的主要作用是什么？', level:'基础', options:['加密数据','划分广播域','路由转发','地址转换'], answer:1, explain:'VLAN通过逻辑划分隔离广播域'},
{q:'ICMP协议常用于哪个命令？', level:'基础', options:['ssh','ping','ftp','telnet'], answer:1, explain:'ping命令使用ICMP回显请求/应答'},
{q:'HTTPS默认使用哪个端口？', level:'基础', options:['21','22','80','443'], answer:3, explain:'HTTPS默认端口为443'},
{q:'SSH默认使用哪个端口？', level:'基础', options:['21','22','23','80'], answer:1, explain:'SSH默认端口为22'},
{q:'ARP协议的作用是什么？', level:'基础', options:['IP转MAC','MAC转IP','域名转IP','IP转域名'], answer:0, explain:'ARP通过IP地址解析MAC地址'},
{q:'HTTP默认端口是多少？', level:'基础', options:['21','22','80','443'], answer:2, explain:'HTTP默认端口为80'},
{q:'FTP默认使用哪个端口？', level:'基础', options:['20和21','22和23','80和443','53和67'], answer:0, explain:'FTP使用21(控制)和20(数据)端口'},
{q:'Telnet默认端口是多少？', level:'基础', options:['21','22','23','25'], answer:2, explain:'Telnet默认端口为23'},
{q:'SMTP默认端口是多少？', level:'基础', options:['23','25','53','110'], answer:1, explain:'SMTP默认端口为25'},
{q:'DNS默认端口是多少？', level:'基础', options:['25','53','80','110'], answer:1, explain:'DNS默认使用53端口(UDP为主)'},
{q:'POP3默认端口是多少？', level:'基础', options:['25','53','110','143'], answer:2, explain:'POP3默认端口为110'},
{q:'STP协议的主要作用是什么？', level:'基础', options:['防止路由环路','防止交换环路','加密传输','地址转换'], answer:1, explain:'STP生成树协议防止二层交换环路'},
{q:'NAT的主要作用是什么？', level:'基础', options:['加密数据','网络地址转换','域名解析','负载均衡'], answer:1, explain:'NAT实现私网与公网地址转换'},
{q:'CDN的全称是什么？', level:'基础', options:['内容分发网络','公共数据网','综合数字网','电路交换网'], answer:0, explain:'CDN是Content Delivery Network'},
{q:'DMZ区域的作用是什么？', level:'基础', options:['内部办公区','隔离公共服务区','数据库区','开发测试区'], answer:1, explain:'DMZ放置对外提供服务的服务器'},
{q:'SNMP协议用于什么？', level:'基础', options:['文件传输','网络管理','邮件发送','域名解析'], answer:1, explain:'SNMP是简单网络管理协议'},
{q:'NTP协议用于什么？', level:'基础', options:['时间同步','文件传输','远程登录','域名解析'], answer:0, explain:'NTP实现网络时间同步'},
{q:'BGP属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','外部网关'], answer:3, explain:'BGP是外部网关协议(EGP)'},
{q:'OSPF属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','混合协议'], answer:1, explain:'OSPF是链路状态路由协议'},
{q:'RIP属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','外部网关'], answer:0, explain:'RIP是距离矢量路由协议'},
{q:'TLS协议位于OSI哪一层？', level:'基础', options:['网络层','传输层','会话层','表示层'], answer:3, explain:'TLS工作在表示层，对应用层数据加密'},
{q:'UDP协议相对于TCP的特点是？', level:'基础', options:['可靠传输','面向连接','无连接低开销','流量控制'], answer:2, explain:'UDP是无连接协议，开销小但不可靠'},
{q:'TCP协议相对于UDP的特点是？', level:'基础', options:['无连接','不可靠','可靠有序','低延迟'], answer:2, explain:'TCP提供可靠、有序、重传的传输'},
{q:'子网掩码255.255.255.0对应CIDR前缀是？', level:'基础', options:['/8','/16','/24','/32'], answer:2, explain:'255.255.255.0对应/24，前24位网络位'},
{q:'CIDR前缀/16对应子网掩码是？', level:'基础', options:['255.0.0.0','255.255.0.0','255.255.255.0','255.255.255.255'], answer:1, explain:'/16对应255.255.0.0'},
{q:'WiFi加密协议WPA2的加密算法是？', level:'基础', options:['WEP','TKIP','CCMP(AES)','DES'], answer:2, explain:'WPA2使用CCMP即AES加密算法'},
{q:'代理服务器的主要作用不包括？', level:'基础', options:['访问控制','缓存加速','加密用户数据','隐藏内部地址'], answer:2, explain:'代理不直接加密用户原始数据'},
{q:'IDS的全称是什么？', level:'基础', options:['入侵检测系统','入侵防御系统','集成开发系统','内部域名系统'], answer:0, explain:'IDS是Intrusion Detection System'},
{q:'VPN的主要作用是什么？', level:'基础', options:['加速网络','建立安全加密隧道','域名解析','负载均衡'], answer:1, explain:'VPN在公网建立加密通信隧道'},
{q:'IMAP默认端口是多少？', level:'基础', options:['25','110','143','993'], answer:2, explain:'IMAP默认端口为143'},
{q:'MAC地址长度是多少位？', level:'基础', options:['32位','48位','64位','128位'], answer:1, explain:'MAC地址为48位(6字节)十六进制表示'},
{q:'IPv4地址长度是多少位？', level:'基础', options:['32位','48位','64位','128位'], answer:0, explain:'IPv4地址为32位二进制'},
{q:'IPv6地址长度是多少位？', level:'基础', options:['32位','48位','64位','128位'], answer:3, explain:'IPv6地址为128位二进制'},
{q:'netstat命令中查看TCP连接的参数是？', level:'基础', options:['-a','-t','-u','-n'], answer:1, explain:'netstat -t显示TCP连接'},
{q:'ss命令的作用是？', level:'基础', options:['查看进程','查看网络套接字','查看内存','查看磁盘'], answer:1, explain:'ss比netstat更高效地查看套接字'},
{q:'lsof -i命令的作用是？', level:'基础', options:['查看打开文件','查看监听网络的进程','查看用户登录','查看系统负载'], answer:1, explain:'lsof -i列出打开网络套接字的进程'},
{q:'tcpdump抓包的作用是？', level:'基础', options:['修改报文','捕获和分析网络报文','发送报文','路由转发'], answer:1, explain:'tcpdump用于抓取和分析网络数据包'},
{q:'L4负载均衡是基于哪层信息？', level:'基础', options:['MAC层','IP层','传输层端口','应用层内容'], answer:2, explain:'四层负载基于IP+端口进行分发'},
{q:'L7负载均衡是基于哪层信息？', level:'基础', options:['MAC层','IP层','传输层','应用层内容'], answer:3, explain:'七层负载基于URL/HTTP头等应用信息'},
{q:'WAF的全称是什么？', level:'基础', options:['Web应用防火墙','广域防火墙','无线接入防火墙','Web访问功能'], answer:0, explain:'WAF是Web Application Firewall'},
{q:'ACL的全称是什么？', level:'基础', options:['访问控制列表','应用控制层','自动配置列表','接入认证层'], answer:0, explain:'ACL是Access Control List'},
{q:'QoS的主要作用是什么？', level:'基础', options:['加密数据','服务质量保证','地址转换','域名解析'], answer:1, explain:'QoS为特定流量提供服务质量保障'},
{q:'MPLS的标签长度是多少？', level:'基础', options:['20位','32位','48位','64位'], answer:1, explain:'MPLS标签32位，含20位标签值等字段'},
{q:'VXLAN的VNI标识符长度是？', level:'基础', options:['12位','16位','24位','32位'], answer:2, explain:'VXLAN网络标识符VNI为24位'},
{q:'SDN的核心思想是什么？', level:'基础', options:['控制与转发分离','硬件加速','加密传输','分布式存储'], answer:0, explain:'SDN将控制平面与数据平面分离'},
{q:'VRRP协议的作用是什么？', level:'基础', options:['网关冗余','链路聚合','路由计算','域名解析'], answer:0, explain:'VRRP实现默认网关的冗余备份'},
{q:'HSRP是哪个厂商的协议？', level:'基础', options:['华为','Cisco','H3C','Juniper'], answer:1, explain:'HSRP是Cisco私有热备份路由协议'},
{q:'LACP协议的作用是什么？', level:'基础', options:['网关冗余','链路聚合控制','域名解析','加密传输'], answer:1, explain:'LACP是链路聚合控制协议标准'},
{q:'SLAAC是哪个协议的功能？', level:'基础', options:['IPv4','IPv6','MPLS','BGP'], answer:1, explain:'SLAAC是IPv6无状态地址自动配置'},
{q:'DHCPv6的客户端端口是？', level:'基础', options:['546','547','67','68'], answer:0, explain:'DHCPv6客户端用546，服务器547'},
{q:'FTP主动模式下服务器连接的端口是？', level:'基础', options:['20','21','随机高端口','1024以下'], answer:0, explain:'主动模式服务器用20端口发起数据连接'},
{q:'FTP被动模式下客户端连接的端口是？', level:'基础', options:['20','21','服务器指定高端口','53'], answer:2, explain:'被动模式客户端连接服务器指定的数据端口'},
{q:'traceroute命令使用什么协议？', level:'基础', options:['TCP','UDP(默认)','ICMP','SCTP'], answer:1, explain:'Linux traceroute默认用UDP，Windows用ICMP'},
{q:'mtr命令结合了哪两个命令？', level:'基础', options:['ping和ssh','ping和traceroute','netstat和ss','ftp和sftp'], answer:1, explain:'mtr结合ping与traceroute功能'},
{q:'组播地址的D类地址范围是？', level:'基础', options:['10.0.0.0/8','172.16.0.0/12','224.0.0.0/4','192.168.0.0/16'], answer:2, explain:'D类组播地址224.0.0.0~239.255.255.255'},
{q:'私网地址192.168.0.0的CIDR范围是？', level:'基础', options:['/8','/12','/16','/24'], answer:2, explain:'192.168.0.0/16是C类私网地址段'},
{q:'私网地址172.16.0.0的CIDR范围是？', level:'基础', options:['/8','/12','/16','/24'], answer:1, explain:'172.16.0.0/12是B类私网地址段'},
{q:'私网地址10.0.0.0的CIDR范围是？', level:'基础', options:['/8','/12','/16','/24'], answer:0, explain:'10.0.0.0/8是A类私网地址段'},
{q:'HTTP状态码301表示什么？', level:'基础', options:['永久重定向','临时重定向','未修改','请求错误'], answer:0, explain:'301 Moved Permanently永久重定向'},
{q:'HTTP状态码404表示什么？', level:'基础', options:['未授权','禁止访问','未找到资源','服务器错误'], answer:2, explain:'404 Not Found请求的资源不存在'},
{q:'HTTP状态码500表示什么？', level:'基础', options:['成功','重定向','客户端错误','服务器内部错误'], answer:3, explain:'500 Internal Server Error服务器内部错误'},
{q:'HTTP状态码302表示什么？', level:'基础', options:['永久重定向','临时重定向','未修改','禁止访问'], answer:1, explain:'302 Found表示临时重定向'},
{q:'HTTP状态码403表示什么？', level:'基础', options:['未授权','禁止访问','未找到','超时'], answer:1, explain:'403 Forbidden服务器拒绝访问'},
{q:'HTTP状态码401表示什么？', level:'基础', options:['未授权需要认证','禁止访问','未找到','请求太大'], answer:0, explain:'401 Unauthorized需要身份认证'},
{q:'IS-IS属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','外部网关'], answer:1, explain:'IS-IS是链路状态IGP路由协议'},
{q:'Diameter协议主要用于什么场景？', level:'基础', options:['网页浏览','AAA认证','文件传输','邮件发送'], answer:1, explain:'Diameter是下一代AAA认证协议'},
{q:'SIP协议主要用于什么？', level:'基础', options:['路由协议','VoIP会话控制','域名解析','文件传输'], answer:1, explain:'SIP是会话发起协议，用于VoIP'},
{q:'PCRF主要应用于哪个领域？', level:'基础', options:['数据中心','移动通信LTE/EPC','企业内网','校园网'], answer:1, explain:'PCRF是LTE/EPC核心网策略计费控制单元'},
{q:'TCP关闭连接需要几次挥手？', level:'基础', options:['2次','3次','4次','5次'], answer:2, explain:'TCP通过四次挥手断开连接'},
{q:'IPsec AH协议提供什么功能？', level:'基础', options:['只加密不认证','只认证完整性','加密+认证','地址转换'], answer:1, explain:'AH提供认证和完整性，不加密'},
{q:'IPsec ESP协议默认提供什么？', level:'基础', options:['只加密','只认证','加密+认证','只压缩'], answer:2, explain:'ESP默认提供加密和认证完整性'},
{q:'SYN flood攻击利用了TCP什么机制？', level:'进阶', options:['三次握手','四次挥手','滑动窗口','拥塞控制'], answer:0, explain:'SYN flood滥用半连接队列资源耗尽服务器'},
{q:'子网192.168.1.0/27的可用主机数是？', level:'进阶', options:['30','32','62','64'], answer:0, explain:'/27有5主机位，2^5-2=30个可用主机'},
{q:'10.0.0.0/22每个子网可用主机数是？', level:'进阶', options:['510','1022','2046','4094'], answer:1, explain:'32-22=10主机位，2^10-2=1022'},
{q:'C类地址划分子网需要4个子网，子网掩码是？', level:'进阶', options:['255.255.255.128','255.255.255.192','255.255.255.224','255.255.255.240'], answer:1, explain:'4子网需借2位，/26即255.255.255.192'},
{q:'需要至少100台主机的子网，最小CIDR前缀是？', level:'进阶', options:['/24','/25','/26','/27'], answer:1, explain:'2^7-2=126≥100，32-7=25，即/25'},
{q:'DNS递归查询与迭代查询的区别是？', level:'进阶', options:['递归客户端请求根服务器','递归服务器替客户端完成查询','迭代必须缓存','迭代更快'], answer:1, explain:'递归DNS服务器代客户端完成完整查询链'},
{q:'DHCP Discover报文采用什么方式发送？', level:'进阶', options:['单播','广播','组播','任播'], answer:1, explain:'客户端无IP，发送255.255.255.255广播'},
{q:'STP中根网桥选举依据是？', level:'进阶', options:['最大MAC','最小MAC+最小优先级','最大优先级','接口带宽'], answer:1, explain:'先比桥优先级(默认32768)再比MAC小者为根'},
{q:'STP中指定端口选举依据是？', level:'进阶', options:['端口ID最小','到根桥开销最小','端口速率最快','MAC最小'], answer:1, explain:'先比到根路径开销，再对比端桥ID、端口ID'},
{q:'标准NAPT转换中，内部地址映射依据是？', level:'进阶', options:['仅IP','IP+端口','仅端口','MAC+IP'], answer:1, explain:'NAPT通过源IP+源端口映射到公网地址端口'},
{q:'正向代理与反向代理的区别是？', level:'进阶', options:['正向代理服务端用','反向代理代表客户端访问','正向代理代表客户端访问','反向代理只能缓存'], answer:2, explain:'正向代理替客户端访问，反向代理替服务器接收'},
{q:'IPsec两种模式区别是？', level:'进阶', options:['传输模式只加密上层数据','隧道模式只认证','传输模式封装整个IP','隧道模式只加密TCP'], answer:0, explain:'传输模式只加密IP上层，隧道模式封装整个IP'},
{q:'SNMPv3相比v2c新增了什么？', level:'进阶', options:['GetBulk操作','Inform消息','认证和加密','视图访问控制'], answer:2, explain:'SNMPv3新增USM安全模型，支持认证加密'},
{q:'BGP建立邻居使用的端口是？', level:'进阶', options:['520','179','161','1701'], answer:1, explain:'BGP使用TCP 179端口建立邻居'},
{q:'OSPF的DR/BDR选举在什么网络类型进行？', level:'进阶', options:['点到点','广播/NBMA','点到多点','虚链路'], answer:1, explain:'广播和NBMA网络才选举DR和BDR减少邻接'},
{q:'OSPF区域0的作用是？', level:'进阶', options:['普通区域','骨干区域所有区域必须连接','Stub区域','NSSA区域'], answer:1, explain:'OSPF骨干区域Area 0，其他区域必须与之连接'},
{q:'TLS握手过程中，Pre-Master Secret谁生成？', level:'进阶', options:['客户端','服务器','双方各一半','CA生成'], answer:0, explain:'客户端生成Pre-Master并用服务器公钥加密发送'},
{q:'HTTP/2多路复用的作用是？', level:'进阶', options:['加密数据','同一连接并发多个请求响应','压缩头部','服务器推送'], answer:1, explain:'二进制帧实现单TCP连接上多路流并发'},
{q:'TCP拥塞控制慢启动阈值ssthresh的作用是？', level:'进阶', options:['低于阈值线性增长','高于阈值指数增长','低于阈值指数增长','固定拥塞窗口'], answer:2, explain:'cwnd<ssthresh指数增长(慢启动)，之后线性(拥塞避免)'},
{q:'netstat -anp中p参数的作用是？', level:'进阶', options:['显示端口号','显示程序名/PID','禁用DNS解析','显示UDP'], answer:1, explain:'-p显示使用该套接字的进程名和PID'},
{q:'ss -s命令的作用是？', level:'进阶', options:['显示TCP socket统计汇总','显示UDP连接','显示程序名','显示路由表'], answer:0, explain:'ss -s输出套接字使用统计摘要'},
{q:'lsof -i:80的作用是？', level:'进阶', options:['查看80端口进程','查看80进程文件','查看端口80硬件','查看80用户'], answer:0, explain:'列出所有监听或使用80端口的进程'},
{q:'tcpdump -i eth0 host 192.168.1.1捕获的是？', level:'进阶', options:['仅源IP是192.168.1.1','仅目的IP是192.168.1.1','源或目的IP是192.168.1.1','仅MAC匹配'], answer:2, explain:'host匹配源或目的IP地址的报文'},
{q:'FTP被动模式相对于主动模式的优势是？', level:'进阶', options:['传输更快','客户端在NAT后更容易连接','更安全','占用端口更少'], answer:1, explain:'被动模式客户端发起数据连接，适合客户端在NAT后'},
{q:'L4与L7负载均衡相比，L4特点是？', level:'进阶', options:['能按URL分发','性能高开销小','能做会话保持cookie','能修改HTTP头'], answer:1, explain:'四层仅处理到传输层，处理速度快开销低'},
{q:'WAF能防护的攻击是？', level:'进阶', options:['DDoS流量型','SQL注入/XSS等应用层','物理层攻击','电源故障'], answer:1, explain:'WAF主要防护SQL注入、XSS等Web应用攻击'},
{q:'VXLAN相比VLAN的主要优势是？', level:'进阶', options:['速度更快','VNI数量远超4096支持多租户','更安全','需要更少设备'], answer:1, explain:'24位VNI支持16M租户，解决VLAN 4096限制'},
{q:'SDN OpenFlow协议作用是？', level:'进阶', options:['交换机内部通信','控制器与交换机间控制信令','服务器间数据','管理配置'], answer:1, explain:'OpenFlow是SDN控制器与转发设备间的标准接口'},
{q:'QoS中DSCP位于报文什么位置？', level:'进阶', options:['以太网帧头','IP报文头部ToS字段','TCP头部','UDP头部'], answer:1, explain:'DSCP占用IPv4 ToS/IPv6 TC字段的前6位'},
{q:'MPLS标签栈中S位为1表示？', level:'进阶', options:['栈顶标签','栈底标签','中间标签','无效标签'], answer:1, explain:'S=1表明这是标签栈中最后一个(栈底)标签'},
{q:'组播PIM-SM模式的特点是？', level:'进阶', options:['推模式主动广播','拉模式按需加入，适合稀疏组','仅本地有效','需要静态RP'], answer:1, explain:'PIM-SM稀疏模式使用RP，接收者按需Join'},
{q:'IPv6 SLAAC获取地址后，如何检测地址冲突？', level:'进阶', options:['发送ARP','发送DAD(NS报文)','发送DHCPv6请求','人工配置'], answer:1, explain:'SLAAC通过DAD重复地址检测(NS报文)确认唯一性'},
{q:'TCP重传定时器(RTO)计算基于？', level:'进阶', options:['固定1秒','RTT的平滑估计值','最大传输单元','拥塞窗口'], answer:1, explain:'RTO基于平滑RTT(SRTT)及RTT偏差计算'},
{q:'NAT穿透(打洞)常用技术不包括？', level:'进阶', options:['STUN','TURN','ICE','OSPF'], answer:3, explain:'OSPF是路由协议，STUN/TURN/ICE是NAT穿透方案'},
{q:'VRRP虚拟路由器默认优先级是？', level:'进阶', options:['0','100','255','1024'], answer:1, explain:'VRRP默认优先级100，255表示IP地址拥有者'},
{q:'LACP模式中主动模式是？', level:'进阶', options:['Passive','Active','On','Off'], answer:1, explain:'LACP Active主动发送LACPDU，Passive被动响应'},
{q:'策略路由(PBR)与普通路由区别是？', level:'进阶', options:['PBR只看目的IP','PBR基于源地址等多条件选路','PBR优先级更低','PBR不可指定下一跳'], answer:1, explain:'PBR基于策略(源/端口等)，优于目的路由表'},
{q:'RIP最大跳数限制是多少？', level:'进阶', options:['15','16','30','255'], answer:0, explain:'RIP最大有效跳数15，16表示不可达'},
{q:'IS-IS相比OSPF的特点是？', level:'进阶', options:['基于IP协议','基于CLNP，区域在路由器内划分','仅支持IP','DR选举更频繁'], answer:1, explain:'IS-IS最初为CLNP设计，一个路由器可属多区域'},
{q:'MPLS VPN中RD和RT的作用是？', level:'进阶', options:['RD用于路由区分，RT控制VPN路由导入导出','RD控制导入导出','RT唯一标识VPN','RD做加密'], answer:0, explain:'RD(8字节)使VPNv4地址唯一，RT是BGP扩展团体属性'},
{q:'Diameter相比RADIUS的优势是？', level:'进阶', options:['基于UDP','基于TCP/TLS支持能力协商更可靠','更简单','端口固定1812'], answer:1, explain:'Diameter用TCP/SCTP+TLS，有确认和能力协商，更可靠'},
{q:'SIP协议中INVITE方法作用是？', level:'进阶', options:['结束会话','发起会话邀请','注册用户','查询状态'], answer:1, explain:'INVITE用于发起建立一个新的SIP会话'},
{q:'PCRF与PCEF之间的接口是？', level:'进阶', options:['S11','Gx','Gy','S5/S8'], answer:1, explain:'Gx接口是PCRF到PCEF(PGW)的策略控制接口'},
{q:'OSI数据链路层的两个子层是？', level:'进阶', options:['LLC和MAC','IP和ICMP','TCP和UDP','PHY和MAC'], answer:0, explain:'数据链路层分为LLC逻辑链路控制和MAC介质访问'},
{q:'TCP滑动窗口的作用是？', level:'进阶', options:['拥塞控制','流量控制，接收方控制发送量','加密数据','路由寻址'], answer:1, explain:'窗口大小由接收方通告，实现端到端流量控制'},
{q:'HTTP状态码304表示什么场景？', level:'进阶', options:['重定向','协商缓存命中，资源未修改','错误请求','禁止访问'], answer:1, explain:'304 Not Modified协商缓存命中，直接用本地缓存'},
{q:'STP Listening到Learning状态的等待时间是？', level:'进阶', options:['10秒','15秒(Forward Delay)','20秒(Max Age)','30秒'], answer:1, explain:'Forward Delay默认15秒，每个过渡状态等待'},
{q:'BGP选路规则中Local_Preference比较顺序是？', level:'进阶', options:['优先比较','第2步(在Weight后)','第5步','最后比较'], answer:1, explain:'BGP选路：1 Weight 2 Local Pref 3 Local起源 4 AS-Path等'},
{q:'ARP缓存表项老化时间默认约为？', level:'进阶', options:['10秒','5分钟','2小时','永久'], answer:1, explain:'Linux/Windows默认ARP缓存约2-5分钟老化'},
{q:'TCP报文段中URG标志的作用是？', level:'进阶', options:['推送数据','紧急指针有效','确认号有效','同步序列号'], answer:1, explain:'URG=1表示紧急指针字段有效，紧急数据优先处理'},
{q:'HTTP/2头部压缩算法是？', level:'进阶', options:['gzip','DEFLATE','HPACK','Brotli'], answer:2, explain:'HTTP/2使用HPACK算法专门压缩HTTP头部'},
{q:'VXLAN外层UDP目的端口号是？', level:'进阶', options:['4789','4790','8472','443'], answer:0, explain:'IANA分配VXLAN UDP目的端口为4789'},
{q:'mtr报告中L%列的含义是？', level:'进阶', options:['延迟百分比','丢包率','负载百分比','标签跳数'], answer:1, explain:'L%是Loss%丢包率，显示各跳的丢包情况'},
{q:'TCP的TIME_WAIT状态一般持续多久？', level:'高级', options:['15秒','30秒','1MSL约1-2分钟','永久'], answer:2, explain:'TIME_WAIT为2MSL，MSL默认通常2分钟'},
{q:'BGP路由黑洞问题通常如何解决？', level:'高级', options:['全互联IBGP','路由反射器+IGP同步或MPLS','关闭同步','增加Metric'], answer:1, explain:'非全互联IBGP下需路由反射/联盟或MPLS标签转发'},
{q:'OSPF虚链路的作用是什么？', level:'高级', options:['加密OSPF报文','连接无法直连Area0的区域','替代物理链路','加速收敛'], answer:1, explain:'虚链路逻辑连接不连续骨干区的ABR到Area 0'},
{q:'TCP拥塞控制BBR算法与CUBIC的区别是？', level:'高级', options:['BBR基于丢包','BBR基于带宽RTT建模不依赖丢包','CUBIC更适合无线','BBR窗口更小'], answer:1, explain:'BBR基于最大带宽和最小RTT构建模型，CUBIC基于丢包'},
{q:'复杂网络中traceroute出现*号最可能的原因？', level:'高级', options:['链路断了','路由器禁用ICMP超时或策略限速','DNS解析失败','MTU不匹配'], answer:1, explain:'路由器常过滤限速ICMP Time Exceeded导致*，非真丢包'},
{q:'tcpdump抓HTTP GET报文过滤表达式正确是？', level:'高级', options:['port 80 and tcp[20:4]=0x47455420','tcp port http','tcp dst port 80','ether proto http'], answer:0, explain:'0x47455420即"GET "，偏移20(TCP头+选项假设20)，匹配GET请求首4字节'},
{q:'LACP LACPDU中Actor/Partner的状态位AGG是？', level:'高级', options:['表示独立链路','表示可聚合链路','表示超时','表示同步'], answer:1, explain:'AGG=1表明该链路可加入聚合组，否则独立'},
{q:'BGP Community属性no-export的作用是？', level:'高级', options:['不通告给任何邻居','不通告出本AS(EBGP邻居)','不通告给IBGP','不通告给RR'], answer:1, explain:'NO_EXPORT(0xFFFFFF01)不通告到EBGP邻居即不出本AS'},
{q:'IS-IS L1/L2路由器如何避免路由环路？', level:'高级', options:['水平分割','设置ATT位，L1默认路由到最近L2','毒性反转','抑制时间'], answer:1, explain:'L1路由器设ATT位时其他L1路由器生成指向它的默认路由到L2区域'},
{q:'MPLS PHP(倒数第二跳弹出)的作用是？', level:'高级', options:['加速标签交换','减少LER查找标签操作，LER直接查IP','增加标签栈','加密标签'], answer:1, explain:'倒数第二跳弹出标签，LER免去标签查找直接IP转发，节省资源'},
{q:'IPsec IKEv2与IKEv1主模式相比优势是？', level:'高级', options:['IKEv2需要6报文主模式','IKEv2只需4报文+支持NAT-T内置+更安全重协商','IKEv2不支持DPD','IKEv1更适合移动'], answer:1, explain:'IKEv2初始交换4报文，集成NAT-T，MOBIKE支持移动性，更高效'},
{q:'TLS 1.3相比1.2的握手延迟优化是？', level:'高级', options:['无变化','1-RTT握手(甚至0-RTT)省去Key Exchange','增加报文数','固定3-RTT'], answer:1, explain:'TLS1.3简化密码套件默认前向保密，正常1-RTT，恢复会话0-RTT'},
{q:'SYN Cookies防御SYN flood的原理是？', level:'高级', options:['丢弃SYN','SYN-ACK的seq编码源/目的IP端口等信息，不存半连接','增大backlog','防火墙阻断'], answer:1, explain:'Cookie将连接信息编码到序列号，ACK回来校验无需占用半连接队列'},
{q:'STP拓扑变更(TC)后CAM表如何处理？', level:'高级', options:['不变','将CAM老化时间缩短到Forward Delay(默认15秒)加速重新学习','永久删除CAM','禁止学习'], answer:1, explain:'TCN触发TC，交换机将CAM表老化时间设为Forward Delay快速刷新'},
{q:'VXLAN头端复制(Head-End Replication)适用场景是？', level:'高级', options:['大型网络多VTEP','没有组播支持的小网络，单播复制给所有VTEP','任何场景都最优','仅加密场景'], answer:1, explain:'头端复制不需要底层组播，但大表项时VTEP复制负担重'},
{q:'BGP ADD-PATH能力的作用是？', level:'高级', options:['仅能发送最优路径','允许发送多条同前缀路径，实现快速切换和负载','加速收敛','加密BGP'], answer:1, explain:'ADD-PATH允许发多条路径，RR不必只反射最优，可用作快速备份'},
{q:'SIP对话中180 Ringing与183 Session Progress的区别？', level:'高级', options:['180无媒体','183可携带SDP建立早期媒体(如彩铃)','180是最终响应','183表示会话成功'], answer:1, explain:'183带SDP可建早期媒体通道放彩铃/忙音等，180仅提示振铃'},
{q:'Diameter会话与信用控制应用(RFC4006)中CCA初答的Result-Code是DIAMETER_CREDIT_CONTROL_NOT_APPLICABLE表示？', level:'高级', options:['认证失败','该业务无需实时计费，允许会话继续','需要终止','需要重定向'], answer:1, explain:'该码返回表示无需实时信用控制，业务可继续但可能离线计费'},
{q:'PCRF中PCC规则的QCI参数的含义是？', level:'高级', options:['计费标识','QoS等级分类，决定调度策略权重丢包率门限','用户标识','PDN类型'], answer:1, explain:'QCI(QoS Class Identifier)1-9，定义了资源类型/优先级/包延迟/丢包率'},
{q:'TCP Fast Open的条件和作用是？', level:'高级', options:['必须3次握手后才能发数据','SYN或SYN-ACK可携带数据减少1-RTT延迟，需Cookie','只能用于UDP','减少MTU'], answer:1, explain:'TFO使用预先获得的TFO Cookie，SYN中可带应用层数据'},
{q:'DHCPv6 PD(前缀委派)的作用是？', level:'高级', options:['分配单个IPv6给客户端','运营商给CPE分配一段IPv6前缀供CPE下联子网自动划分','分配DNS','仅用于链路本地'], answer:1, explain:'PD(Prefix Delegation)让CPE从运营商获得前缀并自动规划下联网络'},
{q:'策略路由中set ip next-hop recursive的作用是？', level:'高级', options:['直接ARP下一跳','递归查找下一跳可达性(即使非直连)后再决定','强制直连','丢弃数据包'], answer:1, explain:'递归下一跳允许下一跳非直连，通过路由表递归解析最终出接口'},
{q:'MPLS TE RSVP-TE中Explicit Route Object(ERO)的作用是？', level:'高级', options:['加密LSP','显式指定LSP路径各跳，实现约束路由','带宽预留','错误报告'], answer:1, explain:'ERO携带严格/松散指定的路径跳列表，CSPF计算出后放入Path消息建立LSP'},
{q:'VXLAN EVPN Type-2/MAC/IP路由的作用是？', level:'高级', options:['宣告VTEP','MAC地址通告+主机IP可达性，用于二层转发表同步','宣告组播','宣告多播'], answer:1, explain:'EVPN Type 2路由携带MAC(+可选IP)，用于VTEP间同步主机可达性，抑制ARP泛洪'},
{q:'BGP Large Community(RFC8092)相比标准Community的特点是？', level:'高级', options:['只有32位','4字节GlobalAdmin+4字节LocalData共12字节，可表达更丰富策略','不能传播','只能IBGP用'], answer:1, explain:'Large Community格式为12字节(4+4+4)，解决标准32位不够用，适合多域策略'}];
