const fs = require('fs');

// 读原始data.js并把QUESTIONS对象拿到内存
let code = fs.readFileSync('/workspace/data.js', 'utf8');
// 执行代码获得QUESTIONS和KNOWLEDGE（const改为var便于在Node中访问）
const sandbox = {};
const vm = require('vm');
const ctx = vm.createContext(sandbox);
vm.runInContext(code.replace(/^const /gm, 'var '), ctx);
const { QUESTIONS, KNOWLEDGE } = sandbox;

// ================ 网络新增150题 ================
const NET_NEW = [{q:'OSI模型共分为几层？', level:'基础', options:['5层','6层','7层','8层'], answer:2, explain:'OSI模型分为7层：物理层到应用层'},
{q:'TCP建立连接需要几次握手？', level:'基础', options:['1次','2次','3次','4次'], answer:2, explain:'TCP通过三次握手建立可靠连接'},
{q:'HTTP状态码200表示什么？', level:'基础', options:['重定向','请求成功','客户端错误','服务器错误'], answer:1, explain:'200 OK表示请求已成功处理'},
{q:'DNS的主要作用是什么？', level:'基础', options:['加密传输','域名解析','路由选择','负载均衡'], answer:1, explain:'DNS将域名解析为IP地址'},
{q:'DHCP协议用于什么？', level:'基础', options:['动态分配IP','远程登录','文件传输','邮件发送'], answer:0, explain:'DHCP动态为主机分配IP地址等参数'},
{q:'VLAN的主要作用是什么？', level:'基础', options:['加密数据','划分广播域','路由转发','地址转换'], answer:1, explain:'VLAN通过逻辑划分隔离广播域'},
{q:'ICMP协议常用于哪个命令？', level:'基础', options:['ssh','ping','ftp','telnet'], answer:1, explain:'ping命令使用ICMP回显请求/应答'},
{q:'HTTPS默认使用哪个端口？', level:'基础', options:['21','22','80','443'], answer:3, explain:'HTTPS默认端口为443'},
{q:'SSH默认使用哪个端口？', level:'基础', options:['21','22','23','80'], answer:1, explain:'SSH默认端口为22'},
{q:'ARP协议的作用是什么？', level:'基础', options:['IP转MAC','MAC转IP','域名转IP','IP转域名'], answer:0, explain:'ARP通过IP地址解析MAC地址'},
{q:'HTTP默认端口是多少？', level:'基础', options:['21','22','80','443'], answer:2, explain:'HTTP默认端口为80'},
{q:'FTP默认使用哪个端口？', level:'基础', options:['20和21','22和23','80和443','53和67'], answer:0, explain:'FTP使用21(控制)和20(数据)端口'},
{q:'Telnet默认端口是多少？', level:'基础', options:['21','22','23','25'], answer:2, explain:'Telnet默认端口为23'},
{q:'SMTP默认端口是多少？', level:'基础', options:['23','25','53','110'], answer:1, explain:'SMTP默认端口为25'},
{q:'DNS默认端口是多少？', level:'基础', options:['25','53','80','110'], answer:1, explain:'DNS默认使用53端口(UDP为主)'},
{q:'POP3默认端口是多少？', level:'基础', options:['25','53','110','143'], answer:2, explain:'POP3默认端口为110'},
{q:'STP协议的主要作用是什么？', level:'基础', options:['防止路由环路','防止交换环路','加密传输','地址转换'], answer:1, explain:'STP生成树协议防止二层交换环路'},
{q:'NAT的主要作用是什么？', level:'基础', options:['加密数据','网络地址转换','域名解析','负载均衡'], answer:1, explain:'NAT实现私网与公网地址转换'},
{q:'CDN的全称是什么？', level:'基础', options:['内容分发网络','公共数据网','综合数字网','电路交换网'], answer:0, explain:'CDN是Content Delivery Network'},
{q:'DMZ区域的作用是什么？', level:'基础', options:['内部办公区','隔离公共服务区','数据库区','开发测试区'], answer:1, explain:'DMZ放置对外提供服务的服务器'},
{q:'SNMP协议用于什么？', level:'基础', options:['文件传输','网络管理','邮件发送','域名解析'], answer:1, explain:'SNMP是简单网络管理协议'},
{q:'NTP协议用于什么？', level:'基础', options:['时间同步','文件传输','远程登录','域名解析'], answer:0, explain:'NTP实现网络时间同步'},
{q:'BGP属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','外部网关'], answer:3, explain:'BGP是外部网关协议(EGP)'},
{q:'OSPF属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','混合协议'], answer:1, explain:'OSPF是链路状态路由协议'},
{q:'RIP属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','外部网关'], answer:0, explain:'RIP是距离矢量路由协议'},
{q:'TLS协议位于OSI哪一层？', level:'基础', options:['网络层','传输层','会话层','表示层'], answer:3, explain:'TLS工作在表示层，对应用层数据加密'},
{q:'UDP协议相对于TCP的特点是？', level:'基础', options:['可靠传输','面向连接','无连接低开销','流量控制'], answer:2, explain:'UDP是无连接协议，开销小但不可靠'},
{q:'TCP协议相对于UDP的特点是？', level:'基础', options:['无连接','不可靠','可靠有序','低延迟'], answer:2, explain:'TCP提供可靠、有序、重传的传输'},
{q:'子网掩码255.255.255.0对应CIDR前缀是？', level:'基础', options:['/8','/16','/24','/32'], answer:2, explain:'255.255.255.0对应/24，前24位网络位'},
{q:'CIDR前缀/16对应子网掩码是？', level:'基础', options:['255.0.0.0','255.255.0.0','255.255.255.0','255.255.255.255'], answer:1, explain:'/16对应255.255.0.0'},
{q:'WiFi加密协议WPA2的加密算法是？', level:'基础', options:['WEP','TKIP','CCMP(AES)','DES'], answer:2, explain:'WPA2使用CCMP即AES加密算法'},
{q:'代理服务器的主要作用不包括？', level:'基础', options:['访问控制','缓存加速','加密用户数据','隐藏内部地址'], answer:2, explain:'代理不直接加密用户原始数据'},
{q:'IDS的全称是什么？', level:'基础', options:['入侵检测系统','入侵防御系统','集成开发系统','内部域名系统'], answer:0, explain:'IDS是Intrusion Detection System'},
{q:'VPN的主要作用是什么？', level:'基础', options:['加速网络','建立安全加密隧道','域名解析','负载均衡'], answer:1, explain:'VPN在公网建立加密通信隧道'},
{q:'IMAP默认端口是多少？', level:'基础', options:['25','110','143','993'], answer:2, explain:'IMAP默认端口为143'},
{q:'MAC地址长度是多少位？', level:'基础', options:['32位','48位','64位','128位'], answer:1, explain:'MAC地址为48位(6字节)十六进制表示'},
{q:'IPv4地址长度是多少位？', level:'基础', options:['32位','48位','64位','128位'], answer:0, explain:'IPv4地址为32位二进制'},
{q:'IPv6地址长度是多少位？', level:'基础', options:['32位','48位','64位','128位'], answer:3, explain:'IPv6地址为128位二进制'},
{q:'netstat命令中查看TCP连接的参数是？', level:'基础', options:['-a','-t','-u','-n'], answer:1, explain:'netstat -t显示TCP连接'},
{q:'ss命令的作用是？', level:'基础', options:['查看进程','查看网络套接字','查看内存','查看磁盘'], answer:1, explain:'ss比netstat更高效地查看套接字'},
{q:'lsof -i命令的作用是？', level:'基础', options:['查看打开文件','查看监听网络的进程','查看用户登录','查看系统负载'], answer:1, explain:'lsof -i列出打开网络套接字的进程'},
{q:'tcpdump抓包的作用是？', level:'基础', options:['修改报文','捕获和分析网络报文','发送报文','路由转发'], answer:1, explain:'tcpdump用于抓取和分析网络数据包'},
{q:'L4负载均衡是基于哪层信息？', level:'基础', options:['MAC层','IP层','传输层端口','应用层内容'], answer:2, explain:'四层负载基于IP+端口进行分发'},
{q:'L7负载均衡是基于哪层信息？', level:'基础', options:['MAC层','IP层','传输层','应用层内容'], answer:3, explain:'七层负载基于URL/HTTP头等应用信息'},
{q:'WAF的全称是什么？', level:'基础', options:['Web应用防火墙','广域防火墙','无线接入防火墙','Web访问功能'], answer:0, explain:'WAF是Web Application Firewall'},
{q:'ACL的全称是什么？', level:'基础', options:['访问控制列表','应用控制层','自动配置列表','接入认证层'], answer:0, explain:'ACL是Access Control List'},
{q:'QoS的主要作用是什么？', level:'基础', options:['加密数据','服务质量保证','地址转换','域名解析'], answer:1, explain:'QoS为特定流量提供服务质量保障'},
{q:'MPLS的标签长度是多少？', level:'基础', options:['20位','32位','48位','64位'], answer:1, explain:'MPLS标签32位，含20位标签值等字段'},
{q:'VXLAN的VNI标识符长度是？', level:'基础', options:['12位','16位','24位','32位'], answer:2, explain:'VXLAN网络标识符VNI为24位'},
{q:'SDN的核心思想是什么？', level:'基础', options:['控制与转发分离','硬件加速','加密传输','分布式存储'], answer:0, explain:'SDN将控制平面与数据平面分离'},
{q:'VRRP协议的作用是什么？', level:'基础', options:['网关冗余','链路聚合','路由计算','域名解析'], answer:0, explain:'VRRP实现默认网关的冗余备份'},
{q:'HSRP是哪个厂商的协议？', level:'基础', options:['华为','Cisco','H3C','Juniper'], answer:1, explain:'HSRP是Cisco私有热备份路由协议'},
{q:'LACP协议的作用是什么？', level:'基础', options:['网关冗余','链路聚合控制','域名解析','加密传输'], answer:1, explain:'LACP是链路聚合控制协议标准'},
{q:'SLAAC是哪个协议的功能？', level:'基础', options:['IPv4','IPv6','MPLS','BGP'], answer:1, explain:'SLAAC是IPv6无状态地址自动配置'},
{q:'DHCPv6的客户端端口是？', level:'基础', options:['546','547','67','68'], answer:0, explain:'DHCPv6客户端用546，服务器547'},
{q:'FTP主动模式下服务器连接的端口是？', level:'基础', options:['20','21','随机高端口','1024以下'], answer:0, explain:'主动模式服务器用20端口发起数据连接'},
{q:'FTP被动模式下客户端连接的端口是？', level:'基础', options:['20','21','服务器指定高端口','53'], answer:2, explain:'被动模式客户端连接服务器指定的数据端口'},
{q:'traceroute命令使用什么协议？', level:'基础', options:['TCP','UDP(默认)','ICMP','SCTP'], answer:1, explain:'Linux traceroute默认用UDP，Windows用ICMP'},
{q:'mtr命令结合了哪两个命令？', level:'基础', options:['ping和ssh','ping和traceroute','netstat和ss','ftp和sftp'], answer:1, explain:'mtr结合ping与traceroute功能'},
{q:'组播地址的D类地址范围是？', level:'基础', options:['10.0.0.0/8','172.16.0.0/12','224.0.0.0/4','192.168.0.0/16'], answer:2, explain:'D类组播地址224.0.0.0~239.255.255.255'},
{q:'私网地址192.168.0.0的CIDR范围是？', level:'基础', options:['/8','/12','/16','/24'], answer:2, explain:'192.168.0.0/16是C类私网地址段'},
{q:'私网地址172.16.0.0的CIDR范围是？', level:'基础', options:['/8','/12','/16','/24'], answer:1, explain:'172.16.0.0/12是B类私网地址段'},
{q:'私网地址10.0.0.0的CIDR范围是？', level:'基础', options:['/8','/12','/16','/24'], answer:0, explain:'10.0.0.0/8是A类私网地址段'},
{q:'HTTP状态码301表示什么？', level:'基础', options:['永久重定向','临时重定向','未修改','请求错误'], answer:0, explain:'301 Moved Permanently永久重定向'},
{q:'HTTP状态码404表示什么？', level:'基础', options:['未授权','禁止访问','未找到资源','服务器错误'], answer:2, explain:'404 Not Found请求的资源不存在'},
{q:'HTTP状态码500表示什么？', level:'基础', options:['成功','重定向','客户端错误','服务器内部错误'], answer:3, explain:'500 Internal Server Error服务器内部错误'},
{q:'HTTP状态码302表示什么？', level:'基础', options:['永久重定向','临时重定向','未修改','禁止访问'], answer:1, explain:'302 Found表示临时重定向'},
{q:'HTTP状态码403表示什么？', level:'基础', options:['未授权','禁止访问','未找到','超时'], answer:1, explain:'403 Forbidden服务器拒绝访问'},
{q:'HTTP状态码401表示什么？', level:'基础', options:['未授权需要认证','禁止访问','未找到','请求太大'], answer:0, explain:'401 Unauthorized需要身份认证'},
{q:'IS-IS属于哪类路由协议？', level:'基础', options:['距离矢量','链路状态','路径矢量','外部网关'], answer:1, explain:'IS-IS是链路状态IGP路由协议'},
{q:'Diameter协议主要用于什么场景？', level:'基础', options:['网页浏览','AAA认证','文件传输','邮件发送'], answer:1, explain:'Diameter是下一代AAA认证协议'},
{q:'SIP协议主要用于什么？', level:'基础', options:['路由协议','VoIP会话控制','域名解析','文件传输'], answer:1, explain:'SIP是会话发起协议，用于VoIP'},
{q:'PCRF主要应用于哪个领域？', level:'基础', options:['数据中心','移动通信LTE/EPC','企业内网','校园网'], answer:1, explain:'PCRF是LTE/EPC核心网策略计费控制单元'},
{q:'TCP关闭连接需要几次挥手？', level:'基础', options:['2次','3次','4次','5次'], answer:2, explain:'TCP通过四次挥手断开连接'},
{q:'IPsec AH协议提供什么功能？', level:'基础', options:['只加密不认证','只认证完整性','加密+认证','地址转换'], answer:1, explain:'AH提供认证和完整性，不加密'},
{q:'IPsec ESP协议默认提供什么？', level:'基础', options:['只加密','只认证','加密+认证','只压缩'], answer:2, explain:'ESP默认提供加密和认证完整性'},
{q:'SYN flood攻击利用了TCP什么机制？', level:'进阶', options:['三次握手','四次挥手','滑动窗口','拥塞控制'], answer:0, explain:'SYN flood滥用半连接队列资源耗尽服务器'},
{q:'子网192.168.1.0/27的可用主机数是？', level:'进阶', options:['30','32','62','64'], answer:0, explain:'/27有5主机位，2^5-2=30个可用主机'},
{q:'10.0.0.0/22每个子网可用主机数是？', level:'进阶', options:['510','1022','2046','4094'], answer:1, explain:'32-22=10主机位，2^10-2=1022'},
{q:'C类地址划分子网需要4个子网，子网掩码是？', level:'进阶', options:['255.255.255.128','255.255.255.192','255.255.255.224','255.255.255.240'], answer:1, explain:'4子网需借2位，/26即255.255.255.192'},
{q:'需要至少100台主机的子网，最小CIDR前缀是？', level:'进阶', options:['/24','/25','/26','/27'], answer:1, explain:'2^7-2=126≥100，32-7=25，即/25'},
{q:'DNS递归查询与迭代查询的区别是？', level:'进阶', options:['递归客户端请求根服务器','递归服务器替客户端完成查询','迭代必须缓存','迭代更快'], answer:1, explain:'递归DNS服务器代客户端完成完整查询链'},
{q:'DHCP Discover报文采用什么方式发送？', level:'进阶', options:['单播','广播','组播','任播'], answer:1, explain:'客户端无IP，发送255.255.255.255广播'},
{q:'STP中根网桥选举依据是？', level:'进阶', options:['最大MAC','最小MAC+最小优先级','最大优先级','接口带宽'], answer:1, explain:'先比桥优先级(默认32768)再比MAC小者为根'},
{q:'STP中指定端口选举依据是？', level:'进阶', options:['端口ID最小','到根桥开销最小','端口速率最快','MAC最小'], answer:1, explain:'先比到根路径开销，再对比端桥ID、端口ID'},
{q:'标准NAPT转换中，内部地址映射依据是？', level:'进阶', options:['仅IP','IP+端口','仅端口','MAC+IP'], answer:1, explain:'NAPT通过源IP+源端口映射到公网地址端口'},
{q:'正向代理与反向代理的区别是？', level:'进阶', options:['正向代理服务端用','反向代理代表客户端访问','正向代理代表客户端访问','反向代理只能缓存'], answer:2, explain:'正向代理替客户端访问，反向代理替服务器接收'},
{q:'IPsec两种模式区别是？', level:'进阶', options:['传输模式只加密上层数据','隧道模式只认证','传输模式封装整个IP','隧道模式只加密TCP'], answer:0, explain:'传输模式只加密IP上层，隧道模式封装整个IP'},
{q:'SNMPv3相比v2c新增了什么？', level:'进阶', options:['GetBulk操作','Inform消息','认证和加密','视图访问控制'], answer:2, explain:'SNMPv3新增USM安全模型，支持认证加密'},
{q:'BGP建立邻居使用的端口是？', level:'进阶', options:['520','179','161','1701'], answer:1, explain:'BGP使用TCP 179端口建立邻居'},
{q:'OSPF的DR/BDR选举在什么网络类型进行？', level:'进阶', options:['点到点','广播/NBMA','点到多点','虚链路'], answer:1, explain:'广播和NBMA网络才选举DR和BDR减少邻接'},
{q:'OSPF区域0的作用是？', level:'进阶', options:['普通区域','骨干区域所有区域必须连接','Stub区域','NSSA区域'], answer:1, explain:'OSPF骨干区域Area 0，其他区域必须与之连接'},
{q:'TLS握手过程中，Pre-Master Secret谁生成？', level:'进阶', options:['客户端','服务器','双方各一半','CA生成'], answer:0, explain:'客户端生成Pre-Master并用服务器公钥加密发送'},
{q:'HTTP/2多路复用的作用是？', level:'进阶', options:['加密数据','同一连接并发多个请求响应','压缩头部','服务器推送'], answer:1, explain:'二进制帧实现单TCP连接上多路流并发'},
{q:'TCP拥塞控制慢启动阈值ssthresh的作用是？', level:'进阶', options:['低于阈值线性增长','高于阈值指数增长','低于阈值指数增长','固定拥塞窗口'], answer:2, explain:'cwnd<ssthresh指数增长(慢启动)，之后线性(拥塞避免)'},
{q:'netstat -anp中p参数的作用是？', level:'进阶', options:['显示端口号','显示程序名/PID','禁用DNS解析','显示UDP'], answer:1, explain:'-p显示使用该套接字的进程名和PID'},
{q:'ss -s命令的作用是？', level:'进阶', options:['显示TCP socket统计汇总','显示UDP连接','显示程序名','显示路由表'], answer:0, explain:'ss -s输出套接字使用统计摘要'},
{q:'lsof -i:80的作用是？', level:'进阶', options:['查看80端口进程','查看80进程文件','查看端口80硬件','查看80用户'], answer:0, explain:'列出所有监听或使用80端口的进程'},
{q:'tcpdump -i eth0 host 192.168.1.1捕获的是？', level:'进阶', options:['仅源IP是192.168.1.1','仅目的IP是192.168.1.1','源或目的IP是192.168.1.1','仅MAC匹配'], answer:2, explain:'host匹配源或目的IP地址的报文'},
{q:'FTP被动模式相对于主动模式的优势是？', level:'进阶', options:['传输更快','客户端在NAT后更容易连接','更安全','占用端口更少'], answer:1, explain:'被动模式客户端发起数据连接，适合客户端在NAT后'},
{q:'L4与L7负载均衡相比，L4特点是？', level:'进阶', options:['能按URL分发','性能高开销小','能做会话保持cookie','能修改HTTP头'], answer:1, explain:'四层仅处理到传输层，处理速度快开销低'},
{q:'WAF能防护的攻击是？', level:'进阶', options:['DDoS流量型','SQL注入/XSS等应用层','物理层攻击','电源故障'], answer:1, explain:'WAF主要防护SQL注入、XSS等Web应用攻击'},
{q:'VXLAN相比VLAN的主要优势是？', level:'进阶', options:['速度更快','VNI数量远超4096支持多租户','更安全','需要更少设备'], answer:1, explain:'24位VNI支持16M租户，解决VLAN 4096限制'},
{q:'SDN OpenFlow协议作用是？', level:'进阶', options:['交换机内部通信','控制器与交换机间控制信令','服务器间数据','管理配置'], answer:1, explain:'OpenFlow是SDN控制器与转发设备间的标准接口'},
{q:'QoS中DSCP位于报文什么位置？', level:'进阶', options:['以太网帧头','IP报文头部ToS字段','TCP头部','UDP头部'], answer:1, explain:'DSCP占用IPv4 ToS/IPv6 TC字段的前6位'},
{q:'MPLS标签栈中S位为1表示？', level:'进阶', options:['栈顶标签','栈底标签','中间标签','无效标签'], answer:1, explain:'S=1表明这是标签栈中最后一个(栈底)标签'},
{q:'组播PIM-SM模式的特点是？', level:'进阶', options:['推模式主动广播','拉模式按需加入，适合稀疏组','仅本地有效','需要静态RP'], answer:1, explain:'PIM-SM稀疏模式使用RP，接收者按需Join'},
{q:'IPv6 SLAAC获取地址后，如何检测地址冲突？', level:'进阶', options:['发送ARP','发送DAD(NS报文)','发送DHCPv6请求','人工配置'], answer:1, explain:'SLAAC通过DAD重复地址检测(NS报文)确认唯一性'},
{q:'TCP重传定时器(RTO)计算基于？', level:'进阶', options:['固定1秒','RTT的平滑估计值','最大传输单元','拥塞窗口'], answer:1, explain:'RTO基于平滑RTT(SRTT)及RTT偏差计算'},
{q:'NAT穿透(打洞)常用技术不包括？', level:'进阶', options:['STUN','TURN','ICE','OSPF'], answer:3, explain:'OSPF是路由协议，STUN/TURN/ICE是NAT穿透方案'},
{q:'VRRP虚拟路由器默认优先级是？', level:'进阶', options:['0','100','255','1024'], answer:1, explain:'VRRP默认优先级100，255表示IP地址拥有者'},
{q:'LACP模式中主动模式是？', level:'进阶', options:['Passive','Active','On','Off'], answer:1, explain:'LACP Active主动发送LACPDU，Passive被动响应'},
{q:'策略路由(PBR)与普通路由区别是？', level:'进阶', options:['PBR只看目的IP','PBR基于源地址等多条件选路','PBR优先级更低','PBR不可指定下一跳'], answer:1, explain:'PBR基于策略(源/端口等)，优于目的路由表'},
{q:'RIP最大跳数限制是多少？', level:'进阶', options:['15','16','30','255'], answer:0, explain:'RIP最大有效跳数15，16表示不可达'},
{q:'IS-IS相比OSPF的特点是？', level:'进阶', options:['基于IP协议','基于CLNP，区域在路由器内划分','仅支持IP','DR选举更频繁'], answer:1, explain:'IS-IS最初为CLNP设计，一个路由器可属多区域'},
{q:'MPLS VPN中RD和RT的作用是？', level:'进阶', options:['RD用于路由区分，RT控制VPN路由导入导出','RD控制导入导出','RT唯一标识VPN','RD做加密'], answer:0, explain:'RD(8字节)使VPNv4地址唯一，RT是BGP扩展团体属性'},
{q:'Diameter相比RADIUS的优势是？', level:'进阶', options:['基于UDP','基于TCP/TLS支持能力协商更可靠','更简单','端口固定1812'], answer:1, explain:'Diameter用TCP/SCTP+TLS，有确认和能力协商，更可靠'},
{q:'SIP协议中INVITE方法作用是？', level:'进阶', options:['结束会话','发起会话邀请','注册用户','查询状态'], answer:1, explain:'INVITE用于发起建立一个新的SIP会话'},
{q:'PCRF与PCEF之间的接口是？', level:'进阶', options:['S11','Gx','Gy','S5/S8'], answer:1, explain:'Gx接口是PCRF到PCEF(PGW)的策略控制接口'},
{q:'OSI数据链路层的两个子层是？', level:'进阶', options:['LLC和MAC','IP和ICMP','TCP和UDP','PHY和MAC'], answer:0, explain:'数据链路层分为LLC逻辑链路控制和MAC介质访问'},
{q:'TCP滑动窗口的作用是？', level:'进阶', options:['拥塞控制','流量控制，接收方控制发送量','加密数据','路由寻址'], answer:1, explain:'窗口大小由接收方通告，实现端到端流量控制'},
{q:'HTTP状态码304表示什么场景？', level:'进阶', options:['重定向','协商缓存命中，资源未修改','错误请求','禁止访问'], answer:1, explain:'304 Not Modified协商缓存命中，直接用本地缓存'},
{q:'STP Listening到Learning状态的等待时间是？', level:'进阶', options:['10秒','15秒(Forward Delay)','20秒(Max Age)','30秒'], answer:1, explain:'Forward Delay默认15秒，每个过渡状态等待'},
{q:'BGP选路规则中Local_Preference比较顺序是？', level:'进阶', options:['优先比较','第2步(在Weight后)','第5步','最后比较'], answer:1, explain:'BGP选路：1 Weight 2 Local Pref 3 Local起源 4 AS-Path等'},
{q:'ARP缓存表项老化时间默认约为？', level:'进阶', options:['10秒','5分钟','2小时','永久'], answer:1, explain:'Linux/Windows默认ARP缓存约2-5分钟老化'},
{q:'TCP报文段中URG标志的作用是？', level:'进阶', options:['推送数据','紧急指针有效','确认号有效','同步序列号'], answer:1, explain:'URG=1表示紧急指针字段有效，紧急数据优先处理'},
{q:'HTTP/2头部压缩算法是？', level:'进阶', options:['gzip','DEFLATE','HPACK','Brotli'], answer:2, explain:'HTTP/2使用HPACK算法专门压缩HTTP头部'},
{q:'VXLAN外层UDP目的端口号是？', level:'进阶', options:['4789','4790','8472','443'], answer:0, explain:'IANA分配VXLAN UDP目的端口为4789'},
{q:'mtr报告中L%列的含义是？', level:'进阶', options:['延迟百分比','丢包率','负载百分比','标签跳数'], answer:1, explain:'L%是Loss%丢包率，显示各跳的丢包情况'},
{q:'TCP的TIME_WAIT状态一般持续多久？', level:'高级', options:['15秒','30秒','1MSL约1-2分钟','永久'], answer:2, explain:'TIME_WAIT为2MSL，MSL默认通常2分钟'},
{q:'BGP路由黑洞问题通常如何解决？', level:'高级', options:['全互联IBGP','路由反射器+IGP同步或MPLS','关闭同步','增加Metric'], answer:1, explain:'非全互联IBGP下需路由反射/联盟或MPLS标签转发'},
{q:'OSPF虚链路的作用是什么？', level:'高级', options:['加密OSPF报文','连接无法直连Area0的区域','替代物理链路','加速收敛'], answer:1, explain:'虚链路逻辑连接不连续骨干区的ABR到Area 0'},
{q:'TCP拥塞控制BBR算法与CUBIC的区别是？', level:'高级', options:['BBR基于丢包','BBR基于带宽RTT建模不依赖丢包','CUBIC更适合无线','BBR窗口更小'], answer:1, explain:'BBR基于最大带宽和最小RTT构建模型，CUBIC基于丢包'},
{q:'复杂网络中traceroute出现*号最可能的原因？', level:'高级', options:['链路断了','路由器禁用ICMP超时或策略限速','DNS解析失败','MTU不匹配'], answer:1, explain:'路由器常过滤限速ICMP Time Exceeded导致*，非真丢包'},
{q:'tcpdump抓HTTP GET报文过滤表达式正确是？', level:'高级', options:['port 80 and tcp[20:4]=0x47455420','tcp port http','tcp dst port 80','ether proto http'], answer:0, explain:'0x47455420即"GET "，偏移20(TCP头+选项假设20)，匹配GET请求首4字节'},
{q:'LACP LACPDU中Actor/Partner的状态位AGG是？', level:'高级', options:['表示独立链路','表示可聚合链路','表示超时','表示同步'], answer:1, explain:'AGG=1表明该链路可加入聚合组，否则独立'},
{q:'BGP Community属性no-export的作用是？', level:'高级', options:['不通告给任何邻居','不通告出本AS(EBGP邻居)','不通告给IBGP','不通告给RR'], answer:1, explain:'NO_EXPORT(0xFFFFFF01)不通告到EBGP邻居即不出本AS'},
{q:'IS-IS L1/L2路由器如何避免路由环路？', level:'高级', options:['水平分割','设置ATT位，L1默认路由到最近L2','毒性反转','抑制时间'], answer:1, explain:'L1路由器设ATT位时其他L1路由器生成指向它的默认路由到L2区域'},
{q:'MPLS PHP(倒数第二跳弹出)的作用是？', level:'高级', options:['加速标签交换','减少LER查找标签操作，LER直接查IP','增加标签栈','加密标签'], answer:1, explain:'倒数第二跳弹出标签，LER免去标签查找直接IP转发，节省资源'},
{q:'IPsec IKEv2与IKEv1主模式相比优势是？', level:'高级', options:['IKEv2需要6报文主模式','IKEv2只需4报文+支持NAT-T内置+更安全重协商','IKEv2不支持DPD','IKEv1更适合移动'], answer:1, explain:'IKEv2初始交换4报文，集成NAT-T，MOBIKE支持移动性，更高效'},
{q:'TLS 1.3相比1.2的握手延迟优化是？', level:'高级', options:['无变化','1-RTT握手(甚至0-RTT)省去Key Exchange','增加报文数','固定3-RTT'], answer:1, explain:'TLS1.3简化密码套件默认前向保密，正常1-RTT，恢复会话0-RTT'},
{q:'SYN Cookies防御SYN flood的原理是？', level:'高级', options:['丢弃SYN','SYN-ACK的seq编码源/目的IP端口等信息，不存半连接','增大backlog','防火墙阻断'], answer:1, explain:'Cookie将连接信息编码到序列号，ACK回来校验无需占用半连接队列'},
{q:'STP拓扑变更(TC)后CAM表如何处理？', level:'高级', options:['不变','将CAM老化时间缩短到Forward Delay(默认15秒)加速重新学习','永久删除CAM','禁止学习'], answer:1, explain:'TCN触发TC，交换机将CAM表老化时间设为Forward Delay快速刷新'},
{q:'VXLAN头端复制(Head-End Replication)适用场景是？', level:'高级', options:['大型网络多VTEP','没有组播支持的小网络，单播复制给所有VTEP','任何场景都最优','仅加密场景'], answer:1, explain:'头端复制不需要底层组播，但大表项时VTEP复制负担重'},
{q:'BGP ADD-PATH能力的作用是？', level:'高级', options:['仅能发送最优路径','允许发送多条同前缀路径，实现快速切换和负载','加速收敛','加密BGP'], answer:1, explain:'ADD-PATH允许发多条路径，RR不必只反射最优，可用作快速备份'},
{q:'SIP对话中180 Ringing与183 Session Progress的区别？', level:'高级', options:['180无媒体','183可携带SDP建立早期媒体(如彩铃)','180是最终响应','183表示会话成功'], answer:1, explain:'183带SDP可建早期媒体通道放彩铃/忙音等，180仅提示振铃'},
{q:'Diameter会话与信用控制应用(RFC4006)中CCA初答的Result-Code是DIAMETER_CREDIT_CONTROL_NOT_APPLICABLE表示？', level:'高级', options:['认证失败','该业务无需实时计费，允许会话继续','需要终止','需要重定向'], answer:1, explain:'该码返回表示无需实时信用控制，业务可继续但可能离线计费'},
{q:'PCRF中PCC规则的QCI参数的含义是？', level:'高级', options:['计费标识','QoS等级分类，决定调度策略权重丢包率门限','用户标识','PDN类型'], answer:1, explain:'QCI(QoS Class Identifier)1-9，定义了资源类型/优先级/包延迟/丢包率'},
{q:'TCP Fast Open的条件和作用是？', level:'高级', options:['必须3次握手后才能发数据','SYN或SYN-ACK可携带数据减少1-RTT延迟，需Cookie','只能用于UDP','减少MTU'], answer:1, explain:'TFO使用预先获得的TFO Cookie，SYN中可带应用层数据'},
{q:'DHCPv6 PD(前缀委派)的作用是？', level:'高级', options:['分配单个IPv6给客户端','运营商给CPE分配一段IPv6前缀供CPE下联子网自动划分','分配DNS','仅用于链路本地'], answer:1, explain:'PD(Prefix Delegation)让CPE从运营商获得前缀并自动规划下联网络'},
{q:'策略路由中set ip next-hop recursive的作用是？', level:'高级', options:['直接ARP下一跳','递归查找下一跳可达性(即使非直连)后再决定','强制直连','丢弃数据包'], answer:1, explain:'递归下一跳允许下一跳非直连，通过路由表递归解析最终出接口'},
{q:'MPLS TE RSVP-TE中Explicit Route Object(ERO)的作用是？', level:'高级', options:['加密LSP','显式指定LSP路径各跳，实现约束路由','带宽预留','错误报告'], answer:1, explain:'ERO携带严格/松散指定的路径跳列表，CSPF计算出后放入Path消息建立LSP'},
{q:'VXLAN EVPN Type-2/MAC/IP路由的作用是？', level:'高级', options:['宣告VTEP','MAC地址通告+主机IP可达性，用于二层转发表同步','宣告组播','宣告多播'], answer:1, explain:'EVPN Type 2路由携带MAC(+可选IP)，用于VTEP间同步主机可达性，抑制ARP泛洪'},
{q:'BGP Large Community(RFC8092)相比标准Community的特点是？', level:'高级', options:['只有32位','4字节GlobalAdmin+4字节LocalData共12字节，可表达更丰富策略','不能传播','只能IBGP用'], answer:1, explain:'Large Community格式为12字节(4+4+4)，解决标准32位不够用，适合多域策略'}];

// ================ Linux新增150题 ================
const LIN_NEW = [{q:'ls命令查看隐藏文件的参数是？', level:'基础', options:['-l','-a','-h','-t'], answer:1, explain:'-a或--all显示以.开头的隐藏文件'},
{q:'cd ~的作用是什么？', level:'基础', options:['回到根目录','回到当前用户家目录','回到上一级','进入临时目录'], answer:1, explain:'~代表当前用户家目录，cd ~切换到家目录'},
{q:'pwd命令的作用是？', level:'基础', options:['打印用户目录','打印当前工作目录','打印根目录','切换目录'], answer:1, explain:'pwd是Print Working Directory显示当前绝对路径'},
{q:'mkdir创建多层目录的参数是？', level:'基础', options:['-v','-p','-r','-f'], answer:1, explain:'-p递归创建父目录，不存在则创建'},
{q:'rm删除目录需要加哪个参数？', level:'基础', options:['-f','-r','-i','-v'], answer:1, explain:'-r或-R递归删除，删除目录必须指定'},
{q:'cp复制目录需要加哪个参数？', level:'基础', options:['-f','-r','-p','-u'], answer:1, explain:'-r递归复制整个目录树'},
{q:'touch命令的作用是？', level:'基础', options:['新建文件或修改文件时间戳','复制文件','移动文件','查看文件'], answer:0, explain:'touch可创建空文件，也可更新文件的mtime/atime'},
{q:'cat命令反向显示文件的命令是？', level:'基础', options:['cat -r','tac','rev','tail'], answer:1, explain:'tac反向逐行显示，rev反向每行字符'},
{q:'head默认显示前多少行？', level:'基础', options:['5行','10行','20行','100行'], answer:1, explain:'head默认显示文件前10行'},
{q:'tail实时跟踪文件变化的参数是？', level:'基础', options:['-n','-f','-c','-q'], answer:1, explain:'-f跟随文件增长，实时输出新内容'},
{q:'wc命令统计行数的参数是？', level:'基础', options:['-c','-w','-l','-m'], answer:2, explain:'wc -l统计行数，-w单词数，-c字节数'},
{q:'grep忽略大小写的参数是？', level:'基础', options:['-v','-i','-r','-n'], answer:1, explain:'-i不区分大小写匹配'},
{q:'grep显示行号的参数是？', level:'基础', options:['-i','-n','-v','-c'], answer:1, explain:'-n在匹配行前显示行号'},
{q:'grep反向匹配的参数是？', level:'基础', options:['-i','-v','-r','-l'], answer:1, explain:'-v显示不匹配模式的行'},
{q:'find按文件名搜索的参数是？', level:'基础', options:['-name','-type','-size','-mtime'], answer:0, explain:'-name按文件名匹配，可用通配符'},
{q:'chmod 755表示什么权限？', level:'基础', options:['所有用户读写','所有者rwx，组和其他rx','所有只读','所有者rw'], answer:1, explain:'7=111(rwx) 5=101(r-x) 属主读写执行，其他读执行'},
{q:'chown命令的作用是？', level:'基础', options:['修改权限','修改文件所有者和所属组','修改时间','修改大小'], answer:1, explain:'chown改变文件属主和属组：chown user:group file'},
{q:'软链接和硬链接的区别是？', level:'基础', options:['硬链接跨文件系统','软链接是快捷方式指向原文件路径','软链接inode相同','硬链接可对目录'], answer:1, explain:'软链接(symlink)是特殊文件存目标路径，硬链接同inode'},
{q:'创建软链接的命令是？', level:'基础', options:['cp -s','ln -s','link -s','mkln'], answer:1, explain:'ln -s target linkname创建符号(软)链接'},
{q:'ps命令查看所有进程的参数是？', level:'基础', options:['ps -a','ps aux','ps -f','ps -u'], answer:1, explain:'BSD风格ps aux显示所有用户所有进程，含TTY?'},
{q:'top命令中按CPU排序的快捷键是？', level:'基础', options:['M','P','T','k'], answer:1, explain:'P按CPU使用率排序，M按内存排序'},
{q:'kill发送强制终止信号的参数是？', level:'基础', options:['-HUP','-9','-TERM','-15'], answer:1, explain:'kill -9即SIGKILL强制终止，不可被捕获忽略'},
{q:'df命令显示人类可读格式的参数是？', level:'基础', options:['-a','-h','-T','-i'], answer:1, explain:'-h自动以KB/MB/GB显示大小'},
{q:'du统计目录总大小的参数是？', level:'基础', options:['-a','-s','-h','-d'], answer:1, explain:'-s仅汇总总和，不列出每个子项'},
{q:'free命令默认显示单位是？', level:'基础', options:['KB','MB','GB','字节'], answer:0, explain:'free默认单位KB，-h自动单位，-m为MB'},
{q:'uname -a显示什么？', level:'基础', options:['仅内核版本','内核版本+主机名+架构+时间等全部信息','CPU信息','内存信息'], answer:1, explain:'uname -a显示所有系统信息：内核主机架构版本时间等'},
{q:'uptime命令显示什么？', level:'基础', options:['当前时间','系统运行时间+用户数+1/5/15分钟平均负载','登录历史','CPU频率'], answer:1, explain:'输出：时间 up XX天, X用户, load average: 0.xx,0.xx,0.xx'},
{q:'关机的命令是？', level:'基础', options:['halt','shutdown -h now','poweroff','以上均是'], answer:3, explain:'三者多数系统可执行安全关机，shutdown可带时间计划'},
{q:'重启的命令是？', level:'基础', options:['reboot','shutdown -r now','init 6','以上均是'], answer:3, explain:'三者都可重启，init 6切换到运行级别6即重启'},
{q:'ssh登录远程主机的命令格式是？', level:'基础', options:['ssh host','ssh user@host','ssh host:user','ssh -u user host'], answer:1, explain:'ssh user@hostname是标准格式，user可省略用当前用户'},
{q:'scp复制远程文件到本地的格式是？', level:'基础', options:['scp user@host:/path /local','scp /local user@host:/path','scp -r user@host /local','scp user@host local'], answer:0, explain:'scp 源 目标，远程用user@host:path 到本地为下载'},
{q:'tar解压缩tar.gz的参数组合是？', level:'基础', options:['tar -cvf','tar -xzvf','tar -cjvf','tar -tvf'], answer:1, explain:'-x解压 -z gzip -v详细 -f文件，xzvf解压tar.gz'},
{q:'gzip压缩文件的命令是？', level:'基础', options:['gzip file','gzip -d file','gunzip file','tar gz'], answer:0, explain:'gzip file压缩为file.gz，原文件删除。-d解压'},
{q:'zip压缩目录的命令格式是？', level:'基础', options:['zip -r out.zip dir/','zip out.zip dir/','tar -czf out.zip dir/','7z a out.zip dir'], answer:0, explain:'zip需要-r递归，否则只打包文件不含子目录'},
{q:'用户信息保存在哪个文件？', level:'基础', options:['/etc/passwd','/etc/shadow','/etc/group','/etc/gshadow'], answer:0, explain:'/etc/passwd存用户基本信息(uid/gid/home/shell等)，每行一用户'},
{q:'用户密码哈希保存在哪个文件？', level:'基础', options:['/etc/passwd','/etc/shadow','/etc/gshadow','/etc/secure'], answer:1, explain:'/etc/shadow需root权限，存加密密码和过期策略'},
{q:'添加新用户的命令是？', level:'基础', options:['useradd','adduser','两者都可能是','newuser'], answer:2, explain:'useradd是底层命令，Debian/Ubuntu下adduser是交互友好前端脚本'},
{q:'删除用户的命令是？', level:'基础', options:['userdel','deluser','rmuser','两者都可能是'], answer:3, explain:'userdel是底层，deluser是Debian系前端。-r连家目录删'},
{q:'用户组信息保存在哪个文件？', level:'基础', options:['/etc/passwd','/etc/shadow','/etc/group','/etc/sudoers'], answer:2, explain:'/etc/group存组名、GID、组成员列表'},
{q:'切换到root用户的命令是？', level:'基础', options:['su','su -','sudo -i','以上都可以'], answer:3, explain:'su切换需root密码；sudo -i/su - 使用登录shell加载完整环境'},
{q:'环境变量PATH的作用是？', level:'基础', options:['保存家目录','命令搜索路径列表','保存密码','保存网络配置'], answer:1, explain:'PATH是冒号分隔的目录列表，shell按顺序查找可执行文件'},
{q:'查看所有环境变量的命令是？', level:'基础', options:['env','export -p','printenv','以上都可以'], answer:3, explain:'三者均输出环境变量，printenv可单独打印某个变量'},
{q:'bash脚本的首行shebang是？', level:'基础', options:['#!/bin/bash','#bash','@echo off','/bin/bash'], answer:0, explain:'#!开头的行指定解释器路径，称为shebang/sharp-bang'},
{q:'给脚本添加执行权限的命令是？', level:'基础', options:['chmod +x script.sh','chmod a+x script.sh','chmod 755 script.sh','以上都可以'], answer:3, explain:'+x给用户加执行权限；755=rwxr-xr-x，也可执行'},
{q:'crontab定时任务中计划格式有几个字段？', level:'基础', options:['3','5','6','7'], answer:1, explain:'5字段：分 时 日 月 周 0-59 0-23 1-31 1-12 0-7(0和7周日)'},
{q:'查看当前用户crontab的命令是？', level:'基础', options:['crontab -l','crontab -e','crontab -r','crontab -a'], answer:0, explain:'-l列出 -e编辑 -r删除所有计划任务'},
{q:'/var/log/syslog或/var/log/messages是？', level:'基础', options:['邮件日志','系统全局日志','认证日志','cron日志'], answer:1, explain:'syslog/messages是系统核心日志，多数程序输出汇总于此'},
{q:'/var/log/secure或/var/log/auth.log记录？', level:'基础', options:['邮件','认证登录相关(ssh/sudo)','计划任务','内核崩溃'], answer:1, explain:'RedHat系叫secure，Debian系叫auth.log，认证安全日志'},
{q:'查看内核环形缓存日志的命令是？', level:'基础', options:['dmesg','journalctl -k','两者均是','klog'], answer:2, explain:'dmesg直接读内核环形缓冲；systemd可用journalctl -k'},
{q:'journalctl查看systemd日志，显示最后100行是？', level:'基础', options:['journalctl -a','journalctl -n 100','journalctl -f','journalctl --head'], answer:1, explain:'-n指定行数，类似tail；-f实时跟踪新日志'},
{q:'网络配置文件在CentOS 7下位于？', level:'基础', options:['/etc/network/interfaces','/etc/sysconfig/network-scripts/ifcfg-*','/etc/netplan/','/etc/resolvconf/'], answer:1, explain:'CentOS/RHEL用network-scripts目录下的ifcfg-网卡名配置'},
{q:'Ubuntu 18.04+网络配置工具是？', level:'基础', options:['network','netplan','ifcfg','wcid'], answer:1, explain:'Ubuntu 18.04引入netplan YAML配置：/etc/netplan/*.yaml'},
{q:'查看网卡IP地址的命令是？', level:'基础', options:['ifconfig','ip addr show','ip a','以上都可以'], answer:3, explain:'ifconfig老工具，ip a / ip addr 是新iproute2推荐用法'},
{q:'启动/停止服务在systemd系统用命令？', level:'基础', options:['service name start','systemctl start name','/etc/init.d/name start','以上均有'], answer:3, explain:'systemctl主用；service兼容SysV；脚本直接调用也还常见'},
{q:'设置服务开机自启的命令是？', level:'基础', options:['systemctl enable name','systemctl start name','chkconfig name on','enable和chkconfig因系统而异'], answer:3, explain:'systemd：systemctl enable；CentOS6 chkconfig；update-rc.d是Debian老方式'},
{q:'查看服务状态的命令是？', level:'基础', options:['systemctl status name','service name status','两者都可','ps aux | grep name'], answer:2, explain:'systemctl status详细(Syslog+PID+状态)；service status兼容老系统'},
{q:'SELinux临时关闭的命令是？', level:'基础', options:['setenforce 0','setenforce 1','setenforce off','selinux --disable'], answer:0, explain:'setenforce 0切Permissive模式(仅记录不拦截)；重启失效。1为Enforcing'},
{q:'查看SELinux状态的命令是？', level:'基础', options:['getenforce','sestatus','两者都是','seinfo'], answer:2, explain:'getenforce仅打印Enforcing/Permissive/Disabled；sestatus更详细'},
{q:'防火墙CentOS 7默认是？', level:'基础', options:['iptables','firewalld','ufw','nftables'], answer:1, explain:'RHEL/CentOS 7+默认firewalld动态管理(底层iptables/nft)'},
{q:'Ubuntu默认防火墙前端是？', level:'基础', options:['iptables','ufw','firewalld','pf'], answer:1, explain:'Ubuntu默认ufw(Uncomplicated Firewall)简化iptables配置'},
{q:'查看CPU信息的命令是？', level:'基础', options:['cat /proc/cpuinfo','lscpu','两者都是','cpustat'], answer:2, explain:'/proc/cpuinfo是内核暴露的原始数据；lscpu友好格式化输出'},
{q:'查看内存信息的文件是？', level:'基础', options:['/proc/meminfo','/proc/memory','/sys/mem','/var/log/mem'], answer:0, explain:'/proc/meminfo展示内存总量、空闲、缓存、Swap等详细信息'},
{q:'lsblk命令的作用是？', level:'基础', options:['查看块设备(磁盘分区)列表','格式化磁盘','挂载分区','建立LVM'], answer:0, explain:'lsblk列出所有块设备(磁盘/分区/LVM)及树形挂载点、大小'},
{q:'fdisk命令的作用是？', level:'基础', options:['格式化分区','MBR分区表操作工具','挂载','查看内存'], answer:1, explain:'fdisk创建/删除/修改MBR分区表；GPT用gdisk或parted更合适'},
{q:'mkfs.ext4命令的作用是？', level:'基础', options:['创建ext4文件系统(格式化)','检查ext4错误','修复ext4','扩容ext4'], answer:0, explain:'mkfs=make filesystem在分区上写入ext4文件系统元数据'},
{q:'mount命令的作用是？', level:'基础', options:['挂载文件系统到目录','卸载文件系统','格式化文件系统','创建目录'], answer:0, explain:'mount设备 挂载点 挂载文件系统；umount卸载'},
{q:'开机自动挂载配置文件是？', level:'基础', options:['/etc/fstab','/etc/mtab','/etc/auto.mount','/proc/mounts'], answer:0, explain:'/etc/fstab中每行定义：设备 挂载点 类型 options dump pass'},
{q:'/etc/fstab第4列常用defaults代表？', level:'基础', options:['只读','rw,suid,dev,exec,auto,nouser,async','全部选项关闭','自动卸载'], answer:1, explain:'defaults集合多个常见挂载选项，不同文件系统略有扩展'},
{q:'LVM中物理卷的缩写是？', level:'基础', options:['PV','VG','LV','PE'], answer:0, explain:'Physical Volume物理卷=底层真实磁盘/分区加入LVM的单元'},
{q:'LVM中卷组的缩写是？', level:'基础', options:['PV','VG','LV','LE'], answer:1, explain:'Volume Group卷组=由一个或多个PV组成的存储资源池'},
{q:'LVM中逻辑卷的缩写是？', level:'基础', options:['PV','VG','LV','PE'], answer:2, explain:'Logical Volume逻辑卷=从VG切出可使用的分区，可格式化挂载'},
{q:'创建物理卷命令是？', level:'基础', options:['pvcreate','vgcreate','lvcreate','pvscan'], answer:0, explain:'pvcreate /dev/sdb1 将分区标记为LVM物理卷PV'},
{q:'扩展逻辑卷大小的命令是？', level:'基础', options:['lvextend -L +10G /dev/vg/lv','lvs','resize2fs','lvresize'], answer:0, explain:'lvextend扩展LV容量；然后还需resize2fs/xfs_growfs扩展文件系统'},
{q:'RPM软件包安装命令是？', level:'基础', options:['rpm -ivh pkg.rpm','yum install pkg','dnf install pkg','以上均是(RHEL系不同层)'], answer:3, explain:'rpm底层直接装rpm；yum/dnf解决依赖从仓库装并升级'},
{q:'查询文件属于哪个RPM包的命令是？', level:'基础', options:['rpm -qf /path/file','rpm -qa','rpm -ql pkg','rpm -qi pkg'], answer:0, explain:'rpm -qf查询路径所属包；-qa所有已装包；-ql包内文件列表'},
{q:'Debian系软件包管理工具底层是？', level:'基础', options:['rpm','dpkg','apt','apk'], answer:1, explain:'dpkg是deb包底层工具；apt/apt-get是高层依赖解决工具'},
{q:'查询deb包中文件列表的命令是？', level:'基础', options:['dpkg -L pkg','dpkg -l','dpkg -S /path','apt list'], answer:0, explain:'dpkg -L列出包内所有文件安装位置；-S查文件归属包'},
{q:'apt update的作用是？', level:'基础', options:['升级所有软件','刷新软件包索引缓存','删除缓存','自动删除不用的包'], answer:1, explain:'apt update只拉取仓库元数据；升级软件用apt upgrade'},
{q:'bash中$?变量含义是？', level:'基础', options:['当前脚本PID','上一条命令退出状态码','全部参数','参数个数'], answer:1, explain:'$?为0表示上条命令成功，非0失败，shell脚本if判断常用'},
{q:'bash中$#变量含义是？', level:'基础', options:['脚本名','参数个数','全部参数串','最后参数'], answer:1, explain:'$#是位置参数个数，如./a.sh a b中$#=2'},
{q:'ifconfig查看网卡RX/TX代表？', level:'基础', options:['接收/发送字节/包数','读/写速率','上行/下行IP','重传/错误'], answer:0, explain:'RX=Received接收，TX=Transmitted发送，含bytes packets errors drops'},
{q:'ip link set eth0 up的作用是？', level:'基础', options:['配置IP','启用网卡(链路UP)','重启网卡','删除网卡'], answer:1, explain:'启用物理/虚拟网卡；down禁用。配IP用ip addr add'},
{q:'ulimit的作用是？', level:'基础', options:['设置用户磁盘配额','设置shell资源限制(打开文件数等)','限制CPU使用率','限制内存'], answer:1, explain:'ulimit -n设置进程最大打开文件数；-a查看当前所有限制'},
{q:'LANG环境变量控制？', level:'基础', options:['时区','系统默认语言locale','键盘布局','终端颜色'], answer:1, explain:'LANG=zh_CN.UTF-8 设置语言地区和字符编码，影响输出提示等'},
{q:'timedatectl set-timezone的作用是？', level:'基础', options:['设置时间','设置时区，如Asia/Shanghai','设置NTP服务器','设置硬件时钟'], answer:1, explain:'systemd系统timedatectl set-timezone Asia/Shanghai 设时区'},
{q:'nohup command &的作用是？', level:'基础', options:['前台运行命令','忽略挂起信号后台运行，即使退出终端也继续','暂停进程','优先运行'], answer:1, explain:'nohup忽略SIGHUP防止终端关闭杀进程；&放入后台'},
{q:'Linux文件系统目录/root是？', level:'基础', options:['根目录','root超级用户家目录','临时文件','用户家目录父目录'], answer:1, explain:'/是根目录；/root是管理员root的家目录，普通用户/home/user'},
{q:'Linux临时目录/tmp默认特性？', level:'基础', options:['永久保存','重启清理部分(如systemd-tmpfiles)或特殊挂载tmpfs','只读','仅root写'], answer:1, explain:'/tmp默认所有用户可写(sticky bit)，重启可能清理或根据age清理'},
{q:'/proc目录是什么？', level:'基础', options:['普通配置目录','虚拟文件系统反映内核/进程运行时状态','备份目录','日志目录'], answer:1, explain:'/proc是procfs虚拟文件系统，/proc/[pid]进程信息，/proc/sys内核参数'},
{q:'/sys目录是什么？', level:'基础', options:['内核源码','sysfs虚拟文件系统，暴露硬件/驱动/设备模型到用户态','系统配置','备份'], answer:1, explain:'sysfs将内核设备模型、驱动参数等以树形目录导出，udev等依赖'},
{q:'Linux开机启动顺序中systemd的第一个进程是？', level:'基础', options:['init','PID=1的systemd','bash','kernel'], answer:1, explain:'systemd系统内核装载后启动init即systemd(PID=1)，负责其他所有进程'},
{q:'rsync -avz src/ dest的作用是？', level:'进阶', options:['增量同步src/到dest，归档压缩详细','完整复制','仅比较不复制','加密传输'], answer:0, explain:'rsync -a归档保留权限时间等；-v详细；-z压缩；增量算法只传差异块'},
{q:'AWK打印第3列的命令是？', level:'进阶', options:["awk '{print $3}'","awk 'NR==3'","awk -F: '{print $0}'","awk '{print NF}'"], answer:0, explain:'默认空白为分隔符，$1...$n字段，$0整行，NF字段数，NR行号'},
{q:'AWK指定分隔符为冒号的参数是？', level:'进阶', options:['-d:','-F:','--delim :','-s:'], answer:1, explain:'-F或FS变量指定字段分隔符，支持正则表达式'},
{q:'sed替换命令将file中的A全部替换为B是？', level:'进阶', options:["sed 's/A/B/g' file","sed 's/A/B/' file","sed -n 'A/B/p' file","sed 'y/A/B/' file"], answer:0, explain:'s///g全局(g)替换；无g只换每行第一个匹配'},
{q:'sed -i参数的作用是？', level:'进阶', options:['忽略大小写','原地修改文件(in-place)','插入','编辑模式'], answer:1, explain:'-i直接修改原文件(可备份如-i.bak)'},
{q:'diff比较两个目录差异，递归+统一格式是？', level:'进阶', options:['diff a b','diff -r -u dir1 dir2','diff -Nur dir1 dir2','diff -y dir1 dir2'], answer:2, explain:'-r递归；-u统一格式(unified)3行上下文；-N把不存在当空文件用于补丁'},
{q:'patch命令的作用是？', level:'进阶', options:['对比文件','应用diff生成的补丁文件','生成补丁','备份文件'], answer:1, explain:'patch -p1 < file.patch 把diff生成的差异应用到源文件'},
{q:'find按修改时间查找7天内修改的文件是？', level:'进阶', options:['find . -mtime 7','find . -mtime -7','find . -mtime +7','find . -atime 7'], answer:1, explain:'-mtime N：N×24小时，-N之内，+N之外，正好N无±。-7表示7天内修改'},
{q:'find查找大于100M的文件是？', level:'进阶', options:['find . -size 100M','find . -size +100M','find . -size -100M','find . -size 100m'], answer:1, explain:'-size +N比N大；单位M=1024*1024字节，注意大小写区别c/k/M/G'},
{q:'chmod 4755中首位4代表什么？', level:'进阶', options:['SetUID','SetGID','Sticky Bit','ACL'], answer:0, explain:'4=SUID执行时以文件属主身份运行；2=SGID；1=Sticky(/tmp就是1777)'},
{q:'chmod 2775中2的作用是？', level:'进阶', options:['SUID','SGID，新建文件继承目录所属组','Sticky','SUID+SGID'], answer:1, explain:'2=SGID，目录设置SGID后新建文件/子目录继承其组(组协作常用)'},
{q:'chmod 1777中1代表？', level:'进阶', options:['SGID','SUID','Sticky Bit，只有文件所有者/root能删除','不可修改'], answer:2, explain:'Sticky粘滞位：目录中仅文件所有者、目录所有者或root能删除'},
{q:'/etc/sudoers文件应如何安全编辑？', level:'进阶', options:['vi /etc/sudoers','visudo命令(含语法检查)','编辑后chmod','root用nano即可'], answer:1, explain:'visudo锁定文件并检查语法，防止sudo整组失效；-f指定其他文件'},
{q:'bash脚本中for循环遍历当前目录文件？', level:'进阶', options:["for f in $(ls); do ... done","for f in *; do ... done","for i in `dir`; do ... done","for f in .; do ... done"], answer:1, explain:'直接用glob通配*更安全，避免空格/特殊字符文件名问题'},
{q:'bash条件判断中-z "$var"表示？', level:'进阶', options:['变量非空','变量长度为0(空串)','文件存在','数字等于0'], answer:1, explain:'字符串测试：-z空为真；-n非空为真；=相等；!=不等'},
{q:'bash中if [ -f file ]表示？', level:'进阶', options:['file是目录','file存在且是普通文件','file可执行','file可读'], answer:1, explain:'文件测试：-f普通文件存在；-d目录；-x可执行；-r可读；-e存在'},
{q:'top中VIRT/RES/SHR分别表示？', level:'进阶', options:['虚拟内存总量/常驻物理内存/共享内存','虚拟/交换/缓存','用户/系统/空闲','读/写/共享'], answer:0, explain:'VIRT=全部地址空间；RES=实际驻留RAM；SHR=与其他进程共享内存量'},
{q:'nice值范围和含义是？', level:'进阶', options:['-20~19，越小优先级越高','0~39，越大越高','-100~100','0~100%'], answer:0, explain:'nice值-20(最高优先级)~19(最低)，默认0；root可设负值'},
{q:'strace命令的作用是？', level:'进阶', options:['统计CPU时间','追踪系统调用和信号','追踪网络连接','追踪库函数调用'], answer:1, explain:'strace -p PID或strace cmd打印所有系统调用(open/read/write/close等)，排查问题利器'},
{q:'ltrace命令的作用是？', level:'进阶', options:['追踪系统调用','追踪动态库函数调用','追踪锁竞争','追踪malloc'], answer:1, explain:'ltrace追踪用户态调用的动态库(libc等)函数调用，与strace互补'},
{q:'sar命令作用是？', level:'进阶', options:['即时查看CPU','系统活动报告(收集/查看历史CPU/内存/IO/网络)','调度任务','安全审计'], answer:1, explain:'sar来自sysstat，可历史回溯性能，-u CPU，-r内存，-b IO，-n DEV网络'},
{q:'vmstat 1 5输出r/b列含义？', level:'进阶', options:['运行/等待队列(可运行进程数/不可中断睡眠数)','读/写字节','接收/发送','root/备份数'], answer:0, explain:'r：CPU等待队列长度(负载参考)；b：等待IO被阻塞不可中断进程数'},
{q:'iostat -x 1中%util含义是？', level:'进阶', options:['使用率(设备忙时间占比)','利用率百分比CPU','用户空间时间','空闲率'], answer:0, explain:'%util接近100%通常表示该磁盘IO饱和，并发模型可能低但代表忙'},
{q:'pidof和pgrep的区别是？', level:'进阶', options:['pidof通过/proc查找，pgrep用/proc+更多匹配，都能得到PID','pidof精确匹配名；pgrep支持正则/uid/父进程','两者完全相同','pgrep只能找用户进程'], answer:1, explain:'pidof 进程名→PID列表；pgrep [-f 命令行正则]更强大支持部分匹配/高级筛选'},
{q:'lsof -p PID的作用是？', level:'进阶', options:['查看进程打开的文件描述符(文件/网络/socket/管道)','杀死PID','暂停PID','查看进程树'], answer:0, explain:'列出进程所有打开的fd：含常规文件、目录、socket(含IPv4/IPv6/TCP/UDP)、pipe等'},
{q:'fuser /path/file的作用是？', level:'进阶', options:['查找正在使用该文件/挂载点的进程','文件所有者','文件修改用户','删除文件用户'], answer:0, explain:'fuser -m /mnt查找占用挂载点的进程，常用于卸载前处理；-k可直接杀'},
{q:'umount提示device is busy时？', level:'进阶', options:['强制umount -f','先fuser/lsof找出占用进程终止或切换目录再卸载','直接rm','reboot'], answer:1, explain:'umount -l lazy detach在IO结束后卸载(风险)；最佳先找占用者(常见当前shell cwd)'},
{q:'inode耗尽表现是df -h仍有空间但无法写文件？', level:'进阶', options:['磁盘坏道','inode用完(大量小文件)，用df -i查看','权限问题','RAM满'], answer:1, explain:'df -i查看IUse%；小文件或邮件队列场景常见，创建文件需inode和数据块两者'},
{q:'LVM给新磁盘扩容根分区顺序正确是？', level:'进阶', options:['mkfs→mount→pvcreate','pvcreate→vgextend→lvextend→resize2fs/xfs_growfs','lvcreate→mkfs','vgcreate→pvcreate'], answer:1, explain:'先把磁盘做成PV，加入VG(vgextend)，扩LV(lvextend)，最后扩文件系统才有效'},
{q:'RAID5最少需要几块盘及容错？', level:'进阶', options:['2块，容1块','3块，容1块故障','4块，容2块','3块，容2块'], answer:1, explain:'RAID5分布式奇偶校验N≥3，任意1块盘坏可重建；写有校验写开销'},
{q:'mdadm创建RAID1的命令？', level:'进阶', options:['mdadm --create /dev/md0 -l 1 -n 2 /dev/sdb /dev/sdc','mdadm -A /dev/md0','raid create','parted --raid'], answer:0, explain:'-l 1级别raid1，-n 2成员盘2个。保存配置到mdadm.conf以防重启丢失'},
{q:'xfs_growfs针对什么场景？', level:'进阶', options:['ext2/3/4扩容','xfs文件系统已挂载的在线扩容','xfs缩容','修复xfs'], answer:1, explain:'xfs不支持离线/挂载点外操作，挂载状态执行xfs_growfs扩大到LV大小'},
{q:'swap分区创建启用步骤是？', level:'进阶', options:['mkfs.swap→mount','mkswap /dev/sdXn → swapon /dev/sdXn，fstab加一行','mkswapfile→on','free -s'], answer:1, explain:'mkswap格式化swap区或swapfile→swapon启用；fstab写defaults或sw 确保开机'},
{q:'systemd查看单元文件位置？', level:'进阶', options:['systemctl list-units','systemctl status unit','systemctl cat unit','systemd-analyze'], answer:2, explain:'systemctl cat name.service 显示合并后单元内容并标注原始文件路径'},
{q:'systemd-analyze blame的作用是？', level:'进阶', options:['分析启动耗时，各服务按耗时排序显示','分析依赖图','分析日志','分析崩溃'], answer:0, explain:'排查开机慢神器，显示每个服务启动用时时长'},
{q:'PAM是什么？', level:'进阶', options:['包管理','可插拔认证模块(Pluggable Auth Modules)统一认证接口','分区管理','电源管理'], answer:1, explain:'/etc/pam.d/*配置PAM栈，login/sshd/sudo通过PAM调用不同认证模块(pam_unix等)'},
{q:'SELinux上下文格式user:role:type:level中type用于？', level:'进阶', options:['用户标识','主要匹配规则的类型标签(如httpd_sys_content_t)','角色','安全级别'], answer:1, explain:'大多数策略基于类型强制TE，进程域type访问文件type，setroubleshoot辅助分析'},
{q:'restorecon -Rv /var/www的作用是？', level:'进阶', options:['改权限','根据规则恢复SELinux文件上下文标签到默认正确值','卸载context','关闭SELinux'], answer:1, explain:'经常cp/mv跨目录导致context错，restorecon按/etc/selinux/targeted/contexts恢复'},
{q:'firewalld永久开放80/tcp规则命令？', level:'进阶', options:['firewall-cmd --add-port=80/tcp','firewall-cmd --permanent --add-port=80/tcp && firewall-cmd --reload','iptables -A','firewall-config'], answer:1, explain:'--permanent写永久规则，不加--permanent重启后失效；--reload加载永久配置'},
{q:'ufw允许来自192.168.1.0/24的SSH？', level:'进阶', options:['ufw allow 22','ufw allow from 192.168.1.0/24 to any port 22','ufw enable ssh','ufw insert'], answer:1, explain:'可按源地址+端口写规则；然后ufw status verbose查看顺序'},
{q:'tcp_wrapper(/etc/hosts.allow deny)的作用是？', level:'进阶', options:['防火墙','基于libwrap的简单访问控制，被编译启用wrap的服务(如sshd/tcpd)识别','路由','NAT'], answer:1, explain:'仅对编译时加libwrap的服务有效；sshd常用。现代基本由firewalld/nftables/sshd_config替代'},
{q:'Fail2ban的作用是？', level:'进阶', options:['防DDoS','扫描日志按规则封禁暴力破解源IP(iptables/nftables/firewalld)','防病毒','防XSS'], answer:1, explain:'Fail2ban正则解析auth.log等，超过阈值触发封禁动作，保护ssh等服务'},
{q:'awk中NR和FNR的区别是？', level:'高级', options:['相同，行号','NR全局累计行号；FNR当前文件行号，多文件时重置','NR字段数；FNR行号','NR打印；FNR格式化'], answer:1, explain:'处理多文件NR持续加，FNR每新文件从1开始。awk 'NR==FNR{a[$0];next}$0 in a' file1 file2取交集'},
{q:'bash中${var##*/}作用是？', level:'高级', options:['取文件名去掉最长前缀*/(basename效果)','取扩展名','取目录名','大写'], answer:0, explain:'参数扩展##贪婪去掉前缀匹配；${var%/*}去后缀最后/(dirname)；#非贪婪，%%贪婪后缀'},
{q:'bash中${var:-default}和${var:=default}区别是？', level:'高级', options:['相同',':-仅本次展开用默认不赋值；:=若空则赋值给var并使用',':=永久，:-临时错误',':-报错'], answer:1, explain:'未设或空时：:-替换但不改var；:=同时将default写入var；:?空时报错退出'},
{q:'sed中N和P和D组合作用？', level:'高级', options:['多行模式空间处理，N读下一行拼接，P打印模式空间首行，D删除首行不读取新输入','N=编号P=打印D=删除整行','仅处理注释','仅处理数字'], answer:0, explain:'典型跨多行匹配模式，如sed '$!N;/^a.*\\nb$/!P;D' 跨行匹配等'},
{q:'进程D状态(不可中断睡眠)什么含义？', level:'高级', options:['僵尸','等待IO完成(内核路径中不可被信号中断，ps TASK_UNINTERRUPTIBLE)','停止','空闲'], answer:1, explain:'常见NFS/磁盘IO卡顿；此时kill -9无效；wchan字段可看阻塞在内核哪函数'},
{q:'僵尸进程(Z)和孤儿进程区别？', level:'高级', options:['相同','僵尸父未wait子已结束；孤儿父死子存被init/systemd收养','孤儿死了僵尸活着','无区别'], answer:1, explain:'僵尸占PID资源，需处理父进程(wait或杀父让其被init收养后清)；孤儿无害'},
{q:'cgroup v1和v2区别核心？', level:'高级', options:['无','v2统一层次单树，支持真正按进程组资源核算(非v1多树竞争)，systemd新系统用v2多','v1更好','v2仅内存'], answer:1, explain:'v1按子系统(cpu,cpuacct,memory,blkio)独立层级造成复杂；v2单棵进程树加多个controller属性。'},
{q:'Linux OOM Killer如何选择受害者？', level:'高级', options:['随机','基于oom_score(+oom_score_adj调整)，倾向杀占内存大、非关键、非root、nice高的','最后启动的','最占CPU的'], answer:1, explain:'oom_score=基准+内存占比换算；进程可设oom_score_adj(-1000~+1000)，-1000则不会被OOM杀。'},
{q:'内核参数overcommit_memory=2含义是？', level:'高级', options:['允许任意过量申请','严格模式：申请不超过Commit Limit(物理内存比例+swap)才成功','禁止申请','保守允许'], answer:1, explain:'0默认启发式；1总是允许(数据库场景)；2严格，与overcommit_ratio或vm.overcommit_kbytes配合上限。'},
{q:'dmesg中Out of memory: Killed process XXX (name)发生后？', level:'高级', options:['立即重启','OOM killer杀了top受害者释放内存，系统通常继续运行','内核panic','磁盘损坏'], answer:1, explain:'记录被杀进程UID、VmRSS、anon/file等；检查oom_score_adj和程序内存泄漏'},
{q:'systemd Slice=和Delegate=yes的含义？', level:'高级', options:['无','放入指定cgroup slice；Delegate=yes允许该单元内部自己管理子cgroup(如容器)','仅安全','仅日志'], answer:1, explain:'systemd-run --scope --slice=app.slice podman run；Delegate=1交给容器runtime管理cgroup子树'},
{q:'NetworkManager与systemd-networkd的主要区别？', level:'高级', options:['完全相同','NM动态、桌面/无线/多连接好；networkd轻量、静态服务器/容器、确定性高配置简洁','NM更安全','networkd无CLI'], answer:1, explain:'服务器云主机常用networkd(通过netplan或直接.network文件)；笔记本/DHCP多WiFi选NM'},
{q:'PAM pam_limits.so /etc/security/limits.conf中soft/hard nofile区别？', level:'高级', options:['相同','soft=当前限制可由进程自提升到hard上限；hard=root才能改的上限值','soft严格','hard可超'], answer:1, explain:'用户会话生效，nproc进程数、nofile打开文件数等；soft非特权用户可ulimit -Sn调≤hard'},
{q:'LVM快照(snapshot)原理？', level:'高级', options:['全量复制','Copy-on-Write：首次写源块前先把原块写入快照区；读快照时未改块从源读，已改块从快照区读','仅索引','压缩备份'], answer:1, explain:'快照LV大小按写压力估算；写负载高很快用满快照自动失效。lvs可显示Data%使用率。'},
{q:'drbd是什么核心特性？', level:'高级', options:['网络RAID1，块设备跨主机同步复制，高可用常用双活主备','本地RAID','负载均衡','集群文件系统'], answer:0, explain:'DRBD=Distributed Replicated Block Device，主备复制；Pacemaker+DRBD经典共享存储替代HA方案'},
{q:'Kpatch/KGraft和Ksplice作用是？', level:'高级', options:['内核补丁管理','内核活补丁：不重启热替换内核函数修复安全/严重bug，保持运行时间','用户态补丁','库热更'], answer:1, explain:'kexec快速重启；kpatch是红帽；kGraft/ksplice属其他发行。关键补丁无需重启生效，生产可用'},
{q:'systemd-nspawn相比chroot增强？', level:'高级', options:['无','完整容器化：隔离UTS/IPC/PID/网络+cgroup资源限制，可像容器启动完整OS镜像','仅更安全','仅兼容老内核'], answer:1, explain:'类似"chroot on steroids"，可-n建私有netns、-M注册machinectl、--bind挂载、systemd-networkd集成'}];

// ================ 前端新增150题 ================
const FE_NEW = [{q:'HTML中DOCTYPE声明的作用是？', level:'基础', options:['引入样式','声明HTML版本，让浏览器用标准模式渲染','定义脚本','注释'], answer:1, explain:'DOCTYPE告知文档HTML版本，浏览器选标准/怪异模式，影响盒模型等渲染'},
{q:'<meta charset="UTF-8">作用是？', level:'基础', options:['页面标题','声明文档字符编码为UTF-8，防乱码','关键字','作者'], answer:1, explain:'charset元信息声明字符编码，必须放<head>最前，确保中文不乱码'},
{q:'<a target="_blank">作用是？', level:'基础', options:['当前页打开','新标签/新窗口打开链接','无效果','同框架打开'], answer:1, explain:'_blank新窗口；_self当前；_parent父框架；_top顶层。加rel=noopener更安全'},
{q:'引入外部CSS的标签是？', level:'基础', options:['<style>','<link>','<script>','<css>'], answer:1, explain:'<link rel="stylesheet" href="style.css">放在head中外部引入；<style>内嵌样式'},
{q:'引入外部JavaScript的标签是？', level:'基础', options:['<script src="a.js">','<link src="a.js">','<style src="a.js">','<javascript src="a.js">'], answer:0, explain:'<script>标签src属性引入外部JS；可放body末尾减少首屏阻塞'},
{q:'defer和async加载脚本区别是？', level:'基础', options:['相同','defer按序在DOM解析后执行；async加载完立即执行乱序','async更慢','defer立刻执行'], answer:1, explain:'两者均并行下载不阻塞HTML；defer顺序执行适合依赖关系；async无依赖统计脚本适用'},
{q:'HTML5新增语义化标签不包括？', level:'基础', options:['<header>','<nav>','<section>','<table>'], answer:3, explain:'<table>早就有；新增header/footer/nav/main/article/section/aside语义化标签利于SEO和可读'},
{q:'<img>必须的属性是？', level:'基础', options:['src','alt','src和alt都非常重要','width'], answer:2, explain:'src必填；alt替代文本无障碍和SEO必需，图片加载失败时显示，两者都应写'},
{q:'<ul>和<ol>区别是？', level:'基础', options:['相同','ul无序列表(unordered)圆点；ol有序(ordered)1.2.3.','ul是横向；ol是纵向','ul下拉；ol弹出'], answer:1, explain:'<ul><li>用于无序，默认•；<ol><li>用于数字字母排序，默认1 2 3'},
{q:'创建下拉菜单的标签是？', level:'基础', options:['<input>','<select><option>','<menu>','<dropdown>'], answer:1, explain:'<select multiple>多选或单选；<optgroup>分组选项'},
{q:'CSS选择器优先级从高到低正确是？', level:'基础', options:['标签>类>ID>!import','!important>行内>ID(#)>类(.)/伪类/属性>标签/伪元素>通配','类>ID','行内最低'], answer:1, explain:'权重：!important>行内1000>ID 100>类/伪类/属性10>标签/伪元素1；通配*为0。同权重后者覆盖前者'},
{q:'CSS盒模型box-sizing:border-box表示？', level:'基础', options:['默认盒模型','宽高包含content+padding+border，布局更直观','仅border算宽','宽高只算content'], answer:1, explain:'现代前端常用*{box-sizing:border-box}统一；content-box默认，宽高仅内容区'},
{q:'margin合并(塌陷)发生在哪？', level:'基础', options:['所有元素','垂直方向相邻块级元素；父子块无padding/border/content分隔时','内联元素','水平方向'], answer:1, explain:'上下margin非简单相加，取大者。BFC(overflow:hidden/flex等)可防止。水平margin不合并'},
{q:'display:none和visibility:hidden区别？', level:'基础', options:['相同','display:none完全脱离文档流不占空间；visibility:hidden仍占空间仅视觉隐藏','前者性能好','后者更兼容'], answer:1, explain:'display:none重排+重绘；visibility仅重绘。过渡动画需从非none值开始'},
{q:'实现水平垂直居中父position:relative,子应该？', level:'基础', options:['子 position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)','子 float:center','子 margin:auto','text-align:center'], answer:0, explain:'absolute+50%偏移+反向translate是最常用不定宽高居中法；或flex:justify+align-items:center'},
{q:'Flex布局主轴对齐属性是？', level:'基础', options:['align-items','justify-content','flex-wrap','flex-direction'], answer:1, explain:'justify-content主轴(X默认)对齐；align-items交叉轴；align-content多行堆叠对齐'},
{q:'Flex:1是哪三个属性的简写？', level:'基础', options:['flex-grow+flex-shrink+flex-basis','flex-direction+flex-wrap+flex','auto+none+1','grow+shrink+width'], answer:0, explain:'flex:1 => flex-grow:1; flex-shrink:1; flex-basis:0%；实现等比分配剩余空间'},
{q:'媒体查询语法@media (max-width:768px)含义？', level:'基础', options:['大屏生效','视口宽度≤768px时应用里面样式(移动端适配)','打印样式','横屏'], answer:1, explain:'max-width=断点以下；min-width=以上。移动端优先常写min-width升序堆叠媒体查询。'},
{q:'CSS定位position:sticky作用是？', level:'基础', options:['固定视口','滚动到阈值前相对定位，之后固定(sticky吸附)，如吸顶导航','绝对定位','相对定位'], answer:1, explain:'sticky需要top/left等阈值；祖先元素不能overflow:hidden；兼容性现代浏览器好'},
{q:'CSS中em和rem区别是？', level:'基础', options:['相同','em相对父元素字号；rem相对根html字号做响应式自适应','rem相对父','em固定单位'], answer:1, explain:'html{font-size:16px}则1rem=16px；组件内边距可用em相对组件字号缩放'},
{q:'JS中==和===区别？', level:'基础', options:['相同','==允许类型转换后比较；===严格等同时比较类型和值(推荐)','===更快但不准','==更安全'], answer:1, explain:'推荐默认用===和!==；注意NaN与任何都不等，用Number.isNaN()判断'},
{q:'var let const区别是？', level:'基础', options:['相同','var函数提升、可重复声明；let/const块级作用域、暂时性死区；const值不可变(对象内部可变)','const可变'], answer:1, explain:'现代优先const，需要重新赋值才用let；避免var。const声明的数组push/对象改属性是可以的'},
{q:'箭头函数与普通函数区别？', level:'基础', options:['相同','箭头函数无自己this继承外层；不能当构造函数；无arguments；不能作Generator','箭头函数性能差','箭头函数有arguments'], answer:1, explain:'const fn=()=>{} 词法this，定时器和事件回调常用来避免that=this保存'},
{q:'数组方法map和forEach区别是？', level:'基础', options:['都是遍历','map返回等长新数组不修改原数组；forEach仅遍历返回undefined','map更快','forEach更函数式'], answer:1, explain:'纯函数转换用map；副作用(打印/改外部/请求)用forEach。链式Promise.then返回用map非forEach'},
{q:'typeof null的结果是？', level:'基础', options:['"null"','"object"(历史遗留bug)','"number"','undefined'], answer:1, explain:'typeof null==="object"是JS第一版设计错误，Array/Date也是object需Array.isArray()/toString.call判断'},
{q:'Promise三种状态是？', level:'基础', options:['开始/中间/结束','pending(等待)/fulfilled(成功)/rejected(失败)，状态不可逆','new/old/error','sync/async/error'], answer:1, explain:'Promise构造函数内resolve→fulfilled或reject→rejected；一旦fulfilled/reject不可再变'},
{q:'async function返回什么？', level:'基础', options:['undefined','返回Promise对象，可用await取值','Generator','直接值'], answer:1, explain:'async函数即使return 1也会包装成Promise<1>；await仅在async函数或ESM顶层可用'},
{q:'事件冒泡和捕获区别是？', level:'基础', options:['相同','冒泡：从目标向根(document)传播；捕获：从根向目标；addEventListener第三参数true=捕获','冒泡更快','捕获旧浏览器才用'], answer:1, explain:'标准流：捕获阶段→目标阶段→冒泡阶段。stopPropagation阻止继续传播，preventDefault阻止默认行为'},
{q:'事件委托/代理是什么？', level:'基础', options:['事件仅自己响应','父元素监听事件，通过e.target判断匹配子元素统一处理动态元素也有效','取消事件','多事件合并'], answer:1, explain:'适合列表/表格动态增删项，不用每个子项绑定；减少监听器数量提升性能'},
{q:'localStorage和sessionStorage区别是？', level:'基础', options:['相同','localStorage同源持久化永久(除非手动清)；sessionStorage同源同标签页关闭即清','localStorage容量小','sessionStorage跨标签'], answer:1, explain:'容量约5MB同源；存值只能字符串，对象要JSON.stringify。sessionStorage刷新仍在，标签页关就清'},
{q:'AJAX核心对象是？', level:'基础', options:['ActiveX','XMLHttpRequest','HTTPRequest','AJAX'], answer:1, explain:'var xhr=new XMLHttpRequest(); open/send/onreadystatechange；现代多封装用fetch/axios'},
{q:'HTTP请求方法PUT和POST区别习惯？', level:'基础', options:['相同','PUT幂等多次调用结果相同(通常更新整体)；POST非幂等创建(如新增)','POST改数据','PUT新建'], answer:1, explain:'RESTful常用规范：GET查/POST建/PUT整体改/PATCH局部改/DELETE删；幂等=重复执行N次=1次结果'},
{q:'Cookie的HttpOnly属性作用是？', level:'基础', options:['只能HTTP用','禁止JS访问document.cookie读取，防XSS窃取会话Cookie','仅HTTPS','仅首页用'], answer:1, explain:'HttpOnly+Secure+SameSite配合是防会话劫持的关键安全三属性'},
{q:'Cookie的Secure属性作用是？', level:'基础', options:['防篡改','仅HTTPS传输发送Cookie，HTTP下不会携带，防中间人','仅本地','仅签名'], answer:1, explain:'HTTPS整个链路TLS加密，Secure保证Cookie不会被HTTP明文请求发出'},
{q:'SameSite=Strict/Lax/None区别？', level:'基础', options:['相同','Strict严格完全禁止跨站带Cookie；Lax允许顶层GET导航跨站带；None允许但必须Secure一起','None=严格'], answer:1, explain:'现代浏览器默认Lax；第三方登录/嵌入需None+Secure，否则跨站请求将不带Cookie'},
{q:'Vue/React中"key"作用是？', level:'基础', options:['美观','Diff虚拟DOM算法中唯一标识项，提高列表更新准确率避免复用错误','数据绑定','样式标记'], answer:1, explain:'不要用随机key(每次渲染变全重建)；不要用index(插入删除时兄弟key错位)'},
{q:'Vue v-model本质语法糖？', level:'基础', options:['双向绑定原语','v-bind:value(或:value)+v-on:input(或@input)合成双向','事件绑定','计算属性'], answer:1, explain:'组件内model:{prop,event}可自定义v-model绑定的prop和事件名'},
{q:'React受控组件和非受控组件区别？', level:'基础', options:['相同','受控：表单值由state通过onChange控制value；非受控：DOM原生自己维护ref取','非受控推荐','受控不推荐'], answer:1, explain:'绝大多数场景受控组件更易处理(校验、联动、重置)；非受控适合文件上传等个别场景'},
{q:'React Hooks中useEffect第二个参数[]依赖数组作用是？', level:'基础', options:['返回数组','空数组仅在挂载时执行1次卸载清；非空则依赖变化才重执行','参数数组','错误捕获'], answer:1, explain:'不写第二个参数=每次渲染后都执行；函数返回值是cleanup在下次执行前或卸载时调用'},
{q:'Webpack中loader和plugin区别？', level:'基础', options:['相同','loader转换特定类型模块(如ts→js,scss→css,图片base64)在import时；plugin扩展打包流程任何阶段','plugin转译','loader优化'], answer:1, explain:'常用loader:babel/ts-loader/css-loader/style-loader/url-loader；plugin:HtmlWebpackPlugin/Minicssextract/Terser'},
{q:'Vite相比Webpack开发启动快的核心？', level:'基础', options:['一样快','开发用浏览器原生ESM不打包，按需编译；rollup打包生产。esbuild预处理极快','Vite功能少','Webpack没缓存'], answer:1, explain:'冷启动Vite远胜；首次访问某文件才转译。大型项目热更新Vite按模块更新不走依赖图更稳'},
{q:'前端性能优化中减少白屏时间FCP指？', level:'基础', options:['First Contentful Paint首次内容绘制，看到第一个可见内容时间','完全加载','首字节','DNS时间'], answer:0, explain:'Web Vitals：FCP(首绘)、LCP(最大内容绘)、CLS(累计偏移)、TTI(可交互)、TBT(主线程阻塞)、FID(首次输入延迟)'},
{q:'LCP(Largest Contentful Paint)衡量什么？', level:'基础', options:['脚本执行','最大文本/图片/视频块出现在视口时间，Google核心Web Vitals最重要','样式加载','网络时间'], answer:1, explain:'优化方向：图片压缩/CDN/预加载/懒加载、字体font-display:swap、减少阻塞渲染的CSS/JS'},
{q:'图片懒加载原生HTML属性是？', level:'基础', options:['lazy="true"','<img loading="lazy"> 原生浏览器支持推迟加载视口外图片','data-src','defer'], answer:1, explain:'Chrome 77+/新版Edge/Firefox 75+支持原生；兼容性考虑加IntersectionObserver兜底'},
{q:'浏览器重绘Repaint和重流Reflow(回流)区别？', level:'基础', options:['无','重绘=视觉属性改(颜色)不重排；重流=几何属性改需要重新计算布局(成本高)','重流比重绘便宜','相同'], answer:1, explain:'重流必引起重绘。优化：批量改DOM/离线DocumentFragment/绝对定位脱离文档流/避免频繁读offset族'},
{q:'SPA和MPA区别？', level:'基础', options:['无','SPA单页应用(客户端路由切换无刷新)；MPA多页面每次整页刷新。前者体验好后者首屏快SEO好','MPA性能更优','SPA利于SEO'], answer:1, explain:'Vue/React/Angular默认SPA；SEO重要可SSR(Next/Nuxt)或预渲染/SSG补偿首屏和爬虫。'},
{q:'SSR服务端渲染优点？', level:'基础', options:['减轻服务器','首屏HTML直出更快FCP/LCP+SEO爬虫拿到完整内容','开发简单','不需要JS'], answer:1, explain:'首屏有内容用户不看白屏；搜索引擎不用执行JS也爬得到；以Nuxt Next等框架减少开发量'},
{q:'CORS跨域请求中简单请求和预检请求区别？', level:'进阶', options:['相同','简单请求(GET/HEAD/POST+无自定义头+特定Content-Type)直接发；其他先发OPTIONS预检，服务端返回Access-Control-*才发送真请求','预检更快','预检只一次'], answer:1, explain:'预检OPTIONS头:Access-Control-Request-Method/Headers；响应含Allow-Methods/Headers/Credentials/Max-Age缓存秒数'},
{q:'实现节流throttle和防抖debounce区别？', level:'进阶', options:['相同','防抖：短时间多次触发只执行最后一次(如搜索输入)；节流：固定时间窗内只执行一次(如滚动)','防抖=节流','防抖更省性能'], answer:1, explain:'leading/trailing配置首/尾执行；leading:false trailing:true(默认debounce)；场景：resize防抖、scroll节流。'},
{q:'JS深拷贝常用方法与坑？', level:'进阶', options:['JSON.parse(JSON.stringify())万能','JSON法丢函数/undefined/Symbol/正则/Date等；structuredClone现代原生；lodash.cloneDeep更全','浅拷贝就是深拷贝','递归赋值就行'], answer:1, explain:'支持循环引用的方案：structuredClone(Node17+/新浏览器)、lodash；JSON.stringify遇BigInt抛错，undefined变没'},
{q:'原型链最终尽头是？', level:'进阶', options:['Function.prototype','Object.prototype.__proto__===null','undefined','window'], answer:1, explain:'对象[[Prototype]]→…→Object.prototype→__proto__=null。Object.create(null)创建干净字典对象没有原型链'},
{q:'闭包的典型应用场景？', level:'进阶', options:['内存泄漏','封装私有变量(模块模式)、柯里化、函数工厂、事件回调持久化状态','继承','类'], answer:1, explain:'return function仍能访问外部函数作用域；循环var导致异步回调拿i要立即执行函数或let块级'},
{q:'Event Loop宏任务微任务执行顺序？', level:'进阶', options:['微→宏乱序','同步代码→取出当前所有微任务清空→下一轮宏任务→再清空微任务……Promise.then/queueMicrotask是微任务；setTimeout/setInterval/I/O/UI渲染是宏任务','宏=微','宏优先全跑'], answer:1, explain:'同一轮中微任务队列先全部执行完再取一个宏任务，会影响UI刷新时机。Vue/React调度常用微任务批处理'},
{q:'实现继承Class extends和寄生组合继承本质？', level:'进阶', options:['相同','ES6 Class extends本质原型继承+构造函数call，父类原型链指向super.prototype(Object.setPrototypeOf)；ES5寄生组合继承优化原型对象共享constructor多余属性','寄生更差','Class原型拷贝'], answer:1, explain:'最佳实践：寄生组合：子类原型=Object.create(父类原型)，修正constructor。避免new Parent()导致父实例属性污染共享'},
{q:'Proxy相比Object.defineProperty优势？', level:'进阶', options:['一样','Proxy代理整个对象拦截13种操作含数组下标/Map/新增属性；defineProperty需遍历+单独劫持且改数组需hack','Proxy更兼容','defineProperty性能好'], answer:1, explain:'Vue3用Proxy重写响应式解决Vue2数组索引/新增属性不响应问题，也能代理Set/Map'},
{q:'Generator和async/await关系？', level:'进阶', options:['无关系','async/await是Generator(promise)+自动执行器的语法糖，co库思路','Generator比async新','Generator是ES2020'], answer:1, explain:'function* + yield暂停，返回Iterator；async函数封装成自动Promise运行更直观。Iterator可自定义for...of'},
{q:'CSS BFC是什么及触发条件？', level:'进阶', options:['浏览器前缀','块级格式化上下文，内部布局不影响外部；触发：overflow非visible/flex/grid/position:absolute或fixed/inline-block等','字体格式','块流式'], answer:1, explain:'BFC典型应用：清除浮动(父加overflow:hidden)、阻止margin塌陷、两栏自适应布局避免文字环绕浮动。'},
{q:'实现三栏布局左右定宽中间自适应最佳现代？', level:'进阶', options:['圣杯布局','Flex: .wrap{display:flex}; .mid{flex:1}左右固定宽；或Grid grid-template-columns: 200px 1fr 200px','浮动','绝对定位'], answer:1, explain:'Flex简单；Grid更语义；圣杯/双飞翼是IE时代技巧，现代不必，除非要兼容老IE。'},
{q:'响应式断点移动端优先设计原则？', level:'进阶', options:['先写大屏','先写最小屏幕基础样式，再加min-width媒体查询向平板/桌面扩展；减少覆盖代码','只写媒体查询','像素必须px'], answer:1, explain:'移动端优先(min-width升序)比桌面优先(max-width)代码更少更简洁；断点按内容而非设备型号定。'},
{q:'CSS变量(CSS自定义属性)优点？', level:'进阶', options:['兼容所有IE','--name定义var(--name)使用；可级联覆盖+JS动态读写+主题切换一行改全局+媒体查询改','性能比预处理器好','只能在:root定义'], answer:1, explain:'不支持IE；配合prefers-color-scheme自动深色模式；JS:document.documentElement.style.setProperty("--c","#000")'},
{q:'CSS content-visibility:auto作用？', level:'进阶', options:['隐藏内容','浏览器跳过屏幕外区域子树布局/绘制渲染，长列表大页面极大提升首屏和滚动性能','动画优化','图片自动压缩'], answer:1, explain:'结合contain-intrinsic-size预估占位尺寸避免滚动条跳动，非常适合无限滚动列表性能优化'},
{q:'V8如何优化JS执行？', level:'进阶', options:['解释执行','先Ignition解释字节码→热点函数TurboFan JIT编译优化成机器码；内联缓存/隐藏类/逃逸分析优化','直接机器码','慢于旧引擎'], answer:1, explain:'保持对象形状稳定(同类属性顺序一致)利于隐藏类优化；避免arguments泄漏利于逃逸分析栈分配。'},
{q:'Tree Shaking前提条件是？', level:'进阶', options:['CommonJS','使用ES Module静态import/export语法 + 未使用的纯函数标记sideEffects:false webpack/rollup剔除','任意模块','AMD'], answer:1, explain:'require()动态不能Tree Shaking；"sideEffects":["./*.css","*.scss"] 防止样式/带副作用文件误删'},
{q:'Code Splitting代码分割方法？', level:'进阶', options:['只有路由懒加载','入口分割+路由动态import()按组件分包+vendor分离；动态组件按需加载','只有vendor','必须手动'}, answer:1, explain:'Webpack魔法注释/webpackChunkName命名；React.lazy(()=>import('./A'))+Suspense；Vue defineAsyncComponent异步组件'},
{q:'preload和prefetch区别？', level:'进阶', options:['相同','<link rel=preload as=script href=a.js>当前页优先级高资源立即加载；prefetch=闲时预取下页资源将来可能用','prefetch优先级更高','preload仅图片'], answer:1, explain:'滥用preload会挤占当前资源带宽；首屏关键JS/CSS/字体用preload，路由切换下一页用prefetch'},
{q:'HTTP/2与HTTP/1.1核心提升？', level:'进阶', options:['一样','二进制分帧、多路复用单TCP并发多流无队头阻塞(但TCP层面仍有)、HPACK头部压缩、服务器推送','仅加密','URL更好'], answer:1, explain:'域名分片、雪碧图、文件合并等HTTP/1技巧在HTTP/2反而可能不利，让服务器自己决定资源并发更高效'},
{q:'Service Worker核心能力？', level:'进阶', options:['直接操作DOM','可拦截fetch请求、离线缓存策略、推送通知(PWA)；HTTPS必需/localhost例外，独立线程','后台任务仅定时器','同步Ajax'], answer:1, explain:'Cache Storage缓存策略：CacheFirst/NetworkFirst/Stale-While-Revalidate等；workbox库简化复杂缓存规则'},
{q:'WebSocket与SSE(EventSource)区别？', level:'进阶', options:['相同','SSE单向服务端→客户端，HTTP长连接自动重连简单；WebSocket全双工双向适合高频互动(IM/游戏)','SSE双向','WS更简单'], answer:1, explain:'SSE优点：HTTP友好、断线自动重连、文本事件流。ws://wss://二进制、需要协议升级握手'},
{q:'XSS攻击三类和防护核心？', level:'高级', options:['完全由浏览器防御','存储型(入库后渲染)/反射型(URL参注入)/DOM型(前端脚本自己拼)；核心：任何用户输入到HTML/JS/CSS/URL必须按上下文转义+CSP白名单限制脚本源','仅HttpOnly','仅输入校验'], answer:1, explain:'输出转义按场景：HTML实体转义/JS Unicode/URL编码/CSS转义；Vue/React默认转义；v-html/dangerouslySetInnerHTML要先sanitize；CSP严格模式极大降低损害'},
{q:'CSRF攻击和防御核心？', level:'高级', options:['SameSite=Lax足够','核心：跨站请求浏览器自动带Cookie。防护：CSRF Token(请求头/表单携带)+SameSite=Strict/Lax+验证Origin/Referer+关键操作二次验证','只要HTTPS','仅验证码'], answer:1, explain:'CSRF只改读不到返回；JSON API只Content-Type:application/json本身带预检也是一层；但仍加Token更稳'},
{q:'点击劫持(Clickjacking)防御？', level:'高级', options:['验证码','X-Frame-Options:DENY/SAMEORIGIN；CSP frame-ancestors指令；前端top!=self破框(可被sandbox阻止)','仅HTTPS','防JS'], answer:1, explain:'X-Frame-Options HTTP响应头禁止第三方iframe嵌套；CSP frame-ancestors更灵活支持多源白名单'},
{q:'Vue3 Composition API和Options API核心区别？', level:'高级', options:['完全重写不兼容','Options API按选项(data/methods/computed)分散；Composition API按逻辑聚合，更好TypeScript类型、更好逻辑复用(组合函数代替mixin命名冲突)、更好Tree Shaking','Options已废弃','Composition慢'], answer:1, explain:'setup()或<script setup>；ref/reactive响应式；computed/watch/watchEffect；provide/inject跨组件传；mixin因命名污染和来源不明不再推荐'},
{q:'React Fiber架构本质？', level:'高级', options:['就是虚拟DOM','把渲染更新拆成可中断的增量单元，空闲时调度requestIdleCallback式API，避免长任务卡死主线程，从而实现时间切片和可优先级调度','只是性能','服务端渲染'], answer:1, explain:'Fiber=数据结构链表节点=虚拟堆栈帧；优先级Lanes模型；同步模式仍会一次性提交，并发模式(concurrent)才真可打断'},
{q:'虚拟DOM Diff经典协调三策略？', level:'高级', options:['穷举对比','1.不同类型节点直接替换整树 2.同类型DOM节点复用+更新属性 3.列表用key一一复用和移动；O(n)而非O(n³)','全量重建','深度优先'], answer:1, explain:'同层比较(不跨层)；两类型不同直接新树；key提高列表复用正确率减少DOM操作。key错误导致状态错乱'},
{q:'Svelte与Vue/React的根本不同？', level:'高级', options:['相同语法','Svelte编译时框架，无虚拟DOM运行时，编译直接生成命令式DOM更新代码+细粒度订阅，包小性能优；Vue/React需要运行时+VDiff','Svelte必须TS','Svelte兼容性最好'], answer:1, explain:'Svelte包体积极小适合微件/活动页；运行时生态和大型项目成熟度相比React/Vue略弱'},
{q:'Webpack Module Federation微前端核心？', level:'高级', options:['iframe嵌入','多个独立构建应用，运行时通过remote暴露模块/host远程消费共享依赖，无iframe隔离问题的微前端方案','仅是样式隔离','后端BFF'], answer:1, explain:'shared配置共享依赖避免重复加载react/vue；exposes暴露组件；remotes配置目标地址；解决多版本共存和样式隔离方案另外'},
{q:'微前端qiankun的JS隔离和样式隔离原理？', level:'高级', options:['iframe天然隔离','JS沙箱：Proxy劫持window(快照沙箱/Proxy沙箱/Legacy沙箱)；样式：严格模式下shadow DOM或自定义前缀scoped/css modules或运行时动态作用域选择器','仅后缀命名','重写浏览器API'], answer:1, explain:'沙箱保证子应用window读写不污染全局；样式隔离推荐子应用严格按CSS Modules/约定前缀，runtime修补实验性'},
{q:'ESM和CommonJS在打包中差异关键点？', level:'高级', options:['可混用','CJS运行时加载同步动态require；ESM静态编译期分析导入导出可Tree Shaking；互操作时cjs→esm会包装default；__dirname/require仅CJS，import.meta.url仅ESM','ESM更旧','差异不存在'], answer:1, explain:'Node package.json"type":"module"→.js按ESM；cjs文件或"type":"commonjs"按CJS；ESM必须显式扩展名'},
{q:'性能优化之Long Task(长任务)如何定位？', level:'高级', options:['看console.log','Chrome Performance面板看主线程红条+Bottom-Up/Call Tree找耗时函数；PerformanceObserver API监测longtask事件','只看Network','查看内存'], answer:1, explain:'任务>50ms算Long Task影响交互响应性(TBT/FID)；拆分重计算Web Worker离线程；React startTransition降低非紧急更新优先级'}];

// ================ 后端新增150题 ================
const BE_NEW = [{q:'HTTP与HTTPS区别核心？', level:'基础', options:['相同','HTTPS在HTTP下加TLS/SSL加密层，默认443端口HTTP是80，防窃听篡改伪装','HTTPS更快','HTTPS仅改端口'], answer:1, explain:'HTTPS握手+证书验证确认服务端身份；对称加密会话内容+非对称交换密钥+数字签名证书链验证'},
{q:'JWT(JSON Web Token)三段结构是？', level:'基础', options:['头/体/签名','Header(算法+类型).Payload(声明).Signature(密钥签名)，Base64URL编码用.连接','用户/密码/时间戳','公钥/私钥/证书'], answer:1, explain:'Header alg+typ；Payload标准字段sub/iat/exp/nbf/iss/aud；签名=HMACSHA256(base64(header)+"."+base64(payload),secret)防篡改'},
{q:'REST与RPC风格差异？', level:'基础', options:['相同','REST强调资源(名词)+HTTP动词(GET/POST/PUT/DELETE)操作资源；RPC强调动作(动词)调用远程方法如addUser，和语言函数调用贴近','REST是协议','RPC必须HTTP'], answer:1, explain:'对外API推荐REST语义清晰；内部微服务gRPC效率高；GraphQL按需取字段比REST灵活'},
{q:'数据库事务ACID四特性？', level:'基础', options:['原子/一致/隔离/持久','A原子要么全成功要么回滚；C一致约束合法；I隔离并发不互扰；D持久断电不丢','抽象/缓存/索引/双写','异步/提交/立即/删除'], answer:0, explain:'隔离不当时会：脏读/不可重复读/幻读；四种隔离级别逐级加强：读未提交→读已提交→可重复读→串行化'},
{q:'MySQL InnoDB默认隔离级别？', level:'基础', options:['READ UNCOMMITTED','REPEATABLE READ(可重复读)','READ COMMITTED','SERIALIZABLE'], answer:1, explain:'MySQL默认RR(解决脏读+不可重复读，MVCC+间隙锁+Next-Key Lock防幻读)；Oracle/PostgreSQL默认RC'},
{q:'MySQL聚簇索引和非聚簇索引区别？', level:'基础', options:['无','InnoDB聚簇索引(主键)B+树叶子=完整行数据；非聚簇(二级索引)叶子=主键值需回表；MyISAM都是非聚簇','聚簇慢','仅二级有B树'], answer:1, explain:'主键选自增ID利于顺序插入减少页分裂；覆盖索引不用回表直接从二级索引得到所需列'},
{q:'索引最左前缀匹配原则含义？', level:'基础', options:['必须用最左列','联合索引(a,b,c)只有查询条件从最左列连续匹配才能用上索引；跳过a则索引用不上；范围列右侧无法用','仅字符串','倒序匹配'], answer:1, explain:'where a=1 and b=2 and c=3全用；a=1 and c=3仅用a列；a>1 and b=2仅用a。优化要把区分度高列放前面'},
{q:'Nginx正向代理和反向代理区别？', level:'基础', options:['相同','正向代理用户知道代理服务器替客户端访问；反向代理客户端无感，代理替服务端接收转发(负载均衡/缓存)','正代理快','反代理用于翻墙'], answer:1, explain:'Nginx典型配置proxy_pass http://upstream; 做反向代理+负载均衡(轮询/加权轮询/ip_hash/least_conn等)'},
{q:'Nginx rewrite和return 301区别？', level:'基础', options:['完全相同','return 301更直接高效停止后续规则；rewrite可做正则和内部重写/外部重定向，性能略差','rewrite更规范','return仅301'], answer:1, explain:'能用return就不用rewrite；但正则拆分变量时仍需rewrite ^/a/(.*)$ /b/$1 permanent;'},
{q:'Redis与Memcached对比Redis优点？', level:'基础', options:['仅存K/V','Redis支持丰富数据结构(String/Hash/List/Set/ZSet/Geo/HyperLogLog/Stream/Bitmap)、持久化(RDB/AOF)、发布订阅、Lua、事务、主从+集群','Memcached快','Memcached持久化'], answer:1, explain:'单线程事件循环Redis v6引入多线程IO(命令执行仍是单线程)；Memcached仅String内存缓存无持久'},
{q:'Redis持久化RDB和AOF区别？', level:'基础', options:['相同','RDB快照fork子进程定时dump二进制，恢复快可能丢最近数据；AOF追加命令日志，fsync策略可调更安全；生产建议混合使用','仅RDB可用','AOF更快'], answer:1, explain:'Redis 4.0+混合持久化(AOF重写时插入RDB头)：结合RDB快速恢复+AOF减少丢失。宕机重启用aof-use-rdb-preamble yes'},
{q:'Redis缓存穿透、缓存击穿、缓存雪崩区别？', level:'基础', options:['相同','穿透：查不存在键→DB(空值缓存/布隆过滤器)；击穿：热点key过期瞬发→DB(互斥锁/永不过期+后台异步刷新)；雪崩：大量key同时间过期或Redis宕→DB(过期时间随机/多副本/降级)','仅容量问题','全为网络问题'], answer:1, explain:'组合拳：布隆过滤器挡不存在→互斥锁击穿→抖动过期雪崩→兜底多级缓存(本地+Caffeine/Guava Cache+Redis)'},
{q:'消息队列解耦、异步、削峰三大场景？', level:'基础', options:['只存日志','解耦(下单通知库存物流不直接调)；异步(发短信邮件不阻塞主流程)；削峰(活动下单先入队列消费者慢处理保护DB)','加速DB查询','仅缓存'], answer:1, explain:'常见MQ：Kafka吞吐高日志流；RabbitMQ功能全死信延迟等；RocketMQ事务消息；Pulsar存算分离云原生。'},
{q:'Kafka中Topic/Partition/Offset/Consumer Group？', level:'基础', options:['相同概念','Topic主题；Partition分区顺序日志水平扩展；Offset消费位点；Consumer Group消费组内各消费者订阅同topic各分一个partition消费，组间互不影响','仅Offset重要','Group自动删除'], answer:1, explain:'同组消费者数>partition数多余空闲；少则一个消费多partition；重平衡Rebalance在成员变更时触发分配。'},
{q:'RabbitMQ四种主要交换机类型？', level:'基础', options:['TCP/UDP/IP/HTTP','direct(精确路由键匹配)/fanout(广播所有队列)/topic(路由键*.#通配)/headers(消息头匹配)','同步/异步/回调/轮询','push/pull/peek/pop'], answer:1, explain:'bindingKey绑定交换机和队列；publisher送消息指定routingKey；不同exchange匹配规则不同决定送到哪些队列。'},
{q:'Docker容器和虚拟机区别核心？', level:'基础', options:['相同','容器共享宿主机OS内核，轻量秒级启动，镜像MB级；VM独立GuestOS分钟级启动镜像GB级。容器是进程级隔离VM硬件级隔离','容器更安全','容器无法网络'], answer:1, explain:'Namespace(UTS/PID/IPC/NET/MNT/USER)+Cgroups(资源限制)是Linux容器底层核心；Docker daemon+containerd+runc实际运行容器。'},
{q:'Dockerfile中COPY和ADD区别？', level:'基础', options:['无','ADD多两个能力：1.自动解压tar.gz等本地归档到镜像 2.支持URL下载(下载的不解压)；COPY仅复制普通文件，更明确推荐优先用COPY','ADD速度快','COPY仅二进制'], answer:1, explain:'能用COPY就不要ADD；自动解压特性也常带来意外。多阶段构建FROM AS builder + FROM scratch/运行时复制产物减少镜像体积。'},
{q:'Kubernetes Pod/Deployment/Service/Ingress区别？', level:'基础', options:['相同概念','Pod最小调度单元(一个或多个紧密容器共享网络/存储)；Deployment声明式管理Pod副本/滚动更新；Service稳定访问入口集群内发现；Ingress七层HTTP路由入集群','仅Pod需要','Service=Pod'], answer:1, explain:'Service ClusterIP内部/NodePort节点端口/LoadBalancer云LB/ExternalName对接外部DNS；Ingress统一域名路径分流到不同Service'},
{q:'K8s中ConfigMap和Secret区别？', level:'基础', options:['相同','ConfigMap存非敏感配置(明文)；Secret存密码/Token/TLS证书，默认Base64编码(仍需RBAC控制+生产建议加密etcd或外部Vault)','Secret更大','ConfigMap不能挂'], answer:1, explain:'二者均可卷挂载或环境变量注入；Secret env默认不打印日志。敏感数据用HashiCorp Vault/Sealed Secrets更安全。'},
{q:'CI/CD概念解释？', level:'基础', options:['服务器管理','CI持续集成(代码提交后自动构建/测试)；CD持续交付(可随时发布)或持续部署(自动部署生产)；工具Jenkins/GitLab CI/GitHub Actions/ArgoCD','数据库备份','网络加速'], answer:1, explain:'典型流程：开发者提交→流水线触发→静态检查→单元测试→构建镜像→推仓库→部署测试环境→集成测试→人工确认→部署生产。'},
{q:'Spring Boot @SpringBootApplication组合了哪三个？', level:'基础', options:['无','@SpringBootConfiguration=配置类+@EnableAutoConfiguration自动装配+@ComponentScan默认扫描本包及子包','@Web/@Service/@Repository','@Cache/@Async/@Scheduled'], answer:1, explain:'自动装配：SpringFactoriesLoader读取META-INF/spring.factories的EnableAutoConfiguration候选类，根据条件@ConditionalOnClass等按需注册Bean'},
{q:'Spring IOC和DI本质？', level:'基础', options:['AOP','控制反转=对象创建依赖交给容器而非自己new；依赖注入=容器把依赖通过构造器/setter/字段赋值给对象。解耦方便测试扩展','事务','MVC'], answer:1, explain:'BeanFactory是底层接口；ApplicationContext高层含国际化/事件/BeanPostProcessor扩展；@Scope:singleton/prototype/request/session'},
{q:'Spring AOP通知类型？', level:'基础', options:['增删改查','@Before前置/@After返回后(无论异常)/@AfterReturning成功返回/@AfterThrowing异常/@Around环绕最强大','只有@Before','仅事务'], answer:1, explain:'Aspect切面+Pointcut(execution切点)+JoinPoint连接点+Weave织入；事务@Transactional本质AOP环绕+ThreadLocal绑定连接'},
{q:'Spring MVC请求处理流程核心组件？', level:'基础', options:['Socket监听','DispatcherServlet(前端控制器总调度)→HandlerMapping找Handler→HandlerAdapter适配调用Controller→ViewResolver解析视图→渲染返回','仅Servlet','Filter链'], answer:1, explain:'常用注解@RequestMapping/@GetMapping/@RestController=@Controller+@ResponseBody；@RequestBody Jackson自动JSON→对象'},
{q:'Spring Bean默认作用域和线程安全问题？', level:'基础', options:['prototype总是安全','默认singleton(容器唯一实例)，如成员变量被多线程改→线程不安全。应避免在单例Bean保存请求级可变状态，改方法参数/局部变量/request scope','singleton绝对安全','默认request'], answer:1, explain:'Spring/Struts2区别：Struts2默认Action是prototype每次请求新实例，Spring MVC Controller默认singleton但存方法栈上无状态通常OK'},
{q:'Spring @Transactional失效常见原因？', level:'基础', options:['都有效','1.非public方法 2.同类内部方法this调用不经过代理 3.异常非Runtime且未rollbackFor 4.多线程异步方法中事务不生效 5.数据库引擎非InnoDB','仅注解写了就生效','只有抛错才回滚'], answer:1, explain:'同类内调用失效是因为AOP代理：外部类调用才会进代理增强；解决：注入自己/用ApplicationContext.getBean/拆两个Service/编程式事务'},
{q:'Spring Security过滤器链中认证授权核心？', level:'基础', options:['拦截器','过滤器链：UsernamePasswordAuthenticationFilter(表单)/BasicAuthenticationFilter→SecurityContextHolder存认证对象→FilterSecurityInterceptor授权基于URL+角色@PreAuthorize','AOP','Servlet'], answer:1, explain:'JWT场景自定义过滤器从请求头Authorization Bearer解析token设SecurityContext；记住我RememberMe用持久化TokenRepository'},
{q:'MyBatis #{}和${}区别？', level:'基础', options:['相同','#{}预编译占位符PreparedStatement，防SQL注入；${}字符串直接拼接(动态表名/列名/排序字段场景必须用但要校验白名单)','#{}更快','${}更安全'], answer:1, explain:'like模糊查询正确用法:name like concat("%",#{name},"%") 而不是like "%${name}%"。排序字段必须白名单校验防注入。'},
{q:'Go语言goroutine和线程区别？', level:'基础', options:['完全相同','goroutine用户态轻量协程(初始栈2KB可伸缩)；OS线程MB级栈+内核调度上下文切换重。GOMAXPROCS个M:N调度模型','goroutine更慢','goroutine=协程库'], answer:1, explain:'Goroutine由Go runtime调度GMP模型：G协程/M工作线程/P调度上下文(本地队列+全局队列+窃取)；channel通过CSP模型同步通信不要共享内存通信。'},
{q:'Go channel有缓冲和无缓冲区别？', level:'基础', options:['相同','无缓冲ch:=make(chan int)必须收发同时准备好(同步)；有缓冲ch:=make(chan int,10)写入到未满不阻塞，用于解耦/限流/任务队列','有缓冲是数组','无缓冲死锁'], answer:1, explain:'for v:=range ch会持续收直到close(ch)；select多路选择非阻塞case default；关闭后读取立即得零值+ok=false；向关闭写panic。'},
{q:'Go defer执行顺序和return谁先？', level:'基础', options:['先defer后return','返回值赋值→defer执行(可改命名返回值)→RET指令返回。多个defer按LIFO后进先出执行。','先return后defer','同时'], answer:1, explain:'函数返回分三步：1.给返回值赋值 2.执行defer 3.RET；非命名返回值defer改不了，命名返回值defer修改会影响最终结果。'},
{q:'Java内存模型JMM堆/栈/方法区存什么？', level:'基础', options:['全存对象','堆=所有对象实例；栈=每个线程私栈帧(局部变量表/操作数栈/动态链接返回地址)；方法区/元空间=类信息/常量/静态变量/JIT编译代码；堆是GC主战场','仅栈有对象','方法区在栈上'], answer:1, explain:'JDK8永久代→元空间移到本地内存；String.intern()字符串常量池移到堆；TLAB(线程本地分配缓冲)减少多线程堆分配同步。'},
{q:'Java垃圾回收分代收集理论？', level:'基础', options:['全扫描','弱分代假说：绝大多数对象朝生夕死；强分代假说：熬过多次GC越难死。因此堆分年轻代(Eden/S0/S1 复制算法)老年代(Mark-Sweep-Compact)','仅分代无意义','全部复制算法'], answer:1, explain:'Young GC(Minor GC)/Old GC(Major)/Full GC整堆。GC Roots:栈局部变量/方法区静态引用/常量引用/JNI引用/同步锁持有。'},
{q:'G1垃圾回收器相比CMS特点？', level:'基础', options:['CMS更好','G1分Region(2048块Eden/Survivor/Old/Humongous)，可预测停顿时间模型，优先回收收益最大Region，整体标记-整理+局部复制解决CMS碎片；CMS低延迟但有碎片并发失败Full GC风险','G1仅JDK6','G1更慢'], answer:1, explain:'JDK9默认G1；JDK17+ZGC/Shenandoah超低停顿毫秒级大堆TB级。选择看：堆大小、延迟要求、JDK版本。'},
{q:'Java synchronized和ReentrantLock区别？', level:'进阶', options:['相同','synchronized关键字JVM层面自动加解锁；ReentrantLock API层面可中断/可超时/公平锁/多条件Condition，灵活但需try/finally手动unlock。都是可重入。','Lock更快','synchronized更灵活'], answer:1, explain:'锁升级：无锁→偏向锁→轻量级锁(自旋CAS)→重量级锁(monitor)。偏向锁存线程ID；轻量级自旋失败才升级到OS挂起线程。'},
{q:'ConcurrentHashMap JDK8核心变化？', level:'进阶', options:['和JDK7一样分段锁','JDK8:Node数组+链表/红黑树(长度>8转红黑树)；CAS+synchronized只锁数组头节点(首节点)，不再是Segment分段锁，更细粒度并发更高','synchronized锁整个map','仅读写锁'], answer:1, explain:'put：空数组初始化→头空CAS放→否则synchronized(n)锁住首节点→链表插入or红黑插入→size通过CounterCell分段计数，LongAdder思路避免CAS热点。'},
{q:'Java线程池ThreadPoolExecutor七大参数？', level:'进阶', options:['线程数/队列数','1.corePoolSize核心常驻 2.maximumPoolSize最大 3.keepAliveTime非核心线程空闲存活 4.TimeUnit 5.workQueue任务队列 6.threadFactory线程工厂 7.RejectedExecutionHandler拒绝策略','仅3个','最大线程=队列长'], answer:1, explain:'提交顺序：核心满→队列满→扩容到最大→队列又满→拒绝。常见队列：ArrayBlockingQueue有界/LSBlockingQueue无界(OOM风险)/SynchronousQueue不存/ScheduledThreadPool'},
{q:'Java volatile关键字作用？', level:'进阶', options:['原子性+可见性','1.可见性：volatile写会立即刷主存读直接从主存拿，线程间立即可见 2.禁止指令重排(Happens-Before内存屏障)；但i++仍不原子需AtomicInteger','原子性','仅有序性'], answer:1, explain:'双重检查锁单例必须volatile禁止new指令分配内存/初始化/引用赋值重排导致其他线程拿到半初始化对象。'},
{q:'MySQL索引失效常见场景？', level:'进阶', options:['任何场景都有效','1.where中索引列函数/运算/隐式类型转换 2.模糊like左% 3.!=或<> or is not null视情况 4.联合索引不满足最左前缀 5.字符串没加引号转数字 6.优化器觉得全表更快','只要建就会用','仅not null失效'], answer:1, explain:'explain type列:system>const>eq_ref>ref>range>index>ALL(需优化)；Extra:Using index覆盖索引/Using where需回表过滤/Using filesort需排序/Using temporary临时表'},
{q:'MySQL大表加DDL(加字段/索引)注意？', level:'进阶', options:['直接锁表没事','In-Place+Online DDL：ALGORITHM=INPLACE尽量避免重建表；LOCK=NONE允许DML并发。大表生产用pt-online-schema-change或gh-ost外部工具：影子表+触发器拷贝+重命名零停机','直接ALTER就行','仅加索引锁表'], answer:1, explain:'大表直接ALTER会长时间锁元数据+阻塞写入；pt-osc原理在原表加触发器同步增量到新表，后台拷数据完成瞬间RENAME，低峰操作+外键不支持需注意'},
{q:'数据库分库分表ShardingSphere思路？', level:'进阶', options:['只解决容量','水平分表按分片键路由(取模/时间/范围)到多节点；垂直分库按业务模块拆库；缺点：跨库join/分布式事务/分页/全局ID。代理端Sharding-Proxy/客户端Sharding-JDBC/侧车','仅垂直分','不用改应用'], answer:1, explain:'全局唯一ID：雪花算法(64bit时间戳+机器id+序列号)/Leaf/UUID(无序索引性能差)；跨库事务：Seata AT/TCC/Saga/XA可靠消息最终一致。'},
{q:'分布式事务CAP和BASE理论？', level:'进阶', options:['ACID变体','CAP:分布式系统一致性C/可用A/分区容错P三者不能同时，P必选，选CP或AP。BASE:基本可用+软状态+最终一致，大部分业务接受最终一致更强可用性','CAP同时满足','BASE要求强一致'], answer:1, explain:'典型最终一致方案：可靠消息+本地消息表+定时任务补偿；TCC三阶段Try/Confirm/Cancel侵入强；Seata AT一阶段写undo log二阶段提交/回滚'},
{q:'分布式锁Redis实现思路和坑？', level:'进阶', options:['setnx=完美','SET key value NX PX 30000 原子