// === C EXT2 ===
c_ext2_topics: [
  {
    id: "c-complex-decl",
    title: "复杂声明解读：右左法则与函数指针",
    level: "高级",
    content: "**右左法则（Right-Left Rule）**\n- 从变量名开始，先向右看，再向左看，遇到括号跳出\n- * 读作 \"指向...的指针\"\n- [] 读作 \"...的数组\"\n- () 读作 \"返回...的函数\"\n\n**经典复杂声明解读**\n- `int *p;` p 是指向 int 的指针\n- `int p[10];` p 是含10个 int 的数组\n- `int *p[10];` p 是含10个元素的数组，每个元素是指向 int 的指针（指针数组）\n- `int (*p)[10];` p 是指针，指向含10个 int 的数组（数组指针）\n- `int p(void);` p 是返回 int 的函数\n- `int *p(void);` p 是返回 int* 的函数\n- `int (*p)(void);` p 是指针，指向返回 int 的函数（函数指针）\n\n**函数指针详解**\n- 声明：`int (*fp)(int, int);` fp 指向 `int(int,int)` 的函数\n- 赋值：`fp = &func;` 或 `fp = func;`（函数名退化为指针）\n- 调用：`fp(a, b);` 或 `(*fp)(a, b);`\n- 用途：回调函数、策略模式、跳转表、事件处理\n\n**函数指针数组（跳转表）**\n- `int (*ops[4])(int,int) = {add, sub, mul, div};`\n- 替代 switch-case，O(1) 分发\n- 解释器/虚拟机指令分发的经典手法\n\n**回调函数模式**\n- qsort 的比较函数：`int (*compar)(const void*, const void*)`\n- 线程入口函数：`void* (*start_routine)(void*)`\n- 信号处理：`void (*sighandler_t)(int)`\n\n**typedef 简化复杂声明**\n- `typedef int (*FuncPtr)(int, int);` 之后可写 `FuncPtr fp;`\n- 极大提升可读性\n- 标准库常用：signal/sigaction 等\n\n**陷阱**\n- `int *p[10]` 与 `int (*p)[10]` 含义完全不同\n- 函数不能返回函数，不能返回数组\n- 数组不能含函数，但可含函数指针",
    example: "#include <stdio.h>\n#include <stdlib.h>\n\n// 函数指针\ntypedef int (*BinOp)(int, int);\n\nint add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\nint mul(int a, int b) { return a * b; }\nint div_op(int a, int b) { return b ? a / b : 0; }\n\n// 跳转表（函数指针数组）\nBinOp ops[] = {add, sub, mul, div_op};\n\n// 回调示例：通用计算器\nint compute(int a, int b, BinOp op) {\n    return op(a, b);\n}\n\n// qsort 比较函数\nint cmp_int(const void *a, const void *b) {\n    return *(int*)a - *(int*)b;\n}\n\nint main() {\n    // 直接调用\n    printf(\"%d\\n\", compute(3, 4, add));  // 7\n\n    // 跳转表分发\n    int op = 2;  // 乘法\n    printf(\"%d\\n\", ops[op](3, 4));  // 12\n\n    // qsort 回调\n    int arr[] = {5, 2, 8, 1, 9, 3};\n    qsort(arr, 6, sizeof(int), cmp_int);\n    for (int i = 0; i < 6; i++) printf(\"%d \", arr[i]);\n    // 1 2 3 5 8 9\n    return 0;\n}\n\n// 复杂声明练习：\n// signal(int, void (*handler)(int)) 返回旧的 handler\n// typedef void (*sighandler_t)(int);\n// sighandler_t signal(int signum, sighandler_t handler);\n//\n// 解读：char (*(*x())[])();\n// x 是函数，返回指针，指针指向数组，数组元素是函数指针，函数返回 char"
  },
  {
    id: "c-volatile-const",
    title: "volatile 与 const 关键字深度",
    level: "进阶",
    content: "**const 关键字**\n- 修饰变量：只读，不可修改\n- 修饰指针：\n  - `const int *p` 或 `int const *p`：指向 const int 的指针，不能通过 p 改值，可改指向\n  - `int * const p`：const 指针，指向不可改，可改值\n  - `const int * const p`：都不可改\n- 修饰函数参数：承诺不修改参数，接口契约\n- 修饰函数返回值：返回值不可修改（指针返回时有意义）\n- 修饰结构体成员：该成员不可修改\n\n**const 读写规则（右左法则）**\n- const 在 * 左边：指向的数据是 const\n- const 在 * 右边：指针本身是 const\n\n**volatile 关键字**\n- 告诉编译器变量可能被意外修改，不要优化\n- 每次访问都从内存读取，不缓存到寄存器\n- 禁止编译器对 volatile 变量的激进优化（如消除冗余读）\n\n**volatile 应用场景**\n1. 内存映射 IO（MMIO）：硬件寄存器地址\n2. 中断服务程序修改的全局变量\n3. 多线程共享变量（但不保证线程安全，需配合原子操作）\n4. sig_atomic_t 信号处理中修改的标志\n\n**const volatile 组合**\n- `const volatile int *p`：程序不能改（const）但硬件会改（volatile）\n- 典型：只读硬件状态寄存器\n\n**const 与 #define 的区别**\n- const 有类型检查，#define 无类型\n- const 有作用域，#define 全局（文件级）\n- const 在内存有地址可取，#define 不可取地址\n- const 调试时可见符号，#define 已替换\n\n**const 优化提示**\n- 编译器可对 const 变量做常量传播优化\n- 但 volatile const 不会优化",
    example: "#include <stdio.h>\n\n// const 指针四种组合\nvoid pointer_const() {\n    int a = 10, b = 20;\n    const int *p1 = &a;   // 指向 const int\n    int * const p2 = &a;  // const 指针\n    const int * const p3 = &a;  // 都 const\n\n    // *p1 = 5;   // 错：不能通过 p1 修改\n    p1 = &b;      // 对：可改指向\n    *p2 = 5;      // 对：可改值\n    // p2 = &b;   // 错：不能改指向\n}\n\n// const 参数：承诺不修改字符串\nsize_t my_strlen(const char *s) {\n    size_t n = 0;\n    while (*s++) n++;\n    return n;\n}\n\n// volatile：硬件寄存器\n#define HW_STATUS (*(volatile unsigned int *)0x40000000)\n\nvoid wait_ready() {\n    while ((HW_STATUS & 0x1) == 0) {\n        // 没有 volatile 编译器可能优化成空循环或只读一次\n    }\n}\n\n// volatile 中断标志\nstatic volatile int flag = 0;\n\n// 中断服务程序中设置\nvoid ISR() {\n    flag = 1;\n}\n\nint main() {\n    // 主循环检查\n    while (!flag) {\n        // 编译器不会把 flag 缓存到寄存器\n        // 每次都从内存读取\n    }\n    printf(\"中断触发\\n\");\n    return 0;\n}\n\n// const volatile：只读硬件寄存器\n// 程序不能写（const），但硬件会更新（volatile）\nconst volatile uint32_t *timer = (uint32_t *)0x40001000;\nuint32_t current_time() { return *timer; }\n\n// const 与 #define\n#define PI 3.14159\nconst double pi = 3.14159;\n// &pi 合法，&PI 非法"
  },
  {
    id: "c-memory-alignment",
    title: "内存对齐与字节序",
    level: "进阶",
    content: "**内存对齐（Memory Alignment）**\n- 数据在内存中的地址是其大小的整数倍\n- CPU 访问对齐数据更快（一次读取）\n- 部分架构（ARM/MIPS）非对齐访问会异常\n- x86 支持非对齐访问但性能下降\n\n**对齐规则**\n- 结构体每个成员对齐到自身大小的倍数\n- 结构体整体大小是最大成员对齐值的倍数\n- 编译器自动插入填充字节（padding）\n\n**#pragma pack**\n- `#pragma pack(1)` 取消对齐（1字节对齐）\n- `#pragma pack()` 恢复默认\n- 节省空间但可能牺牲性能\n- 网络协议/文件格式常需紧凑结构\n\n**__attribute__((packed))**\n- GCC/Clang 语法\n- `struct __attribute__((packed)) S { ... };`\n- 作用同 #pragma pack(1)\n\n**offsetof 宏**\n- `offsetof(struct_type, member)` 计算成员偏移\n- stddef.h 定义\n- 用于实现通用容器\n\n**字节序（Endianness）**\n- **小端（Little-Endian）**：低字节存低地址。x86/ARM（默认）\n  - 0x12345678 在内存：78 56 34 12\n- **大端（Big-Endian）**：高字节存低地址。网络字节序、PowerPC\n  - 0x12345678 在内存：12 34 56 78\n\n**判断字节序**\n- 用 union 或指针转换\n\n**字节序转换函数**\n- htons/htonl：主机序转网络序（大端）\n- ntohs/ntohl：网络序转主机序\n- 网络协议规定用大端传输\n\n**位域（Bit Field）**\n- 结构体成员指定位宽\n- 位域分配顺序由实现定义（通常从低到高）\n- 跨平台不可靠，慎用于协议解析",
    example: "#include <stdio.h>\n#include <stddef.h>\n\n// 默认对齐\ntypedef struct {\n    char a;     // 1 byte + 3 padding\n    int b;      // 4 bytes\n    char c;     // 1 byte + 3 padding\n} S1;  // sizeof = 12\n\n// 紧凑排列\ntypedef struct {\n    int b;      // 4 bytes\n    char a;     // 1 byte\n    char c;     // 1 byte + 2 padding\n} S2;  // sizeof = 8（调整顺序省空间）\n\n// #pragma pack(1)\n#pragma pack(1)\ntypedef struct {\n    char a;\n    int b;\n    char c;\n} S3;  // sizeof = 6（无填充）\n#pragma pack()\n\n// __attribute__((packed))\ntypedef struct __attribute__((packed)) {\n    char a;\n    int b;\n    char c;\n} S4;  // sizeof = 6\n\nint main() {\n    printf(\"S1: %zu\\n\", sizeof(S1));  // 12\n    printf(\"S2: %zu\\n\", sizeof(S2));  // 8\n    printf(\"S3: %zu\\n\", sizeof(S3));  // 6\n    printf(\"S4: %zu\\n\", sizeof(S4));  // 6\n\n    // offsetof\n    printf(\"S1.b offset: %zu\\n\", offsetof(S1, b));  // 4\n\n    // 判断字节序\n    union {\n        int i;\n        char c[4];\n    } u = { .i = 0x12345678 };\n\n    if (u.c[0] == 0x78) {\n        printf(\"小端\\n\");\n    } else {\n        printf(\"大端\\n\");\n    }\n\n    // 通用判断\n    int x = 1;\n    if (*(char *)&x == 1) printf(\"小端\\n\");\n    else printf(\"大端\\n\");\n    return 0;\n}\n\n// 位域\ntypedef struct {\n    unsigned int a : 1;   // 1 bit\n    unsigned int b : 3;   // 3 bits\n    unsigned int c : 4;   // 4 bits\n} Bits;  // sizeof 通常为 4\n\n// 网络字节序\n#include <arpa/inet.h>\nuint32_t host_val = 0x12345678;\nuint32_t net_val = htonl(host_val);  // 转大端\n// 小端机器上 net_val == 0x78563412"
  },
  {
    id: "c-varargs",
    title: "可变参数函数与 va_list",
    level: "进阶",
    content: "**可变参数函数**\n- 参数个数和类型可变\n- 经典示例：printf/scanf/fprintf\n- 通过 stdarg.h 的 va_list 实现\n\n**stdarg.h 宏**\n- `va_list ap;` 声明参数指针\n- `va_start(ap, last)` 初始化，last 是最后一个命名参数\n- `va_arg(ap, type)` 获取下一个参数，需指定类型\n- `va_end(ap)` 清理\n- `va_copy(dest, src)` 复制（C99）\n\n**实现原理**\n- 函数调用时参数从右向左压栈（cdecl 约定）\n- va_list 指向最后一个命名参数之后的栈位置\n- va_arg 根据类型大小移动指针\n\n**类型提升规则**\n- 可变参数会发生默认参数提升\n- char/short → int\n- float → double\n- 因此 va_arg 取 char/short 要用 int，取 float 要用 double\n\n**经典实现：简易 printf**\n- 格式字符串扫描 %d/%s/%c 等\n- 遇到占位符调用 va_arg 取值\n\n**安全注意事项**\n- 无类型检查，类型不匹配导致未定义行为\n- va_arg 取多了会读到栈上垃圾数据\n- 必须有方式知道参数个数（如格式串、哨兵值）\n- printf 的格式串与参数不匹配是常见漏洞\n\n**sentinel 哨兵**\n- execl(path, arg0, arg1, ..., NULL)\n- 最后一个参数必须是 NULL 作为结束标记\n- GCC: __attribute__((sentinel)) 检查\n\n**vfprintf 系列**\n- vprintf(const char *fmt, va_list ap)\n- 用于包装 printf：自定义日志函数",
    example: "#include <stdio.h>\n#include <stdarg.h>\n#include <string.h>\n\n// 求和：n 表示个数\nint sum(int n, ...) {\n    va_list ap;\n    int total = 0;\n    va_start(ap, n);\n    for (int i = 0; i < n; i++) {\n        total += va_arg(ap, int);\n    }\n    va_end(ap);\n    return total;\n}\n\n// 简易 printf 实现\nvoid my_printf(const char *fmt, ...) {\n    va_list ap;\n    va_start(ap, fmt);\n    for (const char *p = fmt; *p; p++) {\n        if (*p == '%') {\n            p++;\n            switch (*p) {\n                case 'd': printf(\"%d\", va_arg(ap, int)); break;\n                case 'f': printf(\"%f\", va_arg(ap, double)); break;  // float 提升\n                case 'c': printf(\"%c\", va_arg(ap, int)); break;     // char 提升\n                case 's': printf(\"%s\", va_arg(ap, char*)); break;\n                case '%': putchar('%'); break;\n                default: putchar('%'); putchar(*p);\n            }\n        } else {\n            putchar(*p);\n        }\n    }\n    va_end(ap);\n}\n\n// 日志函数：包装 vfprintf\nvoid log_msg(int level, const char *fmt, ...) {\n    const char *names[] = {\"DEBUG\", \"INFO\", \"WARN\", \"ERROR\"};\n    printf(\"[%s] \", names[level]);\n    va_list ap;\n    va_start(ap, fmt);\n    vprintf(fmt, ap);  // 传递 va_list\n    va_end(ap);\n    putchar('\\n');\n}\n\n// 哨兵结束\nvoid run_all(void (*fn)(void), ...) {\n    va_list ap;\n    va_start(ap, fn);\n    while (fn != NULL) {\n        fn();\n        fn = va_arg(ap, void(*)(void));\n    }\n    va_end(ap);\n}\n\nint main() {\n    printf(\"%d\\n\", sum(3, 10, 20, 30));      // 60\n    printf(\"%d\\n\", sum(5, 1, 2, 3, 4, 5));    // 15\n\n    my_printf(\"name=%s age=%d score=%f\\n\", \"Alice\", 25, 95.5);\n\n    log_msg(1, \"user %s logged in\", \"admin\");\n    log_msg(3, \"error code %d\", 500);\n    return 0;\n}"
  },
  {
    id: "c-signal",
    title: "信号处理与异步安全",
    level: "高级",
    content: "**信号（Signal）概述**\n- 软件中断，由内核或进程发送\n- 异步发生，可在任意时刻打断当前执行\n- signal.h 定义信号编号\n\n**常见信号**\n- SIGINT(2)：Ctrl+C\n- SIGTERM(15)：终止请求（可捕获）\n- SIGKILL(9)：强制终止（不可捕获/忽略）\n- SIGSEGV(11)：段错误（非法内存访问）\n- SIGABRT(6)：abort() 触发\n- SIGALRM(14)：alarm 定时到期\n- SIGCHLD(17)：子进程状态变化\n- SIGPIPE(13)：写已关闭的管道\n- SIGUSR1/USR2：用户自定义\n\n**signal() vs sigaction()**\n- signal()：老接口，行为跨平台不一致\n- sigaction()：POSIX 标准，功能强大，推荐\n- sigaction 可设置标志（SA_RESTART 自动重启、SA_SIGINFO 带信息）\n\n**信号处理函数的限制（异步信号安全）**\n- 处理函数中只能调用异步信号安全函数（async-signal-safe）\n- 不可调用 malloc/printf/fopen 等（可能持锁导致死锁）\n- 安全函数：write/_exit/signal 等\n- 推荐做法：处理函数只设置 flag，主循环检查\n\n**volatile sig_atomic_t**\n- 信号处理中修改的标志变量必须用 volatile sig_atomic_t\n- volatile 防止编译器优化\n- sig_atomic_t 保证读写原子性\n\n**信号屏蔽**\n- sigprocmask 屏蔽信号（延迟投递而非丢弃）\n- 临界区保护：屏蔽 → 操作 → 恢复\n\n**不可捕获的信号**\n- SIGKILL(9) 和 SIGSTOP(19) 不能被捕获/忽略/屏蔽\n- 这是系统保留的最后手段\n\n**SIGCHLD 处理僵尸进程**\n- 子进程退出后父进程未 wait 会变僵尸\n- 捕获 SIGCHLD 在处理函数中 wait\n- 或显式忽略：signal(SIGCHLD, SIG_IGN)",
    example: "#include <stdio.h>\n#include <signal.h>\n#include <unistd.h>\n#include <string.h>\n#include <sys/wait.h>\n\nvolatile sig_atomic_t stop = 0;\n\nvoid handler(int sig) {\n    // 只做最简单操作：设置标志\n    // 不可用 printf，用 write\n    const char *msg = \"caught signal\\n\";\n    write(STDOUT_FILENO, msg, strlen(msg));\n    stop = 1;\n}\n\n// sigaction 注册\nvoid setup_signal() {\n    struct sigaction sa;\n    memset(&sa, 0, sizeof(sa));\n    sa.sa_handler = handler;\n    sigemptyset(&sa.sa_mask);\n    sa.sa_flags = SA_RESTART;  // 被中断的系统调用自动重启\n    sigaction(SIGINT, &sa, NULL);\n}\n\nint main() {\n    setup_signal();\n    printf(\"pid=%d, Ctrl+C to stop\\n\", getpid());\n    while (!stop) {\n        pause();  // 等待信号\n    }\n    printf(\"exiting\\n\");\n    return 0;\n}\n\n// 定时器\nvoid alarm_handler(int sig) {\n    printf(\"timeout!\\n\");\n    _exit(1);\n}\n\nvoid read_with_timeout() {\n    signal(SIGALRM, alarm_handler);\n    alarm(5);  // 5秒后发送 SIGALRM\n    char buf[100];\n    if (fgets(buf, sizeof(buf), stdin)) {\n        alarm(0);  // 取消定时\n        printf(\"got: %s\", buf);\n    }\n}\n\n// 处理僵尸进程\nvoid sigchld_handler(int sig) {\n    int status;\n    while (waitpid(-1, &status, WNOHANG) > 0) {\n        // 回收所有已退出子进程\n    }\n}\n\n// 忽略 SIGPIPE（写已关闭 socket 时不崩溃）\nsignal(SIGPIPE, SIG_IGN);\n\n// 屏蔽信号（临界区）\nsigset_t mask, oldmask;\nsigemptyset(&mask);\nsigaddset(&mask, SIGINT);\nsigprocmask(SIG_BLOCK, &mask, &oldmask);  // 屏蔽\n// ... 临界区操作 ...\nsigprocmask(SIG_SETMASK, &oldmask, NULL);  // 恢复"
  },
  {
    id: "c-ipc",
    title: "进程间通信 IPC 全集",
    level: "高级",
    content: "**IPC 主要方式**\n1. 管道（Pipe）\n2. 命名管道（FIFO）\n3. 消息队列（Message Queue）\n4. 共享内存（Shared Memory）\n5. 信号量（Semaphore）\n6. 信号（Signal）\n7. 套接字（Socket）\n\n**管道（Pipe）**\n- 半双工，单向数据流\n- 只能在有亲缘关系进程间使用（父子）\n- pipe(fd[2])：fd[0] 读端，fd[1] 写端\n- 内核缓冲区，默认 64KB\n- 读端关闭写端收到 SIGPIPE\n\n**命名管道（FIFO）**\n- 文件系统中的特殊文件\n- 任意进程可打开使用\n- mkfifo(path, mode) 创建\n- 阻塞打开直到对端也打开\n\n**消息队列**\n- System V 和 POSIX 两套 API\n- 消息有类型，可选择性接收\n- msgget/msgsnd/msgrcv/msgctl（System V）\n- 克服管道无格式字节流的缺点\n\n**共享内存**\n- 最快的 IPC（零拷贝）\n- 多个进程映射同一物理内存\n- 需配合信号量同步\n- shmget/shmat/shmdt/shmctl（System V）\n- mmap(MAP_SHARED) 也可实现\n\n**信号量**\n- 用于同步和互斥\n- P 操作（wait）减1，V 操作（post）加1\n- semget/semop/semctl（System V）\n- POSIX 信号量更简洁：sem_open/sem_wait/sem_post\n\n**套接字（Socket）**\n- 最通用，可跨主机\n- 本地 socket（AF_UNIX）用于本机 IPC\n- 网络 socket（AF_INET）跨主机\n\n**选型建议**\n- 父子进程简单通信：管道\n- 任意进程本机通信：FIFO 或 Unix Socket\n- 大数据高效传输：共享内存 + 信号量\n- 跨主机：Socket",
    example: "#include <stdio.h>\n#include <unistd.h>\n#include <string.h>\n#include <sys/wait.h>\n#include <sys/ipc.h>\n#include <sys/shm.h>\n#include <fcntl.h>\n#include <sys/stat.h>\n\n// 管道：父子进程通信\nvoid pipe_example() {\n    int fd[2];\n    pipe(fd);\n    pid_t pid = fork();\n    if (pid == 0) {  // 子进程写\n        close(fd[0]);\n        write(fd[1], \"hello\", 5);\n        close(fd[1]);\n    } else {  // 父进程读\n        close(fd[1]);\n        char buf[100];\n        int n = read(fd[0], buf, sizeof(buf));\n        buf[n] = 0;\n        printf(\"got: %s\\n\", buf);\n        wait(NULL);\n    }\n}\n\n// FIFO 命名管道\nvoid fifo_example() {\n    mkfifo(\"/tmp/myfifo\", 0666);\n    if (fork() == 0) {\n        int fd = open(\"/tmp/myfifo\", O_WRONLY);\n        write(fd, \"via fifo\", 8);\n        close(fd);\n    } else {\n        int fd = open(\"/tmp/myfifo\", O_RDONLY);\n        char buf[100];\n        int n = read(fd, buf, sizeof(buf));\n        buf[n] = 0;\n        printf(\"fifo: %s\\n\", buf);\n    }\n}\n\n// 共享内存\nvoid shm_example() {\n    int shmid = shmget(IPC_PRIVATE, 4096, 0666 | IPC_CREAT);\n    char *addr = shmat(shmid, NULL, 0);\n\n    if (fork() == 0) {\n        strcpy(addr, \"shared data\");\n        shmdt(addr);\n    } else {\n        wait(NULL);\n        printf(\"shm: %s\\n\", addr);\n        shmdt(addr);\n        shmctl(shmid, IPC_RMID, NULL);\n    }\n}\n\n// Unix Socket（本地高性能）\n#include <sys/socket.h>\n#include <sys/un.h>\nvoid unix_socket_example() {\n    int sockfd = socket(AF_UNIX, SOCK_STREAM, 0);\n    struct sockaddr_un addr;\n    addr.sun_family = AF_UNIX;\n    strcpy(addr.sun_path, \"/tmp/unix.sock\");\n    // bind/listen/accept/connect 同网络 socket\n}\n\nint main() {\n    pipe_example();\n    fifo_example();\n    shm_example();\n    return 0;\n}"
  },
  {
    id: "c-pthread",
    title: "多线程编程：pthread 与同步",
    level: "高级",
    content: "**pthread 基础**\n- POSIX 线程标准\n- pthread.h + -lpthread\n- pthread_create(&tid, attr, func, arg)\n- pthread_join(tid, &retval)：等待线程结束\n- pthread_exit(retval)：线程退出\n- pthread_self()：获取自身 tid\n\n**线程终止**\n- 线程函数 return 等价 pthread_exit\n- 主线程 return 或 exit() 会终止整个进程（所有线程）\n- pthread_cancel(tid) 取消线程\n- 主线程只退出用 pthread_exit\n\n**同步原语**\n1. **互斥锁（Mutex）**\n   - pthread_mutex_lock/unlock\n   - 保护临界区\n   - trylock 非阻塞尝试\n   - timedlock 超时锁定\n\n2. **条件变量（Condition Variable）**\n   - pthread_cond_wait/signal/broadcast\n   - 必须配合 mutex 使用\n   - wait 会原子地释放 mutex 并等待\n   - 虚假唤醒：用 while 循环检查条件\n\n3. **读写锁（RWLock）**\n   - 读共享，写独占\n   - 适合读多写少\n   - pthread_rwlock_rdlock/wrlock/unlock\n\n4. **自旋锁（Spinlock）**\n   - 忙等待，不睡眠\n   - 临界区极短时用\n   - pthread_spin_lock/unlock\n\n5. **屏障（Barrier）**\n   - 等待 N 个线程到达后一起继续\n   - pthread_barrier_wait\n\n6. **一次性初始化**\n   - pthread_once(&once_control, init_func)\n   - 保证 init_func 只执行一次\n\n**死锁条件（四大必要条件）**\n- 互斥、持有并等待、不可剥夺、循环等待\n- 避免方法：固定锁顺序、trylock、避免嵌套\n\n**线程安全**\n- 可重入函数（reentrant）：不依赖全局/静态变量\n- 线程安全函数：可用锁保护\n- errno 是线程局部存储（TLS）\n\n**线程局部存储**\n- __thread 关键字（GCC）\n- 每个线程独立副本",
    example: "#include <stdio.h>\n#include <pthread.h>\n#include <unistd.h>\n\n// 互斥锁\npthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;\nint counter = 0;\n\nvoid *increment(void *arg) {\n    for (int i = 0; i < 100000; i++) {\n        pthread_mutex_lock(&lock);\n        counter++;  // 临界区\n        pthread_mutex_unlock(&lock);\n    }\n    return NULL;\n}\n\nvoid mutex_demo() {\n    pthread_t t1, t2;\n    pthread_create(&t1, NULL, increment, NULL);\n    pthread_create(&t2, NULL, increment, NULL);\n    pthread_join(t1, NULL);\n    pthread_join(t2, NULL);\n    printf(\"counter = %d\\n\", counter);  // 200000\n}\n\n// 条件变量：生产者消费者\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\npthread_cond_t cond = PTHREAD_COND_INITIALIZER;\nint queue[100], head = 0, tail = 0;\n\nvoid *producer(void *arg) {\n    for (int i = 0; i < 10; i++) {\n        pthread_mutex_lock(&m);\n        queue[tail++] = i;\n        pthread_cond_signal(&cond);  // 通知消费者\n        pthread_mutex_unlock(&m);\n    }\n    return NULL;\n}\n\nvoid *consumer(void *arg) {\n    for (int i = 0; i < 10; i++) {\n        pthread_mutex_lock(&m);\n        while (head == tail) {  // while 防虚假唤醒\n            pthread_cond_wait(&cond, &m);  // 释放 m 并等待\n        }\n        int item = queue[head++];\n        pthread_mutex_unlock(&m);\n        printf(\"consumed %d\\n\", item);\n    }\n    return NULL;\n}\n\n// 读写锁\npthread_rwlock_t rwlock = PTHREAD_RWLOCK_INITIALIZER;\nint data = 0;\n\nvoid *reader(void *arg) {\n    pthread_rwlock_rdlock(&rwlock);\n    printf(\"read %d\\n\", data);  // 多个读可并发\n    pthread_rwlock_unlock(&rwlock);\n    return NULL;\n}\n\nvoid *writer(void *arg) {\n    pthread_rwlock_wrlock(&rwlock);\n    data++;  // 写独占\n    pthread_rwlock_unlock(&rwlock);\n    return NULL;\n}\n\n// 线程局部存储\n__thread int tid = 0;  // 每线程独立\n\nvoid *tls_demo(void *arg) {\n    tid = (int)(long)arg;\n    printf(\"thread tid=%d\\n\", tid);  // 各线程独立\n    return NULL;\n}\n\nint main() {\n    mutex_demo();\n    pthread_t p, c;\n    pthread_create(&p, NULL, producer, NULL);\n    pthread_create(&c, NULL, consumer, NULL);\n    pthread_join(p, NULL);\n    pthread_join(c, NULL);\n    return 0;\n}"
  },
  {
    id: "c-dlopen",
    title: "动态库与 dlopen 运行时加载",
    level: "高级",
    content: "**静态库 vs 动态库**\n- **静态库（.a）**：编译时链接，代码拷贝进可执行文件\n  - 优点：独立运行、启动快\n  - 缺点：体积大、更新需重新编译、多进程重复占用内存\n- **动态库（.so/.dll）**：运行时链接，内存中只一份\n  - 优点：体积小、可独立更新、多进程共享\n  - 缺点：依赖运行环境、启动稍慢\n\n**动态库创建**\n- `gcc -shared -fPIC -o libfoo.so foo.c`\n- -fPIC：位置无关代码（Position Independent Code）\n- -shared：生成共享库\n\n**链接方式**\n1. **链接时绑定（普通链接）**\n   - `gcc main.c -L. -lfoo -o main`\n   - 运行时由动态链接器加载\n   - LD_LIBRARY_PATH 指定搜索路径\n   - ldd 查看依赖\n\n2. **运行时绑定（dlopen）**\n   - 程序运行中按需加载\n   - dlfcn.h：dlopen/dlsym/dlclose/dlerror\n   - 实现插件系统\n\n**dlopen API**\n- `dlopen(path, flag)`：加载库，返回 handle\n  - RTLD_LAZY：延迟绑定（用到时解析符号）\n  - RTLD_NOW：立即解析所有符号\n  - RTLD_GLOBAL：符号可被后续库共享\n  - RTLD_LOCAL：符号不共享（默认）\n- `dlsym(handle, name)`：查找符号，返回地址\n- `dlclose(handle)`：卸载库（引用计数归零才真卸载）\n- `dlerror()`：获取错误信息\n\n**插件架构实现**\n1. 定义统一接口（头文件）\n2. 插件实现接口，编译为 .so\n3. 主程序扫描插件目录，dlopen 加载\n4. dlsym 获取约定函数（如 plugin_init）\n5. 调用插件功能\n\n**符号可见性**\n- 默认所有全局符号导出\n- __attribute__((visibility(\"hidden\"))) 隐藏\n- -fvisibility=hidden 全局默认隐藏，显式导出用 __attribute__((visibility(\"default\")))\n- 减少符号表，加速加载，避免冲突\n\n**版本管理**\n- .so 通常带版本号：libfoo.so.1.0.0\n- 软链接：libfoo.so → libfoo.so.1 → libfoo.so.1.0.0\n- SONAME：libfoo.so.1",
    example: "// ===== math_plugin.h（公共接口）=====\n// int add(int a, int b);\n// const char *plugin_name(void);\n\n// ===== add_plugin.c（插件实现）=====\n#include \"math_plugin.h\"\nint add(int a, int b) { return a + b; }\nconst char *plugin_name(void) { return \"add\"; }\n// 编译: gcc -shared -fPIC -o libadd.so add_plugin.c\n\n// ===== main.c（主程序加载插件）=====\n#define _GNU_SOURCE\n#include <stdio.h>\n#include <dlfcn.h>\n\ntypedef int (*add_fn)(int, int);\ntypedef const char *(*name_fn)(void);\n\nint main() {\n    // 运行时加载动态库\n    void *handle = dlopen(\"./libadd.so\", RTLD_NOW);\n    if (!handle) {\n        fprintf(stderr, \"dlopen: %s\\n\", dlerror());\n        return 1;\n    }\n\n    // 查找符号\n    add_fn add = (add_fn)dlsym(handle, \"add\");\n    name_fn name = (name_fn)dlsym(handle, \"plugin_name\");\n\n    char *err = dlerror();\n    if (err) {\n        fprintf(stderr, \"dlsym: %s\\n\", err);\n        dlclose(handle);\n        return 1;\n    }\n\n    printf(\"%s: 3+4=%d\\n\", name(), add(3, 4));\n\n    dlclose(handle);\n    return 0;\n}\n// 编译: gcc main.c -ldl -o main\n// 运行: ./main\n\n// 查看动态库依赖\n// ldd ./main\n// LD_LIBRARY_PATH=. ./main\n\n// 符号可见性控制\n__attribute__((visibility(\"default\"))) int exported_func(void) { return 1; }\n__attribute__((visibility(\"hidden\"))) int internal_func(void) { return 2; }\n// 编译: gcc -shared -fPIC -fvisibility=hidden -o libfoo.so foo.c"
  }
],
c_ext2_questions: [
  {q:"int *p[10] 的正确解读是？", level:"高级", options:["指向含10个int数组的指针","含10个元素的数组，每个是指向int的指针（指针数组）","指向int的指针，值为10","10个int的数组"], answer:1, explain:"[] 优先级高于 *，p 先与 [] 结合是数组，元素类型是 int*，所以是指针数组（10个指针）。int (*p)[10] 才是数组指针。"},
  {q:"int (*fp)(int, int) 表示？", level:"高级", options:["返回函数指针的函数","指向返回int、参数两个int的函数的指针（函数指针）","函数名为 fp","int 类型的指针"], answer:1, explain:"括号让 * 先结合，fp 是指针，指向 int(int,int) 类型的函数，即函数指针。"},
  {q:"函数指针数组（跳转表）的优势是？", level:"高级", options:["节省内存","O(1) 分发，替代 switch-case，可扩展","线程安全","类型安全"], answer:1, explain:"函数指针数组通过索引直接调用，O(1) 时间分发，比 switch-case 更灵活，新增操作只需扩展数组，常用于解释器指令分发。"},
  {q:"const int *p 中 const 修饰的是？", level:"进阶", options:["指针 p 本身","p 指向的数据（不能通过 p 修改值）","p 的地址","p 的类型"], answer:1, explain:"const 在 * 左边修饰指向的数据，不能通过 p 修改值但可改 p 的指向；int * const p 才是修饰指针本身。"},
  {q:"volatile 关键字的主要作用是？", level:"进阶", options:["变量不可修改","告诉编译器变量可能被意外修改，禁止优化","线程安全","常量优化"], answer:1, explain:"volatile 告诉编译器变量可能被硬件/中断/其他线程修改，每次访问都从内存读取，禁止缓存到寄存器或消除冗余访问。"},
  {q:"以下哪个场景必须用 volatile？", level:"高级", options:["普通局部变量","内存映射的硬件寄存器","全局配置","函数参数"], answer:1, explain:"内存映射 IO 寄存器的值可能被硬件修改，必须用 volatile 确保每次都从真实地址读取，否则编译器可能优化掉读取。"},
  {q:"const volatile int *p 表示？", level:"高级", options:["矛盾，无意义","程序不能通过 p 修改（const），但值会被外部改变（volatile）","只读常量","可变指针"], answer:1, explain:"const volatile 组合：程序不能写（const）但硬件会更新（volatile），典型用于只读硬件状态寄存器。"},
  {q:"结构体内存对齐的目的是？", level:"进阶", options:["节省内存","提高 CPU 访问效率","加密数据","对齐网络传输"], answer:1, explain:"CPU 访问对齐数据通常只需一次内存读取，非对齐可能需要多次或触发异常，编译器自动填充 padding 以对齐。"},
  {q:"#pragma pack(1) 的作用是？", level:"进阶", options:["优化性能","取消对齐，1字节对齐（紧凑结构）","限制大小为1","对齐到页"], answer:1, explain:"#pragma pack(1) 设置1字节对齐，取消填充，节省空间但可能降低访问性能，常用于网络协议和文件格式。"},
  {q:"小端序（Little-Endian）的特点是？", level:"进阶", options:["高字节存低地址","低字节存低地址","只有1字节","网络字节序"], answer:1, explain:"小端序低字节存低地址，如 0x12345678 在内存为 78 56 34 12。x86 和 ARM（默认）是小端。"},
  {q:"网络字节序采用的是？", level:"进阶", options:["小端","大端","主机序","可配置"], answer:1, explain:"网络协议规定使用大端序传输，htonl/htons 将主机序转网络序，ntohl/ntohs 反向转换。"},
  {q:"sizeof(结构体{char a; int b; char c;}) 在默认对齐下通常是？", level:"进阶", options:["6","8","12","16"], answer:2, explain:"a(1)+3填充+b(4)+c(1)+3填充=12。调整顺序为 {int b; char a; char c;} 可减到8，这是结构体优化的常见手法。"},
  {q:"va_arg 取 float 参数时应使用什么类型？", level:"进阶", options:["float","double","int","long"], answer:1, explain:"可变参数会发生默认参数提升，float 自动提升为 double，char/short 提升为 int，因此 va_arg 必须用提升后的类型。"},
  {q:"可变参数函数如何知道参数个数？", level:"进阶", options:["编译器自动检测","通过命名参数（如 printf 的格式串）或哨兵值","无法知道","运行时反射"], answer:1, explain:"va_arg 无法自动知道个数，调用者必须提供信息：printf 用格式串的占位符数量，execl 用 NULL 哨兵结尾。"},
  {q:"信号处理函数中可以安全调用？", level:"高级", options:["printf","malloc","write","fopen"], answer:2, explain:"信号处理是异步的，只能调用异步信号安全函数。printf/malloc/fopen 可能持锁导致死锁，write 是安全的。"},
  {q:"volatile sig_atomic_t 用于？", level:"高级", options:["原子计数器","信号处理中修改的标志变量，防止优化并保证读写原子","线程同步","大整数"], answer:1, explain:"sig_atomic_t 保证读写原子性，volatile 防止编译器优化，两者结合用于信号处理函数中修改、主循环中检查的标志变量。"},
  {q:"以下哪个信号不能被捕获或忽略？", level:"进阶", options:["SIGINT","SIGTERM","SIGKILL","SIGSEGV"], answer:2, explain:"SIGKILL(9) 和 SIGSTOP(19) 不可捕获/忽略/屏蔽，是系统保留的强制手段。其他信号都可被 signal/sigaction 捕获。"},
  {q:"sigaction 相比 signal 的优势是？", level:"高级", options:["更快","可设置标志（如 SA_RESTART）、获取信号信息、行为更可控","更简单","跨平台"], answer:1, explain:"sigaction 是 POSIX 标准，可控制信号处理行为（SA_RESTART 自动重启中断的系统调用、SA_SIGINFO 获取发送者信息等），而 signal 行为跨平台不一致。"},
  {q:"匿名管道（pipe）的限制是？", level:"进阶", options:["只能单向","只能用于有亲缘关系进程（如父子）","缓冲区有限","以上都是"], answer:3, explain:"pipe 是半双工单向、只能在有亲缘关系进程间使用、内核缓冲区有限（通常64KB）。命名管道 FIFO 可用于任意进程。"},
  {q:"最快的进程间通信方式是？", level:"高级", options:["管道","消息队列","共享内存","套接字"], answer:2, explain:"共享内存零拷贝，进程直接读写同一物理内存，无需内核中转，速度最快。但需要信号量等同步机制配合。"},
  {q:"共享内存需要配合什么机制？", level:"高级", options:["管道","信号量","消息队列","信号"], answer:1, explain:"共享内存本身无同步机制，多进程并发读写会竞争，需配合信号量或互斥锁实现同步与互斥。"},
  {q:"pthread_mutex_lock 与 pthread_cond_wait 的关系是？", level:"高级", options:["无关","cond_wait 会原子地释放 mutex 并等待，被唤醒时重新加锁","cond_wait 不需要 mutex","lock 等待 cond"], answer:1, explain:"pthread_cond_wait 原子地释放 mutex 并阻塞等待信号，被唤醒时自动重新加锁，这避免了等待与加锁之间的竞态窗口。"},
  {q:"条件变量 wait 为什么要用 while 循环检查条件？", level:"高级", options:["性能考虑","防止虚假唤醒（spurious wakeup）","避免死锁","简化代码"], answer:1, explain:"pthread_cond_wait 可能被虚假唤醒（无 signal 也返回），必须用 while 重新检查条件，if 检查会导致虚假唤醒时错误继续。"},
  {q:"读写锁适用于什么场景？", level:"高级", options:["写多读少","读多写少","读写均衡","只读"], answer:1, explain:"读写锁允许多个读并发但写独占，读多写少时能显著提高并发度；写多时退化为互斥锁，无优势。"},
  {q:"死锁的四个必要条件不包括？", level:"高级", options:["互斥","持有并等待","不可剥夺","优先级反转"], answer:3, explain:"死锁四个必要条件是：互斥、持有并等待、不可剥夺、循环等待。优先级反转是另一问题（可导致死锁但不是必要条件）。"},
  {q:"__thread 关键字的作用是？", level:"高级", options:["线程同步","线程局部存储，每线程独立副本","创建线程","线程优先级"], answer:1, explain:"__thread（GCC）声明线程局部存储变量，每个线程有独立副本，互不干扰，避免加锁。C11 用 _Thread_local。"},
  {q:"静态库与动态库的主要区别是？", level:"进阶", options:["无区别","静态库编译时链接代码拷入可执行文件，动态库运行时加载共享","静态库更快","动态库不能更新"], answer:1, explain:"静态库在编译时拷贝进可执行文件，独立但体积大；动态库运行时加载，多进程共享内存，可独立更新。"},
  {q:"编译动态库需要的选项是？", level:"进阶", options:["-static","-shared -fPIC","-dynamic","-lib"], answer:1, explain:"-shared 生成共享库，-fPIC 生成位置无关代码（动态库必须，因为加载地址不确定）。"},
  {q:"dlopen 的 RTLD_LAZY 含义是？", level:"高级", options:["立即解析所有符号","延迟解析，用到符号时才解析","懒加载不解析","快速模式"], answer:1, explain:"RTLD_LAZY 延迟绑定，函数被调用时才解析符号，启动快但可能运行时报错；RTLD_NOW 立即解析所有符号，启动慢但能提前发现错误。"},
  {q:"dlsym 的返回值需要？", level:"高级", options:["直接使用","强制转换为正确的函数指针类型","转成 int","释放"], answer:1, explain:"dlsym 返回 void*，必须强制转换为正确的函数指针类型才能调用，否则无法通过类型检查。"},
  {q:"符号可见性 hidden 的好处是？", level:"高级", options:["加速运行","减少导出符号，加速加载并避免符号冲突","加密代码","节省内存"], answer:1, explain:"visibility(hidden) 隐藏符号不导出，减小符号表加速动态加载，避免与其他库的符号冲突，只显式导出必要接口。"}
]
