// === C++ EXT2 ===
cpp_ext2_topics: [
  {
    id: "cpp-compile-link",
    title: "C++ 编译链接过程详解",
    level: "进阶",
    content: "**编译流程四阶段**\n1. 预处理（Preprocessing）：展开宏、包含头文件、条件编译\n2. 编译（Compilation）：语法分析 → AST → 生成汇编\n3. 汇编（Assembly）：汇编代码 → 目标文件（.o/.obj）\n4. 链接（Linking）：目标文件 + 库 → 可执行文件\n\n**预处理阶段**\n- #include：头文件内容原样插入\n- #define/#undef：宏定义与取消\n- #if/#ifdef/#ifndef/#endif：条件编译\n- #pragma：编译器指令\n- g++ -E 生成预处理结果\n\n**编译阶段**\n- 词法分析 → Token\n- 语法分析 → AST\n- 语义分析 → 类型检查\n- 代码生成 → 汇编（.s）\n- g++ -S 生成汇编\n\n**汇编阶段**\n- 汇编指令 → 机器码\n- 生成目标文件（ELF/COFF 格式）\n- 包含：代码段 .text、数据段 .data/.bss、符号表、重定位表\n- g++ -c 生成目标文件\n\n**链接阶段**\n- **符号解析**：将引用绑定到定义\n- **重定位**：确定最终地址\n- 链接类型：静态链接、动态链接\n\n**链接错误**\n- undefined reference：符号未定义（未实现或未链接库）\n- multiple definition：符号重复定义\n- 解决：检查头文件声明与实现是否匹配、链接库顺序\n\n**One Definition Rule (ODR)**\n- 每个实体在整个程序中只能有一个定义\n- 内联函数/模板/constexpr 可多次定义但必须一致\n- 头文件中只放声明，定义放 cpp（除外：inline/template/constexpr）\n\n**头文件与 include 顺序**\n- 推荐顺序：自身头文件 → C 标准库 → C++ 标准库 → 第三方库 → 项目头文件\n- 自身头文件放最前可检测头文件是否自包含\n- #pragma once / include guard 防止重复包含\n\n**编译优化级别**\n- -O0：不优化（默认，调试用）\n- -O1：基本优化\n- -O2：常用优化（发布推荐）\n- -O3：激进优化（可能增加体积）\n- -Os：优化体积\n- -Og：调试友好优化",
    example: "// 文件结构示例\n// ===== math.h =====\n#pragma once\nint add(int a, int b);  // 声明\n\n// ===== math.cpp =====\n#include \"math.h\"\nint add(int a, int b) { return a + b; }  // 定义\n\n// ===== main.cpp =====\n#include <iostream>\n#include \"math.h\"\nint main() {\n    std::cout << add(1, 2) << std::endl;\n    return 0;\n}\n\n// 编译命令：\n// g++ -E main.cpp -o main.ii    # 预处理\n// g++ -S main.ii -o main.s       # 编译为汇编\n// g++ -c main.s -o main.o        # 汇编为目标文件\n// g++ main.o math.o -o main      # 链接\n// 或一步完成：\n// g++ -O2 main.cpp math.cpp -o main\n\n// include guard vs pragma once\n#ifndef MATH_H\n#define MATH_H\nint add(int a, int b);\n#endif\n\n// 查看符号表\n// nm main.o\n// readelf -s main.o  (ELF)\n\n// 常见链接错误解决\n// undefined reference to `add`:\n//   - 检查 math.cpp 是否编译\n//   - 检查库链接顺序（被依赖的放后面）\n// multiple definition of `foo`:\n//   - 检查是否在头文件中定义了非 inline 函数"
  },
  {
    id: "cpp-raii",
    title: "RAII 与资源管理深度",
    level: "进阶",
    content: "**RAII（Resource Acquisition Is Initialization）**\n- 资源获取即初始化\n- 将资源绑定到对象生命周期\n- 构造时获取资源，析构时释放\n- 利用栈对象确定性销毁保证资源释放\n\n**RAII 核心思想**\n- 用对象管理资源（内存/文件/锁/socket）\n- 异常安全：即使抛异常，栈展开也会析构已构造对象\n- 消除手动管理资源的繁琐和遗漏\n\n**RAII 经典应用**\n- 智能指针：unique_ptr/shared_ptr 管理内存\n- lock_guard/unique_lock 管理锁\n- fstream 管理文件\n- vector/string 管理动态数组\n\n**自定义 RAII 类**\n- 构造函数获取资源\n- 析构函数释放资源\n- 实现拷贝/移动语义（按需）\n- 遵循三/五法则\n\n**三法则（Rule of Three）**\n- 如果定义了析构函数、拷贝构造、拷贝赋值之一，通常需要三个都定义\n- 因为涉及资源管理时默认的浅拷贝会出错\n\n**五法则（Rule of Five）**\n- C++11 加入移动语义后扩展为五\n- 析构、拷贝构造、拷贝赋值、移动构造、移动赋值\n\n**零法则（Rule of Zero）**\n- 优先使用标准 RAII 类型管理资源\n- 类本身不需要定义任何特殊成员函数\n- 让编译器生成默认实现即可\n\n**RAII 与异常安全**\n- 构造函数抛异常：析构函数不会被调用（对象未完成构造）\n- 构造函数中获取多个资源时，成员初始化顺序保证析构逆序\n- 推荐用智能指针管理构造函数中的临时资源\n\n**资源所有权语义**\n- 独占所有权：unique_ptr\n- 共享所有权：shared_ptr\n- 弱引用：weak_ptr\n- 借用（不管理）：裸指针引用",
    example: "#include <memory>\n#include <mutex>\n#include <fstream>\n\n// 自定义 RAII：管理 C API 资源\nclass FileHandle {\n    FILE* fp_;\npublic:\n    explicit FileHandle(const char* path, const char* mode)\n        : fp_(fopen(path, mode)) {\n        if (!fp_) throw std::runtime_error(\"open failed\");\n    }\n    ~FileHandle() { if (fp_) fclose(fp_); }\n\n    // 禁止拷贝（资源独占）\n    FileHandle(const FileHandle&) = delete;\n    FileHandle& operator=(const FileHandle&) = delete;\n\n    // 允许移动\n    FileHandle(FileHandle&& o) noexcept : fp_(o.fp_) { o.fp_ = nullptr; }\n    FileHandle& operator=(FileHandle&& o) noexcept {\n        if (this != &o) {\n            if (fp_) fclose(fp_);\n            fp_ = o.fp_;\n            o.fp_ = nullptr;\n        }\n        return *this;\n    }\n\n    FILE* get() const { return fp_; }\n};\n\n// 使用 RAII\nvoid process() {\n    FileHandle f(\"data.txt\", \"r\");  // 构造获取资源\n    // 使用 f\n    char buf[100];\n    fgets(buf, sizeof(buf), f.get());\n}  // 析构自动 fclose，即使抛异常也安全\n\n// Rule of Zero：优先用标准类型\nclass Good {\n    std::vector<int> data_;\n    std::string name_;\n    std::unique_ptr<Connection> conn_;\npublic:\n    Good() = default;  // 无需自定义析构/拷贝/移动\n};\n\n// RAII 锁\nvoid safe_increment(int& counter, std::mutex& m) {\n    std::lock_guard<std::mutex> lk(m);  // 构造时加锁\n    counter++;\n}  // 析构时解锁，即使抛异常也解锁\n\n// unique_lock 更灵活\nvoid flexible_lock(std::mutex& m) {\n    std::unique_lock<std::mutex> lk(m);\n    // ... 可以手动 unlock/lock\n    lk.unlock();\n    // 做些不需要锁的事\n    lk.lock();\n    // ...\n}  // 析构确保最终解锁"
  },
  {
    id: "cpp-smart-ptr",
    title: "智能指针深度与陷阱",
    level: "高级",
    content: "**unique_ptr**\n- 独占所有权，不可拷贝，可移动\n- 零开销抽象（与裸指针相当）\n- 默认 delete，可自定义删除器\n- make_unique（C++14）创建\n- 数组特化：unique_ptr<T[]>\n\n**shared_ptr**\n- 共享所有权，引用计数\n- 引用计数原子操作，线程安全（计数本身），但对象访问需额外同步\n- 控制块包含：强引用计数、弱引用计数、删除器、分配器\n- make_shared 一次分配（对象+控制块），但内存延迟释放\n- 控制块创建时机：make_shared / shared_ptr 构造 / enable_shared_from_this\n\n**weak_ptr**\n- 不增加强引用计数，不影响对象释放\n- 用于打破循环引用、观察者模式、缓存\n- lock() 提升为 shared_ptr（若对象存活）\n- expired() 检查是否已释放\n\n**循环引用问题**\n- shared_ptr 互相引用导致引用计数永不归零\n- 内存泄漏\n- 解决：一方用 weak_ptr\n\n**enable_shared_from_this**\n- 类继承 enable_shared_from_this<T>\n- shared_from_this() 返回自身的 shared_ptr\n- 不能在构造函数中调用（此时还未纳入管理）\n- 避免用 this 构造 shared_ptr（会产生两个控制块）\n\n**自定义删除器**\n- unique_ptr<T, Deleter> 类型含删除器类型\n- shared_ptr 删除器不影响类型（存在控制块）\n- 用于管理非 new 资源（fopen/malloc/句柄）\n\n**make_shared vs new**\n- make_shared：一次分配，性能好，但内存延迟释放（weak_ptr 延长控制块生命周期）\n- shared_ptr(new T)：两次分配\n- make_shared 不支持自定义删除器和私有构造\n\n**性能考量**\n- shared_ptr 拷贝有原子操作开销\n- 传参优先 const shared_ptr<T>& 或 T&\n- 局部使用优先 unique_ptr\n\n**常见陷阱**\n- 用 this 构造多个 shared_ptr → 双重释放\n- 循环引用 → 内存泄漏\n- shared_ptr 线程安全 ≠ 对象线程安全\n- make_shared 后 weak_ptr 延迟对象内存释放",
    example: "#include <memory>\n#include <iostream>\n\n// unique_ptr 独占\nvoid unique_demo() {\n    auto p = std::make_unique<int>(42);\n    // auto p2 = p;  // 错：不可拷贝\n    auto p2 = std::move(p);  // 移动\n    std::cout << *p2 << std::endl;\n}  // 自动 delete\n\n// 自定义删除器\nauto deleter = [](FILE* f) {\n    if (f) { std::cout << \"closing file\\n\"; fclose(f); }\n};\nstd::unique_ptr<FILE, decltype(deleter)> fp(fopen(\"a.txt\", \"r\"), deleter);\n\n// shared_ptr 共享\nvoid shared_demo() {\n    auto p = std::make_shared<int>(100);\n    auto p2 = p;  // 引用计数 +1\n    std::cout << p.use_count() << std::endl;  // 2\n}\n\n// 循环引用问题\nstruct Node {\n    std::shared_ptr<Node> next;  // 强引用\n    ~Node() { std::cout << \"destroyed\\n\"; }\n};\n\nvoid leak() {\n    auto a = std::make_shared<Node>();\n    auto b = std::make_shared<Node>();\n    a->next = b;\n    b->next = a;  // 循环引用：内存泄漏！\n}  // 引用计数都不归零\n\n// 用 weak_ptr 打破循环\nstruct Node2 {\n    std::shared_ptr<Node2> next;\n    std::weak_ptr<Node2> prev;  // 弱引用打破循环\n};\n\nvoid no_leak() {\n    auto a = std::make_shared<Node2>();\n    auto b = std::make_shared<Node2>();\n    a->next = b;\n    b->prev = a;  // weak_ptr 不增加计数\n}  // 正常释放\n\n// enable_shared_from_this\nclass Widget : public std::enable_shared_from_this<Widget> {\npublic:\n    std::shared_ptr<Widget> get() {\n        return shared_from_this();  // 安全\n        // return shared_ptr<Widget>(this);  // 危险！多控制块\n    }\n};\n\n// weak_ptr 观察者\nvoid weak_demo() {\n    std::weak_ptr<int> wp;\n    {\n        auto sp = std::make_shared<int>(42);\n        wp = sp;\n    }\n    std::cout << wp.expired() << std::endl;  // 1 已释放\n    if (auto sp = wp.lock()) {  // 尝试提升\n        std::cout << *sp << std::endl;\n    }\n}"
  },
  {
    id: "cpp-iterator-invalidation",
    title: "STL 迭代器失效问题",
    level: "高级",
    content: "**迭代器失效概述**\n- 容器结构修改（插入/删除）可能导致已有迭代器失效\n- 使用失效迭代器是未定义行为\n- 不同容器失效规则不同\n\n**序列容器**\n- **vector**：\n  - 插入：若未扩容，插入点之后迭代器失效；扩容则全部失效\n  - 删除：删除点及之后失效\n  - reserve 预分配可减少扩容失效\n- **deque**：\n  - 插入/删除两端：所有迭代器失效（但引用/指针可能不失效）\n  - 中间插入/删除：所有迭代器、引用、指针失效\n- **list/forward_list**：\n  - 插入：不影响其他迭代器\n  - 删除：仅被删除元素的迭代器失效\n  - 链表节点独立，不影响其他\n\n**关联容器（红黑树）**\n- **set/map/multiset/multimap**：\n  - 插入：不影响已有迭代器\n  - 删除：仅被删除元素迭代器失效\n\n**无序容器（哈希）**\n- **unordered_set/unordered_map**：\n  - 插入：若触发 rehash 则所有迭代器失效（引用不失效）\n  - 删除：仅被删除元素失效\n  - reserve 可避免 rehash\n\n**安全删除模式**\n- erase 返回下一个有效迭代器（C++11）\n- it = container.erase(it)\n- 关联容器旧式：container.erase(it++)\n\n**vector 边遍历边删除**\n```cpp\nauto it = v.begin();\nwhile (it != v.end()) {\n    if (condition) it = v.erase(it);\n    else ++it;\n}\n```\n\n**list 边遍历边删除**\n- erase 返回下一个，或 erase(it++)\n\n**关联容器边遍历边删除**\n- C++11：it = m.erase(it)\n- C++11前：m.erase(it++)\n\n**避免失效的技巧**\n- 用 erase-remove 惯用法删除多个\n- std::remove_if + erase 批量删除\n- 先收集要删除的，再统一删除",
    example: "#include <vector>\n#include <list>\n#include <map>\n#include <algorithm>\n\n// vector 边遍历边删除（正确）\nvoid vector_erase(std::vector<int>& v) {\n    auto it = v.begin();\n    while (it != v.end()) {\n        if (*it % 2 == 0) {\n            it = v.erase(it);  // erase 返回下一个有效迭代器\n        } else {\n            ++it;\n        }\n    }\n}\n\n// erase-remove 惯用法（更高效）\nvoid vector_remove(std::vector<int>& v) {\n    v.erase(std::remove_if(v.begin(), v.end(),\n        [](int x){ return x % 2 == 0; }), v.end());\n}\n// C++20: std::erase_if(v, [](int x){ return x % 2 == 0; });\n\n// map 边遍历边删除\nvoid map_erase(std::map<int,int>& m) {\n    for (auto it = m.begin(); it != m.end(); ) {\n        if (it->second == 0) {\n            it = m.erase(it);  // C++11 返回下一个\n        } else {\n            ++it;\n        }\n    }\n}\n\n// 迭代器失效陷阱\nvoid pitfall() {\n    std::vector<int> v = {1,2,3,4,5};\n    auto it = v.begin();\n    v.push_back(6);  // 可能扩容，it 失效！\n    // std::cout << *it;  // 未定义行为\n}\n\n// reserve 避免扩容失效\nvoid safe_reserve() {\n    std::vector<int> v;\n    v.reserve(1000);  // 预分配\n    auto it = v.begin();\n    for (int i = 0; i < 100; i++) {\n        v.push_back(i);  // 不超过 1000 不会扩容\n    }\n    // it 仍有效\n}\n\n// list 迭代器稳定\nvoid list_stable() {\n    std::list<int> l = {1,2,3,4,5};\n    auto it = std::find(l.begin(), l.end(), 3);\n    l.push_front(0);  // 不影响 it\n    l.push_back(6);   // 不影响 it\n    std::cout << *it << std::endl;  // 3 仍有效\n    l.erase(it);  // 仅 it 失效\n}\n\n// unordered_map rehash 失效\nvoid rehash_pitfall() {\n    std::unordered_map<int,int> m;\n    m.reserve(1000);  // 避免后续 rehash\n    auto it = m.find(1);\n    m[2] = 20;  // 未 rehash 则 it 有效，rehash 则失效\n}"
  },
  {
    id: "cpp-sfinae",
    title: "SFINAE 与 tag dispatch",
    level: "高级",
    content: "**SFINAE（Substitution Failure Is Not An Error）**\n- 替换失败不是错误\n- 模板实例化时，某些替换失败不会报错，只是从重载集中移除\n- 用于在编译期根据类型特性选择不同实现\n\n**enable_if**\n- std::enable_if<Condition, T>::type\n- Condition 为 true 时有 type 成员，false 时无（SFINAE）\n- 经典用法：函数模板返回值/参数上 enable_if\n\n**enable_if 三种用法**\n1. 返回值：`template<class T> typename enable_if<cond, Ret>::type f()`\n2. 参数：`template<class T> void f(T, typename enable_if<cond>::type* = nullptr)`\n3. 模板参数：`template<class T, class = typename enable_if<cond>::type> void f()`\n\n**type_traits**\n- is_integral / is_floating_point / is_pointer\n- is_class / is_enum / is_union\n- is_same / is_base_of / is_convertible\n- has_member_xxx（自定义检测）\n- C++17 _v 后缀简化：is_integral_v<T>\n\n**void_t 技巧（C++17）**\n- 检测类型是否有某些成员\n- `template<class, class = void> struct has_x : false_type{};`\n- `template<class T> struct has_x<T, void_t<decltype(T::x)>> : true_type{};`\n\n**if constexpr（C++17）**\n- 编译期条件分支，不满足的分支不实例化\n- 比 SFINAE 更简洁\n- 替代许多 SFINAE 场景\n\n**tag dispatch**\n- 用空结构体作为标签类型\n- 通过重载在编译期选择实现\n- iterator_category 分发是经典案例\n\n**Concepts（C++20）**\n- 替代 SFINAE 的现代方案\n- 语法清晰，错误信息友好\n- requires 表达式\n\n**SFINAE 应用场景**\n- 根据类型选择算法（整数 vs 浮点）\n- 检测成员是否存在\n- 条件启用序列化\n- 限制模板参数类型",
    example: "#include <type_traits>\n#include <iostream>\n\n// enable_if：仅整数类型\ntemplate<class T>\ntypename std::enable_if<std::is_integral<T>::value, T>::type\nfoo(T x) { return x * 2; }\n\n// 仅浮点类型\ntemplate<class T>\ntypename std::enable_if<std::is_floating_point<T>::value, T>::type\nfoo(T x) { return x / 2; }\n\n// C++14 简化\ntemplate<class T>\nstd::enable_if_t<std::is_integral_v<T>, T>\nbar(T x) { return x * 2; }\n\n// if constexpr（推荐）\ntemplate<class T>\nauto process(T x) {\n    if constexpr (std::is_integral_v<T>) {\n        return x * 2;  // 整数分支\n    } else if constexpr (std::is_floating_point_v<T>) {\n        return x / 2;  // 浮点分支\n    } else {\n        return;  // 其他\n    }\n}\n\n// void_t 检测成员\ntemplate<class, class = void>\nstruct has_size : std::false_type {};\n\ntemplate<class T>\nstruct has_size<T, std::void_t<decltype(std::declval<T>().size())>>\n    : std::true_type {};\n\n// 使用\nstatic_assert(has_size<std::vector<int>>::value, \"\");\nstatic_assert(!has_size<int>::value, \"\");\n\n// tag dispatch\ntemplate<class Iter>\nvoid advance_impl(Iter& it, int n, std::random_access_iterator_tag) {\n    it += n;  // 随机访问：O(1)\n}\n\ntemplate<class Iter>\nvoid advance_impl(Iter& it, int n, std::bidirectional_iterator_tag) {\n    if (n > 0) while (n--) ++it;  // 双向：O(n)\n    else while (n++) --it;\n}\n\ntemplate<class Iter>\nvoid my_advance(Iter& it, int n) {\n    advance_impl(it, n,\n        typename std::iterator_traits<Iter>::iterator_category{});\n}\n\n// C++20 Concepts 替代 SFINAE\ntemplate<std::integral T>\nT add_concept(T a, T b) { return a + b; }  // 只接受整数\n\nint main() {\n    std::cout << foo(10) << std::endl;     // 20 (整数版本)\n    std::cout << foo(3.14) << std::endl;   // 1.57 (浮点版本)\n    std::cout << process(5) << std::endl;   // 10\n    std::cout << process(2.5) << std::endl; // 1.25\n    return 0;\n}"
  },
  {
    id: "cpp-exception-safety",
    title: "C++ 异常安全等级",
    level: "高级",
    content: "**异常安全四个等级**\n1. **无异常保证（No guarantee）**：最差，可能资源泄漏、数据损坏\n2. **基本保证（Basic guarantee）**：不泄漏资源，对象处于有效状态（但具体值不确定）\n3. **强保证（Strong guarantee）**：操作要么完全成功，要么回滚到调用前状态（事务语义）\n4. **不抛异常保证（Nothrow guarantee）**：绝不抛异常，用 noexcept 标记\n\n**基本保证实现**\n- RAII 管理资源（保证不泄漏）\n- 维护不变式（对象始终有效）\n- 析构函数、move 操作应 noexcept\n\n**强保证实现**\n- copy-and-swap 惯用法\n- 先在副本上操作，成功后再交换\n- 失败时不影响原对象\n\n**copy-and-swap**\n```cpp\nT& operator=(T other) noexcept {  // 值传递，自带拷贝\n    swap(other);  // 交换\n    return *this;  // other 析构释放旧资源\n}\n```\n- other 拷贝构造时可能抛异常（此时原对象未变）\n- swap 应 noexcept\n- 析构应 noexcept\n\n**noexcept**\n- C++11 关键字，声明函数不抛异常\n- noexcept(true/false) 可条件化\n- noexcept 函数若抛异常会调用 terminate\n- move 操作标记 noexcept 后，vector 扩容时用 move 而非 copy\n- 析构函数默认 noexcept（C++11）\n\n**异常安全与 STL**\n- vector 扩容：若元素 move 是 noexcept，则 move 扩容；否则 copy 扩容（强保证）\n- 因此 move 构造/赋值应标记 noexcept 以获得性能\n- is_nothrow_move_constructible 检测\n\n**异常处理原则**\n- 不要在析构函数中抛异常（栈展开时 terminate）\n- 构造函数可抛异常（但需保证已获取资源被释放）\n- 异常传播路径上的对象靠 RAII 析构清理\n\n**事务编程**\n- 多步操作要保证强安全需整体回滚\n- 复杂场景记录操作日志，失败时逆向回滚\n- 或先操作副本最后提交",
    example: "#include <vector>\n#include <memory>\n#include <utility>\n\n// copy-and-swap 实现强保证\nclass String {\n    char* data_;\n    size_t size_;\npublic:\n    String(const char* s = \"\") : size_(strlen(s)) {\n        data_ = new char[size_ + 1];  // 可能抛 bad_alloc\n        strcpy(data_, s);\n    }\n    ~String() noexcept { delete[] data_; }\n\n    String(const String& o) : size_(o.size_) {\n        data_ = new char[size_ + 1];\n        strcpy(data_, o.data_);\n    }\n\n    // move noexcept\n    String(String&& o) noexcept\n        : data_(o.data_), size_(o.size_) {\n        o.data_ = nullptr; o.size_ = 0;\n    }\n\n    friend void swap(String& a, String& b) noexcept {\n        using std::swap;\n        swap(a.data_, b.data_);\n        swap(a.size_, b.size_);\n    }\n\n    // copy-and-swap：值传递 + swap\n    String& operator=(String other) noexcept {\n        swap(*this, other);  // noexcept\n        return *this;  // other 析构释放旧数据\n    }\n};\n\n// noexcept 使 vector 用 move 扩容\nclass Buffer {\n    int* data_;\n    size_t n_;\npublic:\n    Buffer(size_t n) : data_(new int[n]), n_(n) {}\n    ~Buffer() noexcept { delete[] data_; }\n\n    // noexcept move：vector 扩容会用 move（快）\n    Buffer(Buffer&& o) noexcept\n        : data_(o.data_), n_(o.n_) {\n        o.data_ = nullptr; o.n_ = 0;\n    }\n\n    Buffer& operator=(Buffer&& o) noexcept {\n        if (this != &o) {\n            delete[] data_;\n            data_ = o.data_; n_ = o.n_;\n            o.data_ = nullptr; o.n_ = 0;\n        }\n        return *this;\n    }\n};\n\n// 没有 noexcept move 时 vector 用 copy 扩容（慢但强安全）\n// 有 noexcept move 时用 move 扩容（快）\n\n// 条件 noexcept\ntemplate<class T>\nvoid destroy(T* p) noexcept(std::is_nothrow_destructible_v<T>) {\n    p->~T();\n}\n\n// 异常安全的多步操作：copy-and-swap\ntemplate<class T>\nvoid strong_assign(std::vector<T>& v, const std::vector<T>& new_data) {\n    std::vector<T> tmp(new_data);  // 副本，可能抛异常但不影响 v\n    tmp.swap(v);  // noexcept swap，原子提交\n}  // 旧 v 数据随 tmp 析构"
  },
  {
    id: "cpp-object-layout",
    title: "C++ 对象内存布局",
    level: "高级",
    content: "**空类大小**\n- 空类 sizeof = 1（确保不同对象地址不同）\n- 空基类优化（EBO）：作为基类时不占空间\n\n**成员布局**\n- 成员按声明顺序排列\n- 可能有 padding 对齐\n- 与 C 结构体规则一致\n\n**有虚函数的类**\n- 对象首部有虚函数表指针（vptr，8字节@64位）\n- 每个对象多 8 字节开销\n- vptr 指向类的 vtable\n\n**虚继承**\n- 虚基类指针（vbptr）或 vtable 中记录偏移\n- 解决菱形继承的重复数据\n- 增加额外指针/偏移开销\n\n**多重继承布局**\n- 多个基类按声明顺序排列\n- 每个有虚函数的基类一个 vptr\n- 对象地址转型时可能需要调整指针\n\n**静态成员**\n- 不在对象内，存在全局数据段\n- sizeof 不含静态成员\n\n**对齐**\n- alignas(N) 指定对齐\n- alignof(T) 查询对齐\n- 最大对齐成员决定类对齐\n\n**位域**\n- 紧凑存储，节省空间\n- 不能取地址\n- 内存布局实现相关\n\n**指针调整**\n- 多继承下 static_cast 子对象地址可能偏移\n- Base* 指向派生类时可能不等于 Derived*\n- dynamic_cast 处理向下转型\n\n**空基类优化 EBO**\n- 空基类不占对象空间\n- 常用于策略模式/编译期多态\n- `struct Derived : EmptyPolicy { int x; };` sizeof = 4\n\n**查看布局工具**\n- clang: clang -Xclang -fdump-record-layouts\n- g++: g++ -fdump-lang-class\n- MSVC: /d1reportSingleClassLayout",
    example: "#include <iostream>\n\n// 空类\nstruct Empty {};\nstd::cout << sizeof(Empty) << std::endl;  // 1\n\n// 空基类优化\nstruct EBO : Empty { int x; };\nstd::cout << sizeof(EBO) << std::endl;  // 4（Empty 不占空间）\n\n// 普通类\nstruct A { char a; int b; };\n// sizeof = 8 (a + 3 padding + b)\n\n// 有虚函数\nclass V {\n    int x;\npublic:\n    virtual void f() {}\n};\n// 64位: sizeof = 16 (vptr 8 + x 4 + padding 4)\n\n// 多继承\nclass B1 { int x; public: virtual void f1() {} };\nclass B2 { int y; public: virtual void f2() {} };\nclass D : public B1, public B2 {};\n// sizeof = 32 (B1: vptr+x=16, B2: vptr+y=16)\n// D 内有两个 vptr\n\n// 虚继承（菱形）\nclass Base { int a; };\nclass Left : virtual public Base { int b; };\nclass Right : virtual public Base { int c; };\nclass Diamond : public Left, public Right { int d; };\n// Base 只存一份，但增加虚基类指针开销\n\n// static 不占对象空间\nclass WithStatic {\n    int x;\n    static int s;  // 不算入 sizeof\n};\n// sizeof = 4\n\n// 对齐控制\nstruct alignas(16) Aligned { int x; };\n// sizeof = 16, alignof = 16\n\n// 指针调整（多继承）\nclass Base1 { public: virtual ~Base1(){} int a; };\nclass Base2 { public: virtual ~Base2(){} int b; };\nclass Derived : public Base1, public Base2 { int c; };\n\nDerived* d = new Derived;\nBase1* b1 = d;  // 地址相同\nBase2* b2 = d;  // 地址可能偏移（指向第二个基类子对象）\n// b1 == d 但 b2 != d（reinterpret_cast 不同）\n\n// 查看 clang 布局：\n// clang++ -Xclang -fdump-record-layouts file.cpp"
  },
  {
    id: "cpp-lambda-internals",
    title: "函数对象与 lambda 底层",
    level: "高级",
    content: "**函数对象（Functor）**\n- 重载 operator() 的类\n- 可有状态（成员变量）\n- 可内联，比函数指针高效\n- STL 大量使用：比较器、谓词\n\n**lambda 表达式**\n- 编译期生成匿名函数对象（闭包类型）\n- 每个 lambda 有唯一类型\n- auto 推导闭包类型\n\n**捕获机制**\n- `[]` 不捕获\n- `[=]` 值捕获所有用到的变量（拷贝）\n- `[&]` 引用捕获所有用到的变量\n- `[x]` 值捕获 x\n- `[&x]` 引用捕获 x\n- `[=, &x]` 默认值捕获，x 引用捕获\n- `[this]` 捕获 this 指针\n- `[*this]` C++17 值捕获 *this\n\n**lambda 与闭包类**\n- `[=]` 生成的类有值成员，operator() 是 const\n- `[&]` 生成的类有引用成员\n- `mutable` 关键字使 operator() 非 const，可修改值捕获的副本\n\n**泛型 lambda（C++14）**\n- `auto` 参数\n- 相当于模板 operator()\n\n**模板 lambda（C++20）**\n- `[]<class T>(T x){}` 显式模板参数\n\n**无捕获 lambda 可转函数指针**\n- 无捕获 lambda 可隐式转为函数指针\n- 有捕获则不行\n\n**std::function**\n- 类型擦除的函数包装器\n- 可存储任意可调用对象\n- 有运行时开销（堆分配、虚调用）\n\n**std::bind**\n- 绑定参数生成可调用对象\n- 现代代码优先用 lambda\n\n**lambda 性能**\n- lambda 生成的闭包类可被编译器内联\n- 比 std::function 快（无类型擦除）\n- 传参优先模板 auto 而非 std::function\n\n**递归 lambda**\n- lambda 无法直接递归（类型未知）\n- 用 std::function 包装\n- 或用 C++14 泛型 lambda + 显式传自身",
    example: "#include <functional>\n#include <algorithm>\n#include <vector>\n#include <iostream>\n\n// 函数对象\ntemplate<class T>\nstruct Sum {\n    T total = 0;\n    void operator()(T x) { total += x; }  // 有状态\n};\n\n// lambda 本质是闭包类\nint x = 10;\nauto f = [x](int y) { return x + y; };\n// 等价于：\nstruct __lambda {\n    int x;\n    int operator()(int y) const { return x + y; }\n};\n__lambda f = {x};\n\n// 捕获方式\nint a = 1, b = 2, c = 3;\nauto by_val = [=]() { return a + b + c; };      // 值捕获副本\nauto by_ref = [&]() { a++; b++; c++; };          // 引用捕获\nauto mixed = [=, &c]() { return a + b + c++; };  // 混合\n\n// mutable：可修改值捕获的副本\nint counter = 0;\nauto inc = [counter]() mutable { return ++counter; };\nstd::cout << inc() << std::endl;  // 1\nstd::cout << inc() << std::endl;  // 2\nstd::cout << counter << std::endl; // 0（原变量不变）\n\n// 泛型 lambda（C++14）\nauto add = [](auto a, auto b) { return a + b; };\nadd(1, 2);      // int\nadd(1.5, 2.5);  // double\n\n// 模板 lambda（C++20）\nauto twice = []<class T>(T x) { return x * 2; };\n\n// STL 算法配合 lambda\nstd::vector<int> v = {3, 1, 4, 1, 5};\nstd::sort(v.begin(), v.end(), [](int a, int b) {\n    return a > b;  // 降序\n});\nint sum = 0;\nstd::for_each(v.begin(), v.end(), [&sum](int x) { sum += x; });\n\n// 无捕获 lambda 转函数指针\nusing Cmp = int(*)(int, int);\nCmp cmp = [](int a, int b) { return a - b; };  // 可转换\n\n// std::function（有开销）\nstd::function<int(int,int)> op = [](int a, int b) { return a + b; };\n\n// 递归 lambda（用 std::function）\nstd::function<int(int)> fib = [&](int n) -> int {\n    return n < 2 ? n : fib(n-1) + fib(n-2);\n};\n\n// 递归 lambda（泛型，无 std::function）\nauto fib2 = [](auto& self, int n) -> int {\n    return n < 2 ? n : self(self, n-1) + self(self, n-2);\n};\nfib2(fib2, 10);\n\n// 性能：模板 auto 优于 std::function\ntemplate<class F>\nvoid apply(F&& f) { f(42); }  // 可内联，零开销\n// void apply(std::function<void(int)> f) { f(42); }  // 有开销"
  }
],
cpp_ext2_questions: [
  {q:"C++ 编译的四个阶段正确顺序是？", level:"进阶", options:["编译→预处理→汇编→链接","预处理→编译→汇编→链接","预处理→汇编→编译→链接","编译→汇编→预处理→链接"], answer:1, explain:"四阶段：预处理（展开宏/头文件）→编译（生成汇编）→汇编（生成目标文件）→链接（合并目标文件和库）。"},
  {q:"undefined reference 错误发生在哪个阶段？", level:"进阶", options:["预处理","编译","汇编","链接"], answer:3, explain:"undefined reference 是符号未定义，发生在链接阶段。通常因未实现函数、未链接库、库顺序错误导致。"},
  {q:"ODR（One Definition Rule）规定？", level:"高级", options:["每个函数只能调用一次","每个实体在整个程序中只能有一个定义","头文件只能包含一次","变量只能定义一次"], answer:1, explain:"ODR 要求每个实体（函数/变量/类）在整个程序中只能有一个定义，但 inline/模板/constexpr 可多次定义（必须一致）。"},
  {q:"#pragma once 的作用是？", level:"基础", options:["只编译一次","防止头文件被重复包含","优化代码","只运行一次"], answer:1, explain:"#pragma once 告诉编译器当前文件只包含一次，等效于 include guard，更简洁但非标准（被主流编译器支持）。"},
  {q:"RAII 的核心思想是？", level:"进阶", options:["运行时分配内存","将资源绑定到对象生命周期，构造获取析构释放","引用计数","垃圾回收"], answer:1, explain:"RAII 利用对象生命周期管理资源：构造函数获取资源，析构函数自动释放，借助栈对象确定性销毁和异常安全保证资源不泄漏。"},
  {q:"RAII 保证异常安全的关键是？", level:"高级", options:["异常处理快","栈展开时已构造的局部对象会被析构","try-catch","noexcept"], answer:1, explain:"抛异常时栈展开会析构所有已构造的局部对象，RAII 对象的析构函数释放资源，因此即使异常也能保证资源不泄漏。"},
  {q:"Rule of Five 指？", level:"高级", options:["五个设计原则","需要定义析构、拷贝构造、拷贝赋值、移动构造、移动赋值五个","五个虚函数","五层继承"], answer:1, explain:"Rule of Five：涉及资源管理的类通常需要定义析构函数、拷贝构造、拷贝赋值、移动构造、移动赋值五个特殊成员函数。"},
  {q:"Rule of Zero 建议的是？", level:"高级", options:["不写任何函数","优先用标准 RAII 类型管理资源，类无需自定义特殊成员函数","不用类","零个成员"], answer:1, explain:"Rule of Zero：优先用 vector/string/智能指针等标准 RAII 类型，类本身不需要定义析构/拷贝/移动，让编译器生成默认实现。"},
  {q:"unique_ptr 和 shared_ptr 的核心区别是？", level:"进阶", options:["性能不同","unique_ptr 独占所有权不可拷贝，shared_ptr 共享所有权引用计数","内存位置不同","接口不同"], answer:1, explain:"unique_ptr 独占资源不可拷贝（可移动），零开销；shared_ptr 共享资源通过引用计数管理，可拷贝但有原子操作开销。"},
  {q:"shared_ptr 循环引用会导致？", level:"高级", options:["编译错误","内存泄漏（引用计数永不归零）","段错误","死锁"], answer:1, explain:"两个 shared_ptr 互相引用，引用计数各为1永远不归零，析构不触发，导致内存泄漏。用 weak_ptr 打破循环。"},
  {q:"weak_ptr 的主要用途是？", level:"高级", options:["加速访问","打破 shared_ptr 循环引用、观察者模式、缓存","独占所有权","替代裸指针"], answer:1, explain:"weak_ptr 不增加强引用计数，不影响对象释放，用于打破循环引用、实现观察者（观察对象是否存活）和缓存。"},
  {q:"enable_shared_from_this 的 shared_from_this() 用于？", level:"高级", options:["创建自身副本","安全获取指向自身的 shared_ptr","判断是否被管理","克隆"], answer:1, explain:"shared_from_this() 返回与现有管理一致的 shared_ptr，避免用 this 构造 shared_ptr 产生多个控制块导致双重释放。"},
  {q:"make_shared 相比 shared_ptr(new T) 的优势是？", level:"高级", options:["更快","一次分配（对象+控制块），减少内存碎片和分配次数","更安全","功能更多"], answer:1, explain:"make_shared 一次分配对象和控制块，shared_ptr(new T) 分两次。make_shared 性能更好但 weak_ptr 会延迟对象内存释放。"},
  {q:"vector push_back 导致迭代器失效的原因是？", level:"高级", options:["内存重新分配","元素移动","容量变化","以上都是"], answer:3, explain:"push_back 可能触发扩容，内存重新分配后所有迭代器/指针/引用失效。reserve 预分配可避免扩容导致的失效。"},
  {q:"list 删除元素后其他迭代器？", level:"高级", options:["全部失效","仅被删除元素的迭代器失效","不影响","不确定"], answer:1, explain:"list 是链表，节点独立，删除某节点只使该节点的迭代器失效，其他迭代器仍有效（这是链表相对数组的优势）。"},
  {q:"erase-remove 惯用法删除 vector 中满足条件的元素正确写法是？", level:"高级", options:["v.erase(remove_if(...))","v.erase(remove_if(begin,end,pred), end)","v.remove_if(pred)","v.delete(pred)"], answer:1, explain:"v.erase(std::remove_if(v.begin(), v.end(), pred), v.end())。remove_if 将不删除元素前移，erase 删除尾部多余元素。C++20 可用 std::erase_if。"},
  {q:"map 边遍历边删除的正确方式是？", level:"高级", options:["m.erase(it++)","it = m.erase(it)（C++11）","直接 erase","先收集再删"], answer:1, explain:"C++11 起 erase 返回下一个迭代器：it = m.erase(it);。旧式 m.erase(it++) 在 C++03 用，但新标准推荐返回值方式。"},
  {q:"SFINAE 的含义是？", level:"高级", options:["替换失败导致错误","替换失败不是错误，从重载集中移除","模板失败报错","实例化失败"], answer:1, explain:"SFINAE（Substitution Failure Is Not An Error）：模板替换时某些失败不报错，只是将该重载从候选集中移除，用于编译期条件选择。"},
  {q:"C++17 替代 SFINAE 的更简洁方案是？", level:"高级", options:["if constexpr","static_assert","constexpr if","concept"], answer:0, explain:"if constexpr 在编译期分支，不满足的分支不实例化，比 SFINAE 更直观易读，替代了许多 enable_if 场景。"},
  {q:"C++20 替代 SFINAE 的现代方案是？", level:"高级", options:["Concepts（requires）","if constexpr","static_assert","macro"], answer:0, explain:"Concepts 用 requires 表达式约束模板参数，语法清晰、错误信息友好，是替代 SFINAE 的现代标准方案。"},
  {q:"异常安全的强保证（Strong guarantee）指？", level:"高级", options:["不泄漏资源","操作要么完全成功要么回滚到调用前状态","不抛异常","基本可用"], answer:1, explain:"强保证是事务语义：操作失败时对象状态回滚到操作前，如同从未调用。通常用 copy-and-swap 实现。"},
  {q:"copy-and-swap 惯用法实现强保证的关键是？", level:"高级", options:["值传递参数（自带拷贝），再 noexcept swap","用 try-catch","用 noexcept","深拷贝"], answer:0, explain:"operator=(T other) 值传递触发拷贝（可能抛异常但不影响原对象），拷贝成功后 noexcept swap 交换，实现原子提交的强保证。"},
  {q:"move 操作标记 noexcept 的性能意义是？", level:"高级", options:["更快","vector 扩容时用 move 而非 copy，性能大幅提升","线程安全","省内存"], answer:1, explain:"vector 扩容时若元素 move 是 noexcept，则 move 扩容（快）；否则为强保证用 copy 扩容（慢）。因此 move 操作应标记 noexcept。"},
  {q:"析构函数为什么应该 noexcept？", level:"高级", options:["性能","栈展开时抛异常会 terminate，析构必须可靠","线程安全","内存安全"], answer:1, explain:"异常栈展开时会调用析构函数，若析构再抛异常会导致 terminate。C++11 起析构函数默认 noexcept。"},
  {q:"空类的 sizeof 通常是？", level:"进阶", options:["0","1","4","8"], answer:1, explain:"空类 sizeof 为1，确保不同对象地址不同。但作为空基类时触发 EBO 不占空间。"},
  {q:"有虚函数的类每个对象额外的开销是？", level:"高级", options:["无","虚函数表指针 vptr（64位8字节）","函数指针数组","虚函数表"], answer:1, explain:"有虚函数的类每个对象首部有 vptr 指向虚函数表，64位系统占8字节。vtable 本身是类共享的，不占对象空间。"},
  {q:"空基类优化（EBO）的好处是？", level:"高级", options:["加速","空基类不占派生类空间，常用于策略模式","节省内存","线程安全"], answer:1, explain:"EBO 使空基类在派生类中不占空间，常用于策略模式/编译期多态，如 struct Derived : EmptyPolicy { int x; } sizeof=4。"},
  {q:"lambda 表达式的本质是？", level:"高级", options:["函数指针","编译期生成的匿名闭包类（函数对象）","宏展开","内联函数"], answer:1, explain:"lambda 编译期生成唯一的闭包类，捕获的变量成为成员，operator() 执行函数体。每个 lambda 有唯一类型。"},
  {q:"[=] 捕获方式是？", level:"进阶", options:["引用捕获所有变量","值捕获所有用到的变量（拷贝副本）","捕获 this","不捕获"], answer:1, explain:"[=] 值捕获所有用到的外部变量（拷贝副本），[&] 引用捕获。operator() 默认 const，值捕获的副本不可修改（除非 mutable）。"},
  {q:"lambda 的 mutable 关键字作用是？", level:"高级", options:["可变参数","使 operator() 非 const，可修改值捕获的副本","线程安全","性能优化"], answer:1, explain:"默认 lambda 的 operator() 是 const，不能修改值捕获的副本。mutable 使其非 const，可修改副本（但不影响原变量）。"},
  {q:"无捕获 lambda 的特殊能力是？", level:"高级", options:["更快","可隐式转换为函数指针","可递归","可内联"], answer:1, explain:"无捕获 lambda 没有状态，可隐式转换为对应类型的函数指针，可与 C API 交互。有捕获则不行。"},
  {q:"std::function 相比模板 auto 的缺点是？", level:"高级", options:["不能存储 lambda","有运行时开销（类型擦除、可能的堆分配、虚调用）","不安全","类型不安全"], answer:1, explain:"std::function 用类型擦除存储任意可调用对象，有运行时开销（堆分配、间接调用）。模板 auto 在编译期确定类型可内联，零开销。"}
]
