// === PYTHON EXT2 ===
python_ext2_topics: [
  {
    id: "py-gil",
    title: "GIL 与并发模型深度解析",
    level: "高级",
    content: "**GIL（全局解释器锁）是什么**\n- CPython 解释器中的一把互斥锁\n- 同一时刻只允许一个线程执行 Python 字节码\n- 目的：保护 CPython 内部数据结构（如引用计数）不被并发破坏\n- GIL 是 CPython 实现细节，Jython/IronPython 没有 GIL，PyPy 也有 GIL\n\n**GIL 的释放时机**\n- IO 操作（文件/网络/socket）会主动释放 GIL\n- time.sleep() 释放 GIL\n- 每执行一定数量的字节码指令（sys.getswitchinterval，默认5ms）检查是否释放\n- C 扩展中可手动 Py_BEGIN_ALLOW_THREADS / Py_END_ALLOW_THREADS 释放\n\n**GIL 对性能的影响**\n- CPU 密集型多线程无法利用多核，甚至比单线程更慢（线程切换开销）\n- IO 密集型多线程有效（IO 等待时释放 GIL 让其他线程运行）\n- multiprocessing 绕过 GIL（每个进程独立解释器独立 GIL）\n- C 扩展（如 numpy）在计算时释放 GIL，可多线程加速\n\n**GIL 竞争与线程调度**\n- 多个 CPU 密集线程会激烈竞争 GIL，导致频繁上下文切换\n- 可用 sys.setswitchinterval() 调整检查间隔\n- GIL 的释放是协作式 + 抢占式混合\n\n**PEP 703：移除 GIL 的提案**\n- Python 3.13 引入实验性 free-threaded 模式（--disable-gil）\n- 基于 PEP 689 的修改，引用计数改为原子操作\n- 移除 GIL 后单线程性能略有下降（约5-10%），但多线程可真正并行\n- 未来版本可能默认无 GIL\n\n**为什么不去掉 GIL**\n- 历史包袱：大量 C 扩展依赖 GIL 保证线程安全\n- 单线程性能：带 GIL 的引用计数比原子引用计数快\n- 工程难度：需要重新设计内存管理",
    example: "import sys, threading, time\n\n# 演示 GIL 对 CPU 密集任务的影响\ndef cpu_work(n):\n    s = 0\n    for i in range(n):\n        s += i * i\n    return s\n\n# 单线程\nstart = time.time()\ncpu_work(10**7); cpu_work(10**7)\nprint('单线程:', time.time() - start)\n\n# 多线程（因 GIL 不会更快，可能更慢）\nstart = time.time()\nt1 = threading.Thread(target=cpu_work, args=(10**7,))\nt2 = threading.Thread(target=cpu_work, args=(10**7,))\nt1.start(); t2.start(); t1.join(); t2.join()\nprint('多线程:', time.time() - start)\n\n# 用 multiprocessing 真正并行\nfrom multiprocessing import Pool\nstart = time.time()\nwith Pool(2) as p:\n    p.map(cpu_work, [10**7, 10**7])\nprint('多进程:', time.time() - start)\n\n# IO 密集型多线程有效（GIL 在 IO 时释放）\ndef io_work(url):\n    import urllib.request\n    return urllib.request.urlopen(url).read()\n\n# 查看线程切换间隔\nprint('切换间隔:', sys.getswitchinterval())  # 0.005\nsys.setswitchinterval(0.01)  # 调大减少切换开销"
  },
  {
    id: "py-gc",
    title: "内存管理与垃圾回收",
    level: "高级",
    content: "**Python 内存模型**\n- 一切皆对象，对象在堆上分配\n- 不可变对象：int/float/str/tuple，小整数缓存（-5~256）\n- 可变对象：list/dict/set\n- 引用计数：每个对象有 ob_refcnt 字段记录被引用次数\n\n**引用计数（Reference Counting）**\n- 主回收机制，实时进行\n- 引用 +1：赋值、传参、加入容器\n- 引用 -1：变量离开作用域、del、容器移除\n- ob_refcnt 归零时立即回收对象\n- 优点：即时、可预测\n- 缺点：无法处理循环引用，维护计数有开销\n\n**分代垃圾回收（Generational GC）**\n- 解决循环引用问题\n- 三代：第0代（年轻）、第1代、第2代（年老）\n- 新对象在第0代，存活过 GC 晋升到老代\n- 老代 GC 频率低（对象稳定）\n- gc.collect() 手动触发\n- gc.get_threshold() 默认 (700, 10, 10)\n\n**循环引用示例**\n- a.ref = b, b.ref = a，两者引用计数都不为零但已无用\n- 分代 GC 通过遍历容器对象检测循环引用组\n- 弱引用（weakref）不增加引用计数，可打破循环\n\n**__del__ 与 GC**\n- 有 __del__ 的对象在循环引用时 GC 无法安全回收（3.4 前）\n- PEP 442 修复：3.4+ 可正确回收带 __del__ 的循环引用\n\n**内存优化**\n- __slots__：固定属性集，省去 __dict__，节省内存\n- 生成器：惰性求值不一次性占用内存\n- intern：字符串驻留，相同字符串共享对象\n- 大数据用 numpy array 而非 list\n\n**内存查看工具**\n- sys.getsizeof(obj)：对象直接大小\n- tracemalloc：追踪内存分配\n- objgraph：可视化对象引用关系\n- memory_profiler：逐行内存",
    example: "import sys, gc, weakref\n\n# 引用计数演示\na = [1, 2, 3]\nprint(sys.getrefcount(a))  # 2 (a 和 getrefcount 参数)\nb = a\nprint(sys.getrefcount(a))  # 3\ndel b\nprint(sys.getrefcount(a))  # 2\n\n# 循环引用\nclass Node:\n    def __init__(self):\n        self.ref = None\n    def __del__(self):\n        print('Node deleted')\n\nn1 = Node(); n2 = Node()\nn1.ref = n2; n2.ref = n1\ndel n1; del n2  # 引用计数不为0，等待 GC\nprint('手动 GC 回收循环引用:')\nuncollectable = gc.collect()\nprint('回收:', uncollectable)\n\n# 弱引用打破循环\nclass Cache:\n    def __init__(self):\n        self._data = {}\n    def get(self, key, factory):\n        obj = self._data.get(key)\n        if obj is None or obj() is None:\n            obj = factory()\n            self._data[key] = weakref.ref(obj)\n        return obj\n\n# __slots__ 节省内存\nclass Point:\n    __slots__ = ('x', 'y')\n    def __init__(self, x, y):\n        self.x = x; self.y = y\n# Point 实例无 __dict__，更省内存\np = Point(1, 2)\nprint(sys.getsizeof(p))  # 比普通对象小\n\n# tracemalloc 追踪内存\nimport tracemalloc\ntracemalloc.start()\n# ... 你的代码 ...\nsnapshot = tracemalloc.take_snapshot()\nfor stat in snapshot.statistics('lineno')[:5]:\n    print(stat)\n\n# GC 阈值\ngc.set_threshold(1000, 15, 15)\n# 临时禁用 GC（性能敏感场景）\ngc.disable()\n# gc.enable()"
  },
  {
    id: "py-context-manager",
    title: "上下文管理器与 with 语句原理",
    level: "进阶",
    content: "**with 语句作用**\n- 确保资源（文件/锁/连接）被正确释放\n- 即使发生异常也会执行清理代码\n- 替代 try-finally 的优雅写法\n\n**上下文管理器协议**\n- __enter__(self)：进入时调用，返回值赋给 as 变量\n- __exit__(self, exc_type, exc_val, exc_tb)：退出时调用\n- __exit__ 返回 True 则抑制异常，返回 None/False 则向上抛\n\n**实现方式一：类实现协议**\n- 定义 __enter__ 和 __exit__\n- 适合复杂场景\n\n**实现方式二：contextlib.contextmanager 装饰器**\n- 用生成器函数简化\n- yield 之前为 __enter__，yield 值为 as 变量，yield 之后为 __exit__\n- 异常会在 yield 处重新抛出\n\n**contextlib 常用工具**\n- contextmanager：生成器转上下文管理器\n- suppress(*exceptions)：忽略指定异常\n- redirect_stdout/redirect_stderr：重定向标准流\n- closing(thing)：调用 thing.close()\n- ExitStack：动态管理多个上下文\n- asynccontextmanager：异步版本\n\n**嵌套与 ExitStack**\n- 多个 with 嵌套可用 ExitStack 统一管理\n- 运行时动态决定进入哪些上下文\n- enter_context(cm) 注册，按 LIFO 顺序退出\n\n**常见应用**\n- open() 文件\n- threading.Lock\n- contextvars 上下文变量\n- 数据库连接/事务\n- 临时修改全局状态",
    example: "from contextlib import contextmanager, suppress, redirect_stdout, ExitStack\nimport io\nimport threading\n\n# 方式一：类实现\nclass DatabaseConnection:\n    def __init__(self, dsn):\n        self.dsn = dsn\n    def __enter__(self):\n        print(f'连接 {self.dsn}')\n        return self  # 赋给 as 变量\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        print(f'关闭连接，异常: {exc_type}')\n        # return True 会吞掉异常，通常不这么做\n        return False\n\nwith DatabaseConnection('mysql://localhost') as db:\n    print('使用 db')\n    # raise RuntimeError('test')  # __exit__ 仍会执行\n\n# 方式二：contextmanager 装饰器\n@contextmanager\ndef timer(label):\n    import time\n    start = time.time()\n    try:\n        yield  # as 变量为 None（或 yield 值）\n    finally:\n        print(f'{label}: {time.time()-start:.3f}s')\n\nwith timer('任务'):\n    sum(i for i in range(10**6))\n\n# suppress 忽略异常\nwith suppress(FileNotFoundError):\n    open('not_exist.txt')\nprint('继续执行，未崩溃')\n\n# redirect_stdout 捕获输出\nbuf = io.StringIO()\nwith redirect_stdout(buf):\n    print('这行不会显示，被捕获')\nprint('捕获到:', buf.getvalue())\n\n# ExitStack 管理多个文件\nfiles = ['a.txt', 'b.txt', 'c.txt']\nwith ExitStack() as stack:\n    handles = [stack.enter_context(open(f)) for f in files]\n    for h in handles:\n        print(h.read())\n\n# 异步上下文管理器\nimport asyncio\nclass AsyncResource:\n    async def __aenter__(self):\n        print('获取')\n        return self\n    async def __aexit__(self, *exc):\n        print('释放')\n\nasync def main():\n    async with AsyncResource() as r:\n        print('使用')"
  },
  {
    id: "py-dataclass",
    title: "数据类 dataclass 与类型注解",
    level: "进阶",
    content: "**dataclass（Python 3.7+）**\n- @dataclass 装饰器自动生成 __init__/__repr__/__eq__\n- 减少样板代码，替代手写 __init__\n- 基于类型注解声明字段\n\n**字段配置**\n- default：默认值\n- default_factory：可变默认值（避免共享陷阱）\n- field(default=, default_factory=, init=, repr=, compare=, hash=)\n- init=False：不作为构造参数\n- repr=False：不参与 __repr__\n\n**常用参数**\n- @dataclass(frozen=True)：不可变（可哈希，可作 dict key）\n- @dataclass(slots=True)：3.10+ 自动生成 __slots__\n- @dataclass(order=True)：生成 __lt__/__le__ 等比较方法\n- @dataclass(eq=True, frozen=True) 可哈希\n\n**继承**\n- 子类可扩展字段\n- 父类有默认值时子类字段也必须有默认值\n\n**类型注解（Type Hints）**\n- int / str / float / bool\n- List[int] / Dict[str, int] / Tuple[int, ...]（typing 模块）\n- 3.9+ 可直接 list[int] / dict[str, int]\n- Optional[int] = int | None（3.10+ 用 |）\n- Union[int, str] = int | str\n- Callable[[int], str]：可调用类型\n- TypeVar / Generic：泛型\n- TypedDict：带类型的 dict\n- Literal['a', 'b']：字面量类型\n\n**mypy 静态类型检查**\n- pip install mypy\n- mypy script.py 检查类型错误\n- 渐进式类型：不注解的部分不检查\n\n**Pydantic（运行时数据校验）**\n- 基于类型注解自动校验数据\n- BaseModel 基类\n- 错误时抛 ValidationError\n- FastAPI 核心依赖",
    example: "from dataclasses import dataclass, field\nfrom typing import Optional, List\n\n@dataclass\nclass User:\n    name: str\n    age: int = 0\n    tags: list = field(default_factory=list)  # 可变默认值\n    password: str = field(default='', repr=False)  # 不显示\n\nu = User('Alice', 25, ['a', 'b'])\nprint(u)  # User(name='Alice', age=25, tags=['a', 'b'])\n\n# frozen 不可变\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int\np = Point(1, 2)\n# p.x = 3  # FrozenInstanceError\nprint(hash(p))  # 可哈希\n\n# order 排序\n@dataclass(order=True)\nclass Priority:\n    level: int\nsorted([Priority(3), Priority(1), Priority(2)])\n\n# slots（3.10+）\n@dataclass(slots=True)\nclass Config:\n    host: str\n    port: int\n# Config 实例无 __dict__，节省内存且禁止额外属性\n\n# Pydantic 校验\nfrom pydantic import BaseModel, validator\n\nclass Article(BaseModel):\n    title: str\n    views: int = 0\n    tags: list[str] = []\n\n    @validator('title')\n    def title_not_empty(cls, v):\n        if not v.strip():\n            raise ValueError('标题不能为空')\n        return v\n\nart = Article(title='Hello', views=100, tags=['py'])\nprint(art.model_dump())  # 转字典\n# Article(title='', views='abc')  # ValidationError\n\n# 类型注解示例\nfrom typing import Callable, Optional\n\ndef greet(name: str, times: int = 1) -> str:\n    return f'Hello {name} ' * times\n\n# mypy 检查：greet(123) 会报错"
  },
  {
    id: "py-fastapi",
    title: "FastAPI 框架与 Pydantic",
    level: "进阶",
    content: "**FastAPI 特点**\n- 基于 Starlette（ASGI）+ Pydantic\n- 性能接近 NodeJS/Go\n- 原生支持 async/await\n- 自动生成 OpenAPI/Swagger 文档\n- 类型注解驱动的参数校验\n\n**路由与参数**\n- 路径参数：@app.get('/items/{item_id}')\n- 查询参数：函数参数自动识别为 query\n- 请求体：Pydantic BaseModel 参数\n- Header/Cookie/Form/File：从 fastapi 导入\n\n**依赖注入（Depends）**\n- 公共逻辑提取为依赖\n- 支持嵌套依赖\n- yield 依赖：yield 前为初始化，yield 后为清理\n- 常用于数据库会话、认证、权限\n\n**中间件**\n- @app.middleware('http')\n- CORS、日志、限流等\n- 请求前/响应后处理\n\n**后台任务**\n- BackgroundTasks：响应后执行\n- 适合发邮件、写日志等\n\n**异常处理**\n- HTTPException(status_code, detail)\n- 自定义异常处理器 @app.exception_handler\n\n**数据库集成**\n- SQLAlchemy 2.0 async\n- async sessionmaker\n- 依赖注入管理会话生命周期\n\n**测试**\n- TestClient（基于 httpx）\n- pytest + httpx.AsyncClient",
    example: "from fastapi import FastAPI, Depends, HTTPException, BackgroundTasks\nfrom pydantic import BaseModel\nfrom typing import Optional\nimport uvicorn\n\napp = FastAPI(title='My API', version='1.0')\n\n# Pydantic 模型\nclass Item(BaseModel):\n    name: str\n    price: float\n    tax: Optional[float] = None\n\n# 路径参数 + 查询参数\n@app.get('/items/{item_id}')\nasync def get_item(item_id: int, q: Optional[str] = None):\n    return {'item_id': item_id, 'q': q}\n\n# 请求体\n@app.post('/items/')\nasync def create_item(item: Item):\n    return item\n\n# 依赖注入：数据库会话\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n\n@app.get('/users/')\nasync def list_users(db = Depends(get_db)):\n    return db.query(User).all()\n\n# 认证依赖\nasync def get_current_user(token: str = Depends(oauth2_scheme)):\n    user = verify_token(token)\n    if not user:\n        raise HTTPException(status_code=401, detail='Invalid token')\n    return user\n\n@app.get('/me')\nasync def me(user = Depends(get_current_user)):\n    return user\n\n# 后台任务\ndef send_email(to: str, content: str):\n    # 发邮件逻辑\n    pass\n\n@app.post('/notify/{email}')\nasync def notify(email: str, bg: BackgroundTasks):\n    bg.add_task(send_email, email, 'Hello')\n    return {'msg': 'notification queued'}\n\n# 中间件\n@app.middleware('http')\nasync def add_process_time(request, call_next):\n    import time\n    start = time.time()\n    response = await call_next(request)\n    response.headers['X-Process-Time'] = str(time.time() - start)\n    return response\n\n# 启动\n# uvicorn main:app --reload --host 0.0.0.0 --port 8000\n# 访问 /docs 查看 Swagger 文档"
  },
  {
    id: "py-functional",
    title: "函数式编程与 itertools",
    level: "进阶",
    content: "**函数式编程特性**\n- 函数是一等公民：可赋值、传参、返回\n- 纯函数：无副作用，相同输入相同输出\n- 不可变数据：优先用 tuple/frozen 而非 list/dict\n- 高阶函数：接收函数作为参数或返回函数\n\n**内置高阶函数**\n- map(func, *iterables)：对每个元素应用函数\n- filter(func, iterable)：过滤\n- functools.reduce(func, iterable)：累积\n- sorted(iterable, key=func)：排序\n- any()/all()：判断\n\n**lambda 表达式**\n- 匿名函数，单表达式\n- lambda args: expression\n- 适合简单回调，复杂逻辑用 def\n\n**偏函数 partial**\n- functools.partial(func, *args, **kwargs)\n- 固定部分参数生成新函数\n\n**itertools 核心工具**\n- chain(*iterables)：串联\n- chain.from_iterable(iterables)\n- islice(iterable, start, stop, step)：切片（惰性）\n- takewhile/dropwhile(func, iterable)：取/丢到条件不满足\n- groupby(iterable, key)：分组（需先排序）\n- starmap(func, iterable)：解包参数\n- zip_longest(*iterables, fillvalue)\n- product(*iterables)：笛卡尔积\n- permutations(iterable, r)：排列\n- combinations(iterable, r)：组合\n- count(start, step)/cycle(iterable)/repeat(elem, n)：无限迭代\n- accumulate(iterable, func)：累积\n\n**functools 其他**\n- lru_cache：LRU 缓存\n- wraps：保留元信息\n- total_ordering：自动补全比较方法\n- singledispatch：单分派泛型函数\n\n**生成器表达式**\n- (expr for x in iterable)\n- 惰性求值，节省内存\n- 只能迭代一次",
    example: "from itertools import *\nfrom functools import partial, reduce, lru_cache\nimport operator\n\n# map / filter / reduce\nnums = [1, 2, 3, 4, 5]\nsquared = list(map(lambda x: x**2, nums))\nevens = list(filter(lambda x: x % 2 == 0, nums))\nproduct = reduce(operator.mul, nums)  # 120\n\n# 生成器表达式（节省内存）\ntotal = sum(x**2 for x in range(10**6))  # 不创建列表\n\n# 偏函数\nint2 = partial(int, base=2)\nprint(int2('1010'))  # 10\n\n# chain 串联\nfor x in chain([1,2], [3,4], [5,6]):\n    print(x, end=' ')  # 1 2 3 4 5 6\n\n# groupby 分组（需先排序）\ndata = [('a', 1), ('a', 2), ('b', 3), ('a', 4)]\ndata.sort(key=lambda x: x[0])\nfor k, g in groupby(data, key=lambda x: x[0]):\n    print(k, list(g))\n\n# islice 惰性切片\nfor x in islice(count(1), 5):  # 1 2 3 4 5\n    print(x)\n\n# product 笛卡尔积\nfor a, b in product('AB', '12'):\n    print(a+b, end=' ')  # A1 A2 B1 B2\n\n# combinations / permutations\nprint(list(combinations('ABC', 2)))  # AB AC BC\nprint(list(permutations('ABC', 2)))   # AB AC BA BC CA CB\n\n# accumulate 累积\nprint(list(accumulate([1,2,3,4], operator.add)))  # 1 3 6 10\n\n# singledispatch 泛型函数\nfrom functools import singledispatch\n@singledispatch\ndef to_json(obj):\n    raise TypeError(f'unsupported {type(obj)}')\n@to_json.register(str)\ndef _(s): return f'\"{s}\"'\n@to_json.register(list)\ndef _(l): return '[' + ','.join(to_json(x) for x in l) + ']'\nprint(to_json(['a', 'b']))  # [\"a\",\"b\"]\n\n# lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)"
  },
  {
    id: "py-bytecode",
    title: "Python 内部机制：字节码与执行流程",
    level: "高级",
    content: "**Python 执行流程**\n1. 源码 (.py) → 词法分析 → Token\n2. Token → 语法分析 → AST（抽象语法树）\n3. AST → 编译 → 字节码 (.pyc)\n4. 字节码 → 虚拟机执行\n\n**字节码文件 .pyc**\n- 存放在 __pycache__ 目录\n- 文件名含 Python 版本和 magic number\n- 首次导入时编译生成，后续直接加载（加速）\n- 源码修改后自动重新编译\n\n**dis 模块：反汇编字节码**\n- dis.dis(func) 查看函数字节码\n- 帮助理解 Python 内部行为\n- 优化热点函数时可参考\n\n**帧对象（Frame）**\n- 每次函数调用创建一个 Frame\n- Frame 包含：代码对象、局部变量、全局变量、字节码指针、栈\n- 调用栈：Frame 的链表\n- sys._getframe() 获取当前帧\n\n**代码对象（Code Object）**\n- 函数的编译产物\n- 属性：co_code（字节码）、co_consts（常量）、co_names（全局名）、co_varnames（局部名）、co_argcount（参数数）\n- func.__code__ 访问\n\n**栈式虚拟机**\n- Python 是栈式虚拟机\n- 操作数压栈/出栈\n- 如 LOAD_FAST 加载局部变量到栈顶\n- BINARY_ADD 弹出两个操作数相加压回\n\n**常见的字节码指令**\n- LOAD_CONST / LOAD_FAST / LOAD_GLOBAL\n- STORE_FAST / STORE_GLOBAL\n- CALL_FUNCTION / RETURN_VALUE\n- BINARY_ADD / BINARY_MULTIPLY\n- POP_TOP / ROT_TWO\n- MAKE_FUNCTION\n\n**优化启示**\n- 局部变量访问比全局快（LOAD_FAST vs LOAD_GLOBAL）\n- 常量折叠：编译期计算常量表达式\n- 列表推导比 for 循环快（专用字节码）\n- 属性访问慢：涉及 __dict__ 查找",
    example: "import dis\nimport sys\n\n# 查看函数字节码\ndef add(a, b):\n    return a + b\n\nprint('=== add 字节码 ===')\ndis.dis(add)\n# LOAD_FAST 0 (a)\n# LOAD_FAST 1 (b)\n# BINARY_ADD\n# RETURN_VALUE\n\n# 列表推导 vs for 循环\ndef list_comp():\n    return [i*i for i in range(100)]\n\ndef for_loop():\n    result = []\n    for i in range(100):\n        result.append(i*i)\n    return result\n\nprint('=== 列表推导字节码（更紧凑）===')\ndis.dis(list_comp)\n\n# 代码对象\nprint('=== 代码对象属性 ===')\ncode = add.__code__\nprint('参数数:', code.co_argcount)\nprint('局部变量:', code.co_varnames)\nprint('常量:', code.co_consts)\nprint('字节码长度:', len(code.co_code))\n\n# 当前帧\nframe = sys._getframe()\nprint('当前函数:', frame.f_code.co_name)\nprint('当前行号:', frame.f_lineno)\nprint('局部变量:', frame.f_locals)\n\n# 常量折叠（编译期计算）\ndef folded():\n    return 2 * 3 + 4  # 编译为 LOAD_CONST 10\nprint('=== 常量折叠 ===')\ndis.dis(folded)  # 只有 LOAD_CONST 10; RETURN_VALUE\n\n# 局部 vs 全局性能对比\nimport timeit\nglobal_var = 100\ndef access_global():\n    return global_var  # 慢：LOAD_GLOBAL\ndef access_local():\n    local_var = 100\n    return local_var  # 快：LOAD_FAST\n\nprint('全局:', timeit.timeit(access_global, number=10**6))\nprint('局部:', timeit.timeit(access_local, number=10**6))"
  },
  {
    id: "py-metaprogramming",
    title: "元编程进阶：元类与描述符协议",
    level: "高级",
    content: "**元编程概述**\n- 编写能操作代码的代码\n- 动态修改/创建类和函数\n- Python 元编程手段：装饰器、元类、描述符、__init_subclass__、__class_getitem__\n\n**元类（Metaclass）**\n- 类的类，type 是默认元类\n- class Foo: 等价于 Foo = type('Foo', (), {})\n- 自定义元类继承 type\n- __new__：创建类（控制类创建）\n- __init__：初始化类\n- __call__：实例创建时调用（控制 __new__/__init__）\n\n**元类应用场景**\n- ORM：自动注册模型、生成字段\n- 插件系统：自动发现注册类\n- 单例模式\n- 接口/抽象类强制\n- 自动添加方法\n\n**__init_subclass__（3.6+）**\n- 替代元类的轻量方案\n- 父类定义后，子类创建时自动调用\n- cls 是子类\n- 适合简单的类层级控制\n\n**描述符协议**\n- __get__(self, obj, objtype=None)\n- __set__(self, obj, value)\n- __delete__(self, obj)\n- 数据描述符：同时定义 __get__ 和 __set__\n- 非数据描述符：只有 __get__\n- property 是描述符的简化形式\n\n**描述符查找优先级**\n1. 数据描述符\n2. 实例 __dict__\n3. 非数据描述符\n4. 类 __dict__\n\n**__class_getitem__**\n- 支持类参数化，如 List[int]\n- 3.9+ 用于原生泛型\n\n**import hooks**\n- sys.meta_path：自定义导入器\n- PEP 302/451 导入系统扩展",
    example: "# 元类：自动收集所有子类\nclass PluginMeta(type):\n    def __init__(cls, name, bases, namespace):\n        super().__init__(name, bases, namespace)\n        if not hasattr(cls, '_plugins'):\n            cls._plugins = []\n        else:\n            cls._plugins.append(cls)\n\nclass Plugin(metaclass=PluginMeta):\n    def run(self): pass\n\nclass AuthPlugin(Plugin):\n    def run(self): return 'auth'\n\nclass LogPlugin(Plugin):\n    def run(self): return 'log'\n\nprint([p.__name__ for p in Plugin._plugins])\n# ['AuthPlugin', 'LogPlugin']\n\n# __init_subclass__ 替代元类\nclass Base:\n    registry = []\n    def __init_subclass__(cls, **kwargs):\n        super().__init_subclass__(**kwargs)\n        Base.registry.append(cls)\n\nclass Child1(Base): pass\nclass Child2(Base): pass\nprint([c.__name__ for c in Base.registry])\n\n# 描述符：类型校验\nclass TypedField:\n    def __init__(self, type_):\n        self.type_ = type_\n    def __set_name__(self, owner, name):\n        self.name = name\n    def __get__(self, obj, objtype=None):\n        if obj is None:\n            return self\n        return obj.__dict__.get(self.name)\n    def __set__(self, obj, value):\n        if not isinstance(value, self.type_):\n            raise TypeError(f'{self.name} must be {self.type_.__name__}')\n        obj.__dict__[self.name] = value\n\nclass User:\n    name = TypedField(str)\n    age = TypedField(int)\n\nu = User()\nu.name = 'Alice'\nu.age = 25\n# u.age = 'old'  # TypeError: age must be int\n\n# 单例元类\nclass Singleton(type):\n    _instances = {}\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\nclass DB(metaclass=Singleton):\n    pass\nprint(DB() is DB())  # True\n\n# __class_getitem__\nclass Vector:\n    def __class_getitem__(cls, item):\n        return f'Vector[{item.__name__}]'\nprint(Vector[int])  # Vector[int]"
  }
],
python_ext2_questions: [
  {q:"Python GIL 的主要作用是？", level:"高级", options:["加密代码","保护解释器内部数据结构不被并发破坏","限制内存使用","加速执行"], answer:1, explain:"GIL 保护 CPython 引用计数等内部数据结构，同一时刻只允许一个线程执行字节码，避免并发访问导致数据损坏。"},
  {q:"以下哪种场景多线程能有效提升性能？", level:"高级", options:["CPU 密集型计算","纯数学运算","IO 密集型（网络/文件）","矩阵相乘"], answer:2, explain:"IO 操作会释放 GIL，因此 IO 密集型任务多线程有效；CPU 密集型受 GIL 限制应用多进程。"},
  {q:"绕过 GIL 利用多核的最佳方案是？", level:"高级", options:["增加线程数","用 multiprocessing 多进程","用 asyncio","调大 setswitchinterval"], answer:1, explain:"multiprocessing 每个进程有独立解释器和 GIL，可真正并行利用多核。"},
  {q:"Python 3.13 的 free-threaded 模式指的是？", level:"高级", options:["协程优化","实验性移除 GIL 支持真正的多线程并行","更快的 GC","无锁数据结构"], answer:1, explain:"PEP 703 在 Python 3.13 引入实验性无 GIL 模式（free-threaded），允许多线程真正并行执行字节码。"},
  {q:"Python 内存回收的主要机制是？", level:"高级", options:["标记清除","引用计数为主 + 分代 GC 处理循环引用","复制算法","只用 GC"], answer:1, explain:"CPython 以引用计数为主（实时回收），辅以分代垃圾回收处理引用计数无法解决的循环引用。"},
  {q:"小整数缓存的范围是？", level:"进阶", options:["-1~100","-5~256","0~256","任意整数"], answer:1, explain:"CPython 缓存 -5 到 256 的整数对象，这些整数全局共享，is 比较为 True。"},
  {q:"分代 GC 的作用是？", level:"高级", options:["加速对象创建","检测并回收循环引用","管理内存分配","优化字符串"], answer:1, explain:"引用计数无法处理循环引用（a 引用 b，b 引用 a），分代 GC 通过遍历容器对象检测循环引用组并回收。"},
  {q:"weakref 弱引用的作用是？", level:"高级", options:["加速访问","不增加引用计数，对象可被回收，用于缓存","加密引用","线程安全"], answer:1, explain:"weakref 不增加目标对象的引用计数，目标对象可被正常回收，适合实现缓存、观察者等场景避免内存泄漏。"},
  {q:"__slots__ 的主要好处是？", level:"进阶", options:["加速属性访问","节省内存（省去 __dict__）","线程安全","支持继承"], answer:1, explain:"__slots__ 固定属性集合，实例不创建 __dict__，显著节省内存，同时属性访问也略快。"},
  {q:"上下文管理器需要实现的两个方法是？", level:"进阶", options:["__enter__ 和 __exit__","__init__ 和 __del__","__open__ 和 __close__","__start__ 和 __stop__"], answer:0, explain:"with 语句要求对象实现 __enter__（进入返回资源）和 __exit__（退出执行清理，即使异常也会调用）。"},
  {q:"contextmanager 装饰器中 yield 的作用是？", level:"进阶", options:["生成器","yield 前是 __enter__，yield 值是 as 变量，yield 后是 __exit__","暂停执行","返回多个值"], answer:1, explain:"@contextmanager 将生成器转为上下文管理器：yield 之前对应 __enter__，yield 的值赋给 as 变量，yield 之后（在 finally 中）对应 __exit__。"},
  {q:"ExitStack 的用途是？", level:"高级", options:["栈数据结构","动态管理多个上下文管理器","异常堆栈","调用栈分析"], answer:1, explain:"ExitStack 可动态注册多个上下文管理器，按 LIFO 顺序退出，适合运行时才能确定数量的资源管理。"},
  {q:"dataclass 中可变默认值应使用？", level:"进阶", options:["default=[]","default_factory=list","default=None","直接赋值"], answer:1, explain:"可变对象（list/dict）作为默认值会导致所有实例共享同一对象（经典陷阱），必须用 default_factory 每次创建新实例。"},
  {q:"@dataclass(frozen=True) 的效果是？", level:"进阶", options:["冻结属性不可修改，可哈希","性能优化","内存优化","线程安全"], answer:0, explain:"frozen=True 使实例不可变，修改属性抛 FrozenInstanceError，同时实例可哈希（可作 dict key 或集合元素）。"},
  {q:"Python 3.10+ 表示 Optional[int] 的简写是？", level:"基础", options:["int?","int | None","Option[int]","Maybe[int]"], answer:1, explain:"PEP 604 允许用 | 表示联合类型，Optional[int] 等价于 int | None，Union[int, str] 等价于 int | str。"},
  {q:"Pydantic 与 dataclass 的核心区别是？", level:"进阶", options:["无区别","Pydantic 运行时校验并转换数据类型，dataclass 不校验","Pydantic 更慢","dataclass 支持继承"], answer:1, explain:"Pydantic 基于类型注解在运行时校验并转换数据，类型不匹配抛 ValidationError；dataclass 不做运行时校验。"},
  {q:"FastAPI 性能高的主要原因是？", level:"进阶", options:["用 C 编写","基于 Starlette(ASGI) 异步 + Pydantic","编译执行","多线程"], answer:1, explain:"FastAPI 基于 Starlette ASGI 异步框架和 Pydantic，原生 async/await 支持，可高效处理高并发 IO。"},
  {q:"FastAPI Depends 依赖注入的用途不包括？", level:"高级", options:["数据库会话管理","认证鉴权","共享逻辑复用","前端渲染"], answer:3, explain:"Depends 用于后端逻辑复用（DB 会话、认证、权限等），与前端渲染无关。"},
  {q:"functools.reduce 的作用是？", level:"进阶", options:["过滤","映射","累积计算","排序"], answer:2, explain:"reduce 对序列元素反复应用二元函数累积出单个值，如 reduce(operator.add, [1,2,3,4]) 得 10。"},
  {q:"itertools.chain 的作用是？", level:"进阶", options:["拉链配对","串联多个可迭代对象","循环迭代","笛卡尔积"], answer:1, explain:"chain(*iterables) 将多个可迭代对象串联成一个，逐个遍历；zip 才是配对。"},
  {q:"itertools.product 的作用是？", level:"进阶", options:["乘积运算","笛卡尔积","排列","组合"], answer:1, explain:"product(*iterables) 计算多个序列的笛卡尔积，如 product('AB','12') 得 A1 A2 B1 B2。"},
  {q:"以下哪个不是 itertools 的函数？", level:"基础", options:["permutations","combinations","zip_longest","flatten"], answer:3, explain:"itertools 没有 flatten 函数，可用 chain.from_iterable 展平嵌套。permutations/combinations/zip_longest 都是 itertools 成员。"},
  {q:"singledispatch 的作用是？", level:"高级", options:["单例模式","基于第一个参数类型分发不同实现","单线程调度","信号分发"], answer:1, explain:"@singledispatch 实现单分派泛型函数，根据第一个参数的类型调用对应的注册实现，类似方法重载。"},
  {q:".pyc 文件的作用是？", level:"进阶", options:["加密源码","缓存编译后的字节码加速加载","打包发布","配置文件"], answer:1, explain:".pyc 是源码编译后的字节码缓存，存于 __pycache__，首次导入时生成，后续直接加载避免重复编译。"},
  {q:"dis 模块的用途是？", level:"高级", options:["磁盘操作","反汇编 Python 字节码","调试器","分布式计算"], answer:1, explain:"dis.dis(func) 反汇编函数显示其字节码指令，帮助理解 Python 内部执行机制和性能优化。"},
  {q:"局部变量比全局变量访问快的原因是？", level:"高级", options:["局部变量更小","局部变量用 LOAD_FAST 指令（索引访问），全局用 LOAD_GLOBAL（字典查找）","局部变量在寄存器","全局变量加密"], answer:1, explain:"局部变量通过索引快速访问（LOAD_FAST），全局变量需要字典查找（LOAD_GLOBAL），因此局部变量更快。"},
  {q:"Python 虚拟机属于哪种类型？", level:"高级", options:["寄存器式","栈式","寄存器分配式","混合式"], answer:1, explain:"CPython 是栈式虚拟机，操作数压栈出栈执行运算，如 BINARY_ADD 弹出栈顶两数相加压回。"},
  {q:"元类的本质是？", level:"高级", options:["类的父类","类的类，负责创建类","类的实例","类的装饰器"], answer:1, explain:"元类是类的类，type 是默认元类。class Foo 等价于 Foo = type('Foo', (), {})，自定义元类可控制类的创建过程。"},
  {q:"__init_subclass__ 相比元类的优势是？", level:"高级", options:["性能更高","更简单，不需要自定义元类即可在子类创建时执行逻辑","支持多继承","线程安全"], answer:1, explain:"__init_subclass__（3.6+）是轻量替代方案，在父类定义即可，子类创建时自动调用，避免元类的复杂性。"},
  {q:"数据描述符与非数据描述符的区别是？", level:"高级", options:["数据描述符有 __set__，优先级高于实例 __dict__","数据描述符更快","非数据描述符不支持继承","无区别"], answer:0, explain:"数据描述符同时定义 __get__ 和 __set__，查找优先级高于实例 __dict__；非数据描述符只有 __get__，优先级低于实例 __dict__。"},
  {q:"描述符协议中 __set_name__ 的作用是？", level:"高级", options:["设置类名","在类创建时告知描述符其属性名，便于存储","重命名属性","设置类型"], answer:1, explain:"__set_name__(self, owner, name) 在类创建时自动调用，让描述符知道自己绑定的属性名，便于在实例 __dict__ 中存取。"},
  {q:"property 本质上是？", level:"进阶", options:["内置函数","数据描述符的简化形式","装饰器语法糖","类方法"], answer:1, explain:"property 是数据描述符的封装，实现了 __get__/__set__/__delete__，提供更简洁的属性访问控制语法。"}
]
