// === JAVA EXT2 ===
java_ext2_topics: [
  {
    id: "java-classloader-parent",
    title: "双亲委派模型与打破",
    level: "高级",
    content: "**类加载器层次（JDK 8）**\n1. **Bootstrap ClassLoader（启动类加载器）**\n   - C++ 实现，加载 rt.jar 等 JDK 核心类（java.*）\n   - 无 Java 对象表示，getParent() 返回 null\n2. **Extension ClassLoader（扩展类加载器）**\n   - 加载 jre/lib/ext 目录\n   - javax.* 等\n3. **Application ClassLoader（应用类加载器）**\n   - 加载 classpath 下的类\n   - 默认自定义类加载器的父\n\n**双亲委派模型**\n- 收到加载请求时，先委派给父加载器\n- 父加载器无法加载时，子加载器才尝试\n- 自底向上检查是否已加载，自顶向下尝试加载\n- 保证核心类不被篡改（安全）\n- 保证类的唯一性（同一类只加载一次）\n\n**类加载过程**\n1. 加载（Loading）：通过全限定名获取二进制字节流，生成 Class 对象\n2. 验证（Verification）：字节码安全检查\n3. 准备（Preparation）：静态变量分配内存并设默认值\n4. 解析（Resolution）：符号引用转直接引用\n5. 初始化（Initialization）：执行 <clinit> 静态代码块/静态变量赋值\n\n**打破双亲委派**\n- 自定义 ClassLoader 重写 loadClass（不推荐）或 findClass（推荐）\n- 经典场景：\n  - Tomcat：每个 Web 应用独立类加载器，隔离应用\n  - SPI 机制：bootstrap 加载接口，需用线程上下文类加载器加载实现\n  - OSGi：网状类加载结构\n  - 热部署/热加载\n\n**Tomcat 类加载器结构**\n- Common → WebApp1 / WebApp2\n- 每个 WebApp 独立加载自己的 class\n- 打破双亲委派：先自己加载再委派父\n\n**SPI（Service Provider Interface）**\n- java.sql.Driver 由 Bootstrap 加载接口\n- 实现在 classpath（Application 加载器）\n- 用 Thread.currentThread().getContextClassLoader() 加载实现\n- ServiceLoader.load(Driver.class)\n\n**JDK 9+ 模块化变化**\n- Extension ClassLoader 被 Platform ClassLoader 取代\n- 模块系统改变类加载方式\n- jrt:/ 协议访问模块",
    example: "// 自定义类加载器\nclass MyClassLoader extends ClassLoader {\n    private String classPath;\n\n    public MyClassLoader(String classPath, ClassLoader parent) {\n        super(parent);\n        this.classPath = classPath;\n    }\n\n    // 推荐重写 findClass（不破坏双亲委派）\n    @Override\n    protected Class<?> findClass(String name) throws ClassNotFoundException {\n        byte[] data = loadClassData(name);\n        return defineClass(name, data, 0, data.length);\n    }\n\n    private byte[] loadClassData(String name) {\n        String path = classPath + name.replace('.', '/') + \".class\";\n        try (FileInputStream fis = new FileInputStream(path);\n             ByteArrayOutputStream bos = new ByteArrayOutputStream()) {\n            byte[] buf = new byte[1024];\n            int len;\n            while ((len = fis.read(buf)) != -1) bos.write(buf, 0, len);\n            return bos.toByteArray();\n        } catch (IOException e) { throw new RuntimeException(e); }\n    }\n\n    // 打破双亲委派：重写 loadClass\n    @Override\n    public Class<?> loadClass(String name, boolean resolve)\n            throws ClassNotFoundException {\n        // 自定义类自己加载，其他委派父\n        if (name.startsWith(\"com.myapp.\")) {\n            Class<?> c = findLoadedClass(name);\n            if (c == null) c = findClass(name);\n            if (resolve) resolveClass(c);\n            return c;\n        }\n        return super.loadClass(name, resolve);\n    }\n}\n\n// 使用\nMyClassLoader cl = new MyClassLoader(\"/app/classes/\", \n    ClassLoader.getSystemClassLoader());\nClass<?> clazz = cl.loadClass(\"com.myapp.Hello\");\nObject obj = clazz.newInstance();\n\n// SPI 示例\nServiceLoader<Driver> loaders = ServiceLoader.load(Driver.class);\nfor (Driver d : loaders) { System.out.println(d.getClass()); }\n\n// 查看类加载器\nSystem.out.println(String.class.getClassLoader());  // null (Bootstrap)\nSystem.out.println(MyClass.class.getClassLoader());  // AppClassLoader\n\n// JDK 9+\n// ModuleLayer.boot().findModule(\"java.base\")\n// ClassLoader.getPlatformClassLoader()  // 替代 ExtClassLoader"
  },
  {
    id: "java-aqs",
    title: "AQS 原理与 Lock 体系",
    level: "高级",
    content: "**AQS（AbstractQueuedSynchronizer）**\n- JUC 同步器的基础框架\n- Doug Lea 设计\n- 核心思想：volatile int state 表示同步状态 + CLH FIFO 队列\n- ReentrantLock/Semaphore/CountDownLatch/ReentrantReadWriteLock 均基于 AQS\n\n**state 的含义**\n- ReentrantLock：重入次数\n- Semaphore：剩余许可数\n- CountDownLatch：剩余计数\n- ReentrantReadWriteLock：高16位读、低16位写\n\n**CLH 队列**\n- 变种的 Craig-Landin-Hagersten 队列\n- 双向链表，FIFO 等待队列\n- 节点状态：CANCELLED(1)/SIGNAL(-1)/CONDITION(-2)/PROPAGATE(-3)\n- 获取锁失败时入队，前驱节点唤醒后继\n\n**独占模式**\n- acquire(1)：tryAcquire → 入队 → 自旋/阻塞\n- release(1)：tryRelease → 唤醒后继\n- 子类实现 tryAcquire/tryRelease\n\n**共享模式**\n- acquireShared(1)：tryAcquireShared → 入队\n- releaseShared(1)：tryReleaseShared → 传播唤醒\n\n**ReentrantLock 实现**\n- 非公平（默认）：tryAcquire 先 CAS 抢占，失败再入队\n- 公平：tryAcquire 先检查队列是否有前驱，有则排队\n- 非公平吞吐量更高（减少线程切换）\n\n**ReentrantReadWriteLock**\n- 读锁共享，写锁独占\n- state 高16位读计数、低16位写计数\n- 写锁可降级为读锁（先获写再获读再释放写）\n- 读锁不能升级为写锁（死锁）\n\n**Condition**\n- 替代 Object.wait/notify\n- 一个 Lock 可创建多个 Condition（多等待队列）\n- await/signal/signalAll\n\n**Lock 接口体系**\n- Lock 接口：lock/lockInterruptibly/tryLock/unlock/newCondition\n- ReentrantLock：可重入互斥锁\n- ReentrantReadWriteLock.ReadLock / WriteLock\n- StampedLock（Java 8）：乐观读锁，高性能\n\n**synchronized vs ReentrantLock**\n- synchronized：JVM 内置，自动释放，不可中断，非公平\n- ReentrantLock：API 层，手动 unlock，可中断/超时/公平，多 Condition",
    example: "import java.util.concurrent.locks.*;\n\n// ReentrantLock 使用\nReentrantLock lock = new ReentrantLock();  // 非公平\n// ReentrantLock lock = new ReentrantLock(true);  // 公平\nlock.lock();\ntry {\n    // 临界区\n} finally {\n    lock.unlock();  // 必须 finally 释放\n}\n\n// 可中断锁\ntry {\n    lock.lockInterruptibly();\n    try { /* ... */ } finally { lock.unlock(); }\n} catch (InterruptedException e) {\n    Thread.currentThread().interrupt();\n}\n\n// 超时获取\nif (lock.tryLock(3, TimeUnit.SECONDS)) {\n    try { /* ... */ } finally { lock.unlock(); }\n}\n\n// Condition 多等待队列\nReentrantLock lk = new ReentrantLock();\nCondition notFull = lk.newCondition();\nCondition notEmpty = lk.newCondition();\nObject[] items = new Object[10];\nint count = 0;\n\n// 生产者\npublic void put(Object x) throws InterruptedException {\n    lk.lock();\n    try {\n        while (count == items.length) notFull.await();\n        items[count++] = x;\n        notEmpty.signal();\n    } finally { lk.unlock(); }\n}\n\n// 消费者\npublic Object take() throws InterruptedException {\n    lk.lock();\n    try {\n        while (count == 0) notEmpty.await();\n        Object x = items[--count];\n        notFull.signal();\n        return x;\n    } finally { lk.unlock(); }\n}\n\n// 读写锁\nReentrantReadWriteLock rwLock = new ReentrantReadWriteLock();\nrwLock.readLock().lock();  // 多个读并发\n// 读数据\nrwLock.readLock().unlock();\n\nrwLock.writeLock().lock();  // 写独占\n// 写数据\nrwLock.writeLock().unlock();\n\n// 写锁降级（安全）\nrwLock.writeLock().lock();\nrwLock.readLock().lock();    // 获取读锁\nrwLock.writeLock().unlock(); // 释放写锁，降级为读\n// 读操作\nrwLock.readLock().unlock();\n\n// StampedLock 乐观读（高性能）\nStampedLock sl = new StampedLock();\nlong stamp = sl.tryOptimisticRead();  // 乐观读（不加锁）\nint x = data;\nif (!sl.validate(stamp)) {  // 校验期间是否有写\n    stamp = sl.readLock();   // 升级为悲观读锁\n    try { x = data; } finally { sl.unlockRead(stamp); }\n}\n// 读锁不阻塞写，吞吐量高\n\n// 自定义 AQS 同步器\nclass Mutex extends AbstractQueuedSynchronizer {\n    @Override protected boolean tryAcquire(int arg) {\n        return compareAndSetState(0, 1);\n    }\n    @Override protected boolean tryRelease(int arg) {\n        setState(0); return true;\n    }\n    @Override protected boolean isHeldExclusively() {\n        return getState() == 1;\n    }\n}"
  },
  {
    id: "java-concurrent-collections",
    title: "并发容器详解",
    level: "高级",
    content: "**ConcurrentHashMap**\n- 线程安全的 HashMap\n- JDK 7：分段锁（Segment），默认16段\n- JDK 8+：数组 + 链表/红黑树，CAS + synchronized 锁桶节点\n- 查询无锁，写锁单个桶（粒度小）\n- 不允许 null key/value\n- size() 是弱一致性的估计值\n- 迭代器弱一致性（不抛 ConcurrentModificationException）\n\n**CopyOnWriteArrayList**\n- 写时复制：修改时复制整个数组\n- 读完全无锁，性能极高\n- 写性能差（复制开销）\n- 适合读多写少场景（监听器列表、配置）\n- 最终一致性（读可能看到旧值）\n\n**CopyOnWriteArraySet**\n- 基于 CopyOnWriteArrayList 实现\n- add 时检查去重\n\n**ConcurrentLinkedQueue**\n- 无锁并发队列（CAS）\n- 基于 Michael & Scott 算法\n- 非阻塞，性能高\n- size() 是 O(n) 遍历，不保证准确\n\n**BlockingQueue 体系**\n- **ArrayBlockingQueue**：有界数组，单锁（吞吐量低但稳定）\n- **LinkedBlockingQueue**：链表，默认 Integer.MAX_VALUE，两把锁（读写分离，高吞吐）\n- **SynchronousQueue**：容量0，直接交付（每个 put 等一个 take）\n- **PriorityBlockingQueue**：优先级队列，无界\n- **DelayQueue**：延迟队列，元素到期才能取出\n- **LinkedTransferQueue**：JDK 7+，高性能无界\n\n**BlockingQueue 应用**\n- 生产者消费者模式\n- 线程池任务队列\n- 消息传递\n\n**ConcurrentSkipListMap / Set**\n- 跳表实现的并发有序 Map/Set\n- 替代 TreeMap/TreeSet 的并发版本\n- 平均 O(log n) 操作\n- 无锁读，CAS 写\n\n**选择建议**\n- 高并发读多写少：ConcurrentHashMap / CopyOnWriteArrayList\n- 生产者消费者：ArrayBlockingQueue / LinkedBlockingQueue\n- 任务延迟执行：DelayQueue\n- 并发有序：ConcurrentSkipListMap",
    example: "import java.util.concurrent.*;\nimport java.util.concurrent.atomic.*;\n\n// ConcurrentHashMap\nConcurrentHashMap<String, Integer> map = new ConcurrentHashMap<>();\nmap.put(\"a\", 1);\nmap.put(\"b\", 2);\n// 原子操作\nmap.compute(\"a\", (k, v) -> v == null ? 1 : v + 1);  // a -> 2\nmap.merge(\"c\", 1, Integer::sum);  // 不存在则1，存在则累加\nmap.putIfAbsent(\"d\", 4);  // 不存在才放入\n// 并发遍历（弱一致，不抛异常）\nmap.forEach((k, v) -> System.out.println(k + \"=\" + v));\n\n// CopyOnWriteArrayList（读多写少）\nCopyOnWriteArrayList<Listener> listeners = new CopyOnWriteArrayList<>();\nlisteners.add(new Listener());  // 写时复制\nfor (Listener l : listeners) { l.onEvent(); }  // 读无锁\n\n// ArrayBlockingQueue（有界，生产者消费者）\nBlockingQueue<Task> queue = new ArrayBlockingQueue<>(100);\n// 生产者\nnew Thread(() -> {\n    while (true) queue.put(produceTask());  // 满了阻塞\n}).start();\n// 消费者\nnew Thread(() -> {\n    while (true) {\n        Task t = queue.take();  // 空了阻塞\n        process(t);\n    }\n}).start();\n\n// DelayQueue（延迟执行）\nclass DelayedTask implements Delayed {\n    long executeTime;\n    String name;\n    DelayedTask(long delay, String name) {\n        this.executeTime = System.currentTimeMillis() + delay;\n        this.name = name;\n    }\n    @Override public long getDelay(TimeUnit unit) {\n        return unit.convert(executeTime - System.currentTimeMillis(), TimeUnit.MILLISECONDS);\n    }\n    @Override public int compareTo(Delayed o) {\n        return Long.compare(this.executeTime, ((DelayedTask)o).executeTime);\n    }\n}\nDelayQueue<DelayedTask> dq = new DelayQueue<>();\ndq.put(new DelayedTask(5000, \"5秒后执行\"));\n// take() 会阻塞直到元素到期\nnew Thread(() -> {\n    try { DelayedTask t = dq.take(); System.out.println(t.name); }\n    catch (InterruptedException e) {}\n}).start();\n\n// ConcurrentSkipListMap（并发有序）\nConcurrentSkipListMap<Integer, String> sl = new ConcurrentSkipListMap<>();\nsl.put(3, \"c\"); sl.put(1, \"a\"); sl.put(2, \"b\");\nSystem.out.println(sl.firstKey());  // 1\nSystem.out.println(sl.subMap(1, 3));  // {1=a, 2=b}\n\n// SynchronousQueue（直接传递）\nBlockingQueue<String> sq = new SynchronousQueue<>();\nnew Thread(() -> { try { sq.put(\"data\"); } catch (Exception e) {} }).start();\n// put 会阻塞直到有消费者 take\nString s = sq.take();  // 直接获得"
  },
  {
    id: "java-threadlocal",
    title: "ThreadLocal 原理与内存泄漏",
    level: "高级",
    content: "**ThreadLocal 作用**\n- 线程本地变量，每个线程独立副本\n- 避免参数传递\n- 实现线程隔离\n\n**常见应用**\n- 数据库连接/会话管理\n- 用户上下文（UserContext）\n- 事务管理\n- 日期格式化（SimpleDateFormat 非线程安全）\n- MDC 日志跟踪\n\n**实现原理**\n- 每个 Thread 有 ThreadLocalMap threadLocals 字段\n- ThreadLocalMap 是 ThreadLocal 的内部类\n- key 是 ThreadLocal 对象（弱引用）\n- value 是实际值\n- set/get 时操作当前线程的 ThreadLocalMap\n\n**ThreadLocalMap 结构**\n- Entry 继承 WeakReference<ThreadLocal<?>>\n- key 弱引用 ThreadLocal，value 强引用\n- 数组实现，开放寻址法（线性探测）\n\n**内存泄漏问题**\n- ThreadLocal 被 GC 回收后，key 变 null\n- 但 value 仍被 Entry 强引用\n- Entry 被 ThreadLocalMap 引用\n- ThreadLocalMap 被 Thread 引用\n- 若线程不结束（线程池），value 无法回收\n\n**内存泄漏解决**\n- 使用后必须调用 remove() 清除\n- 尤其线程池环境，线程复用\n- try-finally 中 remove\n\n**InheritableThreadLocal**\n- 子线程可继承父线程的值\n- 创建子线程时复制\n- 线程池中失效（线程复用不会重新复制）\n\n**TransmittableThreadLocal（阿里开源）**\n- 解决线程池中 ThreadLocal 传递问题\n- 在任务提交和执行时传递\n\n**ThreadLocal vs Synchronized**\n- ThreadLocal：空间换时间，各线程独立副本\n- Synchronized：时间换空间，共享变量加锁\n\n**hash 冲突处理**\n- ThreadLocalMap 用开放寻址（线性探测）\n- 不是 HashMap 的链表法\n- 魔数 0x61c88647（黄金分割）使分布均匀",
    example: "import java.text.SimpleDateFormat;\n\n// 基本使用\nThreadLocal<User> userContext = ThreadLocal.withInitial(() -> new User(\"guest\"));\nuserContext.set(new User(\"alice\"));\nUser u = userContext.get();\nuserContext.remove();  // 用完必须清除\n\n// 日期格式化（SimpleDateFormat 非线程安全）\n// 错误：共享实例多线程出错\n// private static final SimpleDateFormat fmt = new SimpleDateFormat(\"yyyy-MM-dd\");\n\n// 正确：ThreadLocal 每线程独立\nprivate static final ThreadLocal<SimpleDateFormat> fmt =\n    ThreadLocal.withInitial(() -> new SimpleDateFormat(\"yyyy-MM-dd\"));\nString dateStr = fmt.get().format(new Date());\n\n// 数据库连接管理\nclass ConnectionManager {\n    private static ThreadLocal<Connection> connHolder = new ThreadLocal<>();\n\n    public static Connection getConnection() {\n        Connection conn = connHolder.get();\n        if (conn == null) {\n            conn = DriverManager.getConnection(url);\n            connHolder.set(conn);\n        }\n        return conn;\n    }\n\n    public static void close() {\n        Connection conn = connHolder.get();\n        if (conn != null) {\n            try { conn.close(); } catch (Exception e) {}\n            connHolder.remove();  // 关键：防止泄漏\n        }\n    }\n}\n\n// 正确使用模式（线程池环境）\nExecutorService pool = Executors.newFixedThreadPool(10);\npool.submit(() -> {\n    try {\n        userContext.set(getCurrentUser());\n        // 业务逻辑使用 userContext.get()\n        doBusiness();\n    } finally {\n        userContext.remove();  // 必须！线程复用会泄漏\n    }\n});\n\n// InheritableThreadLocal（子线程继承）\nThreadLocal<String> itl = new InheritableThreadLocal<>();\nitl.set(\"parent-value\");\nnew Thread(() -> {\n    System.out.println(itl.get());  // parent-value\n}).start();\n// 但线程池中失效（线程复用不重新继承）\n\n// TransmittableThreadLocal 解决线程池传递\n// TransmittableThreadLocal<String> ttl = new TransmittableThreadLocal<>();\n// TtlRunnable.get(() -> { ttl.get(); })\n// TtlExecutors.getTtlExecutorService(pool)"
  },
  {
    id: "java-threadpool-deep",
    title: "线程池深度与调优",
    level: "高级",
    content: "**ThreadPoolExecutor 参数**\n- corePoolSize：核心线程数\n- maximumPoolSize：最大线程数\n- keepAliveTime：空闲线程存活时间\n- unit：时间单位\n- workQueue：任务队列\n- threadFactory：线程工厂（命名、守护线程等）\n- handler：拒绝策略\n\n**任务提交流程**\n1. 线程数 < corePoolSize：创建新核心线程执行\n2. 线程数 >= corePoolSize：任务入队列\n3. 队列满：创建非核心线程（直到 maximumPoolSize）\n4. 线程数 = maximumPoolSize 且队列满：执行拒绝策略\n\n**注意**：不是先创建到最大线程数再入队列，而是先入队列再创建非核心线程\n\n**四种拒绝策略**\n- AbortPolicy（默认）：抛 RejectedExecutionException\n- CallerRunsPolicy：由提交任务的线程执行（降级/背压）\n- DiscardPolicy：静默丢弃\n- DiscardOldestPolicy：丢弃队列最老任务，重试提交\n\n**常见队列选择**\n- 无界队列（LinkedBlockingQueue 默认 Integer.MAX_VALUE）：maximumPoolSize 失效，可能 OOM\n- 有界队列（ArrayBlockingQueue）：需配合 maximumPoolSize\n- SynchronousQueue：不存储，直接交付（Executors.newCachedThreadPool 用）\n\n**Executors 工厂方法（不推荐生产使用）**\n- newFixedThreadPool：固定线程数 + 无界队列（OOM 风险）\n- newSingleThreadExecutor：单线程 + 无界队列（OOM 风险）\n- newCachedThreadPool：0~Integer.MAX_VALUE + SynchronousQueue（线程数失控）\n- newScheduledThreadPool：定时任务\n- 推荐用 ThreadPoolExecutor 显式构造\n\n**线程数设置经验**\n- CPU 密集型：N + 1（N = CPU 核数）\n- IO 密集型：2N 或 N * (1 + 等待时间/计算时间)\n- 混合型：拆分分别用不同线程池\n\n**监控指标**\n- getActiveCount()：活跃线程数\n- getQueue().size()：积压任务数\n- getCompletedTaskCount()：已完成任务数\n- getLargestPoolSize()：历史峰值\n\n**线程池调优**\n- 合理设置队列大小（防止任务丢失）\n- 监控告警（队列积压、拒绝次数）\n- 动态调整（allowCoreThreadTimeOut）\n- 自定义 ThreadFactory 命名线程（便于排查）\n- 优雅关闭（shutdown/shutdownNow）\n\n**ForkJoinPool**\n- 分治任务线程池\n- 工作窃取算法（空闲线程偷其他队列任务）\n- 适合递归分治任务\n- JDK 8 parallelStream 默认用 ForkJoinPool.commonPool",
    example: "import java.util.concurrent.*;\n\n// 标准线程池创建\nThreadPoolExecutor pool = new ThreadPoolExecutor(\n    4,                              // corePoolSize\n    8,                              // maximumPoolSize\n    60L, TimeUnit.SECONDS,          // keepAliveTime\n    new ArrayBlockingQueue<>(100),  // 有界队列\n    new ThreadFactory() {           // 自定义线程工厂\n        private final AtomicInteger counter = new AtomicInteger();\n        public Thread newThread(Runnable r) {\n            Thread t = new Thread(r, \"biz-pool-\" + counter.incrementAndGet());\n            t.setDaemon(false);\n            return t;\n        }\n    },\n    new ThreadPoolExecutor.CallerRunsPolicy()  // 拒绝策略：调用者执行\n);\n\n// 提交任务\nFuture<String> future = pool.submit(() -> {\n    Thread.sleep(1000);\n    return \"result\";\n});\nString result = future.get(5, TimeUnit.SECONDS);  // 超时获取\n\n// 监控\nSystem.out.println(\"活跃线程: \" + pool.getActiveCount());\nSystem.out.println(\"队列积压: \" + pool.getQueue().size());\nSystem.out.println(\"已完成: \" + pool.getCompletedTaskCount());\n\n// CPU 密集型线程数\nint cpuCores = Runtime.getRuntime().availableProcessors();\nThreadPoolExecutor cpuPool = new ThreadPoolExecutor(\n    cpuCores + 1, cpuCores + 1, 0, TimeUnit.SECONDS,\n    new LinkedBlockingQueue<>(1000));\n\n// IO 密集型\nThreadPoolExecutor ioPool = new ThreadPoolExecutor(\n    cpuCores * 2, cpuCores * 4, 60, TimeUnit.SECONDS,\n    new LinkedBlockingQueue<>(500));\n\n// ForkJoinPool 分治\nForkJoinPool fjPool = new ForkJoinPool(4);\nInteger sum = fjPool.invoke(new RecursiveTask<Integer>() {\n    @Override protected Integer compute() {\n        // 分治逻辑\n        return 0;\n    }\n});\n\n// parallelStream 默认用 ForkJoinPool.commonPool()\nIntStream.range(0, 100).parallel().sum();\n\n// 优雅关闭\npool.shutdown();  // 不接受新任务，执行完已提交\nif (!pool.awaitTermination(60, TimeUnit.SECONDS)) {\n    pool.shutdownNow();  // 停止所有任务\n}\n\n// CompletableFuture 异步编排\nCompletableFuture.supplyAsync(() -> queryUser(), pool)\n    .thenApplyAsync(user -> enrichData(user), pool)\n    .thenComposeAsync(data -> saveAsync(data), pool)\n    .exceptionally(ex -> { log.error(ex); return null; });"
  },
  {
    id: "java-jvm-troubleshoot",
    title: "JVM 问题排查实战",
    level: "高级",
    content: "**CPU 飙高排查**\n1. top 找出 CPU 高的 Java 进程 PID\n2. top -Hp PID 找出 CPU 高的线程 TID\n3. printf '%x\\n' TID 转十六进制\n4. jstack PID > stack.log 打印线程栈\n5. grep 十六进制TID 找到对应线程，分析代码\n\n**常见 CPU 高原因**\n- 死循环/忙等待\n- 频繁 GC\n- 加密/压缩等 CPU 密集计算\n- 正则回溯爆炸\n\n**内存溢出（OOM）排查**\n- JVM 参数：-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/path/heap.hprof\n- 工具：MAT (Memory Analyzer Tool)、JProfiler、VisualVM\n- 分析 hprof 文件找出大对象/泄漏\n\n**常见 OOM 类型**\n- java.lang.OutOfMemoryError: Java heap space：堆内存不足\n- Metaspace：元空间不足（类加载过多，如动态代理）\n- GC overhead limit exceeded：GC 耗时超过98%但回收不足2%\n- Direct buffer memory：堆外内存不足\n- unable to create new native thread：线程数超限\n\n**GC 频繁排查**\n- jstat -gc PID 1000 查看 GC 统计\n- 关注 YGC/FGC 次数和耗时\n- -Xlog:gc* (JDK 9+) 或 -XX:+PrintGCDetails\n- 分析大对象、内存泄漏、年轻代太小\n\n**常用诊断工具**\n- jps：列出 Java 进程\n- jstack：打印线程栈（死锁检测）\n- jstat：GC/类加载统计\n- jmap：堆内存分析、dump\n- jcmd（JDK 8+）：多功能命令\n- arthas（阿里）：在线诊断神器\n\n**Arthas 常用命令**\n- dashboard：实时面板\n- thread：线程信息\n- thread -b：找阻塞线程\n- jad：反编译类\n- watch：方法执行监控\n- trace：方法调用链耗时\n- profiler：火焰图\n\n**死锁排查**\n- jstack -l PID 末尾会输出死锁检测\n- 两个线程互相持有对方需要的锁\n- 避免嵌套锁、固定锁顺序\n\n**类加载泄漏**\n- Tomcat 重复部署导致旧 WebAppClassLoader 无法回收\n- 原因：静态引用、ThreadLocal、未注销的监听器\n- jmap -histo 查看类实例数",
    example: "# ===== CPU 飙高排查步骤 =====\n# 1. 找进程\n# top  → 找到 CPU 高的 Java PID (如 12345)\n\n# 2. 找线程\n# top -Hp 12345  → 找到 CPU 高的线程 TID (如 12356)\n\n# 3. 转十六进制\n# printf '%x\\n' 12356  → 0x3044\n\n# 4. dump 线程栈\n# jstack 12345 > /tmp/stack.log\n\n# 5. 查找线程\n# grep '3044' /tmp/stack.log -A 30\n\n# ===== OOM 排查 =====\n# JVM 启动参数加上自动 dump\n# java -XX:+HeapDumpOnOutOfMemoryError \\\n#      -XX:HeapDumpPath=/data/heap.hprof \\\n#      -Xms512m -Xmx512m MyApp\n\n# 手动 dump\n# jmap -dump:format=b,file=heap.hprof 12345\n# jcmd 12345 GC.heap_dump /tmp/heap.hprof\n\n# 查看 GC 情况\n# jstat -gcutil 12345 1000  (每秒一次)\n#  S0    S1    E     O     M    YGC  YGCT  FGC FGCT\n#  0.00 45.23 68.5  32.1  95.2  23   0.234  2  0.456\n\n# ===== Arthas 在线诊断 =====\n# 启动: java -jar arthas-boot.jar <PID>\n# dashboard          # 实时面板\n# thread             # 线程列表\n# thread -b          # 找出阻塞其他线程的线程\n# thread 15          # 查看线程15的栈\n# jad com.foo.Bar    # 反编译确认线上代码\n# watch com.foo.Bar method '{params, returnObj}' '#cost>100'\n#                    # 监控方法参数和返回，耗时>100ms\n# trace com.foo.Bar method  # 方法调用链耗时\n# profiler start; sleep 30; profiler stop  # 火焰图\n\n# ===== 死锁检测 =====\n# jstack -l 12345 | grep -A 20 'Found .* deadlock'\n\n# ===== Java 代码模拟 OOM 分析 =====\n// 大对象导致 OOM\nList<byte[]> list = new ArrayList<>();\nwhile (true) {\n    list.add(new byte[1024 * 1024]);  // 不断分配 1MB\n}\n// MAT 分析：Dominator Tree 找最大对象\n// Leak Suspects 报告自动分析泄漏点\n\n// 线程数过多 OOM\nwhile (true) {\n    new Thread(() -> { try { Thread.sleep(Long.MAX_VALUE); }\n        catch (Exception e){} }).start();\n}\n// 解决：用线程池限制线程数\n// 调整 ulimit -u / kernel 参数"
  },
  {
    id: "java-spring-ioc-aop",
    title: "Spring IOC/AOP 原理",
    level: "高级",
    content: "**IOC（控制反转）**\n- 对象创建和依赖注入由容器管理\n- DI（依赖注入）是 IOC 的实现方式\n- 解耦组件，便于测试\n\n**Bean 生命周期**\n1. 实例化（Instantiation）：调用构造方法创建对象\n2. 属性赋值（Populate）：注入依赖（@Autowired）\n3. Aware 接口回调：BeanNameAware/BeanFactoryAware 等\n4. BeanPostProcessor.postProcessBeforeInitialization\n5. 初始化：@PostConstruct → InitializingBean.afterPropertiesSet → init-method\n6. BeanPostProcessor.postProcessAfterInitialization（AOP 代理在此创建）\n7. 使用\n8. 销毁：@PreDestroy → DisposableBean.destroy → destroy-method\n\n**Bean 作用域**\n- singleton（默认）：单例\n- prototype：每次获取新建\n- request/session：Web 环境\n\n**循环依赖解决（三级缓存）**\n- singletonObjects（一级）：完整 Bean\n- earlySingletonObjects（二级）：早期暴露的半成品\n- singletonFactories（三级）：ObjectFactory（可生成代理）\n- 流程：A 依赖 B，B 依赖 A\n  1. 创建 A，将 A 的 ObjectFactory 放入三级缓存\n  2. 注入 B，创建 B，B 注入 A 时从三级缓存获取 A 的早期引用\n  3. B 完成注入，A 继续注入 B\n- 只能解决 setter/字段注入的单例循环依赖\n- 构造器循环依赖无法解决\n\n**AOP（面向切面编程）**\n- 横切关注点：日志/事务/权限/缓存\n- 术语：切面(Aspect)/切点(Pointcut)/通知(Advice)/织入(Weaving)\n- 通知类型：Before/After/Around/AfterReturning/AfterThrowing\n\n**AOP 实现原理**\n- **JDK 动态代理**：基于接口，Proxy.newProxyInstance\n- **CGLIB 代理**：基于继承，生成子类\n- Spring 默认：有接口用 JDK 代理，无接口用 CGLIB\n- Spring Boot 2.x+ 默认 CGLIB\n- proxy-target-class=true 强制 CGLIB\n\n**AOP 创建时机**\n- BeanPostProcessor.postProcessAfterInitialization 中\n- AnnotationAwareAspectJAutoProxyCreator 扫描 @Aspect\n- 匹配切点则创建代理替换原始 Bean\n\n**事务原理（@Transactional）**\n- 基于 AOP，代理类拦截方法\n- 开启事务 → 执行方法 → 提交/回滚\n- 事务失效场景：\n  - 自调用（this.method() 不走代理）\n  - 方法非 public\n  - 异常被 catch 未抛出\n  - 默认只回滚 RuntimeException（rollbackFor 可配置）\n  - 传播行为配置不当",
    example: "// ===== Bean 生命周期 =====\n@Component\npublic class MyBean implements BeanNameAware, InitializingBean, DisposableBean {\n    @Autowired\n    private Dependency dep;  // 属性赋值阶段\n\n    @PostConstruct\n    public void init() { /* 初始化 */ }\n\n    @Override\n    public void setBeanName(String name) { /* Aware 回调 */ }\n\n    @Override\n    public void afterPropertiesSet() { /* InitializingBean */ }\n\n    @PreDestroy\n    public void cleanup() { /* 销毁前 */ }\n\n    @Override\n    public void destroy() { /* DisposableBean */ }\n}\n\n// ===== 循环依赖（三级缓存）=====\n@Service\nclass A {\n    @Autowired B b;  // A 依赖 B\n}\n@Service\nclass B {\n    @Autowired A a;  // B 依赖 A（setter/字段注入可解决）\n}\n// 构造器循环依赖无法解决：\n// class A { A(B b){} }  class B { B(A a){} }  // 启动报错\n\n// ===== AOP 示例 =====\n@Aspect\n@Component\npublic class LogAspect {\n    // 切点：service 包下所有方法\n    @Pointcut(\"execution(* com.example.service.*.*(..))\")\n    public void servicePoint() {}\n\n    @Before(\"servicePoint()\")\n    public void before(JoinPoint jp) {\n        log.info(\"调用: {}.{}\", jp.getSignature().getDeclaringTypeName(),\n                 jp.getSignature().getName());\n    }\n\n    @Around(\"servicePoint()\")\n    public Object around(ProceedingJoinPoint pjp) throws Throwable {\n        long start = System.currentTimeMillis();\n        try {\n            Object result = pjp.proceed();  // 执行目标方法\n            return result;\n        } finally {\n            log.info(\"耗时: {}ms\", System.currentTimeMillis() - start);\n        }\n    }\n\n    @AfterThrowing(pointcut = \"servicePoint()\", throwing = \"ex\")\n    public void afterThrowing(JoinPoint jp, Exception ex) {\n        log.error(\"异常: {}\", ex.getMessage());\n    }\n}\n\n// ===== 事务失效示例 =====\n@Service\npublic class UserService {\n    @Transactional\n    public void outerMethod() {\n        // selfCall();  // 事务失效！this 调用不走代理\n        // 解决：注入自身代理 或 AopContext.currentProxy()\n        ((UserService) AopContext.currentProxy()).selfCall();\n    }\n\n    @Transactional(rollbackFor = Exception.class)  // 指定回滚异常\n    public void selfCall() throws Exception {\n        // 业务逻辑\n    }\n}\n\n// 强制 CGLIB 代理\n// @EnableAspectJAutoProxy(proxyTargetClass = true)\n// 暴露代理对象\n// @EnableAspectJAutoProxy(exposeProxy = true)"
  },
  {
    id: "java-springboot-autoconfig",
    title: "Spring Boot 自动配置原理",
    level: "高级",
    content: "**核心注解 @SpringBootApplication**\n- @SpringBootConfiguration：配置类（@Configuration）\n- @ComponentScan：组件扫描\n- @EnableAutoConfiguration：自动配置入口\n\n**自动配置原理**\n1. @EnableAutoConfiguration 通过 @Import 加载 AutoConfigurationImportSelector\n2. selectImports() 调用 SpringFactoriesLoader.loadFactoryNames\n3. 读取 META-INF/spring.factories 中 EnableAutoConfiguration 的类列表\n4. Spring Boot 2.7+ 改用 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports\n5. 过滤：@Conditional 条件决定是否生效\n\n**条件注解**\n- @ConditionalOnClass：类路径存在某类才生效\n- @ConditionalOnMissingBean：容器无某 Bean 才生效（用户可覆盖默认）\n- @ConditionalOnProperty：配置项满足条件\n- @ConditionalOnBean：容器存在某 Bean\n- @ConditionalOnWebApplication：Web 应用\n\n**自动配置类示例**\n- DataSourceAutoConfiguration：自动配置数据源\n- RedisAutoConfiguration：自动配置 RedisTemplate\n- 等等上百个\n\n**自定义 Starter**\n1. 创建自动配置类 @Configuration + @Conditional\n2. 注册到 spring.factories 或 imports 文件\n3. 打包，引入即生效\n\n**启动流程**\n1. SpringApplication.run()\n2. 创建 SpringApplication 实例（推断应用类型、加载监听器）\n3. 准备环境（读取 application.yml）\n4. 创建 ApplicationContext\n5. refreshContext：加载 BeanDefinition、实例化单例 Bean\n6. 触发自动配置\n7. 启动内嵌容器（Tomcat）\n8. 发布 ApplicationReadyEvent\n\n**内嵌容器**\n- 默认 Tomcat\n- 可换 Jetty/Undertow\n- ServletWebServerFactory 创建容器\n\n**配置文件加载顺序**\n1. 命令行参数\n2. 环境变量\n3. application-{profile}.yml\n4. application.yml\n5. 默认值\n\n**Actuator 监控**\n- /actuator/health：健康检查\n- /actuator/beans：所有 Bean\n- /actuator/configprops：配置属性\n- /actuator/metrics：指标\n- 生产需谨慎暴露端点",
    example: "// 启动类\n@SpringBootApplication\npublic class MyApp {\n    public static void main(String[] args) {\n        SpringApplication.run(MyApp.class, args);\n    }\n}\n\n// 自定义自动配置\n@Configuration\n@ConditionalOnClass(SmsService.class)  // 类路径有 SmsService 才生效\n@EnableConfigurationProperties(SmsProperties.class)\npublic class SmsAutoConfiguration {\n\n    @Bean\n    @ConditionalOnMissingBean  // 用户未定义则创建默认\n    @ConditionalOnProperty(prefix = \"sms\", name = \"enabled\", havingValue = \"true\")\n    public SmsService smsService(SmsProperties props) {\n        return new SmsService(props.getAccessKey(), props.getSecret());\n    }\n}\n\n@ConfigurationProperties(prefix = \"sms\")\npublic class SmsProperties {\n    private String accessKey;\n    private String secret;\n    private boolean enabled = true;\n    // getter/setter\n}\n\n// 注册自动配置\n// src/main/resources/META-INF/spring.factories:\n// org.springframework.boot.autoconfigure.EnableAutoConfiguration=\\\n//   com.example.SmsAutoConfiguration\n//\n// Spring Boot 2.7+ 用新文件:\n// src/main/resources/META-INF/spring/\n//   org.springframework.boot.autoconfigure.AutoConfiguration.imports\n// 内容: com.example.SmsAutoConfiguration\n\n// application.yml 配置\n'''\nsms:\n  enabled: true\n  access-key: AKID123\n  secret: SECRET456\n'''\n\n// 使用：引入 starter 即自动配置\n@Service\npublic class NotifyService {\n    @Autowired  // 自动注入自动配置创建的 Bean\n    private SmsService smsService;\n}\n\n// 多环境配置\n// application.yml (默认)\n// application-dev.yml (开发)\n// application-prod.yml (生产)\n// spring.profiles.active=dev 激活\n\n// 外部化配置优先级（高到低）\n// 1. 命令行: --sms.access-key=XXX\n// 2. JVM 参数: -Dsms.access-key=XXX\n// 3. 环境变量: SMS_ACCESS_KEY=XXX\n// 4. application-{profile}.yml\n// 5. application.yml"
  }
],
java_ext2_questions: [
  {q:"双亲委派模型中，类加载请求首先委派给？", level:"高级", options:["子加载器","父加载器","自身","随机"], answer:1, explain:"双亲委派：收到加载请求先委派给父加载器，父加载器无法加载时子加载器才尝试，保证核心类安全和类的唯一性。"},
  {q:"双亲委派模型的主要目的是？", level:"高级", options:["提高性能","保证核心类不被篡改和类的唯一性","节省内存","简化加载"], answer:1, explain:"双亲委派保证 java.lang.String 等核心类由 Bootstrap 加载，自定义同名类无法覆盖，防止安全隐患；同时保证同一类只加载一次。"},
  {q:"Tomcat 打破双亲委派的原因是？", level:"高级", options:["性能优化","隔离不同 Web 应用，各自加载自己的类","节省内存","热部署"], answer:1, explain:"Tomcat 每个 Web 应用有独立类加载器，优先自己加载（打破双亲委派），实现应用间类隔离，避免冲突。"},
  {q:"SPI 机制（如 JDBC Driver）加载实现类用的是？", level:"高级", options:["Bootstrap ClassLoader","线程上下文类加载器","Extension ClassLoader","自定义"], answer:1, explain:"SPI 接口由 Bootstrap 加载，实现在 classpath 需 Application 加载器。用 Thread.currentThread().getContextClassLoader() 打破双亲委派加载实现。"},
  {q:"AQS 的核心组成是？", level:"高级", options:["volatile state + CLH 队列","synchronized + 队列","CAS + 锁","volatile + 链表"], answer:0, explain:"AQS 用 volatile int state 表示同步状态 + CLH FIFO 双向队列管理等待线程，是 ReentrantLock/Semaphore/CountDownLatch 的基础。"},
  {q:"ReentrantLock 中非公平锁与公平锁的区别是？", level:"高级", options:["性能不同","非公平锁先 CAS 抢占，公平锁先检查队列是否有前驱","公平锁更快","无区别"], answer:1, explain:"非公平锁 tryAcquire 先 CAS 抢占（可能插队），吞吐量高；公平锁先检查队列有无前驱线程，按 FIFO 顺序，不会饥饿。"},
  {q:"ReentrantReadWriteLock 中 state 的设计是？", level:"高级", options:["单独字段","高16位读锁计数，低16位写锁计数","两个 state","数组"], answer:1, explain:"读写锁用一个 int 的 state：高16位表示读锁持有数（共享），低16位表示写锁重入数（独占），巧妙复用。"},
  {q:"写锁可以降级为读锁吗？", level:"高级", options:["可以，持有写锁时获取读锁再释放写锁","不可以","只能升级","视情况"], answer:0, explain:"写锁可降级：持有写锁时获取读锁，再释放写锁。但读锁不能升级为写锁（会导致死锁）。"},
  {q:"Condition 相比 Object.wait/notify 的优势是？", level:"高级", options:["更快","一个 Lock 可创建多个 Condition（多等待队列），精确唤醒","线程安全","无死锁"], answer:1, explain:"Condition 允许一个 Lock 关联多个等待队列，可以按条件分组等待并精确唤醒，比 Object 的单等待队列更灵活。"},
  {q:"JDK 8 的 ConcurrentHashMap 实现方式是？", level:"高级", options:["分段锁 Segment","CAS + synchronized 锁桶节点","全局锁","无锁"], answer:1, explain:"JDK 8 ConcurrentHashMap 用数组+链表/红黑树，查询无锁，写操作用 CAS + synchronized 锁单个桶节点，粒度比 JDK7 的分段锁更细。"},
  {q:"CopyOnWriteArrayList 适合的场景是？", level:"高级", options:["写多读少","读多写少（如监听器列表、配置）","高并发写","频繁修改"], answer:1, explain:"写时复制整个数组开销大，但读完全无锁性能极高，适合读远多于写的场景，如事件监听器列表、配置缓存。"},
  {q:"ArrayBlockingQueue 和 LinkedBlockingQueue 的区别是？", level:"高级", options:["无区别","Array 有界单锁，Linked 默认无界双锁（读写分离吞吐高）","Array 更快","Linked 更安全"], answer:1, explain:"ArrayBlockingQueue 有界单锁（put/take 互斥）；LinkedBlockingQueue 默认 Integer.MAX_VALUE 近似无界，put/take 两把锁分离，吞吐量更高但有 OOM 风险。"},
  {q:"SynchronousQueue 的特点是？", level:"高级", options:["无界队列","容量为0，每个 put 必须等待一个 take","有界队列","性能最低"], answer:1, explain:"SynchronousQueue 不存储元素，容量为0，每个 put 阻塞直到有 take 接收，直接交付。Executors.newCachedThreadPool 用它实现即时线程创建。"},
  {q:"DelayQueue 取出元素的条件是？", level:"高级", options:["队列非空","元素到期（getDelay <= 0）","先进先出","优先级最高"], answer:1, explain:"DelayQueue 元素必须实现 Delayed 接口，take() 阻塞直到队首元素到期（延迟时间归零），用于定时任务、延迟消息。"},
  {q:"ThreadLocal 的实现原理是？", level:"高级", options:["共享变量加锁","每个 Thread 有 ThreadLocalMap，key 是 ThreadLocal（弱引用）","全局 Map","线程局部栈"], answer:1, explain:"ThreadLocal 的值存在每个 Thread 的 ThreadLocalMap 中，key 是 ThreadLocal 对象（弱引用），value 是实际值，实现线程隔离。"},
  {q:"ThreadLocal 内存泄漏的原因是？", level:"高级", options:["ThreadLocal 被回收","key 弱引用回收后变 null，但 value 被 Entry 强引用且 Thread 存活（线程池）","GC 不工作","value 弱引用"], answer:1, explain:"ThreadLocal 被回收后 key 变 null，但 value 仍被 Entry 强引用，Entry 被 ThreadLocalMap 引用，Thread 不结束（线程池复用）则 value 无法回收，导致泄漏。"},
  {q:"ThreadLocal 正确使用方式是？", level:"高级", options:["用完不管","用完必须调用 remove()，尤其线程池环境","手动 GC","用弱引用 value"], answer:1, explain:"线程池中线程复用，ThreadLocal 不清除会导致数据串号和内存泄漏。必须 try-finally 中 remove()。"},
  {q:"InheritableThreadLocal 在线程池中失效的原因是？", level:"高级", options:["线程池不支持","子线程创建时才复制，线程池复用线程不重新创建","性能问题","安全限制"], answer:1, explain:"InheritableThreadLocal 在子线程创建时复制父线程的值，但线程池复用已有线程（不创建新线程），不会重新复制。需用 TransmittableThreadLocal 解决。"},
  {q:"ThreadPoolExecutor 任务提交流程正确的是？", level:"高级", options:["先创建到最大线程再入队列","先入队列，队列满再创建非核心线程","先创建核心线程，满了入队列，队列满创建非核心线程到最大，再满执行拒绝","直接拒绝"], answer:2, explain:"流程：核心线程未满→创建核心线程；已满→入队列；队列满→创建非核心线程到 maximumPoolSize；都满→执行拒绝策略。注意是先入队列再创建非核心线程。"},
  {q:"ThreadPoolExecutor 默认拒绝策略是？", level:"高级", options:["CallerRunsPolicy","AbortPolicy（抛异常）","DiscardPolicy","DiscardOldestPolicy"], answer:1, explain:"默认 AbortPolicy 抛出 RejectedExecutionException。CallerRunsPolicy 由提交线程执行（背压降级），DiscardPolicy 丢弃，DiscardOldestPolicy 丢最老的。"},
  {q:"Executors.newFixedThreadPool 的潜在问题是？", level:"高级", options:["线程数太少","使用无界队列 LinkedBlockingQueue，可能 OOM","拒绝策略不当","无问题"], answer:1, explain:"newFixedThreadPool 用 LinkedBlockingQueue（默认 Integer.MAX_VALUE 无界），任务积压可能导致 OOM。生产环境应显式用 ThreadPoolExecutor + 有界队列。"},
  {q:"CPU 密集型任务的线程数建议设为？", level:"高级", options:["N×2","N+1（N=CPU核数）","N×10","越多越好"], answer:1, explain:"CPU 密集型线程数设为 N+1（N=CPU核数），多出的1个用于在偶发阻塞（如缺页中断）时保持 CPU 利用率。过多线程反而增加切换开销。"},
  {q:"CPU 飙高排查时 jstack 输出中线程 TID 需要？", level:"高级", options:["直接查找","转十六进制后 grep 匹配 nid","转八进制","不需要转换"], answer:1, explain:"jstack 中线程 nid 是十六进制，top -Hp 得到的 TID 是十进制，需 printf '%x\\n' 转十六进制后 grep 匹配定位线程。"},
  {q:"OOM 排查应开启的 JVM 参数是？", level:"高级", options:["-Xmx","-XX:+HeapDumpOnOutOfMemoryError","-verbose:gc","-XX:+UseG1GC"], answer:1, explain:"-XX:+HeapDumpOnOutOfMemoryError 在 OOM 时自动 dump 堆到 -XX:HeapDumpPath 指定路径，便于用 MAT 等工具分析大对象和泄漏。"},
  {q:"GC overhead limit exceeded 表示？", level:"高级", options:["堆内存不足","GC 耗时超 98% 但回收不足 2%，连续多次","GC 停顿太长","Full GC 太多"], answer:1, explain:"GC overhead limit exceeded：GC 占用超过 98% CPU 时间但回收不到 2% 堆，连续发生时抛出，说明堆几乎满且 GC 无法有效回收。"},
  {q:"Spring Bean 生命周期中 AOP 代理创建的时机是？", level:"高级", options:["实例化时","BeanPostProcessor.postProcessAfterInitialization","初始化后","销毁前"], answer:1, explain:"AOP 代理在 BeanPostProcessor 的 postProcessAfterInitialization 阶段创建，此时 Bean 已完成初始化，AnnotationAwareAspectJAutoProxyCreator 匹配切点后生成代理。"},
  {q:"Spring 三级缓存解决循环依赖，存的是？", level:"高级", options:["完整 Bean / 半成品 Bean / ObjectFactory","三个完整 Bean","三个 Map","无意义"], answer:0, explain:"一级 singletonObjects 存完整 Bean，二级 earlySingletonObjects 存早期半成品，三级 singletonFactories 存 ObjectFactory（可生成代理），三级缓存是为了处理 AOP 代理的循环依赖。"},
  {q:"构造器注入的循环依赖能否被 Spring 解决？", level:"高级", options:["能","不能，启动报错","能但需配置","视情况"], answer:1, explain:"构造器循环依赖无法解决，因为实例化阶段就需要依赖，而此时还未放入缓存。只能解决 setter/字段注入的单例循环依赖。"},
  {q:"@Transactional 事务失效的常见原因不包括？", level:"高级", options:["自调用（this.method 不走代理）","方法非 public","异常被 catch 未抛出","使用 @Autowired"], answer:3, explain:"事务失效原因：自调用不走代理、非 public 方法、异常被吞、回滚异常类型不匹配、传播行为不当等。@Autowired 是正常依赖注入不影响事务。"},
  {q:"Spring AOP 默认代理方式（有接口时）是？", level:"高级", options:["CGLIB","JDK 动态代理（基于接口）","ASM 字节码","无代理"], answer:1, explain:"Spring 默认：目标类有接口时用 JDK 动态代理（基于接口），无接口时用 CGLIB（基于继承）。Spring Boot 2.x+ 默认用 CGLIB。"},
  {q:"Spring Boot 自动配置的加载机制是？", level:"高级", options:["扫描注解","读取 spring.factories / imports 文件中的类列表并按 @Conditional 过滤","反射","配置文件"], answer:1, explain:"@EnableAutoConfiguration 通过 AutoConfigurationImportSelector 读取 META-INF/spring.factories（2.7+ 用 AutoConfiguration.imports），加载自动配置类列表，再经 @Conditional 条件过滤决定是否生效。"},
  {q:"@ConditionalOnMissingBean 的作用是？", level:"高级", options:["容器无此 Bean 才创建默认配置","容器有此 Bean 才创建","缺少 Bean 报错","删除 Bean"], answer:0, explain:"@ConditionalOnMissingBean 表示容器中不存在该类型 Bean 时才创建，允许用户自定义 Bean 覆盖 Spring Boot 的默认自动配置，实现可扩展性。"}
]
