// === SQL EXT2 ===
sql_ext2_topics: [
  {
    id: "sql-dialects",
    title: "SQL 标准与各数据库方言差异",
    level: "进阶",
    content: "**SQL 标准**\n- ANSI SQL / ISO/IEC 9075\n- SQL-86 / SQL-89 / SQL-92 / SQL:1999 / SQL:2003 / SQL:2008 / SQL:2011 / SQL:2016 / SQL:2023\n- 各数据库遵循标准程度不同，均有扩展\n\n**各数据库方言差异**\n\n| 功能 | MySQL | PostgreSQL | Oracle | SQL Server |\n|------|-------|------------|--------|------------|\n| 字符串拼接 | CONCAT() | \\|\\| 或 CONCAT | \\|\\| | + |\n| 分页 | LIMIT n OFFSET m | LIMIT/OFFSET | ROWNUM/OFFSET FETCH | OFFSET FETCH |\n| 自增 | AUTO_INCREMENT | SERIAL/IDENTITY | SEQUENCE | IDENTITY |\n| 字符串引号 | ' 或 \" | ' | ' | ' |\n| 标识符引号 | ` | \" | \" | [] |\n| 布尔类型 | 无(用TINYINT) | BOOLEAN | 无(用NUMBER) | BIT |\n| 日期函数 | NOW()/CURDATE() | NOW()/CURRENT_DATE | SYSDATE | GETDATE() |\n| IF函数 | IF() | 无(用CASE) | 无(用CASE) | IIF() |\n| LIMIT限制 | LIMIT | LIMIT | FETCH FIRST | TOP |\n\n**数据类型差异**\n- 自增主键：MySQL AUTO_INCREMENT / PG SERIAL / Oracle SEQUENCE.nextval\n- 大文本：MySQL TEXT / PG TEXT / Oracle CLOB / SQL Server VARCHAR(MAX)\n- 二进制：MySQL BLOB / PG BYTEA / Oracle BLOB / SQL Server VARBINARY(MAX)\n- 时间戳：MySQL DATETIME/TIMESTAMP / PG TIMESTAMP / Oracle DATE/TIMESTAMP\n\n**函数差异**\n- 取子串：SUBSTRING(s, pos, len) 标准，MySQL 也用 SUBSTR\n- 日期差：MySQL DATEDIFF / PG 减法 / Oracle - / SQL Server DATEDIFF\n- 空值替换：COALESCE（标准）/ IFNULL(MySQL) / NVL(Oracle) / ISNULL(SQL Server)\n- 类型转换：CAST（标准）/ CONVERT\n\n**分页写法对比**\n- MySQL: `SELECT * FROM t LIMIT 10 OFFSET 20`\n- PostgreSQL: `SELECT * FROM t LIMIT 10 OFFSET 20`\n- Oracle 12c+: `SELECT * FROM t OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY`\n- SQL Server: `SELECT * FROM t ORDER BY id OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY`\n\n**可移植性建议**\n- 优先用 ANSI SQL 标准语法\n- 用 COALESCE 替代 IFNULL/NVL\n- 用 CAST 替代数据库特有转换\n- 用 || 或 CONCAT 拼接（注意 MySQL 默认 || 是 OR）\n- 用 LIMIT/OFFSET 或 FETCH（取决于支持）\n- 避免 MySQL 的反引号，用双引号（标准）",
    example: "-- 分页（标准 SQL:2008 FETCH）\nSELECT id, name FROM users\nORDER BY id\nOFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY;\n-- MySQL/PostgreSQL 也支持:\n-- SELECT id, name FROM users ORDER BY id LIMIT 10 OFFSET 20;\n\n-- 空值替换（标准 COALESCE）\nSELECT COALESCE(nickname, name, 'anonymous') AS display_name FROM users;\n-- MySQL: IFNULL(nickname, name)\n-- Oracle: NVL(nickname, name)\n\n-- 字符串拼接\nSELECT first_name || ' ' || last_name AS full_name FROM users;\n-- PostgreSQL/Oracle/SQLite 支持 ||\n-- MySQL 需启用 ANSI_QUOTES 模式或用 CONCAT(first_name,' ',last_name)\n-- SQL Server 用 first_name + ' ' + last_name\n\n-- 日期差（标准做法用 EXTRACT 计算）\n-- MySQL: DATEDIFF(d1, d2) 返回天数\nSELECT DATEDIFF('2024-12-31', '2024-01-01');  -- 365\n-- PostgreSQL: 直接相减\n-- SELECT '2024-12-31'::date - '2024-01-01'::date;\n-- SQL Server: DATEDIFF(day, '2024-01-01', '2024-12-31')\n\n-- 类型转换（标准 CAST）\nSELECT CAST('123' AS INTEGER);\nSELECT CAST(price AS DECIMAL(10,2));\n-- MySQL 也可用 CONVERT('123', SIGNED)\n\n-- 条件表达式（标准 CASE）\nSELECT name,\n  CASE\n    WHEN score >= 90 THEN 'A'\n    WHEN score >= 80 THEN 'B'\n    WHEN score >= 60 THEN 'C'\n    ELSE 'F'\n  END AS grade\nFROM students;\n-- MySQL 也可用 IF(score>=90,'A',...)\n-- SQL Server 也可用 IIF(score>=90,'A',...)\n\n-- 自增主键各数据库\n-- MySQL:\nCREATE TABLE t (id INT AUTO_INCREMENT PRIMARY KEY);\n-- PostgreSQL:\n-- CREATE TABLE t (id SERIAL PRIMARY KEY);\n-- Oracle:\n-- CREATE TABLE t (id NUMBER PRIMARY KEY);\n-- CREATE SEQUENCE t_seq;\n-- INSERT INTO t VALUES(t_seq.nextval);\n-- SQL Server:\n-- CREATE TABLE t (id INT IDENTITY(1,1) PRIMARY KEY);"
  },
  {
    id: "sql-merge-upsert",
    title: "MERGE 语句与 UPSERT",
    level: "进阶",
    content: "**UPSERT 概念**\n- UPDATE or INSERT\n- 存在则更新，不存在则插入\n- 避免先 SELECT 判断再 INSERT/UPDATE 的竞态\n- 原子操作，并发安全\n\n**各数据库 UPSERT 语法**\n\n**MySQL: ON DUPLICATE KEY UPDATE**\n```sql\nINSERT INTO t(id, name, val) VALUES(1,'a',10)\nON DUPLICATE KEY UPDATE val=VALUES(val), name=VALUES(name);\n```\n- 基于唯一键/主键冲突判断\n- VALUES(col) 引用 INSERT 的值\n- MySQL 8.0.19+ 可用 INSERT ... AS new ON DUPLICATE KEY UPDATE val=new.val\n\n**MySQL: REPLACE INTO**\n```sql\nREPLACE INTO t(id, name, val) VALUES(1,'a',10);\n```\n- 冲突时先 DELETE 再 INSERT\n- 会改变自增ID、触发器、外键级联\n- 不推荐（副作用大）\n\n**PostgreSQL: ON CONFLICT**\n```sql\nINSERT INTO t(id, name, val) VALUES(1,'a',10)\nON CONFLICT (id) DO UPDATE SET val=EXCLUDED.val, name=EXCLUDED.name;\n```\n- ON CONFLICT (列) 指定冲突列\n- DO NOTHING 或 DO UPDATE\n- EXCLUDED 引用 INSERT 的值\n\n**Oracle: MERGE**\n```sql\nMERGE INTO t USING (SELECT 1 AS id, 'a' AS name, 10 AS val FROM dual) src\nON (t.id = src.id)\nWHEN MATCHED THEN UPDATE SET t.val = src.val\nWHEN NOT MATCHED THEN INSERT (id, name, val) VALUES (src.id, src.name, src.val);\n```\n\n**SQL Server: MERGE**\n```sql\nMERGE INTO t USING (VALUES(1,'a',10)) AS src(id,name,val)\nON (t.id = src.id)\nWHEN MATCHED THEN UPDATE SET t.val = src.val\nWHEN NOT MATCHED THEN INSERT (id,name,val) VALUES(src.id,src.name,src.val);\n```\n\n**SQL:2003 标准 MERGE**\n- MERGE INTO target USING source ON condition\n- WHEN MATCHED THEN UPDATE/DELETE\n- WHEN NOT MATCHED THEN INSERT\n- Oracle/SQL Server 支持标准 MERGE\n- MySQL 不支持 MERGE（用 ON DUPLICATE KEY UPDATE）\n\n**批量 UPSERT**\n- INSERT INTO t VALUES (...),(...),(...) ON DUPLICATE KEY UPDATE ...\n- 批量高效同步数据\n\n**应用场景**\n- 数据同步（ETL 增量更新）\n- 缓存回写\n- 幂等写入\n- 计数器更新",
    example: "-- MySQL UPSERT\n-- 方式1: ON DUPLICATE KEY UPDATE（推荐）\nINSERT INTO user_stats(user_id, login_count, last_login)\nVALUES(100, 1, NOW())\nON DUPLICATE KEY UPDATE\n  login_count = login_count + 1,\n  last_login = NOW();\n-- 基于主键 user_id 冲突判断\n\n-- MySQL 8.0+ 用别名引用\nINSERT INTO user_stats(user_id, login_count)\nVALUES(100, 1) AS new\nON DUPLICATE KEY UPDATE\n  login_count = user_stats.login_count + new.login_count;\n\n-- 方式2: REPLACE INTO（不推荐，有副作用）\n-- REPLACE INTO user_stats VALUES(100, 1, NOW());\n-- 冲突时 DELETE + INSERT，自增ID变化，触发器异常\n\n-- 批量 UPSERT\nINSERT INTO products(id, name, price, stock)\nVALUES\n  (1, 'A', 10.0, 100),\n  (2, 'B', 20.0, 200),\n  (3, 'C', 30.0, 300)\nON DUPLICATE KEY UPDATE\n  price = VALUES(price),\n  stock = VALUES(stock);\n\n-- PostgreSQL UPSERT\n'''\nINSERT INTO user_stats(user_id, login_count, last_login)\nVALUES(100, 1, NOW())\nON CONFLICT (user_id) DO UPDATE\n  SET login_count = user_stats.login_count + 1,\n      last_login = NOW();\n-- ON CONFLICT DO NOTHING 表示冲突就忽略\n'''\n\n-- Oracle / SQL Server MERGE\n'''\nMERGE INTO user_stats t\nUSING (SELECT 100 AS user_id, 1 AS login_count, SYSDATE AS last_login FROM dual) src\nON (t.user_id = src.user_id)\nWHEN MATCHED THEN\n  UPDATE SET t.login_count = t.login_count + 1, t.last_login = src.last_login\nWHEN NOT MATCHED THEN\n  INSERT (user_id, login_count, last_login) VALUES (src.user_id, src.login_count, src.last_login);\n'''\n\n-- 计数器场景：浏览量累加\nINSERT INTO page_views(page_id, view_count, view_date)\nVALUES(1, 1, CURDATE())\nON DUPLICATE KEY UPDATE\n  view_count = view_count + 1;\n-- 每次访问原子累加，无需先查再判断\n\n-- 幂等写入：消息去重\nINSERT INTO processed_msgs(msg_id, processed_at)\nVALUES('msg-001', NOW())\nON DUPLICATE KEY UPDATE msg_id = msg_id;\n-- 唯一键冲突则什么都不做（利用 UPDATE 无变化）\n-- MySQL 8.0+: ON DUPLICATE KEY UPDATE msg_id = msg_id\n-- 或 PostgreSQL: ON CONFLICT DO NOTHING"
  },
  {
    id: "sql-materialized-view",
    title: "物化视图与查询优化",
    level: "高级",
    content: "**普通视图（View）**\n- 虚拟表，只存定义不存数据\n- 每次查询展开为底层 SQL\n- 不提升性能（除非优化器合并）\n- 作用：简化查询、权限控制、抽象\n\n**物化视图（Materialized View）**\n- 实际存储查询结果\n- 查询直接读结果，极快\n- 需要维护（数据可能过期）\n- 适合报表、聚合、昂贵计算\n\n**物化视图支持**\n- Oracle：原生支持 CREATE MATERIALIZED VIEW\n- PostgreSQL：CREATE MATERIALIZED VIEW + REFRESH\n- SQL Server：索引视图（WITH SCHEMABINDING）\n- MySQL：不原生支持，可用表 + 定时任务模拟\n\n**刷新策略**\n1. **ON DEMAND**：手动 REFRESH\n2. **ON COMMIT**：基表提交时自动刷新（Oracle）\n3. **定时刷新**：定时任务 REFRESH\n4. **增量刷新**：FAST REFRESH 只更新变化部分（需物化视图日志）\n\n**PostgreSQL 物化视图**\n```sql\nCREATE MATERIALIZED VIEW mv_sales_summary AS\nSELECT product_id, SUM(qty) AS total_qty, SUM(amount) AS total_amt\nFROM sales GROUP BY product_id;\n\nREFRESH MATERIALIZED VIEW mv_sales_summary;\nREFRESH MATERIALIZED VIEW CONCURRENTLY mv_sales_summary;  -- 不锁（需唯一索引）\n```\n\n**MySQL 模拟物化视图**\n- 创建汇总表\n- 触发器维护（INSERT/UPDATE/DELETE 同步）\n- 或定时任务（事件调度器/定时脚本）\n\n**查询改写（Query Rewrite）**\n- Oracle 支持自动查询改写：用户查原表，优化器自动用物化视图\n- PostgreSQL 需手动查物化视图\n- SQL Server 索引视图自动匹配\n\n**适用场景**\n- 报表聚合（日/月/年汇总）\n- 昂贵 JOIN 预计算\n- 数据仓库星型模型\n- 实时性要求不高的统计\n\n**权衡**\n- 空间换时间\n- 数据延迟 vs 查询速度\n- 维护成本（刷新开销）",
    example: "-- PostgreSQL 物化视图\nCREATE MATERIALIZED VIEW mv_daily_sales AS\nSELECT\n  DATE(created_at) AS sale_date,\n  product_id,\n  COUNT(*) AS order_count,\n  SUM(qty) AS total_qty,\n  SUM(amount) AS total_amount\nFROM sales\nGROUP BY DATE(created_at), product_id\nWITH DATA;  -- WITH DATA 立即填充，WITH NO DATA 延迟填充\n\n-- 创建唯一索引（支持 CONCURRENTLY 刷新）\nCREATE UNIQUE INDEX idx_mv_daily ON mv_daily_sales(sale_date, product_id);\n\n-- 手动刷新（完全重建，锁表）\nREFRESH MATERIALIZED VIEW mv_daily_sales;\n\n-- 并发刷新（不阻塞查询，需唯一索引）\nREFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_sales;\n\n-- 查询（直接读结果，极快）\nSELECT * FROM mv_daily_sales\nWHERE sale_date = '2024-01-15' ORDER BY total_amount DESC;\n\n-- 定时刷新（pg_cron 扩展）\n-- SELECT cron.schedule('refresh_mv', '0 * * * *',\n--   'REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_sales');\n\n-- MySQL 模拟物化视图：汇总表 + 触发器\nCREATE TABLE daily_sales_summary (\n  sale_date DATE,\n  product_id BIGINT,\n  order_count INT,\n  total_qty INT,\n  total_amount DECIMAL(12,2),\n  PRIMARY KEY (sale_date, product_id)\n);\n\n-- 触发器维护（INSERT 时累加）\nDELIMITER //\nCREATE TRIGGER trg_sales_after_insert\nAFTER INSERT ON sales\nFOR EACH ROW\nBEGIN\n  INSERT INTO daily_sales_summary(sale_date, product_id, order_count, total_qty, total_amount)\n  VALUES(DATE(NEW.created_at), NEW.product_id, 1, NEW.qty, NEW.amount)\n  ON DUPLICATE KEY UPDATE\n    order_count = order_count + 1,\n    total_qty = total_qty + NEW.qty,\n    total_amount = total_amount + NEW.amount;\nEND //\nDELIMITER ;\n\n-- 查询汇总表（快）\nSELECT * FROM daily_sales_summary\nWHERE sale_date = '2024-01-15';\n\n-- Oracle 物化视图 + 查询改写\n'''\nCREATE MATERIALIZED VIEW mv_sales\nREFRESH FAST ON COMMIT\nENABLE QUERY REWRITE  -- 允许自动改写\nAS SELECT product_id, SUM(qty) FROM sales GROUP BY product_id;\n-- 用户查 SELECT product_id, SUM(qty) FROM sales GROUP BY product_id\n-- 优化器自动改写为查 mv_sales\n'''\n\n-- SQL Server 索引视图\n'''\nCREATE VIEW dbo.v_sales WITH SCHEMABINDING AS\n  SELECT product_id, COUNT_BIG(*) AS cnt, SUM(qty) AS total\n  FROM dbo.sales GROUP BY product_id;\nGO\nCREATE UNIQUE CLUSTERED INDEX idx_v_sales ON dbo.v_sales(product_id);\n-- 查询原表时优化器可能自动使用索引视图\n'''"
  },
  {
    id: "sql-injection-defense",
    title: "SQL 注入防御深度",
    level: "进阶",
    content: "**SQL 注入原理**\n- 用户输入被拼接到 SQL 中执行\n- 攻击者构造恶意输入篡改 SQL 语义\n- 可导致数据泄露/篡改/删除/提权\n\n**注入类型**\n1. **联合查询注入（UNION）**：UNION SELECT 读取其他表\n2. **布尔盲注**：根据页面返回真假推断数据\n3. **时间盲注**：SLEEP/BENCHMARK 根据响应时间推断\n4. **报错注入**：利用错误信息回显数据\n5. **堆叠注入**：分号执行多条 SQL\n6. **二阶注入**：数据先存储，使用时触发\n\n**经典攻击示例**\n```\n-- 登录 SQL: SELECT * FROM users WHERE name='输入' AND pwd='输入'\n-- 输入 name: ' OR '1'='1\n-- 结果: SELECT * FROM users WHERE name='' OR '1'='1' -- 永真\n```\n\n**防御措施**\n\n1. **参数化查询（最有效）**\n   - 使用占位符 ? 或命名参数\n   - 预编译 + 参数绑定\n   - 参数作为数据而非代码执行\n   - JDBC PreparedStatement / Python 参数化 / PDO\n\n2. **ORM 框架**\n   - 默认参数化\n   - 注意原生 SQL 拼接（raw query）\n\n3. **输入验证与过滤**\n   - 白名单优于黑名单\n   - 类型/长度/格式校验\n   - 但不能依赖过滤防注入\n\n4. **最小权限原则**\n   - 应用数据库账号不给 DDL/DROP 权限\n   - 只授权必要的表和操作\n\n5. **WAF（Web 应用防火墙）**\n   - 拦截常见注入特征\n   - 补充而非替代参数化\n\n6. **转义特殊字符**\n   - 不推荐（容易遗漏、编码绕过）\n   - 参数化优先\n\n**参数化查询示例**\n- JDBC: `PreparedStatement ps = conn.prepareStatement(\"SELECT * FROM users WHERE id=?\"); ps.setInt(1, id);`\n- Python: `cursor.execute(\"SELECT * FROM users WHERE id=%s\", (id,))`\n- PHP PDO: `$stmt = $pdo->prepare(\"SELECT * FROM users WHERE id=:id\"); $stmt->execute([':id'=>$id]);`\n\n**LIKE 查询的注入**\n- LIKE 中 % 和 _ 是通配符\n- 用户输入的 % 需转义\n- `WHERE name LIKE CONCAT('%', ?, '%')` 参数化通配符内的内容\n\n**ORDER BY 注入**\n- ORDER BY 后不能参数化（是列名/SQL 标识符）\n- 用白名单校验列名\n- `if (!in_array($col, ['name','date','id'])) die();`\n\n**防御纵深**\n- 参数化 + 输入校验 + 最小权限 + WAF + 日志审计",
    example: "-- ===== 危险：字符串拼接（易注入）=====\n-- Java 错误写法\n-- String sql = \"SELECT * FROM users WHERE name='\" + name + \"'\";\n-- Statement stmt = conn.createStatement();\n-- ResultSet rs = stmt.executeQuery(sql);\n-- 攻击: name = \"' OR '1'='1\"\n-- 实际执行: SELECT * FROM users WHERE name='' OR '1'='1'\n\n-- ===== 正确：参数化查询 =====\n-- Java JDBC\n-- PreparedStatement ps = conn.prepareStatement(\n--     \"SELECT * FROM users WHERE name = ? AND status = ?\");\n-- ps.setString(1, name);\n-- ps.setInt(2, status);\n-- ResultSet rs = ps.executeQuery();\n\n-- Python (pymysql)\n-- cursor.execute(\"SELECT * FROM users WHERE name=%s AND status=%s\", (name, status))\n-- 参数作为数据绑定，不会被解释为 SQL\n\n-- PHP PDO\n-- $stmt = $pdo->prepare(\"SELECT * FROM users WHERE name = :name\");\n-- $stmt->execute([':name' => $name]);\n\n-- LIKE 查询参数化\n-- 错误: \"WHERE name LIKE '%\" + keyword + \"%'\"\n-- 正确: \"WHERE name LIKE CONCAT('%', ?, '%')\"\n-- PreparedStatement: ps.setString(1, keyword);\n-- 注意: 用户输入的 % 仍会作为通配符\n-- 如需转义: ESCAPE 子句\nSELECT * FROM users WHERE name LIKE CONCAT('%', ?, '%') ESCAPE '\\\\';\n-- 应用层先把输入中的 % _ \\\\ 转义为 \\\\% \\\\_ \\\\\\\\\n\n-- ORDER BY 白名单校验\n-- 错误: \"ORDER BY \" + sortField  (可注入)\n-- 正确: 白名单\n'''\n// Java\nSet<String> allowed = Set.of(\"name\", \"created_at\", \"id\");\nif (!allowed.contains(sortField)) {\n    throw new IllegalArgumentException(\"invalid sort field\");\n}\nString sql = \"SELECT * FROM users ORDER BY \" + sortField + \" \" +\n    (\"DESC\".equalsIgnoreCase(dir) ? \"DESC\" : \"ASC\");\n'''\n\n-- IN 子句参数化\n-- 错误: \"WHERE id IN (\" + ids + \")\"\n-- 正确: 动态构建占位符\n-- String placeholders = String.join(\",\", Collections.nCopies(ids.size(), \"?\"));\n-- String sql = \"SELECT * FROM users WHERE id IN (\" + placeholders + \")\";\n-- for (int i = 0; i < ids.size(); i++) ps.setInt(i+1, ids.get(i));\n\n-- 最小权限：应用账号不给危险权限\n-- CREATE USER 'app'@'%' IDENTIFIED BY 'pwd';\n-- GRANT SELECT, INSERT, UPDATE, DELETE ON mydb.* TO 'app'@'%';\n-- 不授予 DROP, ALTER, CREATE, FILE, SUPER 等\n\n-- 检测注入：慢查询日志/审计日志\n-- 异常 SQL 如 SLEEP(5)、UNION SELECT、information_schema 查询"
  },
  {
    id: "sql-data-types",
    title: "数据类型选择最佳实践",
    level: "进阶",
    content: "**选择原则**\n1. 够用即可：最小够用类型\n2. 避免 NULL：用 NOT NULL DEFAULT\n3. 整数优于字符串\n4. 定长优于变长（某些场景）\n5. DECIMAL 存金额\n6. 合适字符集\n\n**整数类型**\n| 类型 | 字节 | 范围(有符号) | 范围(无符号) |\n|------|------|-------------|-------------|\n| TINYINT | 1 | -128~127 | 0~255 |\n| SMALLINT | 2 | -32768~32767 | 0~65535 |\n| MEDIUMINT | 3 | ±838万 | 0~1677万 |\n| INT | 4 | ±21亿 | 0~42亿 |\n| BIGINT | 8 | ±922亿亿 | 0~1844亿亿 |\n\n- 优先用 UNSIGNED（如状态、计数）\n- 主键推荐 BIGINT UNSIGNED\n- 布尔用 TINYINT(1)（MySQL 无 BOOLEAN）\n\n**字符串类型**\n| 类型 | 说明 |\n|------|------|\n| CHAR(n) | 定长，n字符，补空格，0-255 |\n| VARCHAR(n) | 变长，n字符，0-65535 |\n| TEXT | 大文本，无默认值 |\n| MEDIUMTEXT | 16MB |\n| LONGTEXT | 4GB |\n\n- CHAR vs VARCHAR：定长存储/查询快但费空间；变长省空间\n- VARCHAR(n) 的 n 是字符数不是字节（utf8mb4 一字符最多4字节）\n- VARCHAR 需 1-2 字节记录长度\n- 短固定长度用 CHAR（如状态码 CHAR(2)）\n- 变长用 VARCHAR\n- 大文本用 TEXT（但注意 TEXT 不能有默认值且影响行格式）\n\n**字符集**\n- utf8mb4：支持完整 Unicode（含 emoji），推荐\n- utf8（MySQL）：3字节，不支持 emoji，已弃用\n- utf8mb4_general_ci：校对速度快但不精确\n- utf8mb4_unicode_ci：基于 Unicode 规则，更精确\n- utf8mb4_0900_ai_ci（8.0默认）：Unicode 9.0\n\n**时间类型**\n| 类型 | 字节 | 范围 |\n|------|------|------|\n| DATE | 3 | 1000-9999年 |\n| TIME | 3 | ±838小时 |\n| DATETIME | 8 | 1000-9999年 |\n| TIMESTAMP | 4 | 1970-2038年 |\n\n- DATETIME：不受时区影响，范围大\n- TIMESTAMP：自动时区转换，范围小（2038问题），4字节省空间\n- 存创建时间用 DATETIME 或 TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n- 存金额、精确时间用 DECIMAL 或 BIGINT(毫秒)\n\n**DECIMAL 类型**\n- DECIMAL(p, s)：p 总位数(1-65)，s 小数位(0-30)\n- DECIMAL(10,2)：存金额，最大 99999999.99\n- 精确计算，不丢精度\n- FLOAT/DOUBLE 浮点不精确，禁止存金额\n\n**枚举类型**\n- MySQL ENUM('a','b','c')：存索引（1字节）\n- 省空间，但修改枚举值需 ALTER\n- PostgreSQL 有原生 ENUM\n- 也可用 TINYINT + 应用层映射（更灵活）\n\n**JSON 类型**\n- MySQL 5.7+ / PostgreSQL 原生支持\n- 适合半结构化数据\n- 可建函数索引\n- 不适合频繁更新的字段\n\n**BLOB 类型**\n- 二进制大对象\n- 不建议在数据库存大文件（用对象存储 + 路径）\n- 影响表性能",
    example: "-- 整数类型选择\nCREATE TABLE example (\n  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,\n  status TINYINT UNSIGNED NOT NULL DEFAULT 0,  -- 0-255 足够\n  age TINYINT UNSIGNED,  -- 0-255\n  view_count INT UNSIGNED DEFAULT 0,  -- 0-42亿\n  user_count BIGINT UNSIGNED  -- 超大计数\n);\n\n-- 字符串选择\nCREATE TABLE products (\n  id BIGINT PRIMARY KEY,\n  sku CHAR(10) NOT NULL,        -- 固定长度编码\n  name VARCHAR(100) NOT NULL,   -- 变长名称\n  description TEXT,             -- 长文本\n  specs JSON                    -- 半结构化规格\n);\n\n-- 字符集设置（推荐 utf8mb4）\nCREATE DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\nCREATE TABLE t (\n  name VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n);\n-- utf8mb4 一字符最多4字节，VARCHAR(50) 最多占 200+2 字节\n\n-- 时间类型\nCREATE TABLE orders (\n  id BIGINT PRIMARY KEY,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,  -- 创建时间\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  expire_at TIMESTAMP NULL  -- 可为空的时间戳\n);\n-- TIMESTAMP 范围到 2038 年，超出用 DATETIME\n\n-- 金额用 DECIMAL\nCREATE TABLE transactions (\n  id BIGINT PRIMARY KEY,\n  amount DECIMAL(18,2) NOT NULL,  -- 精确金额\n  rate DECIMAL(8,6) DEFAULT 0.000000  -- 汇率6位小数\n);\n-- 错误: amount FLOAT  (浮点不精确，0.1+0.2 != 0.3)\n\n-- 布尔值\nCREATE TABLE users (\n  is_active TINYINT(1) DEFAULT 1,  -- MySQL 用 TINYINT 模拟\n  is_admin BOOLEAN DEFAULT FALSE   -- BOOLEAN 是 TINYINT(1) 别名\n);\n\n-- 枚举\nCREATE TABLE tickets (\n  priority ENUM('low','medium','high','urgent') DEFAULT 'medium',\n  -- ENUM 存索引省空间，但加值需 ALTER\n  -- 替代: priority TINYINT + 应用层映射\n  status TINYINT COMMENT '0=new 1=open 2=closed'\n);\n\n-- NOT NULL 原则\nCREATE TABLE t (\n  name VARCHAR(50) NOT NULL DEFAULT '',  -- 避免 NULL\n  age INT NOT NULL DEFAULT 0,\n  nickname VARCHAR(50)  -- 允许 NULL 的才不设\n);\n-- NULL 占空间且影响索引、查询需 IS NULL 判断、聚合忽略\n\n-- 查看 utf8mb4 字节数\nSELECT CHAR_LENGTH('你好'), LENGTH('你好');\n-- utf8mb4: CHAR_LENGTH=2, LENGTH=6 (每中文3字节)\n-- emoji: LENGTH('😀')=4\n\n-- 检查表字符集\nSELECT TABLE_NAME, TABLE_COLLATION\nFROM information_schema.TABLES\nWHERE TABLE_SCHEMA='mydb';"
  },
  {
    id: "sql-tree-query",
    title: "树形结构查询方案",
    level: "高级",
    content: "**树形结构存储模型**\n1. **邻接表（Adjacency List）**：parent_id 指向父节点\n2. **路径枚举（Path Enumeration）**：存完整路径如 /1/4/7/\n3. **嵌套集（Nested Set）**：left/right 值表示区间\n4. **闭包表（Closure Table）**：单独表存所有祖先-后代关系\n\n**邻接表（最常用）**\n```sql\nCREATE TABLE categories (\n  id INT PRIMARY KEY,\n  name VARCHAR(50),\n  parent_id INT,\n  FOREIGN KEY (parent_id) REFERENCES categories(id)\n);\n```\n- 优点：简单、修改容易\n- 缺点：查子树需多次查询或递归\n\n**递归 CTE 查询子树（SQL标准 / MySQL 8.0+ / PG / Oracle）**\n```sql\nWITH RECURSIVE subtree AS (\n  SELECT id, name, parent_id, 0 AS depth\n  FROM categories WHERE id = 1  -- 起点\n  UNION ALL\n  SELECT c.id, c.name, c.parent_id, s.depth+1\n  FROM categories c JOIN subtree s ON c.parent_id = s.id\n)\nSELECT * FROM subtree ORDER BY depth;\n```\n\n**查祖先链**\n```sql\nWITH RECURSIVE ancestors AS (\n  SELECT id, name, parent_id FROM categories WHERE id = 7\n  UNION ALL\n  SELECT c.id, c.name, c.parent_id\n  FROM categories c JOIN ancestors a ON c.id = a.parent_id\n)\nSELECT * FROM ancestors;\n```\n\n**路径枚举**\n- path 字段存 /1/4/7/\n- 查子树：WHERE path LIKE '/1/%'\n- 查祖先：path 分割\n- 优点：查询简单\n- 缺点：路径更新麻烦、长度限制\n\n**嵌套集**\n- 每节点有 lft 和 rgt\n- 子节点 lft/rgt 在父节点区间内\n- 查子树：WHERE lft BETWEEN parent.lft AND parent.rgt\n- 优点：查子树快\n- 缺点：插入/移动需更新大量节点\n\n**闭包表**\n- 单独表 closure(ancestor, descendant, depth)\n- 存所有祖先-后代对\n- 查子树：SELECT descendant FROM closure WHERE ancestor=1\n- 查祖先：SELECT ancestor FROM closure WHERE descendant=7\n- 优点：查询极快\n- 缺点：空间开销大（O(n²)）\n\n**方案选择**\n- 层级浅、更新多：邻接表 + 递归 CTE\n- 查子树频繁：闭包表\n- 树稳定少变：嵌套集\n- 简单场景：路径枚举",
    example: "-- 邻接表 + 递归 CTE（MySQL 8.0+）\nCREATE TABLE org (\n  id INT PRIMARY KEY,\n  name VARCHAR(50),\n  parent_id INT\n);\nINSERT INTO org VALUES\n  (1,'CEO',NULL),(2,'CTO',1),(3,'CFO',1),\n  (4,'研发总监',2),(5,'前端经理',4),(6,'后端经理',4),\n  (7,'财务经理',3);\n\n-- 查询某节点的所有子孙（向下）\nWITH RECURSIVE subtree AS (\n  SELECT id, name, parent_id, 0 AS depth, CAST(name AS CHAR(500)) AS path\n  FROM org WHERE id = 2  -- CTO 子树\n  UNION ALL\n  SELECT c.id, c.name, c.parent_id, s.depth+1,\n         CONCAT(s.path, ' > ', c.name)\n  FROM org c JOIN subtree s ON c.parent_id = s.id\n)\nSELECT id, name, depth, path FROM subtree ORDER BY depth, id;\n-- 结果:\n-- 2  研发总监  0  CTO\n-- 4  研发总监  1  CTO > 研发总监\n-- 5  前端经理  2  CTO > 研发总监 > 前端经理\n-- 6  后端经理  2  CTO > 研发总监 > 后端经理\n\n-- 查询某节点的所有祖先（向上）\nWITH RECURSIVE ancestors AS (\n  SELECT id, name, parent_id FROM org WHERE id = 6\n  UNION ALL\n  SELECT o.id, o.name, o.parent_id\n  FROM org o JOIN ancestors a ON o.id = a.parent_id\n)\nSELECT * FROM ancestors;\n-- 后端经理 -> 研发总监 -> CTO -> CEO\n\n-- 闭包表\nCREATE TABLE org_closure (\n  ancestor INT,\n  descendant INT,\n  depth INT,\n  PRIMARY KEY (ancestor, descendant)\n);\n-- 插入节点 6(后端经理) 时，同时插入:\n-- (6,6,0) 自身\n-- (4,6,1) 父->子\n-- (2,6,2) 祖父->孙\n-- (1,6,3) 曾祖->曾孙\n\n-- 查 2 的所有后代\nSELECT descendant, depth FROM org_closure\nWHERE ancestor = 2 ORDER BY depth;\n\n-- 查 6 的所有祖先\nSELECT ancestor, depth FROM org_closure\nWHERE descendant = 6 ORDER BY depth DESC;\n\n-- 路径枚举\nCREATE TABLE org_path (\n  id INT PRIMARY KEY,\n  name VARCHAR(50),\n  path VARCHAR(500)  -- 如 /1/2/4/6/\n);\n-- 查 2 的子树\nSELECT * FROM org_path WHERE path LIKE '/1/2/%';\n-- 查 6 的祖先（分割 path）\n\n-- 嵌套集\nCREATE TABLE org_nested (\n  id INT PRIMARY KEY, name VARCHAR(50),\n  lft INT, rgt INT\n);\n-- CEO: lft=1, rgt=14\n-- CTO: lft=2, rgt=7\n-- 研发总监: lft=3, rgt=6\n-- 前端经理: lft=4, rgt=5\n-- 查 CTO 子树\nSELECT * FROM org_nested\nWHERE lft BETWEEN 2 AND 7 ORDER BY lft;\n-- 查节点深度（计算外层区间数）"
  },
  {
    id: "sql-timeseries",
    title: "时间序列数据处理",
    level: "高级",
    content: "**时间序列场景**\n- 监控指标（CPU/内存/QPS）\n- 日志数据\n- 股票行情\n- IoT 传感器数据\n- 订单流水\n\n**时间序列表设计**\n- 时间分区（按天/月）\n- 时间列索引\n- 老数据归档（DROP PARTITION）\n\n**常用时间函数**\n- DATE_FORMAT(date, fmt)：格式化\n- DATE_ADD/DATE_SUB：加减时间\n- DATEDIFF/TIMESTAMPDIFF：差值\n- EXTRACT(unit FROM date)：提取部分\n- UNIX_TIMESTAMP/FROM_UNIXTIME：时间戳转换\n\n**按时间聚合**\n- 按小时/天/周/月统计\n- GROUP BY DATE_FORMAT(created_at, '%Y-%m-%d')\n- GROUP BY DATE(created_at)\n\n**填补空时间段**\n- 时间序列可能有缺失点\n- 用日历表或递归 CTE 生成连续时间\n- LEFT JOIN 填补空值为 0\n\n**同比环比**\n- 同比：与去年同期对比\n- 环比：与上一期对比\n- 用 LAG 窗口函数或 JOIN 自身偏移\n\n**移动平均**\n- AVG() OVER(ORDER BY time ROWS BETWEEN N PRECEDING AND CURRENT ROW)\n\n**累计求和**\n- SUM() OVER(ORDER BY time)\n\n**采样与降采样**\n- 高频数据降为低频（1分钟→1小时）\n- GROUP BY 时间桶 + 聚合\n\n**时序数据库对比**\n- TimescaleDB（PostgreSQL 扩展）：SQL 兼容\n- InfluxDB：专用时序数据库\n- ClickHouse：列式分析\n- MySQL：通用，大数据量性能不如专用时序库",
    example: "-- 按小时统计\nSELECT\n  DATE_FORMAT(created_at, '%Y-%m-%d %H:00') AS hour,\n  COUNT(*) AS cnt,\n  AVG(value) AS avg_val\nFROM metrics\nWHERE created_at >= '2024-01-01'\nGROUP BY DATE_FORMAT(created_at, '%Y-%m-%d %H:00')\nORDER BY hour;\n\n-- 按天统计\nSELECT DATE(created_at) AS day, COUNT(*) AS cnt\nFROM orders\nGROUP BY DATE(created_at)\nORDER BY day;\n\n-- 填补空时间段（生成连续小时序列）\n-- MySQL 8.0 递归 CTE 生成时间序列\nWITH RECURSIVE hours AS (\n  SELECT '2024-01-01 00:00:00' AS h\n  UNION ALL\n  SELECT h + INTERVAL 1 HOUR FROM hours WHERE h < '2024-01-01 23:00:00'\n)\nSELECT\n  DATE_FORMAT(h.h, '%Y-%m-%d %H:00') AS hour,\n  COALESCE(COUNT(m.id), 0) AS cnt\nFROM hours h\nLEFT JOIN metrics m\n  ON DATE_FORMAT(m.created_at, '%Y-%m-%d %H:00') = DATE_FORMAT(h.h, '%Y-%m-%d %H:00')\nGROUP BY h.h\nORDER BY h.h;\n\n-- 移动平均（3小时窗口）\nSELECT\n  created_at,\n  value,\n  AVG(value) OVER (\n    ORDER BY created_at\n    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW\n  ) AS moving_avg\nFROM metrics\nORDER BY created_at;\n\n-- 累计求和\nSELECT\n  DATE(created_at) AS day,\n  SUM(amount) AS daily_amount,\n  SUM(SUM(amount)) OVER (ORDER BY DATE(created_at)) AS cumulative\nFROM orders\nGROUP BY DATE(created_at)\nORDER BY day;\n\n-- 同比环比（用 LAG）\nSELECT\n  DATE_FORMAT(created_at, '%Y-%m') AS month,\n  SUM(amount) AS total,\n  LAG(SUM(amount), 1) OVER (ORDER BY DATE_FORMAT(created_at,'%Y-%m')) AS prev_month,  -- 环比\n  LAG(SUM(amount), 12) OVER (ORDER BY DATE_FORMAT(created_at,'%Y-%m')) AS prev_year   -- 同比\nFROM orders\nGROUP BY DATE_FORMAT(created_at, '%Y-%m')\nORDER BY month;\n\n-- 环比增长率\nWITH monthly AS (\n  SELECT DATE_FORMAT(created_at,'%Y-%m') AS m, SUM(amount) AS total\n  FROM orders GROUP BY DATE_FORMAT(created_at,'%Y-%m')\n)\nSELECT m, total,\n  LAG(total,1) OVER (ORDER BY m) AS prev,\n  ROUND((total - LAG(total,1) OVER (ORDER BY m)) /\n        LAG(total,1) OVER (ORDER BY m) * 100, 2) AS growth_rate_pct\nFROM monthly;\n\n-- 降采样：1分钟数据聚合为1小时\nSELECT\n  DATE_FORMAT(created_at, '%Y-%m-%d %H:00') AS hour,\n  AVG(value) AS avg_val,\n  MAX(value) AS max_val,\n  MIN(value) AS min_val\nFROM metrics_1min\nWHERE created_at >= '2024-01-01'\nGROUP BY DATE_FORMAT(created_at, '%Y-%m-%d %H:00');\n\n-- 时间分区表（按月，便于归档）\nCREATE TABLE metrics (\n  id BIGINT AUTO_INCREMENT,\n  created_at DATETIME NOT NULL,\n  value DOUBLE,\n  PRIMARY KEY (id, created_at)\n) PARTITION BY RANGE (TO_DAYS(created_at)) (\n  PARTITION p202401 VALUES LESS THAN (TO_DAYS('2024-02-01')),\n  PARTITION p202402 VALUES LESS THAN (TO_DAYS('2024-03-01')),\n  PARTITION pmax VALUES LESS THAN MAXVALUE\n);\n-- 清理历史: ALTER TABLE metrics DROP PARTITION p202401;  -- 瞬间完成"
  },
  {
    id: "sql-dedup-cleanup",
    title: "数据去重与清洗 SQL",
    level: "进阶",
    content: "**常见去重场景**\n- 完全重复行\n- 业务键重复（如同用户多条记录）\n- 近似重复（大小写/空格差异）\n\n**查找重复**\n```sql\n-- 找重复的键\nSELECT email, COUNT(*) AS cnt\nFROM users\nGROUP BY email\nHAVING COUNT(*) > 1;\n```\n\n**删除重复保留一条**\n\n**方法1：ROW_NUMBER（推荐，8.0+）**\n```sql\nDELETE FROM users\nWHERE id NOT IN (\n  SELECT id FROM (\n    SELECT id, ROW_NUMBER() OVER(PARTITION BY email ORDER BY id) AS rn\n    FROM users\n  ) t WHERE rn = 1\n);\n```\n\n**方法2：GROUP BY + MIN(id)**\n```sql\nDELETE FROM users\nWHERE id NOT IN (\n  SELECT MIN(id) FROM users GROUP BY email\n);\n```\n\n**方法3：自连接**\n```sql\nDELETE u1 FROM users u1\nJOIN users u2 ON u1.email = u2.email AND u1.id > u2.id;\n-- 保留 id 最小的\n```\n\n**方法4：临时表**\n- 创建临时表存去重结果\n- TRUNCATE 原表\n- 插回\n- 适合大量重复\n\n**DISTINCT vs GROUP BY**\n- DISTINCT：去重显示\n- GROUP BY：去重 + 聚合\n- 性能相近\n\n**数据清洗**\n- 去除空格：TRIM/LTRIM/RTRIM\n- 大小写统一：UPPER/LOWER\n- NULL 处理：COALESCE/IFNULL\n- 异常值过滤：WHERE 条件\n- 类型转换：CAST\n\n**字符串清洗**\n- TRIM(name)：去首尾空格\n- REPLACE(name, '  ', ' ')：多个空格变一个\n- REGEXP_REPLACE：正则替换\n\n**数据校验**\n- 邮箱格式：REGEXP\n- 手机号长度\n- 日期有效性\n\n**批量更新清洗**\n- UPDATE ... SET name = TRIM(name) WHERE name != TRIM(name)\n- 分批避免大事务",
    example: "-- 查找重复\nSELECT email, COUNT(*) AS cnt, GROUP_CONCAT(id) AS dup_ids\nFROM users\nGROUP BY email\nHAVING COUNT(*) > 1;\n\n-- 删除重复保留 id 最小（ROW_NUMBER 方式，推荐）\n-- MySQL 8.0+\nWITH dups AS (\n  SELECT id,\n    ROW_NUMBER() OVER(PARTITION BY email ORDER BY id) AS rn\n  FROM users\n)\nDELETE FROM users\nWHERE id IN (SELECT id FROM dups WHERE rn > 1);\n\n-- 方法2：自连接（保留最小 id）\nDELETE u1 FROM users u1\nINNER JOIN users u2\n  ON u1.email = u2.email AND u1.id > u2.id;\n\n-- 方法3：临时表（适合大量重复）\nCREATE TABLE users_dedup AS\nSELECT * FROM users WHERE id IN (\n  SELECT MIN(id) FROM users GROUP BY email\n);\nTRUNCATE TABLE users;\nINSERT INTO users SELECT * FROM users_dedup;\nDROP TABLE users_dedup;\n\n-- DISTINCT 去重显示\nSELECT DISTINCT department FROM employees ORDER BY department;\nSELECT DISTINCT city, country FROM users;\n\n-- 字符串清洗\n-- 去首尾空格\nUPDATE users SET name = TRIM(name) WHERE name != TRIM(name);\n-- 多空格变单空格\nUPDATE articles SET content = REGEXP_REPLACE(content, ' +', ' ');\n-- 统一大小写\nUPDATE users SET email = LOWER(TRIM(email));\n-- 去除不可见字符\nUPDATE users SET name = TRIM(BOTH '\\\\n' FROM name);\n\n-- NULL 处理\n-- 填充默认值\nUPDATE users SET nickname = '匿名' WHERE nickname IS NULL;\n-- 查询时替换\nSELECT COALESCE(nickname, name, 'unknown') AS display FROM users;\n\n-- 异常值过滤\nSELECT * FROM orders\nWHERE amount > 0\n  AND amount < 1000000  -- 过滤异常金额\n  AND created_at <= NOW()\n  AND user_id IS NOT NULL;\n\n-- 邮箱格式校验\nSELECT * FROM users\nWHERE email NOT REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\\\.[A-Za-z]{2,}$';\n-- 手机号校验\nSELECT * FROM users\nWHERE phone NOT REGEXP '^1[3-9][0-9]{9}$';\n\n-- 找出可能重复的近似数据（大小写/空格差异）\nSELECT LOWER(TRIM(email)) AS normalized, COUNT(*) AS cnt\nFROM users\nGROUP BY LOWER(TRIM(email))\nHAVING COUNT(*) > 1;\n\n-- 合并重复用户数据（保留主记录，合并附属信息）\n-- 把重复账号的订单转移到保留账号\nUPDATE orders SET user_id = (\n  SELECT MIN(id) FROM users u2 WHERE u2.email = (\n    SELECT email FROM users WHERE id = orders.user_id\n  )\n)\nWHERE user_id IN (\n  SELECT id FROM users WHERE id NOT IN (\n    SELECT MIN(id) FROM users GROUP BY email\n  )\n);\n-- 然后删除重复用户\n\n-- 数据采样检查\nSELECT * FROM users ORDER BY RAND() LIMIT 100;  -- 随机抽样\n-- 注意 RAND() 性能差，大表用：\nSELECT * FROM users WHERE id >= (\n  SELECT FLOOR(RAND() * (SELECT MAX(id) FROM users))\n) LIMIT 100;"
  }
],
sql_ext2_questions: [
  {q:"SQL 标准中字符串拼接运算符是？", level:"进阶", options:["+","||","CONCAT","&"], answer:1, explain:"SQL 标准用 || 拼接字符串，PostgreSQL/Oracle/SQLite 支持。MySQL 默认 || 是逻辑 OR，需启用 PIPES_AS_CONCAT 模式或用 CONCAT()。SQL Server 用 +。"},
  {q:"跨数据库通用的空值替换函数是？", level:"进阶", options:["IFNULL","NVL","COALESCE","ISNULL"], answer:2, explain:"COALESCE 是 SQL 标准，所有主流数据库支持。IFNULL 是 MySQL，NVL 是 Oracle，ISNULL 是 SQL Server。优先用 COALESCE 保证可移植性。"},
  {q:"SQL 标准的分页语法（SQL:2008）是？", level:"进阶", options:["LIMIT n OFFSET m","TOP n","ROWNUM","OFFSET ... FETCH NEXT"], answer:3, explain:"SQL:2008 标准用 OFFSET ... ROWS FETCH NEXT ... ROWS ONLY，Oracle 12c+/SQL Server 支持。MySQL/PostgreSQL 用 LIMIT/OFFSET。"},
  {q:"UPSERT 的含义是？", level:"进阶", options:["删除后插入","存在则更新不存在则插入（原子操作）","批量插入","更新所有"], answer:1, explain:"UPSERT = UPDATE or INSERT，存在则更新不存在则插入，原子操作避免先查再写的竞态，常用于幂等写入和数据同步。"},
  {q:"MySQL 实现 UPSERT 的推荐语法是？", level:"进阶", options:["REPLACE INTO","INSERT ON DUPLICATE KEY UPDATE","MERGE INTO","UPDATE OR INSERT"], answer:1, explain:"INSERT ... ON DUPLICATE KEY UPDATE 基于唯一键冲突判断，存在则更新。REPLACE INTO 是先 DELETE 再 INSERT，有副作用（自增ID变化、触发器异常），不推荐。"},
  {q:"REPLACE INTO 的副作用不包括？", level:"高级", options:["自增 ID 变化","触发器先触发 DELETE 再 INSERT","外键级联删除","查询变慢"], answer:3, explain:"REPLACE INTO 冲突时先 DELETE 再 INSERT，导致自增ID变化、DELETE/INSERT 触发器都触发、外键级联删除。查询性能不受影响。"},
  {q:"PostgreSQL 的 UPSERT 语法是？", level:"高级", options:["ON DUPLICATE KEY UPDATE","ON CONFLICT DO UPDATE","MERGE INTO","REPLACE INTO"], answer:1, explain:"PostgreSQL 用 INSERT ... ON CONFLICT (列) DO UPDATE SET ...，ON CONFLICT 指定冲突列，DO NOTHING 表示忽略冲突，EXCLUDED 引用插入值。"},
  {q:"SQL:2003 标准 MERGE 语句支持的分支是？", level:"高级", options:["INSERT/DELETE","WHEN MATCHED THEN UPDATE/DELETE 和 WHEN NOT MATCHED THEN INSERT","只有 UPDATE","只有 INSERT"], answer:1, explain:"MERGE INTO target USING source ON condition，WHEN MATCHED THEN UPDATE/DELETE（匹配则更新或删除），WHEN NOT MATCHED THEN INSERT（不匹配则插入）。Oracle/SQL Server 支持标准 MERGE。"},
  {q:"普通视图与物化视图的区别是？", level:"高级", options:["无区别","普通视图只存定义不存数据，物化视图实际存储查询结果","物化视图更快但无数据","普通视图存数据"], answer:1, explain:"普通视图是虚拟表只存 SQL 定义，每次查询展开执行；物化视图实际存储查询结果，查询极快但需维护（数据可能过期）。"},
  {q:"物化视图的刷新策略不包括？", level:"高级", options:["ON DEMAND 手动刷新","ON COMMIT 自动刷新","定时刷新","每次查询刷新"], answer:3, explain:"物化视图刷新策略：ON DEMAND 手动 REFRESH、ON COMMIT 基表提交时自动刷新、定时任务刷新、FAST 增量刷新。不会每次查询都刷新（那样就失去意义）。"},
  {q:"MySQL 原生是否支持物化视图？", level:"高级", options:["支持","不支持，需用汇总表+触发器/定时任务模拟","仅企业版支持","8.0开始支持"], answer:1, explain:"MySQL 不原生支持物化视图，可用汇总表配合触发器（实时同步）或定时任务（延迟同步）模拟实现。PostgreSQL/Oracle/SQL Server 原生支持。"},
  {q:"Oracle 物化视图的查询改写（Query Rewrite）是指？", level:"高级", options:["改写用户SQL","用户查原表，优化器自动改写为查物化视图","自动创建视图","优化SQL语法"], answer:1, explain:"启用 QUERY REWRITE 后，用户查询原表时优化器自动判断能否用物化视图替代，透明加速查询，应用无需修改 SQL。"},
  {q:"防御 SQL 注入最有效的措施是？", level:"进阶", options:["过滤特殊字符","参数化查询（预编译+参数绑定）","WAF","输入校验"], answer:1, explain:"参数化查询将参数作为数据而非代码执行，从根本上杜绝注入。预编译 SQL 模板固定，参数无法改变 SQL 结构。是最有效的防御手段。"},
  {q:"以下哪种写法能防 SQL 注入？", level:"进阶", options:["拼接字符串：sql+name","使用 ? 占位符的 PreparedStatement","用 replace 替换引号","正则过滤"], answer:1, explain:"PreparedStatement 使用 ? 占位符，参数通过 setString 等方法绑定，参数值不会被解释为 SQL 代码，有效防止注入。字符串拼接则可被注入。"},
  {q:"LIKE 查询防注入的正确做法是？", level:"高级", options:["直接拼接 %keyword%","CONCAT('%', ?, '%') 参数化通配符内内容","转义引号","过滤%"], answer:1, explain:"用 CONCAT('%', ?, '%') 配合参数绑定，keyword 作为参数传入。注意用户输入的 % 仍作通配符，需 ESCAPE 子句转义用户输入的 % 和 _。"},
  {q:"ORDER BY 字段不能直接参数化的原因是？", level:"高级", options:["性能问题","ORDER BY 后是列名/标识符而非数据值，占位符只能绑定数据","语法不支持","安全限制"], answer:1, explain:"参数化查询只能绑定数据值，不能绑定列名/表名等 SQL 标识符。ORDER BY 后是列名，需用白名单校验后拼接，不能用 ? 占位符。"},
  {q:"最小权限原则防御注入指的是？", level:"进阶", options:["用户权限最小","应用数据库账号只授必要权限，不给 DROP/ALTER/FILE 等","只读","单用户"], answer:1, explain:"应用数据库账号应遵循最小权限，只授 SELECT/INSERT/UPDATE/DELETE，不给 DDL(DROP/ALTER/CREATE) 和 FILE/SUPER 等高危权限，即使被注入也限制破坏范围。"},
  {q:"MySQL 存金额应使用的数据类型是？", level:"进阶", options:["FLOAT","DOUBLE","DECIMAL","VARCHAR"], answer:2, explain:"金额必须用 DECIMAL 精确存储，FLOAT/DOUBLE 是浮点数有精度损失（0.1+0.2≠0.3）。DECIMAL(18,2) 可精确到分。"},
  {q:"MySQL 推荐使用的字符集是？", level:"基础", options:["utf8（3字节）","utf8mb4（4字节支持emoji）","latin1","gbk"], answer:1, explain:"utf8mb4 支持完整 Unicode 含 emoji（4字节），MySQL 的 utf8 是 3 字节子集不支持 emoji 已弃用。MySQL 8.0 默认 utf8mb4。"},
  {q:"DATETIME 与 TIMESTAMP 的区别是？", level:"进阶", options:["无区别","TIMESTAMP 自动时区转换但范围到2038年，DATETIME不受时区影响范围大","DATETIME更小","TIMESTAMP更慢"], answer:1, explain:"TIMESTAMP(4字节) 存 UTC 自动时区转换，但范围只到2038年；DATETIME(8字节) 不受时区影响范围到9999年。跨时区用 TIMESTAMP，历史日期用 DATETIME。"},
  {q:"VARCHAR(50) 在 utf8mb4 下最多占多少字节？", level:"进阶", options:["50","100","200","202"], answer:3, explain:"utf8mb4 一字符最多4字节，VARCHAR(50) 最多 50×4=200 字节，加上1-2字节长度记录，共约 202 字节。n 是字符数不是字节数。"},
  {q:"为什么建议字段设为 NOT NULL？", level:"进阶", options:["节省查询时间","NULL 占空间、影响索引、查询需 IS NULL、聚合忽略 NULL","NOT NULL 更快插入","无区别"], answer:1, explain:"NULL 值额外占空间（bitmap），影响索引效率，查询需用 IS NULL 判断，COUNT/AVG 等聚合忽略 NULL。建议 NOT NULL DEFAULT 默认值。"},
  {q:"树形结构查询子树的推荐方案（MySQL 8.0+）是？", level:"高级", options:["多次查询","递归 CTE（WITH RECURSIVE）","自连接","存储过程"], answer:1, explain:"MySQL 8.0+ 支持递归 CTE，用 WITH RECURSIVE 从起点出发递归查询所有子孙，一次查询完成，是邻接表模型的最佳查询方案。"},
  {q:"闭包表（Closure Table）存储的是？", level:"高级", options:["节点信息","所有祖先-后代对及深度","路径字符串","左右值"], answer:1, explain:"闭包表单独存储每个节点到所有祖先和后代的关系对(ancestor, descendant, depth)，查询子树或祖先极快（单次查询），但空间开销大 O(n²)。"},
  {q:"嵌套集模型查询子树的方式是？", level:"高级", options:["WHERE parent_id","递归","WHERE lft BETWEEN parent.lft AND parent.rgt","路径LIKE"], answer:2, explain:"嵌套集每个节点有 lft/rgt 区间，子节点的 lft/rgt 在父节点区间内。查子树用 WHERE lft BETWEEN parent.lft AND parent.rgt，一次查询但插入/移动需更新大量节点。"},
  {q:"时间序列数据填补空时间段的技巧是？", level:"高级", options:["忽略空值","生成连续时间序列(递归CTE/日历表)再 LEFT JOIN","用0填充","UNION"], answer:1, explain:"时间序列可能有缺失点，用递归 CTE 或日历表生成连续时间段，再 LEFT JOIN 数据表，缺失的用 COALESCE 填 0，保证时间轴完整。"},
  {q:"计算环比增长率正确的 SQL 是？", level:"高级", options:["用子查询","用 LAG 窗口函数获取上一期值再计算","用 JOIN","用 UNION"], answer:1, explain:"LAG(total,1) OVER(ORDER BY month) 获取上一期的值，然后 (total - LAG值)/LAG值*100 计算环比增长率，窗口函数一次扫描完成。"},
  {q:"移动平均的窗口函数写法是？", level:"高级", options:["AVG OVER()","AVG() OVER(ORDER BY time ROWS BETWEEN N PRECEDING AND CURRENT ROW)","SUM/M","AVG GROUP BY"], answer:1, explain:"移动平均用 AVG(value) OVER(ORDER BY time ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) 计算当前及前2行的平均，实现3点移动平均。"},
  {q:"删除重复行保留 id 最小的推荐方法是？", level:"进阶", options:["DELETE 一行行删","ROW_NUMBER 窗口函数标记后删除 rn>1 的","TRUNCATE","用 DISTINCT 删除"], answer:1, explain:"用 ROW_NUMBER() OVER(PARTITION BY 业务键 ORDER BY id) 给每组编号，删除 rn>1 的行，保留 rn=1（id最小）的，高效且准确。"},
  {q:"DISTINCT 和 GROUP BY 去重的区别是？", level:"进阶", options:["DISTINCT 更快","GROUP BY 更快","功能相近，GROUP BY 还可配合聚合函数","DISTINCT 去重所有列"], answer:2, explain:"DISTINCT 和 GROUP BY 去重性能相近。GROUP BY 更灵活，可配合聚合函数（COUNT/SUM），DISTINCT 只去重显示。优化器可能将 DISTINCT 优化为 GROUP BY。"},
  {q:"字符串清洗去除首尾空格的函数是？", level:"基础", options:["REPLACE","TRIM","LOWER","SUBSTRING"], answer:1, explain:"TRIM 去首尾空格，LTRIM/RTRIM 去左/右空格。UPDATE users SET name=TRIM(name) 可批量清洗数据。"},
  {q:"时间序列表通常采用什么分区方式便于归档？", level:"高级", options:["HASH 分区","LIST 分区","RANGE 按时间分区","不分区"], answer:2, explain:"时间序列表按时间 RANGE 分区（如按月），清理历史数据时 DROP PARTITION 瞬间完成（比 DELETE 快得多），且查询可分区裁剪加速。"}
]
