// === MYSQL EXT2 ===
mysql_ext2_topics: [
  {
    id: "mysql-repl-delay",
    title: "主从延迟排查与优化",
    level: "高级",
    content: "**主从延迟表现**\n- Seconds_Behind_Master 持续增大\n- 从库数据滞后，读写分离读到旧数据\n- 业务依赖强一致性时出错\n\n**延迟原因**\n1. **从库单线程重放慢**：主库多线程写入，从库 SQL 线程串行重放\n2. **大事务**：一个事务执行很久，从库需同等时间重放\n3. **DDL 操作**：ALTER TABLE 锁表且耗时长\n4. **从库硬件差**：CPU/IO/内存不如主库\n5. **网络延迟**：主从跨机房/跨地域\n6. **从库负载高**：从库承担大量查询，影响 SQL 重放\n7. **无主键/索引**：ROW 格式 binlog 重放需全表扫描定位行\n\n**排查方法**\n- SHOW REPLICA STATUS\\G 查看 Seconds_Behind_Master\n- 关注 Slave_IO_Running / Slave_SQL_Running\n- pt-heartbeat 工具精确测量延迟（基于时间戳对比）\n- 检查从库 slow log 是否有大事务\n- 检查 Relay_Log_Space 是否积压\n\n**优化方案**\n1. **多线程复制（MTS）**\n   - MySQL 5.7+ 并行复制\n   - 基于 group commit（slave_parallel_type=LOGICAL_CLOCK）\n   - MySQL 8.0 基于 WRITESET（slave_parallel_type=LOGICAL_CLOCK + binlog_transaction_dependency_tracking=WRITESET）\n   - slave_parallel_workers 设置并发数\n\n2. **减少大事务**\n   - 拆分大事务为小批次\n   - 避免一次性 DELETE/UPDATE 大量行\n   - 分批操作：DELETE ... LIMIT 1000 循环\n\n3. **从库硬件提升**\n   - SSD、更大内存、更多 CPU\n\n4. **网络优化**\n   - 主从同机房\n   - 压缩 binlog 传输（binlog_transaction_compression）\n\n5. **确保有主键**\n   - ROW 格式 binlog 重放依赖主键定位行\n   - 无主键会导致全表扫描，极慢\n\n6. **半同步复制**\n   - 至少保证数据到达从库（但不减少重放延迟）\n\n7. **读写分离策略**\n   - 关键读走主库\n   - 容忍延迟的读走从库\n   - 强制读主库的会话标记",
    example: "-- 查看复制状态\nSHOW REPLICA STATUS\\G\n-- 关键指标:\n--   Slave_IO_Running: Yes\n--   Slave_SQL_Running: Yes\n--   Seconds_Behind_Master: 0 (理想)\n--   Relay_Log_Space: 积压大小\n\n-- 多线程复制配置（my.cnf）\n-- MySQL 8.0 基于 WRITESET 的并行复制\n'''\n[mysqld]\nslave_parallel_type = LOGICAL_CLOCK\nslave_parallel_workers = 8\nbinlog_transaction_dependency_tracking = WRITESET\nbinlog_transaction_dependency_history_size = 25000\nslave_preserve_commit_order = ON\n'''\n\n-- 查看从库 worker 线程状态\nSELECT * FROM performance_schema.replication_applier_status_by_worker;\n\n-- pt-heartbeat 精确测量延迟\n-- 主库持续写入心跳表\n-- pt-heartbeat --master --daemonize\n-- 从库检测\n-- pt-heartbeat --check --master-server-id=1\n\n-- 拆分大事务示例\n-- 错误：一次性删除百万行\n-- DELETE FROM logs WHERE created < '2024-01-01';\n\n-- 正确：分批删除\n-- DELIMITER //\n-- CREATE PROCEDURE batch_delete()\n-- BEGIN\n--   DECLARE done INT DEFAULT 0;\n--   REPEAT\n--     DELETE FROM logs WHERE created < '2024-01-01' LIMIT 1000;\n--     SET done = ROW_COUNT();\n--     COMMIT;\n--   UNTIL done = 0 END REPEAT;\n-- END //\n-- DELIMITER ;\n\n-- 检查无主键的表\nSELECT TABLE_SCHEMA, TABLE_NAME\nFROM information_schema.TABLES t\nWHERE t.TABLE_TYPE = 'BASE TABLE'\n  AND NOT EXISTS (\n    SELECT 1 FROM information_schema.KEY_COLUMN_USAGE k\n    WHERE k.TABLE_SCHEMA = t.TABLE_SCHEMA\n      AND k.TABLE_NAME = t.TABLE_NAME\n  );\n\n-- 强制读主库（应用层）\n-- 关键业务读操作走主库连接\n-- 或使用 hint: /*MASTER*/ SELECT ..."
  },
  {
    id: "mysql-online-ddl",
    title: "大表 DDL 与在线变更",
    level: "高级",
    content: "**传统 DDL 的问题**\n- ALTER TABLE 可能锁表、重建全表\n- 大表 DDL 耗时数小时甚至数天\n- 阻塞业务读写\n- 主从延迟暴增\n\n**MySQL Online DDL（5.6+）**\n- INPLACE 算法：引擎内部修改，不复制全表\n- COPY 算法：创建临时表复制数据（锁表）\n- INSTANT 算法（8.0.12+）：只改元数据，瞬间完成\n- ALGORITHM/NLOCK/LOCK 控制\n\n**各操作的 Online 程度**\n- 加列（默认最后）：8.0 INSTANT，秒级\n- 加索引：INPLACE，允许 DML 但耗时\n- 修改列类型：通常 COPY，锁表\n- 删除列：INPLACE，耗时\n- 修改字符集：COPY，锁表\n- 重命名列：INSTANT（8.0+不改类型）\n- 加主键：INPLACE 但耗时\n\n**ALGORITHM 与 LOCK**\n- ALGORITHM=INSTANT：优先尝试，秒级\n- ALGORITHM=INPLACE, LOCK=NONE：不锁表，允许 DML\n- ALGORITHM=COPY, LOCK=SHARED：允许读不允许写\n- ALGORITHM=COPY, LOCK=EXCLUSIVE：完全锁表\n\n**大表变更工具**\n1. **gh-ost（GitHub 开源）**\n   - 基于 binlog 同步，无触发器\n   - 创建影子表 → 拷贝数据 → 用 binlog 增量同步 → 切换\n   - 可暂停、可回滚、限流\n   - 不影响主库负载（触发器会）\n\n2. **pt-online-schema-change（Percona Toolkit）**\n   - 基于触发器同步增量\n   - 创建影子表 → 拷贝 → 触发器同步 → rename\n   - 成熟稳定但触发器有性能影响\n\n3. **原生 INSTANT DDL（8.0.12+）**\n   - 加列、重命名列等秒级完成\n   - 不复制数据、不锁表\n   - 局限：仅部分操作支持\n\n**变更最佳实践**\n- 低峰期执行\n- 先在测试环境验证\n- 使用 ALGORITHM=INSTANT 优先\n- 大表用 gh-ost/pt-osc\n- 关注 binlog 大小和主从延迟\n- 设置超时和限流\n\n**Instant DDL 限制**\n- 只支持加列到末尾、删列（8.0.29+）等\n- 修改列类型不支持\n- 加索引不支持",
    example: "-- Online DDL 语法\n-- 优先 INSTANT，失败再 INPLACE\nALTER TABLE orders ADD COLUMN remark VARCHAR(100),\n  ALGORITHM=INSTANT, LOCK=NONE;\n\n-- INSTANT 不支持时用 INPLACE\nALTER TABLE orders ADD INDEX idx_user(user_id),\n  ALGORITHM=INPLACE, LOCK=NONE;\n\n-- 查看 DDL 是否支持 INSTANT\n-- MySQL 8.0: ALTER ... ALGORITHM=INSTANT 直接报错说明不支持\n\n-- gh-ost 在线加列（不锁表、无触发器）\n# gh-ost \\\n#   --host=master.db \\\n#   --user=root --password=xxx \\\n#   --database=mydb --table=orders \\\n#   --alter=\"ADD COLUMN status INT\" \\\n#   --execute\n\n# gh-ost 暂停/恢复\n# echo throttle | nc -U /tmp/gh-ost.sock\n# echo no-throttle | nc -U /tmp/gh-ost.sock\n\n# pt-online-schema-change 在线加索引\n# pt-online-schema-change \\\n#   --alter=\"ADD INDEX idx_created(created_at)\" \\\n#   D=mydb,t=orders \\\n#   --execute\n\n-- 检查 DDL 进度（8.0）\nSELECT * FROM performance_schema.events_stages_current\nWHERE EVENT_NAME LIKE 'stage/innodb/alter%';\n\n-- 查看表的 Instant DDL 历史记录\nSELECT * FROM information_schema.INNODB_TABLES\nWHERE NAME = 'mydb/orders';\n\n-- 大表分批加索引（避免长事务）\n-- 某些场景可先在影子库加索引再切换\n\n-- 扩展 VARCHAR 长度（8.0 INPLACE）\nALTER TABLE users MODIFY name VARCHAR(200),\n  ALGORITHM=INPLACE, LOCK=NONE;\n-- 注意：缩短长度需要 COPY（可能截断数据）\n\n-- 修改列类型（通常锁表）\nALTER TABLE orders MODIFY amount BIGINT,\n  ALGORITHM=COPY, LOCK=SHARED;  -- 允许读不允许写\n-- 生产环境大表建议用 gh-ost"
  },
  {
    id: "mysql-slow-governance",
    title: "慢查询治理方法论",
    level: "高级",
    content: "**慢查询治理流程**\n1. **采集**：开启 slow_query_log\n2. **分析**：mysqldumpslow / pt-query-digest\n3. **定位**：EXPLAIN 分析执行计划\n4. **优化**：加索引/改写 SQL/调参数\n5. **验证**：对比优化前后性能\n6. **监控**：持续跟踪防止回退\n\n**慢查询日志配置**\n- slow_query_log = ON\n- long_query_time = 1（阈值秒数）\n- log_queries_not_using_indexes = ON（记录未走索引的查询）\n- min_examined_row_limit（忽略扫描行数少的）\n\n**pt-query-digest 分析**\n- 按指纹（fingerprint）聚合相似 SQL\n- 统计：次数、总耗时、平均耗时、扫描行数\n- 按总耗时/次数/单次耗时排序\n- 重点关注：耗时占比高、扫描行数多、次数频繁\n\n**慢查询分类与对策**\n1. **未走索引**\n   - 原因：无索引、索引失效、隐式转换\n   - 对策：建索引、避免函数操作列、注意类型匹配\n\n2. **索引不合理**\n   - 索引选择度低（如状态字段）\n   - 联合索引顺序不当\n   - 对策：调整索引设计\n\n3. **返回数据量大**\n   - SELECT * 查全部字段\n   - 无分页\n   - 对策：只查需要的列、加分页\n\n4. **JOIN 低效**\n   - 驱动表选择不当\n   - JOIN 字段无索引\n   - 对策：小表驱动大表、JOIN 字段建索引\n\n5. **锁等待**\n   - 长事务持锁\n   - 对策：缩短事务、避免长事务\n\n6. **临时表/文件排序**\n   - Using temporary / Using filesort\n   - 对策：优化 ORDER BY/GROUP BY 走索引\n\n**SQL 审核机制**\n- 上线前 EXPLAIN 审核\n- 自动化审核工具（如 Yearning、Archery）\n- 禁止全表扫描的查询上线\n\n**监控指标**\n- 慢查询数量趋势\n- 平均查询响应时间\n- TOP N 慢 SQL",
    example: "-- 开启慢查询日志\nSET GLOBAL slow_query_log = ON;\nSET GLOBAL long_query_time = 1;\nSET GLOBAL log_queries_not_using_indexes = ON;\nSHOW VARIABLES LIKE 'slow_query_log_file';\n\n-- pt-query-digest 分析慢日志\n-- pt-query-digest /var/lib/mysql/slow.log > report.txt\n-- 输出示例:\n-- Rank  Query ID      Calls  R/Call   V/M\n-- ====  ============  =====  ======   ===\n--    1  0xABC123...      42  3.5000   0.5  <- 重点优化\n--    2  0xDEF456...     120  0.8000   0.1\n\n-- 按指纹聚合后查看具体 SQL\nSELECT * FROM mysql.slow_log ORDER BY start_time DESC LIMIT 10;\n\n-- EXPLAIN 分析\nEXPLAIN SELECT * FROM orders\nWHERE user_id = 100 AND status = 1\nORDER BY created_at DESC LIMIT 20;\n-- 关注:\n--   type: ALL(全表) -> ref/range(走索引)\n--   rows: 扫描行数\n--   Extra: Using filesort(需优化) / Using index(好)\n\n-- 优化案例1：未走索引\n-- 优化前: SELECT * FROM orders WHERE DATE(created_at)='2024-01-01';\n-- 函数导致索引失效！\n-- 优化后: SELECT * FROM orders\n--   WHERE created_at >= '2024-01-01' AND created_at < '2024-01-02';\n\n-- 优化案例2：分页深翻\n-- 优化前: SELECT * FROM orders ORDER BY id DESC LIMIT 1000000,10;\n-- 优化后(延迟关联):\nSELECT a.* FROM orders a\nINNER JOIN (\n  SELECT id FROM orders ORDER BY id DESC LIMIT 1000000,10\n) b ON a.id = b.id;\n-- 或游标分页: WHERE id < #{last_id} ORDER BY id DESC LIMIT 10\n\n-- 优化案例3：避免 SELECT *\nSELECT id, title, amount FROM orders WHERE user_id=100;\n-- 而非 SELECT *（多查无用列，无法覆盖索引）\n\n-- 优化案例4：JOIN 加索引\n-- 被驱动表 JOIN 字段必须建索引\nALTER TABLE orders ADD INDEX idx_user_id(user_id);\n-- 小表驱动大表：users(小) JOIN orders(大)\n\n-- performance_schema 监控（8.0）\nSELECT DIGEST_TEXT, COUNT_STAR, AVG_TIMER_WAIT/1000000000 AS avg_ms\nFROM performance_schema.events_statements_summary_by_digest\nORDER BY AVG_TIMER_WAIT DESC LIMIT 10;"
  },
  {
    id: "mysql-deadlock-analysis",
    title: "死锁分析与预防",
    level: "高级",
    content: "**死锁产生条件**\n- 两个或多个事务互相持有对方需要的锁\n- 互相等待，形成循环依赖\n- InnoDB 自动检测死锁并回滚代价较小的事务\n\n**常见死锁场景**\n1. **交叉更新**\n   - 事务A：UPDATE t SET... WHERE id=1 → UPDATE t WHERE id=2\n   - 事务B：UPDATE t SET... WHERE id=2 → UPDATE t WHERE id=1\n2. **间隙锁冲突**（RR 隔离级别）\n   - 事务A范围查询加间隙锁\n   - 事务B插入到间隙中被阻塞\n3. **唯一索引冲突**\n   - 两个事务同时 INSERT 相同唯一键\n4. **外键检查**\n5. **不同加锁顺序**\n\n**死锁排查**\n- SHOW ENGINE INNODB STATUS\\G 查看 LATEST DETECTED DEADLOCK\n- 记录两个事务的 SQL 和持有的锁\n- 开启 innodb_print_all_deadlocks 记录所有死锁到错误日志\n- performance_schema 可查锁信息\n\n**死锁日志解读**\n- TRANSACTION 1：持有锁、等待锁\n- TRANSACTION 2：持有锁、等待锁\n- 标记 ROLLING BACK 的事务是被回滚的（victim）\n- 关注 HOLDS THE LOCK(S) 和 WAITING FOR LOCK\n\n**预防死锁**\n1. **固定加锁顺序**\n   - 多表/多行更新时，所有事务按相同顺序加锁\n   - 如按主键升序更新\n\n2. **缩短事务**\n   - 事务越小持锁时间越短\n   - 避免事务中包含耗时操作（如 RPC 调用）\n\n3. **降低隔离级别**\n   - RR 改 RC，减少间隙锁\n   - 但需评估业务对一致性的要求\n\n4. **合理使用索引**\n   - 无索引会锁更多行（甚至锁表）\n   - 走索引只锁匹配行\n\n5. **批量操作分批**\n   - 大批量更新拆分为小批次\n\n6. **重试机制**\n   - 捕获 DeadlockLoserDetector 异常重试\n   - 但需找到根因而非仅重试\n\n**innodb_deadlock_detect**\n- 默认开启，自动检测死锁\n- 高并发下检测本身消耗 CPU\n- 可关闭改用 innodb_lock_wait_timeout 超时回滚\n- 但关闭后死锁会一直等到超时",
    example: "-- 查看最近死锁\nSHOW ENGINE INNODB STATUS\\G\n-- 找到 LATEST DETECTED DEADLOCK 段\n-- 示例日志:\n-- *** (1) TRANSACTION:\n-- UPDATE account SET balance=balance-100 WHERE id=1\n-- *** (1) HOLDS THE LOCK(S):  记录id=1的X锁\n-- *** (1) WAITING FOR THIS LOCK TO BE GRANTED: 记录id=2的X锁\n-- *** (2) TRANSACTION:\n-- UPDATE account SET balance=balance+100 WHERE id=2\n-- *** (2) HOLDS THE LOCK(S): 记录id=2的X锁\n-- *** (2) WAITING FOR THIS LOCK TO BE GRANTED: 记录id=1的X锁\n-- *** WE ROLL BACK TRANSACTION (2)  <- 事务2被回滚\n\n-- 开启所有死锁记录\nSET GLOBAL innodb_print_all_deadlocks = ON;\n-- 之后查看错误日志\n\n-- MySQL 8.0 查看锁\nSELECT * FROM performance_schema.data_locks;\nSELECT * FROM performance_schema.data_lock_waits;\n\n-- 预防：固定加锁顺序\n-- 错误：事务间加锁顺序不一致\n-- 事务A: UPDATE t WHERE id=1; UPDATE t WHERE id=2;\n-- 事务B: UPDATE t WHERE id=2; UPDATE t WHERE id=1;\n-- 正确：统一按 id 升序\n-- 事务A: UPDATE t WHERE id=1; UPDATE t WHERE id=2;\n-- 事务B: UPDATE t WHERE id=1; UPDATE t WHERE id=2;\n\n-- 应用层重试（Java 示例）\n'''\n@Retryable(value = DeadlockLoserDataAccessException.class, maxAttempts = 3)\n@Transactional\npublic void transfer(Long from, Long to, BigDecimal amount) {\n    // 按 id 排序加锁\n    Long first = Math.min(from, to);\n    Long second = Math.max(from, to);\n    accountDao.lockById(first);\n    accountDao.lockById(second);\n    accountDao.deduct(from, amount);\n    accountDao.add(to, amount);\n}\n'''\n\n-- 间隙锁死锁场景（RR）\n-- 表有 id: 1, 5, 10\n-- 事务A: SELECT * FROM t WHERE id BETWEEN 3 AND 7 FOR UPDATE;\n--   加间隙锁 (1,5) (5,10)\n-- 事务B: INSERT INTO t VALUES(4);\n--   阻塞（在间隙 (1,5) 中插入）\n-- 如果事务B也持有其他间隙锁且事务A要插入该间隙 -> 死锁\n-- 预防：改 RC 隔离级别减少间隙锁\n\n-- 查看锁等待超时\nSHOW VARIABLES LIKE 'innodb_lock_wait_timeout';  -- 默认50秒\n\n-- 高并发场景关闭死锁检测（谨慎）\n-- SET GLOBAL innodb_deadlock_detect = OFF;\n-- 改用超时回滚: SET GLOBAL innodb_lock_wait_timeout = 5;"
  },
  {
    id: "mysql-new-features",
    title: "MySQL 8.0/9.0 新特性",
    level: "高级",
    content: "**MySQL 8.0 核心新特性**\n1. **默认引擎 InnoDB**，移除 Query Cache\n2. **自增主键持久化**：重启不再重置（5.7 重启可能重置）\n3. **隐藏列（Invisible Index）**：索引可设为不可见，验证删除影响\n4. **降序索引**：真正支持 DESC 索引（5.7 只是语法兼容）\n5. **函数索引**：可对表达式建索引\n6. **CTE（公用表表达式）**：WITH 子句，递归查询\n7. **窗口函数**：ROW_NUMBER/RANK/LAG/LEAD 等\n8. **JSON 增强**：JSON_TABLE、部分更新\n9. **角色（Role）**：角色管理权限\n10. **原子 DDL**：DDL 操作原子化（崩溃不残留）\n11. **不可见列**：对 SELECT * 隐藏\n12. **SKIP LOCKED / NOWAIT**：跳过锁定的行\n13. **直方图统计**：优化器更准确\n\n**复制与高可用**\n- MGR（Group Replication）增强\n- 基于 WRITESET 的并行复制\n- 事件追踪增强\n\n**JSON 增强**\n- JSON_TABLE：JSON 转关系表\n- JSON_PRETTY / JSON_STORAGE_SIZE\n- 部分更新（JSON_SET 增量）\n\n**MySQL 8.0 性能提升**\n- 直方图让优化器更智能\n- WRITESET 并行复制\n- Instant DDL（8.0.12+）\n- 资源组（Resource Group）控制线程优先级\n\n**MySQL 9.0（2024）新特性**\n- **JavaScript 存储函数**（企业版）：用 JS 写存储过程\n- **向量类型 VECTOR**：AI 场景存储向量数据\n- **EXPLAIN INTO**：保存执行计划\n- **INSERT...RETURNING**：插入返回数据\n- 优化器改进\n- 注意：9.0 是 Innovation 版本，非 LTS，生产建议 8.0 LTS\n\n**MySQL 版本策略**\n- 8.0 LTS（长期支持）\n- 9.0+ Innovation（创新版，快速迭代）\n- 生产环境优先 LTS 版本\n\n**升级注意事项**\n- 5.7 → 8.0 需 mysql_upgrade（8.0.16 后自动）\n- 字符集默认 utf8mb4（5.7 是 latin1）\n- 检查 SQL 兼容性（如保留字变化）\n- 复制兼容性：低版本不能作为高版本的从库",
    example: "-- 1. 不可见索引（验证删除影响）\nALTER TABLE orders ALTER INDEX idx_user INVISIBLE;\n-- 观察查询性能是否受影响\n-- 如果没问题再删除：\nALTER TABLE orders DROP INDEX idx_user;\n-- 恢复：ALTER INDEX idx_user VISIBLE;\n\n-- 2. 降序索引（8.0 真正生效）\nCREATE INDEX idx_time ON orders(created_at DESC, user_id ASC);\n-- 8.0 会按降序存储，加速 ORDER BY created_at DESC\n\n-- 3. 函数索引\nCREATE INDEX idx_lower_email ON users((LOWER(email)));\nSELECT * FROM users WHERE LOWER(email) = 'alice@test.com';  -- 走索引\n\n-- 4. CTE 递归查询\nWITH RECURSIVE org_tree AS (\n  SELECT id, name, parent_id, 1 AS level\n  FROM departments WHERE parent_id IS NULL\n  UNION ALL\n  SELECT d.id, d.name, d.parent_id, t.level+1\n  FROM departments d JOIN org_tree t ON d.parent_id = t.id\n)\nSELECT * FROM org_tree;\n\n-- 5. 窗口函数\nSELECT user_id, created_at, amount,\n  ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY created_at DESC) AS rn,\n  LAG(amount) OVER(PARTITION BY user_id ORDER BY created_at) AS prev_amount\nFROM orders;\n\n-- 6. JSON_TABLE\nSELECT * FROM JSON_TABLE('[{\"name\":\"Alice\",\"age\":25},{\"name\":\"Bob\",\"age\":30}]',\n  '$[*]' COLUMNS (\n    name VARCHAR(50) PATH '$.name',\n    age INT PATH '$.age'\n  )\n) AS jt;\n\n-- 7. SKIP LOCKED（跳过锁定的行，适合任务队列）\nSELECT * FROM task_queue WHERE status='pending'\n  ORDER BY id LIMIT 10 FOR UPDATE SKIP LOCKED;\n-- 不阻塞，直接跳过被其他事务锁定的任务\n\n-- 8. 直方图统计\nANALYZE TABLE orders UPDATE HISTOGRAM ON status WITH 100 BUCKETS;\n-- 优化器利用直方图更准确估算行数\n\n-- 9. 角色（权限管理）\nCREATE ROLE 'app_read', 'app_write';\nGRANT SELECT ON mydb.* TO 'app_read';\nGRANT INSERT, UPDATE, DELETE ON mydb.* TO 'app_write';\nGRANT 'app_read', 'app_write' TO 'user1'@'%';\nSET DEFAULT ROLE 'app_read', 'app_write' TO 'user1'@'%';\n\n-- 10. INSERT...RETURNING（9.0+）\nINSERT INTO users(name) VALUES('Alice') RETURNING id, name;\n\n-- 11. 向量类型（9.0+）\nCREATE TABLE embeddings (id INT, vec VECTOR(4));\nINSERT INTO embeddings VALUES(1, '[1.0,2.0,3.0,4.0]');\n-- DISTANCE 函数计算向量距离（AI 场景）"
  },
  {
    id: "mysql-primary-key-design",
    title: "主键设计与 ID 生成方案",
    level: "进阶",
    content: "**主键的作用**\n- InnoDB 聚簇索引按主键组织数据\n- 主键影响数据物理存储顺序\n- 影响插入性能、索引大小、页分裂\n\n**主键选择原则**\n1. **自增（推荐）**：顺序插入，页不分裂，性能好\n2. **越小越好**：BIGINT(8) > INT(4) > UUID(16)\n3. **非空 NOT NULL**：主键不允许 NULL\n4. **不可变**：主键值不应修改（导致数据移动）\n5. **无业务含义**：避免业务变化影响主键\n\n**自增主键优势**\n- 顺序写入，避免页分裂\n- 主键索引紧凑\n- 占用空间小（INT/BIGINT）\n- 简单可靠\n\n**UUID 的问题**\n- 随机无序，导致页分裂频繁\n- 16字节，索引体积大\n- 可读性差\n- 优势：全局唯一、无需中心化\n\n**UUID 优化**\n- UUID v7/v8（时间有序）：减少页分裂\n- 把 UUID 前 8 字节时间戳反转：变有序\n- 存储 BINARY(16) 而非 CHAR(36)：省空间\n\n**雪花算法 Snowflake**\n- 64位 = 1位符号 + 41位时间戳 + 10位机器ID + 12位序列号\n- 趋势递增（时间有序）\n- 分布式唯一\n- 时钟回拨问题\n- 可存为 BIGINT\n\n**号段模式（Leaf-Segment）**\n- 数据库批量分配 ID（如每次取 1000 个）\n- 应用内存缓存号段\n- 减少数据库压力\n- 步长可配置\n\n**Redis INCR**\n- 简单，高性能\n- 依赖 Redis 可用性\n- 持久化需考虑（RDB 可能丢）\n\n**多主自增**\n- 不同实例设置不同 auto_increment_offset 和 step\n- 如两台：A 奇数 B 偶数\n- 缺点：扩容困难\n\n**分库分表 ID 方案**\n- 雪花算法（主流）\n- 号段模式\n- 数据库多主自增\n- 避免 UUID（无序导致数据倾斜）\n\n**主键与二级索引关系**\n- 二级索引叶子存储主键值\n- 主键越大，所有二级索引都变大\n- 因此主键要小",
    example: "-- 自增主键（推荐）\nCREATE TABLE orders (\n  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,\n  user_id BIGINT NOT NULL,\n  amount DECIMAL(10,2),\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  INDEX idx_user(user_id)\n) ENGINE=InnoDB;\n\n-- 无主键的后果\n-- InnoDB 会选唯一非空索引或生成隐藏 6 字节 ROWID\n-- 隐藏 ROWID 全局共享，可能导致数据竞争\n-- ROW 格式 binlog 重放极慢（无主键定位行）\n\n-- UUID 存储（如必须用）\nCREATE TABLE sessions (\n  id BINARY(16) PRIMARY KEY,  -- 用 BINARY(16) 而非 CHAR(36)\n  data TEXT\n);\n-- 插入: INSERT INTO sessions VALUES(UNHEX(REPLACE(UUID(),'-','')), '...');\n\n-- 时间有序 UUID（MySQL 8.0 UUID_TO_BIN）\n-- UUID v1 含时间戳但顺序不对\n-- UUID_TO_BIN(uuid, swap_flag) 将时间部分前置，变有序\nINSERT INTO sessions VALUES(UUID_TO_BIN(UUID(), 1), '...');\n\n-- 雪花算法生成 BIGINT（应用层）\n-- 64位: 1符号 + 41时间戳 + 10机器 + 12序列\n-- 存为 BIGINT\nCREATE TABLE distributed_data (\n  id BIGINT PRIMARY KEY,  -- 雪花算法生成\n  ...\n);\n\n-- 号段模式表结构\nCREATE TABLE id_segment (\n  biz_tag VARCHAR(64) PRIMARY KEY,\n  max_id BIGINT NOT NULL DEFAULT 1,\n  step INT NOT NULL DEFAULT 1000,\n  version INT NOT NULL DEFAULT 0\n);\n-- 业务取号: UPDATE id_segment SET max_id=max_id+step WHERE biz_tag='order';\n-- 然后取 max_id 到 max_id+step 作为本批次 ID\n\n-- 多主自增（双主防冲突）\n-- 主库A: auto_increment_offset=1, auto_increment_increment=2  (1,3,5,7...)\n-- 主库B: auto_increment_offset=2, auto_increment_increment=2  (2,4,6,8...)\n\n-- 主键越小二级索引越小\n-- BIGINT 主键: 每个二级索引叶子多存 8 字节\n-- UUID 主键: 每个二级索引叶子多存 16 字节\n-- 千万行表，10个二级索引，差距: (16-8)*10*10000000 = 800MB\n\n-- 复合主键（某些场景）\nCREATE TABLE order_items (\n  order_id BIGINT NOT NULL,\n  item_id INT NOT NULL,\n  quantity INT,\n  PRIMARY KEY (order_id, item_id)  -- 复合主键\n);\n-- 注意：二级索引会引用整个复合主键，体积更大"
  },
  {
    id: "mysql-read-write-split",
    title: "读写分离实现方案",
    level: "进阶",
    content: "**为什么要读写分离**\n- 主库承担写压力，从库分担读压力\n- 提升整体并发能力\n- 读多写少场景效果显著\n\n**实现层次**\n1. **应用层**\n   - 应用代码中手动选择数据源\n   - 写操作走主库，读操作走从库\n   - 灵活但侵入性强\n\n2. **中间件层**\n   - ShardingSphere-JDBC / Proxy\n   - MyCat\n   - ProxySQL\n   - 对应用透明\n   - SQL 自动路由\n\n3. **驱动层**\n   - MySQL Router\n   - 连接代理\n\n**ShardingSphere 读写分离**\n- 配置主库和从库列表\n- 写 SQL 路由主库\n- 读 SQL 路由从库（负载均衡）\n- 支持强制走主库（Hint）\n- 支持从库健康检查\n\n**负载均衡策略**\n- 轮询（Round Robin）\n- 随机（Random）\n- 权重（Weight）\n- 最少连接\n\n**主从延迟带来的问题**\n- 写主库后立即读从库，可能读到旧数据\n- 用户感知数据不一致\n\n**解决延迟读不一致**\n1. **强制读主库**\n   - 关键业务（如写后立即读）走主库\n   - Hint: /*MASTER*/ SELECT ...\n   - ShardingSphere: HintManager.getInstance().setMasterRouteOnly()\n\n2. **会话粘连**\n   - 写操作后在一定时间内读走主库\n   - 基于线程变量/Session 标记\n\n3. **半同步复制 + 等待**\n   - 写后等待从库同步完成再读\n   - 降低性能\n\n4. **缓存过渡**\n   - 写后先写缓存，读优先缓存\n   - 缓存过期后读从库\n\n**ShardingSphere 配置示例**\n```yaml\nrules:\n  - !READWRITE_SPLITTING\n    dataSources:\n      readwrite_ds:\n        writeDataSourceName: master_ds\n        readDataSourceNames:\n          - slave_ds_0\n          - slave_ds_1\n        transactionalReadQueryStrategy: PRIMARY\n        loadBalancerName: round_robin\n    loadBalancers:\n      round_robin:\n        type: ROUND_ROBIN\n```\n\n**ProxySQL**\n- 数据库代理，MySQL 协议\n- 自动路由读写\n- 查询规则（Query Rules）灵活配置\n- 连接池管理\n- 监控统计",
    example: "-- ProxySQL 配置读写分离\n-- 1. 添加后端服务器\n'''\nINSERT INTO mysql_servers(hostgroup_id,hostname,port)\nVALUES (0,'master.db',3306), (1,'slave1.db',3306), (1,'slave2.db',3306);\n-- hostgroup 0=写组, 1=读组\n'''\n\n-- 2. 配置路由规则\n'''\n-- SELECT 走读组\nINSERT INTO mysql_query_rules(rule_id,active,match_digest,destination_hostgroup)\nVALUES (1,1,'^SELECT.*',1);\n-- 其他走写组（默认）\n'''\n\n-- 3. 强制读主库（规则例外）\n-- SELECT /*MASTER*/ * FROM users ...\n-- INSERT INTO mysql_query_rules(rule_id,active,match_digest,destination_hostgroup)\n-- VALUES (2,1,'^SELECT.*MASTER.*',0);\n\n-- ShardingSphere-JDBC 强制主库\n'''\n// Java 代码\ntry (HintManager hint = HintManager.getInstance()) {\n    hint.setWriteRouteOnly();  // 强制走主库\n    List<User> users = userDao.selectAfterWrite();\n}\n'''\n\n-- 应用层手动选择数据源\n'''\n// Spring 多数据源\n@TargetDataSource(\"master\")\npublic void createUser(User u) { ... write ... }\n\n@TargetDataSource(\"slave\")\npublic User getUser(Long id) { ... read ... }\n\n// 写后立即读的关键操作走主库\n@TargetDataSource(\"master\")\npublic User createAndGet(User u) {\n    userMapper.insert(u);\n    return userMapper.selectById(u.getId());\n}\n'''\n\n-- 从库健康检查\n-- ShardingSphere 自动剔除不可用从库\n-- ProxySQL 定期检测\n-- SELECT * FROM mysql_servers;  查看状态\n\n-- 监控读写比例\nSELECT hostgroup, COUNT(*), SUM(duration)\nFROM stats_mysql_query_digest\nGROUP BY hostgroup;\n-- 评估读写比例是否合理，调整从库数量"
  },
  {
    id: "mysql-monitoring",
    title: "MySQL 监控与告警",
    level: "进阶",
    content: "**监控维度**\n1. **可用性**：服务是否存活、能否连接\n2. **性能**：QPS/TPS、响应时间、慢查询\n3. **资源**：CPU/内存/磁盘/IO/网络\n4. **复制**：主从状态、延迟\n5. **连接**：连接数、活跃连接、连接拒绝\n6. **锁**：锁等待、死锁\n7. **容量**：表空间、增长趋势\n\n**关键监控指标**\n- Threads_connected：当前连接数\n- Threads_running：活跃线程数\n- QPS（Questions/s）、TPS（Com_commit+Com_rollback）/s\n- Slow_queries：慢查询数\n- Innodb_rows_read/written：行读写数\n- Innodb_buffer_pool_read_requests / reads：缓冲池命中率\n- Seconds_Behind_Master：主从延迟\n- Aborted_clients/connections：异常断开\n\n**监控工具**\n1. **Prometheus + mysqld_exporter + Grafana**\n   - 业界主流方案\n   - mysqld_exporter 采集 MySQL 指标\n   - Grafana 可视化\n\n2. **Percona PMM**\n   - 基于 Prometheus 的 MySQL 监控平台\n   - 含查询分析\n\n3. **MySQL Enterprise Monitor**\n   - 官方商业产品\n\n4. **Zabbix**\n   - 传统监控方案\n\n**告警规则**\n- 连接数 > 80% max_connections\n- 慢查询数突增\n- 主从延迟 > 60s\n- 缓冲池命中率 < 95%\n- 磁盘使用率 > 80%\n- 复制中断\n- 死锁频繁\n\n**SHOW STATUS / SHOW GLOBAL STATUS**\n- 实时查看各项状态\n- SHOW STATUS LIKE 'Threads%'\n- SHOW STATUS LIKE 'Innodb%'\n\n**performance_schema**\n- MySQL 内置性能监控\n- 事件统计、锁监控、内存监控\n- sys 库提供友好视图\n\n**常用 sys 库视图**\n- sys.processlist：进程列表\n- sys.innodb_lock_waits：锁等待\n- sys.schema_index_statistics：索引使用统计\n- sys.statements_with_errors_or_warnings：错误SQL\n- sys.statements_with_full_table_scans：全表扫描SQL\n\n**日志监控**\n- error log：错误日志\n- slow query log：慢查询\n- general log：全量查询（慎用，影响性能）\n- binlog：数据变更\n\n**容量规划**\n- 监控数据增长趋势\n- 预测何时达到容量瓶颈\n- 提前规划扩容/分库分表",
    example: "-- 关键状态查询\nSHOW GLOBAL STATUS LIKE 'Threads_connected';  -- 当前连接数\nSHOW GLOBAL STATUS LIKE 'Threads_running';    -- 活跃线程\nSHOW GLOBAL STATUS LIKE 'Slow_queries';        -- 慢查询总数\nSHOW GLOBAL STATUS LIKE 'Questions';           -- 总查询数\nSHOW GLOBAL STATUS LIKE 'Uptime';              -- 运行时间\n-- QPS = Questions / Uptime\n\n-- 缓冲池命中率\nSHOW GLOBAL STATUS LIKE 'Innodb_buffer_pool_read_requests';\nSHOW GLOBAL STATUS LIKE 'Innodb_buffer_pool_reads';\n-- 命中率 = 1 - reads/read_requests\n\n-- InnoDB 行操作\nSHOW GLOBAL STATUS LIKE 'Innodb_rows%';\n-- rows_read/read, inserted, updated, deleted\n\n-- 连接相关\nSHOW GLOBAL STATUS LIKE 'Aborted%';\nSHOW GLOBAL STATUS LIKE 'Connections';\nSHOW VARIABLES LIKE 'max_connections';\nSHOW STATUS LIKE 'Max_used_connections';\n\n-- 复制状态\nSHOW REPLICA STATUS\\G\n-- 关注 Seconds_Behind_Master, Slave_IO_Running, Slave_SQL_Running\n\n-- performance_schema 锁监控\nSELECT * FROM performance_schema.data_lock_waits;\n\n-- sys 库友好视图\n-- 谁在等待锁\nSELECT * FROM sys.innodb_lock_waits;\n\n-- 全表扫描的 SQL\nSELECT * FROM sys.statements_with_full_table_scans\nLIMIT 10;\n\n-- 冗余索引\nSELECT * FROM sys.schema_redundant_indexes;\n\n-- 未使用的索引\nSELECT * FROM sys.schema_unused_indexes;\n\n-- mysqld_exporter 配置（Prometheus）\n'''\n[client]\nuser=exporter\npassword=xxx\n\n[mysqld]\n# exporter 连接配置\n'''\n# 启动: mysqld_exporter --config.my-cnf=.my.cnf\n# Prometheus 抓取:\n#   - job_name: mysql\n#     static_configs:\n#       - targets: ['localhost:9104']\n\n-- Grafana 常用 PromQL\n-- QPS: rate(mysql_global_status_questions[1m])\n-- 连接数: mysql_global_status_threads_connected\n-- 缓冲池命中率:\n--   1 - rate(mysql_global_status_innodb_buffer_pool_reads[1m])\n--   / rate(mysql_global_status_innodb_buffer_pool_read_requests[1m])\n-- 主从延迟: mysql_global_status_seconds_behind_master\n\n-- 告警示例（Prometheus alerting rules）\n'''\n- alert: MysqlHighConnections\n  expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections > 0.8\n  for: 5m\n  labels: { severity: warning }\n  annotations: { summary: \"MySQL 连接数超80%\" }\n\n- alert: MysqlReplicationLag\n  expr: mysql_global_status_seconds_behind_master > 60\n  for: 5m\n  labels: { severity: critical }\n  annotations: { summary: \"主从延迟超60秒\" }\n'''"
  }
],
mysql_ext2_questions: [
  {q:"主从延迟 Seconds_Behind_Master 持续增大的常见原因是？", level:"高级", options:["网络慢","从库单线程串行重放 binlog、大事务、DDL","主库写入太快","从库内存大"], answer:1, explain:"从库 SQL 线程串行重放 binlog，主库多线程写入时从库跟不上；大事务和 DDL 也需同等时间重放，导致延迟累积。"},
  {q:"MySQL 多线程复制（MTS）基于哪种并行机制（8.0最优）？", level:"高级", options:["基于表","基于行","基于 WRITESET（分析无冲突事务并行）","随机并行"], answer:2, explain:"MySQL 8.0 基于 WRITESET 的并行复制（binlog_transaction_dependency_tracking=WRITESET），分析事务修改的行是否冲突，无冲突则可并行重放，效果最优。"},
  {q:"无主键表导致从库重放慢的原因是？", level:"高级", options:["无索引查询慢","ROW 格式 binlog 重放需全表扫描定位行","锁表","内存不足"], answer:1, explain:"ROW 格式 binlog 记录每行变更，从库重放 UPDATE/DELETE 需定位行。无主键只能全表扫描匹配，极慢。有主键则通过索引快速定位。"},
  {q:"MySQL 8.0 INSTANT DDL 的特点是？", level:"高级", options:["复制全表","只修改元数据，瞬间完成，不锁表","需要触发器","耗时但无锁"], answer:1, explain:"INSTANT DDL（8.0.12+）只修改数据字典元数据，不复制数据、不锁表，瞬间完成。但仅支持部分操作（如末尾加列）。"},
  {q:"大表在线变更推荐使用的工具是？", level:"高级", options:["直接 ALTER TABLE","gh-ost / pt-online-schema-change","mysqldump","复制表"], answer:1, explain:"gh-ost（基于 binlog 无触发器）和 pt-osc（基于触发器）通过创建影子表+增量同步+切换实现无锁在线变更，适合大表 DDL。"},
  {q:"gh-ost 相比 pt-osc 的优势是？", level:"高级", options:["更快","基于 binlog 同步不使用触发器，对主库负载影响小","支持更多操作","更简单"], answer:1, explain:"gh-ost 基于 binlog 同步增量数据，不使用触发器，避免触发器对主库的性能影响；pt-osc 基于触发器，可能影响主库写入性能。"},
  {q:"pt-query-digest 分析慢日志的方式是？", level:"高级", options:["逐行查看","按 SQL 指纹（fingerprint）聚合并统计耗时/次数","按时间排序","只看最后一条"], answer:1, explain:"pt-query-digest 将相似 SQL 归一化为指纹（如参数替换为?），聚合统计调用次数、总耗时、平均耗时、扫描行数，便于定位 TOP 慢查询。"},
  {q:"以下哪种 SQL 会导致索引失效？", level:"进阶", options:["WHERE id=1","WHERE DATE(created)='2024-01-01'","WHERE name LIKE 'abc%'","WHERE status IN(1,2)"], answer:1, explain:"对索引列使用函数（DATE、UPPER 等）会导致索引失效。应改为 created >= '2024-01-01' AND created < '2024-01-02' 范围查询。"},
  {q:"EXPLAIN 中 Extra 显示 Using filesort 表示？", level:"进阶", options:["使用了索引","需要额外排序（可能需优化 ORDER BY 走索引）","使用了临时表","查询很快"], answer:1, explain:"Using filesort 表示无法用索引完成排序，需额外排序操作，大结果集时性能差。应优化 ORDER BY 字段使其走索引。"},
  {q:"死锁产生的必要条件是？", level:"高级", options:["单事务","两个或多个事务互相持有对方需要的锁形成循环等待","锁等待超时","事务太长"], answer:1, explain:"死锁是多个事务互相持有对方需要的锁，形成循环等待。InnoDB 自动检测并回滚代价较小的事务（victim）。"},
  {q:"预防死锁最有效的方法是？", level:"高级", options:["缩短事务","固定加锁顺序（所有事务按相同顺序加锁）","降低隔离级别","增加超时"], answer:1, explain:"固定加锁顺序（如按主键升序更新）可避免循环等待，是最有效的预防方法。缩短事务和降低隔离级别也有帮助。"},
  {q:"查看最近死锁信息的命令是？", level:"高级", options:["SHOW PROCESSLIST","SHOW ENGINE INNODB STATUS","SHOW ERRORS","SHOW WARNINGS"], answer:1, explain:"SHOW ENGINE INNODB STATUS\\G 的 LATEST DETECTED DEADLOCK 段显示最近一次死锁详情，包括两个事务的 SQL 和锁持有/等待情况。"},
  {q:"间隙锁导致的死锁通常发生在哪个隔离级别？", level:"高级", options:["READ UNCOMMITTED","READ COMMITTED","REPEATABLE READ（RR）","SERIALIZABLE"], answer:2, explain:"RR 隔离级别下 InnoDB 使用临键锁（含间隙锁）防幻读，范围查询加间隙锁可能与其他事务的插入冲突导致死锁。RC 无间隙锁。"},
  {q:"MySQL 8.0 不可见索引（Invisible Index）的用途是？", level:"高级", options:["隐藏数据","验证删除索引的影响，无影响再删除","加速查询","节省空间"], answer:1, explain:"将索引设为 INVISIBLE 后优化器不使用它，观察查询性能是否受影响，若不受影响说明索引无用可安全删除，降低删除风险。"},
  {q:"MySQL 8.0 真正生效的降序索引指的是？", level:"进阶", options:["语法兼容","按 DESC 真正存储索引，加速 ORDER BY DESC","只是排序方向","无实际作用"], answer:1, explain:"5.7 的 DESC 索引只是语法兼容，实际仍升序存储；8.0 真正按降序存储 B+ 树，能加速 ORDER BY ... DESC 查询。"},
  {q:"SKIP LOCKED 的适用场景是？", level:"高级", options:["跳过错误","任务队列中跳过被锁定的行，避免阻塞","跳过权限","跳过索引"], answer:1, explain:"FOR UPDATE SKIP LOCKED 跳过被其他事务锁定的行，不阻塞，适合任务队列并发取任务，每个 worker 取不同任务。"},
  {q:"MySQL 9.0 新增的 VECTOR 类型用于？", level:"高级", options:["图形处理","AI 场景存储向量数据，支持相似度搜索","数组存储","坐标存储"], answer:1, explain:"MySQL 9.0 新增 VECTOR 类型用于 AI/机器学习场景存储向量嵌入，配合 DISTANCE 函数计算向量相似度，支持向量检索。"},
  {q:"InnoDB 聚簇索引推荐使用自增主键的原因是？", level:"进阶", options:["查询快","顺序写入避免页分裂，插入性能好且索引紧凑","节省内存","唯一性好"], answer:1, explain:"自增主键顺序写入，新数据追加到 B+ 树末尾，避免页分裂和碎片；主键越小二级索引也越小（二级索引存储主键值）。"},
  {q:"UUID 作为主键的主要问题是？", level:"进阶", options:["太长","随机无序导致频繁页分裂，索引体积大(16字节)","不唯一","不能做主键"], answer:1, explain:"UUID 随机无序，插入位置随机导致频繁页分裂和碎片，性能差；16字节比 BIGINT(8) 大，所有二级索引都变大。可用 UUID v7 或 UUID_TO_BIN 变有序。"},
  {q:"雪花算法 Snowflake 生成的 ID 特点是？", level:"进阶", options:["完全随机","趋势递增、分布式唯一、可存为 BIGINT","字符串","固定长度"], answer:1, explain:"雪花算法 64 位 = 时间戳+机器ID+序列号，趋势递增（时间有序，减少页分裂），分布式唯一，存为 BIGINT 节省空间。需处理时钟回拨。"},
  {q:"读写分离中写后立即读从库可能遇到的问题是？", level:"进阶", options:["权限不足","主从延迟导致读到旧数据","连接失败","死锁"], answer:1, explain:"主库写入后 binlog 异步同步到从库，立即读从库可能因延迟读到旧数据。解决：关键读走主库、会话粘连、半同步复制等。"},
  {q:"ShardingSphere 强制读主库的方式是？", level:"高级", options:["无法强制","HintManager.setWriteRouteOnly() 或 SQL Hint","修改配置","重启"], answer:1, explain:"ShardingSphere 支持 HintManager.setWriteRouteOnly() 在代码中强制走主库，也支持 SQL 注释 /*MASTER*/ 等方式，用于写后立即读场景。"},
  {q:"缓冲池命中率计算公式是？", level:"高级", options:["reads/questions","1 - Innodb_buffer_pool_reads / Innodb_buffer_pool_read_requests","reads/Uptime","命中/总连接"], answer:1, explain:"命中率 = 1 - 物理读/逻辑读 = 1 - Innodb_buffer_pool_reads / Innodb_buffer_pool_read_requests。命中率应 >99%，低说明缓冲池太小。"},
  {q:"sys.schema_unused_indexes 视图的用途是？", level:"进阶", options:["查找错误","找出未被使用的索引（可考虑删除）","找重复索引","找缺失索引"], answer:1, explain:"sys.schema_unused_indexes 列出从未被查询使用的索引，这些索引只增加写入开销不带来查询收益，可考虑删除以提升写入性能。"},
  {q:"连接数告警通常设置为？", level:"进阶", options:["超过1","超过 max_connections 的 80%","超过10","固定100"], answer:1, explain:"Threads_connected 超过 max_connections 的 80% 应告警，预留缓冲避免连接耗尽导致拒绝连接。可通过连接池控制。"},
  {q:"Prometheus 监控 MySQL 使用的采集组件是？", level:"进阶", options:["node_exporter","mysqld_exporter","mysqld_agent","mysql_monitor"], answer:1, explain:"mysqld_exporter 连接 MySQL 采集 SHOW GLOBAL STATUS 等指标，暴露给 Prometheus 抓取，配合 Grafana 可视化监控。"},
  {q:"performance_schema 相比 SHOW STATUS 的优势是？", level:"高级", options:["更快","细粒度事件级监控（锁、IO、语句、内存等）","更简单","不需要权限"], answer:1, explain:"performance_schema 提供细粒度的事件级监控，包括锁等待、IO 等待、语句执行、内存分配等详细数据，比 SHOW STATUS 的全局聚合更精细。sys 库提供友好视图。"}
]
