// === SQL EXT3 ===
sql_ext3_topics: [
  {
    id: "sql-pivot-unpivot",
    title: "行列转换：PIVOT 与 UNPIVOT",
    level: "高级",
    content: "**PIVOT（行转列）**\\n- 将行数据转换为列展示\\n- 典型场景：将按月份存储的销售数据转为月份作为列\\n- MySQL 不支持原生 PIVOT，需用 CASE + 聚合模拟\\n- SQL Server/Oracle 支持原生 PIVOT 语法\\n\\n**MySQL 模拟 PIVOT**\\n```sql\\nSELECT \\n  product,\\n  SUM(CASE WHEN month='Jan' THEN amount ELSE 0 END) AS Jan,\\n  SUM(CASE WHEN month='Feb' THEN amount ELSE 0 END) AS Feb,\\n  SUM(CASE WHEN month='Mar' THEN amount ELSE 0 END) AS Mar\\nFROM sales\\nGROUP BY product;\\n```\\n\\n**UNPIVOT（列转行）**\\n- 将多列数据转为行格式\\n- 典型场景：将各月份列转为 month/amount 两行\\n- MySQL 同样需用 UNION ALL 模拟\\n\\n**动态 PIVOT**\\n- 当列值动态变化时，需要用动态 SQL\\n- 先查询所有可能的列值\\n- 拼接 CASE 语句或 PIVOT 语句执行\\n\\n**适用场景**\\n- 报表展示（交叉表/透视表）\\n- 数据对比（多维度并排显示）\\n- 导入导出格式转换\",
    example: \"-- MySQL 行转列（PIVOT）\\nSELECT \\n  department,\\n  SUM(CASE WHEN quarter='Q1' THEN revenue END) AS Q1,\\n  SUM(CASE WHEN quarter='Q2' THEN revenue END) AS Q2,\\n  SUM(CASE WHEN quarter='Q3' THEN revenue END) AS Q3,\\n  SUM(CASE WHEN quarter='Q4' THEN revenue END) AS Q4,\\n  SUM(revenue) AS total\\nFROM quarterly_revenue\\nGROUP BY department;\\n\\n-- MySQL 列转行（UNPIVOT）\\nSELECT product, 'Q1' AS quarter, Q1 AS revenue FROM pivot_data\\nUNION ALL\\nSELECT product, 'Q2' AS quarter, Q2 AS revenue FROM pivot_data\\nUNION ALL\\nSELECT product, 'Q3' AS quarter, Q3 AS revenue FROM pivot_data\\nUNION ALL\\nSELECT product, 'Q4' AS quarter, Q4 AS revenue FROM pivot_data;\\n\\n-- 动态 PIVOT（MySQL 存储过程）\\nDELIMITER //\\nCREATE PROCEDURE dynamic_pivot()\\nBEGIN\\n  SET @sql = NULL;\\n  SELECT\\n    GROUP_CONCAT(DISTINCT\\n      CONCAT(\\n        'SUM(CASE WHEN month = ''', month, ''' THEN amount ELSE 0 END) AS ', month\\n      )\\n    ) INTO @sql\\n  FROM sales;\\n  \\n  SET @sql = CONCAT('SELECT product, ', @sql, ' FROM sales GROUP BY product');\\n  PREPARE stmt FROM @sql;\\n  EXECUTE stmt;\\n  DEALLOCATE PREPARE stmt;\\nEND //\\nDELIMITER ;\\n\\n-- SQL Server 原生 PIVOT\\nSELECT *\\nFROM sales\\nPIVOT (\\n  SUM(amount) FOR month IN ([Jan], [Feb], [Mar])\\n) AS pvt;\\n\\n-- Oracle 原生 PIVOT\\nSELECT * FROM sales\\nPIVOT (\\n  SUM(amount) FOR month IN ('Jan' AS Jan, 'Feb' AS Feb, 'Mar' AS Mar)\\n);"
  },
  {
    id: "sql-window-functions",
    title: "窗口函数实战与分析",
    level: "高级",
    content: "**窗口函数语法**\\n```sql\\nfunction(expression) OVER (\\n  [PARTITION BY col1, col2]\\n  [ORDER BY col3 [ASC|DESC]]\\n  [frame_clause]\\n)\\n```\\n\\n**排名函数**\\n- ROW_NUMBER()：连续唯一编号（1,2,3,4）\\n- RANK()：相同值同排名，跳号（1,2,2,4）\\n- DENSE_RANK()：相同值同排名，不跳号（1,2,2,3）\\n- NTILE(n)：将行分为 n 个桶\\n\\n**聚合窗口函数**\\n- SUM/AVG/COUNT/MIN/MAX() OVER()\\n- 累计求和、移动平均\\n- frame_clause：ROWS/RANGE BETWEEN\\n\\n**取值函数**\\n- LAG(expr, offset, default)：向前取第 N 行\\n- LEAD(expr, offset, default)：向后取第 N 行\\n- FIRST_VALUE(expr)：窗口内第一行\\n- LAST_VALUE(expr)：窗口内最后一行\\n- NTH_VALUE(expr, n)：窗口内第 N 行\\n\\n**框架子句（Frame Clause）**\\n- ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW：从开头到当前行\\n- ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING：前后各 2 行\\n- RANGE BETWEEN INTERVAL '7' DAY PRECEDING AND CURRENT ROW：日期范围\\n\\n**使用限制**\\n- 窗口函数不能直接用在 WHERE 子句中\\n- 需要嵌套子查询或 CTE 过滤窗口函数结果\",
    example: \"-- 排名示例\\nSELECT \\n  name, department, salary,\\n  ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS row_num,\\n  RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS rank_num,\\n  DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dense_rank_num\\nFROM employees;\\n\\n-- 累计求和\\nSELECT \\n  date, amount,\\n  SUM(amount) OVER (ORDER BY date ROWS UNBOUNDED PRECEDING) AS running_total\\nFROM transactions;\\n\\n-- 移动平均（7 天）\\nSELECT \\n  date, value,\\n  AVG(value) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ma7\\nFROM stock_prices;\\n\\n-- 同比环比（LAG/LEAD）\\nSELECT \\n  month, revenue,\\n  LAG(revenue, 1) OVER (ORDER BY month) AS prev_month,\\n  revenue - LAG(revenue, 1) OVER (ORDER BY month) AS mom_diff,\\n  ROUND((revenue - LAG(revenue, 1) OVER (ORDER BY month)) / LAG(revenue, 1) OVER (ORDER BY month) * 100, 2) AS mom_pct,\\n  LAG(revenue, 12) OVER (ORDER BY month) AS prev_year,\\n  ROUND((revenue - LAG(revenue, 12) OVER (ORDER BY month)) / LAG(revenue, 12) OVER (ORDER BY month) * 100, 2) AS yoy_pct\\nFROM monthly_revenue;\\n\\n-- 分组 Top N\\nSELECT * FROM (\\n  SELECT \\n    name, category, sales,\\n    ROW_NUMBER() OVER (PARTITION BY category ORDER BY sales DESC) AS rn\\n  FROM products\\n) t WHERE rn <= 3;\\n\\n-- 去重保留最新（不用 GROUP BY）\\nSELECT * FROM (\\n  SELECT *,\\n    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY update_time DESC) AS rn\\n  FROM user_logs\\n) t WHERE rn = 1;"
  },
  {
    id: "sql-recursive-cte",
    title: "递归 CTE 与层次查询",
    level: "高级",
    content: "**递归 CTE 语法**\\n```sql\\nWITH RECURSIVE cte_name AS (\\n  -- 锚定成员（初始结果集）\\n  SELECT ... FROM table WHERE condition\\n  UNION ALL\\n  -- 递归成员（引用 CTE 自身）\\n  SELECT ... FROM table JOIN cte_name ON ...\\n)\\nSELECT * FROM cte_name;\\n```\\n\\n**执行原理**\\n1. 执行锚定成员，生成初始结果集 R0\\n2. 用 R0 作为输入执行递归成员，生成 R1\\n3. 用 R1 作为输入执行递归成员，生成 R2\\n4. 重复直到递归成员返回空集\\n5. 用 UNION ALL（或 UNION）合并所有结果\\n\\n**终止条件**\\n- 必须确保递归最终会终止，否则会无限循环\\n- 可以用 WHERE 条件限制递归深度\\n- MySQL 8.0+ 默认递归深度限制 cte_max_recursion_depth（默认 1000）\\n\\n**典型应用场景**\\n1. **组织架构查询**：查找所有下属、上级链\\n2. **树形结构遍历**：分类树、菜单树、文件系统\\n3. **路径搜索**：图的最短路径（简单场景）\\n4. **生成序列**：日期序列、数字序列\\n5. **字符串拆分**：将逗号分隔字符串拆分为多行\\n\\n**避免循环**\\n- 记录已访问节点，在 WHERE 中排除\\n- 添加深度计数器限制层级\",
    example: \"-- 组织架构：查某员工的所有下属\\nWITH RECURSIVE subordinates AS (\\n  SELECT id, name, manager_id, 0 AS depth\\n  FROM employees WHERE id = 1  -- CEO\\n  UNION ALL\\n  SELECT e.id, e.name, e.manager_id, s.depth + 1\\n  FROM employees e\\n  INNER JOIN subordinates s ON e.manager_id = s.id\\n)\\nSELECT * FROM subordinates;\\n\\n-- 查某员工的所有上级（反向递归）\\nWITH RECURSIVE managers AS (\\n  SELECT id, name, manager_id, 0 AS level\\n  FROM employees WHERE id = 10\\n  UNION ALL\\n  SELECT e.id, e.name, e.manager_id, m.level + 1\\n  FROM employees e\\n  INNER JOIN managers m ON e.id = m.manager_id\\n)\\nSELECT * FROM managers;\\n\\n-- 生成年月序列\\nWITH RECURSIVE dates AS (\\n  SELECT '2024-01-01' AS dt\\n  UNION ALL\\n  SELECT DATE_ADD(dt, INTERVAL 1 MONTH)\\n  FROM dates\\n  WHERE dt < '2024-12-01'\\n)\\nSELECT dt FROM dates;\\n\\n-- 字符串拆分（逗号分隔）\\nWITH RECURSIVE split AS (\\n  SELECT \\n    SUBSTRING_INDEX('a,b,c,d', ',', 1) AS val,\\n    SUBSTRING('a,b,c,d', LENGTH(SUBSTRING_INDEX('a,b,c,d', ',', 1)) + 2) AS remainder\\n  UNION ALL\\n  SELECT \\n    SUBSTRING_INDEX(remainder, ',', 1),\\n    NULLIF(SUBSTRING(remainder, LENGTH(SUBSTRING_INDEX(remainder, ',', 1)) + 2), '')\\n  FROM split\\n  WHERE remainder IS NOT NULL\\n)\\nSELECT val FROM split;\\n\\n-- 层级缩进展示\\nWITH RECURSIVE org_tree AS (\\n  SELECT id, name, manager_id, 0 AS depth,\\n         CAST(name AS CHAR(100)) AS path\\n  FROM employees WHERE manager_id IS NULL\\n  UNION ALL\\n  SELECT e.id, e.name, e.manager_id, ot.depth + 1,\\n         CONCAT(ot.path, ' > ', e.name)\\n  FROM employees e\\n  JOIN org_tree ot ON e.manager_id = ot.id\\n)\\nSELECT CONCAT(REPEAT('  ', depth), name) AS org_chart, path\\nFROM org_tree ORDER BY path;\\n\\n-- 限制递归深度\\nSET SESSION cte_max_recursion_depth = 100;"
  },
  {
    id: "sql-injection",
    title: "SQL 注入防御深度",
    level: "高级",
    content: "**SQL 注入原理**\\n- 用户输入被当作 SQL 代码执行\\n- 经典例子：' OR '1'='1\\n- 可以绕过认证、读取、修改、删除任意数据\\n\\n**防御措施（按优先级）**\\n\\n1. **参数化查询/预处理语句（最可靠）**\\n   - 使用 PreparedStatement（Java）、参数化查询（Python）、PDO（PHP）\\n   - 数据库将参数视为纯数据，不解析为 SQL 代码\\n   - 无论输入什么字符都不会改变 SQL 结构\\n\\n2. **ORM 框架**\\n   - Hibernate、Django ORM、SQLAlchemy 等自动转义\\n   - 但仍需注意原生 SQL 查询的安全\\n\\n3. **输入验证与白名单**\\n   - 对数字、日期、枚举值做严格类型检查\\n   - 对字符串做长度和格式限制\\n   - 拒绝而非清理（黑名单容易被绕过）\\n\\n4. **最小权限原则**\\n   - 应用连接数据库的账号只给必要权限\\n   - 禁止 DROP/GRANT 等高危权限\\n   - 读账户和写账户分离\\n\\n5. **错误信息处理**\\n   - 生产环境不暴露数据库错误细节\\n   - 统一返回友好的错误提示\\n\\n**常见绕过手段**\\n- 编码绕过：URL 编码、Unicode 编码\\n- 注释绕过：--、/* */、#\\n- 盲注：通过时间延迟或布尔条件推断数据\\n- 二次注入：先存入数据库，再被其他功能使用\\n\\n**检测工具**\\n- sqlmap：自动化 SQL 注入检测与利用\\n- Burp Suite：Web 安全测试\",
    example: \"-- 危险的字符串拼接（SQL 注入）\\nString sql = \\\"SELECT * FROM users WHERE name='\\\" + userInput + \\\"'\\\";\\n-- 如果 userInput = \\\"' OR '1'='1\\\"，则返回所有用户\\n\\n-- 安全的参数化查询（Java JDBC）\\nString sql = \\\"SELECT * FROM users WHERE name = ? AND age = ?\\\";\\nPreparedStatement ps = conn.prepareStatement(sql);\\nps.setString(1, userInput);\\nps.setInt(2, 25);\\nResultSet rs = ps.executeQuery();\\n\\n-- Python SQLAlchemy（安全）\\nresult = session.query(User).filter(User.name == user_input).all()\\n\\n-- Python psycopg2（安全）\\ncursor.execute(\\\"SELECT * FROM users WHERE name = %s\\\", (user_input,))\\n\\n-- PHP PDO（安全）\\n$stmt = $pdo->prepare('SELECT * FROM users WHERE name = :name');\\n$stmt->execute(['name' => $userInput]);\\n\\n-- 输入验证示例\\nif (!preg_match('/^[a-zA-Z0-9_]+$/', $userInput)) {\\n  throw new Exception('Invalid input');\\n}\\n\\n-- 最小权限\\n-- 应用账号只给 SELECT/INSERT/UPDATE/DELETE\\nCREATE USER 'appuser'@'%' IDENTIFIED BY 'password';\\nGRANT SELECT, INSERT, UPDATE, DELETE ON mydb.* TO 'appuser'@'%';\\n-- 禁止 DROP, ALTER, GRANT\\n\\n-- 存储过程中也要注意（避免动态 SQL）\\n-- 如果必须用动态 SQL，严格转义\\nSET @safe_id = CAST(user_input AS UNSIGNED);\\nSET @sql = CONCAT('SELECT * FROM orders WHERE id = ', @safe_id);\\nPREPARE stmt FROM @sql;\\nEXECUTE stmt;"
  },
  {
    id: "sql-etl-dwh",
    title: "ETL 与数据仓库 SQL",
    level: "高级",
    content: "**ETL 流程**\\n- Extract（抽取）：从各数据源获取数据\\n- Transform（转换）：清洗、关联、聚合、格式化\\n- Load（加载）：加载到目标数据仓库\\n\\n**数据仓库特点**\\n- 面向主题：按业务主题组织（销售、库存、客户）\\n- 集成性：多源数据统一格式\\n- 时变性：保存历史数据，支持时间维度分析\\n- 非易失性：一般不删除，只追加\\n\\n**星型模型与雪花模型**\\n- 事实表：记录业务事件（销售额、数量）\\n- 维度表：描述业务实体（时间、产品、地区）\\n- 星型模型：事实表直接关联维度表\\n- 雪花模型：维度表进一步规范化\\n\\n** slowly changing dimensions（SCD）**\\n- SCD Type 1：直接覆盖旧值\\n- SCD Type 2：增加新行，保留历史（生效/失效日期）\\n- SCD Type 3：增加列保留上一个值\\n\\n**ETL SQL 技巧**\\n- MERGE/UPSERT：存在更新，不存在插入\\n- 批量加载：LOAD DATA、BULK INSERT\\n- 增量抽取：基于时间戳或自增 ID\\n- 数据清洗：NULL 处理、去重、格式标准化\\n- 拉链表：记录数据历史变化\",
    example: \"-- 增量抽取（基于时间戳）\\nSELECT * FROM source_table\\nWHERE update_time > (SELECT MAX(last_load_time) FROM etl_log);\\n\\n-- MERGE（UPSERT）语法 - SQL Server\\nMERGE target_table AS t\\nUSING source_table AS s\\nON t.id = s.id\\nWHEN MATCHED THEN\\n  UPDATE SET t.value = s.value, t.update_time = GETDATE()\\nWHEN NOT MATCHED THEN\\n  INSERT (id, value, update_time) VALUES (s.id, s.value, GETDATE());\\n\\n-- MySQL INSERT ... ON DUPLICATE KEY UPDATE\\nINSERT INTO target (id, value, update_time)\\nSELECT id, value, NOW() FROM source\\nON DUPLICATE KEY UPDATE\\n  value = VALUES(value),\\n  update_time = VALUES(update_time);\\n\\n-- SCD Type 2 实现\\n-- 1. 失效旧记录\\nUPDATE dim_customer\\nSET end_date = CURRENT_DATE - 1, is_current = 0\\nWHERE customer_id = @id AND is_current = 1;\\n\\n-- 2. 插入新记录\\nINSERT INTO dim_customer (customer_id, name, address, start_date, end_date, is_current)\\nVALUES (@id, @name, @new_address, CURRENT_DATE, '9999-12-31', 1);\\n\\n-- 拉链表查询当前有效记录\\nSELECT * FROM dim_customer WHERE is_current = 1;\\n\\n-- 查询某历史时间点的记录\\nSELECT * FROM dim_customer\\nWHERE @history_date BETWEEN start_date AND end_date;\\n\\n-- 数据清洗示例\\nUPDATE staging_table SET\\n  email = LOWER(TRIM(email)),\\n  phone = REGEXP_REPLACE(phone, '[^0-9]', ''),\\n  status = COALESCE(status, 'UNKNOWN')\\nWHERE load_batch = @batch_id;\\n\\n-- 维度聚合\\nCREATE TABLE sales_summary AS\\nSELECT \\n  d.date_month,\\n  p.category,\\n  r.region,\\n  SUM(s.amount) AS total_sales,\\n  COUNT(DISTINCT s.order_id) AS order_count\\nFROM fact_sales s\\nJOIN dim_date d ON s.date_id = d.date_id\\nJOIN dim_product p ON s.product_id = p.product_id\\nJOIN dim_region r ON s.region_id = r.region_id\\nGROUP BY d.date_month, p.category, r.region;"
  },
  {
    id: "sql-dialect-diff",
    title: "SQL 标准与各数据库方言差异",
    level: "高级",
    content: "**SQL 标准演进**\\n- SQL-92：基础语法\\n- SQL:1999：CTE、窗口函数（部分）\\n- SQL:2003：窗口函数、MERGE\\n- SQL:2011：时态数据库\\n- SQL:2016：JSON 支持、行模式识别\\n\\n**分页语法差异**\\n- MySQL/PostgreSQL：LIMIT offset, count / LIMIT count OFFSET offset\\n- SQL Server：OFFSET offset ROWS FETCH NEXT count ROWS ONLY（2012+）\\n- Oracle：ROWNUM / OFFSET FETCH\\n- DB2：FETCH FIRST n ROWS ONLY\\n\\n**字符串拼接**\\n- MySQL：CONCAT(str1, str2)\\n- PostgreSQL：CONCAT 或 ||\\n- SQL Server：+（注意 NULL 处理）\\n- Oracle：||\\n\\n**日期函数差异**\\n- 当前日期：NOW()/CURRENT_TIMESTAMP（MySQL）、GETDATE()（SQL Server）、SYSDATE（Oracle）\\n- 日期加减：DATE_ADD/DATE_SUB（MySQL）、+ INTERVAL（PostgreSQL）、DATEADD（SQL Server）\\n- 格式化：DATE_FORMAT（MySQL）、TO_CHAR（Oracle/PostgreSQL）、FORMAT（SQL Server）\\n\\n**空值处理**\\n- COALESCE：标准，所有数据库支持\\n- ISNULL：SQL Server\\n- NVL：Oracle\\n- IFNULL：MySQL\\n\\n**自增主键**\\n- MySQL：AUTO_INCREMENT\\n- PostgreSQL：SERIAL / GENERATED ALWAYS AS IDENTITY\\n- SQL Server：IDENTITY(1,1)\\n- Oracle：SEQUENCE\\n\\n**布尔类型**\\n- PostgreSQL：原生 BOOLEAN\\n- MySQL：TINYINT(1)\\n- SQL Server：BIT\\n- Oracle：无原生布尔\\n\\n**限制与变通**\\n- 写跨库兼容 SQL 的复杂度很高\\n- 通常使用 ORM 或数据库抽象层\\n- 数据迁移时用工具（如 AWS DMS、pgloader）处理方言转换\",
    example: \"-- 分页对比\\n-- MySQL\\nSELECT * FROM users ORDER BY id LIMIT 20 OFFSET 40;\\n\\n-- PostgreSQL\\nSELECT * FROM users ORDER BY id LIMIT 20 OFFSET 40;\\n\\n-- SQL Server 2012+\\nSELECT * FROM users ORDER BY id OFFSET 40 ROWS FETCH NEXT 20 ROWS ONLY;\\n\\n-- Oracle 12c+\\nSELECT * FROM users ORDER BY id OFFSET 40 ROWS FETCH NEXT 20 ROWS ONLY;\\n\\n-- 字符串拼接\\n-- MySQL\\nSELECT CONCAT(first_name, ' ', last_name) AS full_name;\\n-- PostgreSQL/Oracle\\nSELECT first_name || ' ' || last_name AS full_name;\\n-- SQL Server\\nSELECT first_name + ' ' + last_name AS full_name;\\n\\n-- 日期加减\\n-- MySQL\\nSELECT DATE_ADD(NOW(), INTERVAL 7 DAY);\\n-- PostgreSQL\\nSELECT NOW() + INTERVAL '7 days';\\n-- SQL Server\\nSELECT DATEADD(day, 7, GETDATE());\\n-- Oracle\\nSELECT SYSDATE + 7 FROM dual;\\n\\n-- 空值处理\\nSELECT COALESCE(middle_name, 'N/A') FROM users;  -- 标准\\nSELECT ISNULL(middle_name, 'N/A') FROM users;    -- SQL Server\\nSELECT NVL(middle_name, 'N/A') FROM users;       -- Oracle\\nSELECT IFNULL(middle_name, 'N/A') FROM users;    -- MySQL\\n\\n-- 自增主键\\n-- MySQL\\nCREATE TABLE t (id INT AUTO_INCREMENT PRIMARY KEY);\\n-- PostgreSQL\\nCREATE TABLE t (id SERIAL PRIMARY KEY);\\n-- SQL Server\\nCREATE TABLE t (id INT IDENTITY(1,1) PRIMARY KEY);\\n-- Oracle\\nCREATE SEQUENCE t_seq;\\nCREATE TABLE t (id NUMBER PRIMARY KEY DEFAULT t_seq.NEXTVAL);\\n\\n-- 插入或更新\\n-- MySQL\\nINSERT INTO t (id, val) VALUES (1, 'a') ON DUPLICATE KEY UPDATE val='a';\\n-- PostgreSQL\\nINSERT INTO t (id, val) VALUES (1, 'a') ON CONFLICT (id) DO UPDATE SET val='a';\\n-- SQL Server\\nMERGE t USING (VALUES(1,'a')) AS s(id,val) ON t.id=s.id\\nWHEN MATCHED THEN UPDATE SET val=s.val\\nWHEN NOT MATCHED THEN INSERT (id, val) VALUES (s.id, s.val);"
  },
  {
    id: "sql-time-series",
    title: "时间序列数据处理",
    level: "高级",