// === MYSQL EXT3 ===
mysql_ext3_topics: [
  {
    id: "mysql-innodb-page",
    title: "InnoDB 页结构与行存储格式",
    level: "高级",
    content: "**InnoDB 页（Page）结构**\\n- 默认页大小 16KB（可配置 4K/8K/16K/32K/64K）\\n- 页是 InnoDB 读写磁盘的最小单位\\n- 页类型：数据页、Undo 页、系统页、事务数据页等\\n\\n**页头部结构（File Header + Page Header）**\\n- FIL_PAGE_SPACE：表空间 ID\\n- FIL_PAGE_OFFSET：页偏移量\\n- FIL_PAGE_TYPE：页类型（0x45BF 为数据页）\\n- PAGE_N_RECS：页内记录数\\n- PAGE_FREE：空闲链表头指针\\n- PAGE_LAST_INSERT：最后插入位置\\n- PAGE_N_DIR_SLOTS：页目录槽数\\n\\n**行格式（Row Format）**\\n1. **COMPACT（默认）**\\n   - 变长字段长度列表 + NULL 标志位 + 记录头信息 + 列数据\\n   - 更省空间，适合大多数场景\\n\\n2. **REDUNDANT**\\n   - MySQL 5.0 之前格式，已废弃\\n\\n3. **DYNAMIC**\\n   - 大字段（BLOB/TEXT）只存 20 字节指针，数据存在溢出页\\n   - 更灵活，推荐用于大字段场景\\n\\n4. **COMPRESSED**\\n   - 支持页级压缩，节省存储\\n   - 需要开启 innodb_file_per_table 和特定 key_block_size\\n\\n**溢出页（Off-page）**\\n- 当行数据超过页大小一半（约 8000 字节）时，大字段存到溢出页\\n- COMPACT：前 768 字节存在本页，其余在溢出页\\n- DYNAMIC：只存 20 字节指针\\n\\n**页目录（Page Directory）**\\n- 页内维护一个稀疏索引（槽/slot）\\n- 每 4-8 条记录有一个槽，指向记录位置\\n- 利用页目录进行二分查找，加速页内定位\",
    example: \"# 查看表的行格式\\nSHOW TABLE STATUS LIKE 'users'\\\\G\\n# Row_format: Dynamic\\n\\n# 修改行格式\\nALTER TABLE users ROW_FORMAT=DYNAMIC;\\n\\n# 查看页大小\\nSHOW VARIABLES LIKE 'innodb_page_size';\\n# 默认 16384 (16KB)\\n\\n# 查看表空间信息\\nSELECT * FROM information_schema.INNODB_TABLESPACES WHERE NAME='db/users';\\n\\n# 使用 innodb_ruby 工具分析页结构（第三方）\\n# gem install innodb_ruby\\n# innodb_space -s ibdata1 -T db/users space-page-type-summary\\n\\n# 查看表数据页分布\\nSELECT \\n  table_name, \\n  index_name, \\n  SUM(data_size) / COUNT(*) AS avg_page_fill\\nFROM information_schema.INNODB_BUFFER_PAGE\\nWHERE table_name = 'db/users'\\nGROUP BY index_name;\\n\\n# 压缩表示例\\nSET GLOBAL innodb_file_per_table=1;\\nCREATE TABLE compressed_table (\\n  id INT PRIMARY KEY,\\n  data VARCHAR(4000)\\n) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;"
  },
  {
    id: "mysql-redo-undo",
    title: "Redo Log 与 Undo Log 深度原理",
    level: "高级",
    content: "**Redo Log（重做日志）**\\n- 物理日志，记录页的物理修改（某页某偏移量改成什么值）\\n- 保证事务的持久性（Durability）\\n- 循环写入，固定大小的日志文件组（ib_logfile0/1）\\n- Write-Ahead Logging（WAL）：先写日志，再刷脏页\\n\\n**Redo Log 写入流程**\\n1. 修改 Buffer Pool 中的页\\n2. 生成 Redo Log，写入 Log Buffer（内存）\\n3. 根据 innodb_flush_log_at_trx_commit 策略刷盘：\\n   - 0：每秒刷盘（可能丢 1 秒数据）\\n   - 1：每次事务提交刷盘（默认，最安全）\\n   - 2：每次提交写入 OS cache，每秒刷盘\\n4. 日志顺序号（LSN）单调递增\\n\\n**Undo Log（回滚日志）**\\n- 逻辑日志，记录反向操作（INSERT 对应 DELETE，UPDATE 记录旧值）\\n- 保证事务的原子性（Atomicity）\\n- 支持 MVCC：未提交事务的数据通过 Undo 构造旧版本\\n- 存储在 Undo Tablespace（MySQL 8.0 独立表空间）\\n\\n**Undo 链与 Purge**\\n- 同一行的多个历史版本通过 roll_ptr 形成版本链\\n- Purge 线程异步清理不再需要的 Undo 记录\\n- 长事务会导致 Undo 堆积，影响性能和空间\\n\\n**Checkpoint 机制**\\n- Sharp Checkpoint：关闭时全部刷盘\\n- Fuzzy Checkpoint：运行时定期刷脏页\\n- LSN 比对确定恢复起点\",
    example: \"# 查看 Redo Log 配置\\nSHOW VARIABLES LIKE 'innodb_log_file%';\\n# innodb_log_file_size: 48M\\n# innodb_log_files_in_group: 2\\n\\n# 查看 Redo Log 状态\\nSHOW ENGINE INNODB STATUS\\\\G\\n# Log sequence number、Log flushed up to、Pages flushed up to\\n\\n# 调整 Redo Log 大小（MySQL 8.0 支持在线调整）\\nSET GLOBAL innodb_redo_log_capacity = 1073741824;  -- 1GB\\n\\n# 查看 Undo Tablespace\\nSELECT * FROM information_schema.INNODB_TABLESPACES WHERE SPACE_TYPE='Undo';\\n\\n# 查看活跃事务和 Undo\\nSELECT \\n  trx_id, \\n  trx_state, \\n  TIMESTAMPDIFF(SECOND, trx_started, NOW()) AS trx_seconds,\\n  trx_tables_locked,\\n  trx_rows_locked\\nFROM information_schema.INNODB_TRX\\nORDER BY trx_started;\\n\\n# 查看 Purge 状态\\nSHOW ENGINE INNODB STATUS\\\\G\\n# 看 History list length（Undo 堆积长度）\\n\\n# 长事务排查\\nSELECT \\n  p.ID, p.USER, p.HOST, p.DB, p.TIME, p.STATE, t.TRX_STARTED, t.TRX_QUERY\\nFROM information_schema.PROCESSLIST p\\nJOIN information_schema.INNODB_TRX t ON p.ID = t.TRX_MYSQL_THREAD_ID\\nWHERE p.TIME > 60;\\n\\n# innodb_flush_log_at_trx_commit 性能对比\\n# 1: 每次提交 fsync，最安全，TPS 最低\\n# 2: 提交时 write，每秒 fsync，可能丢 1 秒\\n# 0: 每秒 write+fsync，可能丢 1 秒且可能丢事务"
  },
  {
    id: "mysql-explain",
    title: "EXPLAIN 执行计划深度解读",
    level: "高级",
    content: "**EXPLAIN 输出列详解**\\n\\n1. **id**：查询标识符，id 相同从上到下执行，id 越大越先执行\\n2. **select_type**：查询类型\\n   - SIMPLE：简单查询，无子查询/UNION\\n   - PRIMARY：最外层查询\\n   - SUBQUERY：SELECT 中的子查询\\n   - DERIVED：FROM 中的子查询（产生临时表）\\n   - UNION / UNION RESULT：联合查询\\n\\n3. **table**：访问的表名或别名\\n4. **partitions**：命中的分区（分区表）\\n5. **type：访问类型（重要！）**\\n   - system/const：主键/唯一索引等值查询，最优\\n   - eq_ref：JOIN 中主键/唯一索引关联，一行匹配\\n   - ref：非唯一索引等值查询，多行匹配\\n   - range：索引范围扫描\\n   - index：索引全扫描（遍历整棵索引树）\\n   - ALL：全表扫描，最差\\n\\n6. **possible_keys**：可能使用的索引\\n7. **key**：实际使用的索引\\n8. **key_len**：使用的索引长度（可判断用了哪些字段）\\n9. **ref**：与索引比较的列或常量\\n10. **rows：预估扫描行数**\\n11. **filtered：按条件过滤后剩余比例**\\n12. **Extra：额外信息（关键！）**\\n    - Using index：覆盖索引，不回表\\n    - Using where：WHERE 条件过滤\\n    - Using temporary：使用临时表\\n    - Using filesort：需要额外排序\\n    - Using index condition：ICP 索引条件下推\\n    - Range checked for each record：索引选择逐行判断\\n\\n**EXPLAIN ANALYZE（MySQL 8.0.18+）**\\n- 实际执行并显示真实时间和行数\\n- 基于 Iterator 模型展示执行流程\",
    example: \"-- 基本 EXPLAIN\\nEXPLAIN SELECT * FROM users WHERE age > 18;\\n\\n-- 详细格式\\nEXPLAIN FORMAT=JSON SELECT * FROM users WHERE age > 18;\\n\\n-- 实际执行分析（MySQL 8.0.18+）\\nEXPLAIN ANALYZE SELECT * FROM users WHERE age > 18;\\n\\n-- 查看执行计划中的关键指标\\n-- type=ALL 表示全表扫描，需要优化\\n-- type=range 表示索引范围扫描\\n-- key_len 帮助判断联合索引用了几列\\n\\n-- 覆盖索引示例\\n-- 索引 idx(name, age)，查询 SELECT name, age FROM users WHERE name='Tom'\\n-- Extra 显示 Using index 表示不需要回表\\n\\n-- ICP（索引条件下推）\\n-- 索引 idx(age, name)，查询 SELECT * FROM users WHERE age=20 AND name LIKE 'T%'\\n-- 存储引擎在索引层过滤 name，减少回表\\n-- Extra 显示 Using index condition\\n\\n-- 查看执行计划树\\nEXPLAIN FORMAT=TREE SELECT * FROM users u JOIN orders o ON u.id=o.user_id;\\n\\n-- 使用 Optimizer Trace 深入分析优化器选择\\nSET optimizer_trace='enabled=on';\\nSELECT ...;\\nSELECT * FROM information_schema.OPTIMIZER_TRACE;\\n\\n-- 强制/忽略索引\\nSELECT * FROM users USE INDEX(idx_age) WHERE age=20;\\nSELECT * FROM users IGNORE INDEX(idx_age) WHERE age=20;\\nSELECT * FROM users FORCE INDEX(idx_age) WHERE age=20;"
  },
  {
    id: "mysql-deadlock",
    title: "死锁分析与排查实战",
    level: "高级",
    content: "**死锁产生条件**\\n- 互斥、持有并等待、不可剥夺、循环等待\\n- InnoDB 自动检测死锁，选择代价较小的事务回滚\\n- 死锁不是数据库 bug，是并发访问的正常现象\\n\\n**死锁日志分析**\\n- SHOW ENGINE INNODB STATUS\\\\G 中的 LATEST DETECTED DEADLOCK\\n- 包含：事务信息、持有的锁、等待的锁、回滚哪个事务\\n- MySQL 8.0：innodb_print_all_deadlocks=ON 记录所有死锁到 error log\\n\\n**常见死锁场景**\\n1. **间隙锁（Gap Lock）导致的死锁**\\n   - 范围查询加锁，并发插入相同间隙\\n   - RR 隔离级别下常见\\n\\n2. **唯一键冲突死锁**\\n   - 插入相同唯一键，都持有点号锁等待对方\\n\\n3. **反向顺序加锁**\\n   - 事务 A 先锁记录 1 再请求记录 2\\n   - 事务 B 先锁记录 2 再请求记录 1\\n\\n4. **外键导致的死锁**\\n   - 子表插入/更新需要检查父表，加共享锁\\n\\n**排查步骤**\\n1. 开启死锁日志：innodb_print_all_deadlocks=ON\\n2. 复现问题，获取死锁信息\\n3. 分析事务的 SQL 顺序和锁类型\\n4. 调整事务顺序、缩短事务、降低隔离级别、优化索引\\n\\n**预防措施**\\n- 按固定顺序访问资源\\n- 尽量使用主键或唯一索引更新\\n- 减少事务持有锁的时间\\n- 避免大批量操作在一个事务中\\n- 考虑降低隔离级别到 READ COMMITTED（减少间隙锁）\",
    example: \"-- 开启死锁日志\\nSET GLOBAL innodb_print_all_deadlocks = ON;\\n\\n-- 查看最近死锁\\nSHOW ENGINE INNODB STATUS\\\\G\\n-- 找到 LATEST DETECTED DEADLOCK 部分\\n\\n-- 死锁示例复现\\n-- 会话 1\\nBEGIN;\\nSELECT * FROM accounts WHERE id = 1 FOR UPDATE;\\n-- 会话 2\\nBEGIN;\\nSELECT * FROM accounts WHERE id = 2 FOR UPDATE;\\n-- 会话 1\\nSELECT * FROM accounts WHERE id = 2 FOR UPDATE;  -- 等待\\n-- 会话 2\\nSELECT * FROM accounts WHERE id = 1 FOR UPDATE;  -- 死锁，会话 2 回滚\\n\\n-- 查看锁等待\\nSELECT \\n  r.trx_id waiting_trx,\\n  r.trx_mysql_thread_id waiting_thread,\\n  b.trx_id blocking_trx,\\n  b.trx_mysql_thread_id blocking_thread,\\n  w.lock_mode waiting_lock,\\n  b2.lock_mode blocking_lock\\nFROM information_schema.innodb_lock_waits w\\nJOIN information_schema.innodb_trx b ON b.trx_id = w.blocking_trx_id\\nJOIN information_schema.innodb_trx r ON r.trx_id = w.requesting_trx_id\\nJOIN information_schema.innodb_locks b2 ON b2.lock_trx_id = w.blocking_trx_id\\nJOIN information_schema.innodb_locks r2 ON r2.lock_trx_id = w.requesting_trx_id;\\n\\n-- 查看行锁详情\\nSELECT * FROM performance_schema.data_locks WHERE OBJECT_NAME='accounts';\\n\\n-- 预防：统一加锁顺序\\n-- 总是按主键升序加锁\\nSELECT * FROM accounts WHERE id IN (1,2) ORDER BY id FOR UPDATE;\\n\\n-- 使用 READ COMMITTED 减少间隙锁\\nSET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;"
  },
  {
    id: "mysql-slow-query",
    title: "慢查询治理与优化",
    level: "高级",
    content: "**慢查询配置**\\n- slow_query_log = ON\\n- long_query_time = 1（秒）\\n- log_queries_not_using_indexes = ON\\n- min_examined_row_limit = 100（避免小表记录）\\n\\n**慢查询日志分析工具**\\n1. **mysqldumpslow**\\n   - MySQL 自带，按 SQL 指纹聚合\\n   - mysqldumpslow -s t -t 10 slow.log\\n\\n2. **pt-query-digest（Percona Toolkit）**\\n   - 最强大，提供详细统计和优化建议\\n   - pt-query-digest slow.log > report.txt\\n\\n3. **MySQL Workbench / Performance Schema**\\n   - 可视化分析\\n\\n**优化方法论**\\n1. **确认慢查询原因**\\n   - 是否缺少索引？\\n   - 是否数据量太大？\\n   - 是否锁等待？\\n   - 是否临时表/文件排序？\\n\\n2. **索引优化**\\n   - 添加合适的索引\\n   - 优化联合索引顺序\\n   - 覆盖索引避免回表\\n\\n3. **SQL 改写**\\n   - 大事务拆分\\n   - 深分页优化（延迟关联、书签方式）\\n   - 避免 SELECT *\\n   - 子查询改 JOIN\\n\\n4. **架构优化**\\n   - 读写分离\\n   - 分库分表\\n   - 引入缓存\\n   - 归档历史数据\\n\\n**Performance Schema 分析**\\n- events_statements_summary_by_digest：按 SQL 指纹聚合\\n- events_waits_summary_by_instance：等待事件分析\",
    example: \"-- 开启慢查询日志\\nSET GLOBAL slow_query_log = 'ON';\\nSET GLOBAL long_query_time = 1;\\nSET GLOBAL log_queries_not_using_indexes = 'ON';\\n\\n-- 分析慢查询日志\\nmysqldumpslow -s t -t 10 /var/lib/mysql/slow.log\\n\\n-- pt-query-digest 分析\\npt-query-digest --type=slowlog /var/lib/mysql/slow.log > slow_report.txt\\n\\n-- 通过 Performance Schema 找慢 SQL\\nSELECT \\n  DIGEST_TEXT,\\n  COUNT_STAR,\\n  AVG_TIMER_WAIT/1000000000000 AS avg_sec,\\n  MAX_TIMER_WAIT/1000000000000 AS max_sec,\\n  SUM_ROWS_EXAMINED/COUNT_STAR AS avg_examined\\nFROM performance_schema.events_statements_summary_by_digest\\nORDER BY AVG_TIMER_WAIT DESC\\nLIMIT 10;\\n\\n-- 深分页优化（延迟关联）\\n-- 原始慢查询\\nSELECT * FROM orders ORDER BY create_time DESC LIMIT 1000000, 10;\\n-- 优化后\\nSELECT o.* FROM orders o\\nJOIN (SELECT id FROM orders ORDER BY create_time DESC LIMIT 1000000, 10) tmp\\nON o.id = tmp.id;\\n\\n-- 查看执行计划确认优化效果\\nEXPLAIN SELECT ...;\\n\\n-- 锁等待导致的慢查询排查\\nSELECT \\n  sql_text,\\n  event_name,\\n  timer_wait/1000000000000 AS wait_sec\\nFROM performance_schema.events_statements_history_long\\nWHERE timer_wait > 1000000000000  -- 超过 1 秒\\nORDER BY timer_wait DESC;\\n\\n-- 清理历史数据（按时间归档）\\nCREATE TABLE orders_archive LIKE orders;\\nINSERT INTO orders_archive SELECT * FROM orders WHERE create_time < '2023-01-01';\\nDELETE FROM orders WHERE create_time < '2023-01-01';\\n-- 或分区表直接 DROP PARTITION"
  },
  {
    id: "mysql-8-features",
    title: "MySQL 8.0 / 9.0 新特性与升级",
    level: "高级",
    content: "**MySQL 8.0 重大改进**\\n\\n1. **数据字典（Data Dictionary）**\\n   - 元数据从 MyISAM 文件（.frm 等）迁移到 InnoDB 表\\n   - 支持原子 DDL（CREATE/DROP 等操作要么全成功要么全回滚）\\n   - information_schema 查询性能大幅提升\\n\\n2. **降序索引（Descending Indexes）**\\n   - CREATE INDEX idx ON t(a DESC, b ASC)\\n   - 避免 filesort，优化 ORDER BY ... DESC\\n\\n3. **不可见索引（Invisible Indexes）**\\n   - CREATE INDEX idx ON t(a) INVISIBLE\\n   - 优化器不可见，用于安全测试索引效果\\n\\n4. **函数索引（Functional Indexes）**\\n   - CREATE INDEX idx ON t((LOWER(name)))\\n   - 索引表达式结果，支持虚拟列\\n\\n5. **CTE（Common Table Expressions）**\\n   - WITH 子句，支持递归 CTE\\n   - 提高复杂查询可读性\\n\\n6. **窗口函数（Window Functions）**\\n   - ROW_NUMBER()、RANK()、LEAD()、LAG() 等\\n   - 避免自连接，简化排名/累计计算\\n\\n7. **JSON 增强**\\n   - JSON 数据类型存储优化（部分更新）\\n   - JSON_TABLE 函数将 JSON 转为关系表\\n   - ->> 操作符（JSON unquoting）\\n\\n8. **TempTable 引擎**\\n   - 替代 Memory 引擎处理内部临时表\\n   - 支持 BLOB/TEXT 字段， spilled to disk\\n\\n9. **角色（Role）**\\n   - CREATE ROLE、GRANT ROLE TO USER\\n   - 简化权限管理\\n\\n10. **密码管理增强**\\n    - caching_sha2_password 默认认证插件\\n    - 密码历史、过期策略\\n\\n**MySQL 9.0 前瞻**\\n- AI/向量支持（Vector 类型）\\n- 更完善的 JSON 功能\\n- 性能持续优化\",
    example: \"-- 原子 DDL 示例\\nDROP TABLE t1, t2;  -- 要么都删除，要么都不删（8.0 之前可能删一半失败）\\n\\n-- 降序索引\\nCREATE INDEX idx_orders ON orders(create_time DESC, status ASC);\\n-- 直接支持 ORDER BY create_time DESC, status ASC 不走 filesort\\n\\n-- 不可见索引\\nCREATE INDEX idx_test ON users(age) INVISIBLE;\\n-- 测试时 ALTER TABLE users ALTER INDEX idx_test VISIBLE;\\n\\n-- 函数索引\\nCREATE INDEX idx_lower_name ON users((LOWER(name)));\\n-- 支持 WHERE LOWER(name) = 'tom' 走索引\\n\\n-- CTE 递归查询（层级数据）\\nWITH RECURSIVE subordinates AS (\\n  SELECT id, name, manager_id FROM employees WHERE id = 1\\n  UNION ALL\\n  SELECT e.id, e.name, e.manager_id\\n  FROM employees e\\n  INNER JOIN subordinates s ON s.id = e.manager_id\\n)\\nSELECT * FROM subordinates;\\n\\n-- 窗口函数\\nSELECT \\n  name,\\n  department,\\n  salary,\\n  RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dept_rank,\\n  SUM(salary) OVER (ORDER BY salary ROWS UNBOUNDED PRECEDING) AS cum_sum\\nFROM employees;\\n\\n-- JSON 部分更新（MySQL 8.0.3+）\\nUPDATE users SET info = JSON_SET(info, '$.age', 30) WHERE id = 1;\\n-- 如果 info 列使用 JSON 类型，且更新不影响文档大小，可以部分更新\\n\\n-- 角色管理\\nCREATE ROLE app_read, app_write;\\nGRANT SELECT ON app.* TO app_read;\\nGRANT SELECT, INSERT, UPDATE ON app.* TO app_write;\\nGRANT app_read TO 'user1'@'%';\\nSET DEFAULT ROLE app_read TO 'user1'@'%';\\n\\n-- 查看数据字典表\\nSELECT * FROM mysql.tables WHERE name='users';"
  },
  {
    id: "mysql-read-write-split",
    title: "读写分离与高可用架构",
    level: "高级",