[
{q:'以下哪个标签是HTML5语义化标签，用于定义页面独立的内容区域？', level:'基础', options:['<div>','<section>','<span>','<table>'], answer:1, explain:'section是HTML5语义化标签，用于定义文档中的独立节或区域；div是无语义容器。'},
{q:'以下哪个标签用于定义HTML文档中最重要的标题？', level:'基础', options:['<h6>','<heading>','<h1>','<title>'], answer:2, explain:'h1定义最高级别标题，用于页面最重要的标题；title是浏览器标签页标题。'},
{q:'<a>标签中哪个属性用于指定链接的目标地址？', level:'基础', options:['src','href','link','url'], answer:1, explain:'href属性指定超链接目标URL；src用于img、script等标签。'},
{q:'<img>标签中哪个属性用于指定图片无法显示时的替代文本？', level:'基础', options:['title','alt','text','desc'], answer:1, explain:'alt属性提供图片替代文本，用于无障碍访问和图片加载失败时显示。'},
{q:'HTML表格中，用于定义表头单元格的标签是？', level:'基础', options:['<td>','<tr>','<th>','<thead>'], answer:2, explain:'th定义表头单元格，默认加粗居中；td定义普通数据单元格。'},
{q:'HTML表单中，以下哪个input类型用于密码输入框？', level:'基础', options:['type="text"','type="password"','type="hidden"','type="secret"'], answer:1, explain:'type="password"创建密码输入框，输入内容以圆点或星号显示。'},
{q:'以下哪个标签用于创建多行文本输入框？', level:'基础', options:['<input>','<textarea>','<text>','<multiline>'], answer:1, explain:'textarea用于多行文本输入；input是单行输入控件。'},
{q:'<button>标签的type属性默认值是？', level:'基础', options:['button','reset','submit','image'], answer:2, explain:'button标签type默认为submit，在表单内点击会提交表单，建议显式设置type。'},
{q:'以下哪个标签用于创建下拉选择列表？', level:'基础', options:['<list>','<option>','<select>','<dropdown>'], answer:2, explain:'select创建下拉列表，内含option标签定义选项。'},
{q:'复选框checkbox的input类型是？', level:'基础', options:['type="check"','type="checkbox"','type="box"','type="select"'], answer:1, explain:'type="checkbox"创建复选框，允许多选；radio是单选。'},
{q:'以下哪个CSS选择器优先级最高？', level:'基础', options:['类选择器','ID选择器','标签选择器','通配符选择器'], answer:1, explain:'选择器优先级：ID > 类/伪类 > 标签 > 通配符，!important可覆盖。'},
{q:'CSS后代选择器的写法是？', level:'基础', options:['A>B','A B','A+B','A~B'], answer:1, explain:'空格分隔表示后代选择器，匹配A的所有后代B元素；>是子代选择器。'},
{q:'CSS子代选择器的写法是？', level:'基础', options:['A>B','A B','A+B','A~B'], answer:0, explain:'>是子代选择器，只匹配直接子元素；空格是后代，匹配所有层级。'},
{q:'以下哪个是相邻兄弟选择器？', level:'基础', options:['A>B','A+B','A~B','A B'], answer:1, explain:'+是相邻兄弟选择器，匹配紧跟在A后的同级B元素；~是通用兄弟。'},
{q:':hover属于哪类CSS选择器？', level:'基础', options:['伪元素','伪类','属性选择器','关系选择器'], answer:1, explain:':hover是伪类选择器，用于鼠标悬停状态；伪元素是::开头如::before。'},
{q:'CSS盒模型中，以下哪个属性不在元素宽度width内（标准盒模型）？', level:'基础', options:['content内容','padding内边距','border边框','margin外边距'], answer:3, explain:'标准盒模型width只包含content；padding、border在width外；margin始终不计入。'},
{q:'box-sizing: border-box的作用是？', level:'基础', options:['width=content','width=content+padding+border','width=content+margin','包含margin'], answer:1, explain:'border-box让width包含content+padding+border，便于计算布局。'},
{q:'以下哪个display值会让元素独占一行？', level:'基础', options:['inline','block','inline-block','none'], answer:1, explain:'block元素独占一行，可设宽高；inline不换行，宽高无效。'},
{q:'display: inline-block的特点是？', level:'基础', options:['独占一行','可设宽高且不换行','完全隐藏','清除浮动'], answer:1, explain:'inline-block结合inline和block特点：不换行但可设置宽高。'},
{q:'display: none与visibility: hidden的区别是？', level:'基础', options:['无区别','none不占空间，hidden占空间','none占空间，hidden不占','都占空间'], answer:1, explain:'display:none完全移除，不占空间；visibility:hidden隐藏但保留占位空间。'},
{q:'CSS定位中position: relative相对于谁定位？', level:'基础', options:['浏览器窗口','最近已定位祖先','自身原始位置','父元素'], answer:2, explain:'relative相对自身原本位置偏移，不脱离文档流，原位置保留。'},
{q:'position: absolute相对于谁定位？', level:'基础', options:['浏览器窗口','最近已定位的祖先元素','自身原始位置','父元素'], answer:1, explain:'absolute相对于最近非static定位的祖先，若无则相对于初始包含块。'},
{q:'position: fixed相对于谁定位？', level:'基础', options:['浏览器视口','父元素','最近已定位祖先','包含块'], answer:0, explain:'fixed固定定位，相对于浏览器视口，页面滚动时位置不变。'},
{q:'position: sticky的特点是？', level:'基础', options:['始终固定','滚动到阈值前相对，之后固定','绝对定位','浮动元素'], answer:1, explain:'sticky粘性定位：未达阈值时relative，达到阈值后fixed效果。'},
{q:'CSS浮动float会导致什么常见问题？', level:'基础', options:['元素消失','父元素高度塌陷','字体变大','颜色变深'], answer:1, explain:'浮动元素脱离文档流，父容器无其他内容时高度为0，即高度塌陷。'},
{q:'以下哪个CSS属性用于清除浮动？', level:'基础', options:['float: none','clear: both','overflow: auto','display: block'], answer:1, explain:'clear属性清除浮动，常用clear:both；也可通过overflow:hidden/BFC清除。'},
{q:'以下哪个是相对单位，相对于父元素字体大小？', level:'基础', options:['px','em','rem','vw'], answer:1, explain:'em相对于当前元素（继承）父级字体大小；rem相对于根元素html字体。'},
{q:'rem单位相对于哪个元素的字体大小？', level:'基础', options:['body','父元素','html根元素','最近的字体设置'], answer:2, explain:'rem（root em）相对于html根元素的font-size，常用于响应式。'},
{q:'1vw等于多少？', level:'基础', options:['1%视口宽度','1%视口高度','1px','1em'], answer:0, explain:'vw是视口宽度百分比，1vw=视口宽度的1%；vh是视口高度。'},
{q:'以下哪个CSS颜色值表示方式是错误的？', level:'基础', options:['#fff','rgb(255,0,0)','hsl(0,100%,50%)','color: red()'], answer:3, explain:'red是关键字不用括号；前三种都是合法CSS颜色表示方式。'},
{q:'CSS background简写属性不包含以下哪个？', level:'基础', options:['background-color','background-image','background-size','background-font'], answer:3, explain:'background简写包含color、image、position、size、repeat、origin、clip、attachment，无font。'},
{q:'以下哪个不是CSS font简写属性包含的内容？', level:'基础', options:['font-size','font-family','font-weight','font-shadow'], answer:3, explain:'font简写至少包含size和family，可含style/weight/line-height等，无shadow。'},
{q:'以下哪个CSS属性用于设置文字下划线？', level:'基础', options:['text-decoration','text-style','font-decoration','text-line'], answer:0, explain:'text-decoration: underline设置下划线；还可设overline、line-through、none。'},
{q:'CSS3 border-radius: 50%的效果是？', level:'基础', options:['50px圆角','圆形/椭圆形','没有圆角','边框加粗'], answer:1, explain:'border-radius:50%将元素变成圆形（宽高相等）或椭圆形（宽高不等）。'},
{q:'以下哪个CSS属性用于创建盒子阴影？', level:'基础', options:['text-shadow','box-shadow','shadow','element-shadow'], answer:1, explain:'box-shadow创建盒子阴影，text-shadow是文字阴影。'},
{q:'CSS3 transform: translate(10px, 20px)的作用是？', level:'基础', options:['向右10px向下20px平移','向左10px向上20px','放大10倍','旋转10度'], answer:0, explain:'translate平移，x正方向向右，y正方向向下（屏幕坐标系）。'},
{q:'CSS3 transform: rotate(45deg)表示？', level:'基础', options:['缩放45%','顺时针旋转45度','逆时针45度','倾斜45度'], answer:1, explain:'rotate正值为顺时针旋转，单位deg；skew是倾斜，scale是缩放。'},
{q:'CSS transition过渡的哪个属性指定过渡效果持续时间？', level:'基础', options:['transition-property','transition-duration','transition-timing-function','transition-delay'], answer:1, explain:'transition-duration指定过渡持续时间，如.3s；property指定哪些属性过渡。'},
{q:'CSS animation动画的哪个属性指定动画名称？', level:'基础', options:['animation-name','animation-duration','animation-name: 用@keyframes定义','animation-timing'], answer:0, explain:'animation-name绑定@keyframes定义的动画关键帧名称。'},
{q:'Flex布局中，主轴默认是什么方向？', level:'基础', options:['垂直方向','水平方向','对角线方向','无方向'], answer:1, explain:'flex默认flex-direction:row，主轴水平；column则主轴垂直。'},
{q:'Flex布局中，justify-content属性控制的是？', level:'基础', options:['交叉轴对齐','主轴对齐','换行方式','元素顺序'], answer:1, explain:'justify-content控制主轴方向的对齐；align-items控制交叉轴。'},
{q:'Flex布局中，align-items属性控制的是？', level:'基础', options:['主轴对齐','交叉轴对齐（单行）','多行交叉轴','元素增长'], answer:1, explain:'align-items控制单行项目在交叉轴的对齐；align-content控制多行。'},
{q:'CSS Grid布局中，grid-template-columns用于定义？', level:'基础', options:['行模板','列模板','区域','间距'], answer:1, explain:'grid-template-columns定义网格列的大小和数量；rows定义行。'},
{q:'BFC的全称是？', level:'基础', options:['Block Format Context','Block Formatting Context','Box Format Content','Basic Flow Context'], answer:1, explain:'BFC（Block Formatting Context）块级格式化上下文，独立渲染区域。'},
{q:'JS中声明变量不允许重复声明的关键字是？', level:'基础', options:['var','let','function','以上都可以'], answer:1, explain:'let和const不允许同作用域重复声明；var可以重复声明会覆盖。'},
{q:'var let const哪个声明的变量有块级作用域？', level:'基础', options:['var','let和const','只有let','只有var'], answer:1, explain:'let/const有块级作用域；var只有函数和全局作用域，无块级。'},
{q:'以下哪个不是JS的基本数据类型？', level:'基础', options:['string','number','array','boolean'], answer:2, explain:'array是对象（引用类型）；基本类型：string、number、boolean、null、undefined、symbol、bigint。'},
{q:'typeof null的返回值是？', level:'基础', options:['null','undefined','object','string'], answer:2, explain:'这是JS历史遗留bug，typeof null返回"object"，实际null是基本类型。'},
{q:'typeof undefined的返回值是？', level:'基础', options:['null','undefined','object','number'], answer:1, explain:'typeof undefined返回字符串"undefined"，是正确的行为。'},
{q:'instanceof运算符的作用是？', level:'基础', options:['判断类型名称','判断原型链上是否有该构造函数的prototype','判断值是否相等','判断是否为空'], answer:1, explain:'instanceof检查右侧构造函数的prototype是否在左侧对象的原型链上。'},
{q:'以下哪个数组方法会修改原数组？', level:'基础', options:['concat','slice','splice','map'], answer:2, explain:'splice修改原数组（增删）；push/pop/shift/unshift/sort/reverse也修改原数组。'},
{q:'数组方法slice(start, end)的特点是？', level:'基础', options:['修改原数组','不修改原数组，返回新数组（含end）','不修改原数组，返回新数组（不含end）','删除元素'], answer:2, explain:'slice不修改原数组，提取[start, end)左闭右开的子数组作为新数组返回。'},
{q:'数组map方法的返回值是？', level:'基础', options:['undefined','原数组','新数组（每个元素是回调返回值）','布尔值'], answer:2, explain:'map创建并返回新数组，每个元素是回调函数处理后的结果，原数组不变。'},
{q:'数组filter方法的作用是？', level:'基础', options:['映射转换','过滤满足条件的元素组成新数组','累加求和','遍历无返回'], answer:1, explain:'filter返回由满足条件（回调返回true）的元素组成的新数组，不修改原数组。'},
{q:'字符串indexOf方法的返回值表示？', level:'基础', options:['是否包含','找到的第一个索引位置，未找到返回-1','找到的个数','最后出现位置'], answer:1, explain:'indexOf返回查找值首次出现的索引，未找到返回-1；lastIndexOf是最后一次。'},
{q:'字符串split方法的作用是？', level:'基础', options:['拼接字符串','按分隔符分割为数组','截取子串','替换子串'], answer:1, explain:'split将字符串按分隔符拆分成数组；join是数组拼接成字符串。'},
{q:'substring与substr的主要区别是？', level:'基础', options:['无区别','参数：substring是[start,end)索引，substr是start+length','substr更标准','substring支持负数'], answer:1, explain:'substring(start,end)两个索引；substr(start,length)第二个是长度，已不推荐使用。'},
{q:'JS中==和===的主要区别是？', level:'基础', options:['无区别','==比较值，===比较值和类型','===比较值，==比较值和类型','===更快'], answer:1, explain:'==会强制类型转换后比较值；===严格相等，值和类型都必须相同。'},
{q:'以下哪个循环会先执行一次循环体再判断条件？', level:'基础', options:['for','while','do-while','for-in'], answer:2, explain:'do-while先执行循环体，再判断条件，至少执行一次；其他先判断。'},
{q:'箭头函数与普通函数的主要区别之一是？', level:'基础', options:['语法相同','箭头函数没有自己的this','箭头函数可以作为构造函数','箭头函数有arguments'], answer:1, explain:'箭头函数没有自己的this、arguments、super、new.target，不能用作构造函数。'},
{q:'箭头函数中的this指向？', level:'基础', options:['调用者','定义时所在作用域的this','window','undefined'], answer:1, explain:'箭头函数this是词法作用域，继承定义时外层作用域的this，且不可改变。'},
{q:'获取id为app的DOM元素，正确的方法是？', level:'基础', options:['document.querySelector("#app")','document.getElementByID("app")','document.getById("app")','document.find("#app")'], answer:0, explain:'querySelector用CSS选择器语法；注意是getElementById（大小写Id），B选项ID写错。'},
{q:'addEventListener相比onclick的优势是？', level:'基础', options:['支持多个事件监听器','更短的代码','只触发一次','支持选择器'], answer:0, explain:'addEventListener可绑定多个监听器；onclick赋值会覆盖，只有一个生效。'},
{q:'事件冒泡的传播方向是？', level:'基础', options:['从window到目标元素','从目标元素向上到window','在目标元素停留','随机方向'], answer:1, explain:'冒泡是事件从目标元素向上逐层传播到祖先；捕获是从window向下。'},
{q:'阻止事件冒泡的方法是？', level:'基础', options:['e.preventDefault()','e.stopPropagation()','e.stopBubble()','event.cancel()'], answer:1, explain:'stopPropagation()阻止冒泡/捕获传播；preventDefault()阻止默认行为。'},
{q:'事件委托的优点是？', level:'基础', options:['代码更长','减少事件绑定，动态元素也有效','事件更快','兼容性更好'], answer:1, explain:'事件委托利用冒泡，将监听器绑在父元素，适合动态元素，减少内存占用。'},
{q:'window.onload与DOMContentLoaded的区别是？', level:'基础', options:['同时触发','onload等所有资源加载完，DOMContentLoaded等DOM解析完','onload更早','都只等DOM'], answer:1, explain:'DOMContentLoaded在DOM解析完成后立即触发；load等图片、样式等全部资源加载完。'},
{q:'localStorage、sessionStorage、cookie三者共同点是？', level:'基础', options:['都存服务器','都是客户端存储','容量相同','都随请求自动发送'], answer:1, explain:'三者都在浏览器（客户端）存储；cookie会随请求发送，Web Storage不会。'},
{q:'localStorage与sessionStorage的主要区别是？', level:'基础', options:['容量不同','localStorage永久（手动删），sessionStorage关标签页即失效','API不同','localStorage存对象'], answer:1, explain:'存储期限不同：localStorage持久化，sessionStorage会话级别（同标签页）。'},
{q:'JSON.parse的作用是？', level:'基础', options:['对象转JSON字符串','JSON字符串转JS对象','JSON压缩','加密数据'], answer:1, explain:'JSON.parse将JSON格式字符串解析为JS值；JSON.stringify是JS值转JSON字符串。'},
{q:'以下哪个是宏任务（macrotask）？', level:'基础', options:['setTimeout回调','Promise.then回调','async函数await后','MutationObserver回调'], answer:0, explain:'setTimeout/setInterval/setImmediate/I/O/UI渲染是宏任务；Promise.then等是微任务。'},
{q:'Promise.then()中的回调属于？', level:'基础', options:['宏任务','微任务','同步执行','UI渲染'], answer:1, explain:'Promise.then/catch/finally、async函数内await后、queueMicrotask都是微任务。'},
{q:'以下哪个是ES6解构赋值的正确写法？', level:'基础', options:['let [a, b] = [1, 2]','let (a, b) = [1, 2]','let {a; b} = obj','let a, b = [1,2]'], answer:0, explain:'数组解构用[]，对象解构用{}如let {a, b} = obj；其他写法语法错误。'},
{q:'ES6模板字符串使用什么符号包裹？', level:'基础', options:['单引号','双引号','反引号 `','美元符号'], answer:2, explain:'反引号`包裹模板字符串，支持${expression}插值和多行字符串。'},
{q:'ES6模块中导出单个默认值使用？', level:'基础', options:['export default','export','import default','exports'], answer:0, explain:'export default导出默认值，导入可不加大括号；命名导出import需加大括号。'},
{q:'JS中，对象的__proto__和构造函数的prototype关系是？', level:'进阶', options:['完全相同','obj.__proto__ === Constructor.prototype','毫无关系','prototype是实例属性'], answer:1, explain:'实例的__proto__（隐式原型）指向其构造函数的prototype（显式原型）。'},
{q:'原型链的顶端是什么？', level:'进阶', options:['Function','Object','Object.prototype.__proto__即null','window'], answer:2, explain:'原型链末端是Object.prototype.__proto__，值为null，表示原型链到此终止。'},
{q:'以下哪种JS继承方式最优（解决了组合继承两次调用父构造函数问题）？', level:'进阶', options:['原型链继承','组合继承','寄生组合继承','原型式继承'], answer:2, explain:'寄生组合继承：用Object.create创建父原型副本再赋给子原型，避免父构造函数执行两次。'},
{q:'ES6 class extends本质上是哪种继承的语法糖？', level:'进阶', options:['原型链继承','组合继承','寄生组合继承','拷贝继承'], answer:2, explain:'ES6类继承内部实现是寄生组合继承的语法糖，但内部方法不可枚举等细节有差异。'},
{q:'闭包的定义是？', level:'进阶', options:['嵌套函数','函数及其词法环境的组合','任何函数','立即执行函数'], answer:1, explain:'闭包=函数+其定义时的词法环境，使函数可访问定义时作用域外的变量。'},
{q:'作用域链的顶端是？', level:'进阶', options:['函数作用域','全局作用域','块级作用域','eval作用域'], answer:1, explain:'作用域链从当前作用域逐级向上到全局作用域，全局是最外层作用域。'},
{q:'JS执行上下文栈的工作方式是？', level:'进阶', options:['先进先出','后进先出（栈）','随机','并发'], answer:1, explain:'执行上下文栈（调用栈）LIFO后进先出，全局上下文在栈底。'},
{q:'JS事件循环中，微任务在什么时候执行？', level:'进阶', options:['宏任务之前','每个宏任务执行完后、渲染前','渲染之后','与宏任务并行'], answer:1, explain:'每次宏任务执行完毕后，会清空当前所有微任务队列，然后才可能进行UI渲染。'},
{q:'async/await本质上是什么的语法糖？', level:'进阶', options:['setTimeout','Promise和Generator','事件监听','回调函数'], answer:1, explain:'async函数返回Promise；await相当于Promise.then的语法糖，底层基于Generator+Promise。'},
{q:'防抖（debounce）的作用是？', level:'进阶', options:['立即执行','高频事件在最后一次触发n秒后才执行','间隔n秒执行一次','降低执行精度'], answer:1, explain:'防抖：连续触发时只执行最后一次（或开头一次），适用于输入搜索等。'},
{q:'节流（throttle）的作用是？', level:'进阶', options:['只执行一次','n秒内只执行一次，稀释高频事件频率','延迟执行','快速执行'], answer:1, explain:'节流：规定时间窗口内无论触发多少次只执行一次，适用于滚动、resize等。'},
{q:'深拷贝与浅拷贝的区别是？', level:'进阶', options:['深浅一样','浅拷贝只复制引用，深拷贝递归复制所有层级','深拷贝更快','浅拷贝不能复制对象'], answer:1, explain:'浅拷贝只复制第一层属性值，嵌套对象还是同一引用；深拷贝递归复制所有层级。'},
{q:'数组扁平化[1,[2,[3]]]变为[1,2,3]，以下哪个ES2019方法可直接实现？', level:'进阶', options:['flatten()','flat(Infinity)','reduce()','toString()'], answer:1, explain:'Array.prototype.flat(depth)，flat(Infinity)可扁平化任意深度嵌套数组。'},
{q:'实现数组去重[1,2,2,3]→[1,2,3]，最简洁的ES6方法是？', level:'进阶', options:['filter+indexOf','[...new Set(arr)]','reduce','for循环'], answer:1, explain:'Set结构自动去重，展开运算符转数组，最简洁；filter+indexOf也可但更啰嗦。'},
{q:'柯里化（currying）的定义是？', level:'进阶', options:['缓存结果','将多参数函数转为一系列单参数函数的技术','延迟执行','惰性求值'], answer:1, explain:'柯里化：f(a,b,c)→f(a)(b)(c)，每次调用返回接收下一个参数的新函数。'},
{q:'正则表达式中，^和$分别代表？', level:'进阶', options:['反义、连接','行首、行尾','或、与','任意字符、结束'], answer:1, explain:'^匹配字符串开头，$匹配字符串结尾；[^abc]是字符类取反，不要混淆。'},
{q:'正则表达式中，.默认情况下不匹配什么？', level:'进阶', options:['数字','字母','换行符','空格'], answer:2, explain:'.匹配除换行符(\n\r)外任意单字符；加s标志（dotAll）后才匹配包括换行。'},
{q:'正则贪婪匹配与非贪婪匹配的区别是？', level:'进阶', options:['无区别','贪婪尽可能多匹配，非贪婪（量词后加?）尽可能少匹配','非贪婪更快','贪婪匹配失败'], answer:1, explain:'量词默认贪婪(*+{})；其后加?变成非贪婪，满足条件的最短匹配。'},
{q:'正则反向引用\1的作用是？', level:'进阶', options:['引用第一个字符','引用第1个捕获组匹配的内容','回溯','替换'], answer:1, explain:'\1引用正则中第1个括号(捕获组)匹配到的相同内容，常用于查找重复字符。'},
{q:'以下哪个条件不能触发BFC？', level:'进阶', options:['overflow: hidden','display: inline-block','float: left','position: static'], answer:3, explain:'position:static是默认值不触发BFC；非static、overflow非visible、float、flex item等可触发。'},
{q:'BFC的一个典型应用是？', level:'进阶', options:['动画效果','清除浮动、阻止margin合并','字体渲染','响应式布局'], answer:1, explain:'BFC内部元素不影响外部；可以包含浮动（清除塌陷）、阻止相邻margin合并。'},
{q:'Flex布局中flex-wrap: wrap的作用是？', level:'进阶', options:['反向排列','空间不足时换行','等分空间','元素排序'], answer:1, explain:'flex-wrap:wrap允许项目在主轴空间不够时换行；nowrap是默认不换行压缩。'},
{q:'CSS中var()函数的作用是？', level:'进阶', options:['创建变量','引用自定义属性（CSS变量）','定义函数','计算值'], answer:1, explain:'CSS变量用--name: value定义，用var(--name)引用，配合JS可实现主题切换等。'},
{q:'CSS @supports的作用是？', level:'进阶', options:['支持旧浏览器','特性检测，浏览器支持某CSS特性时才应用样式','打印样式','媒体查询'], answer:1, explain:'@supports是CSS特性查询，用于渐进增强，类似Modernizr但原生CSS级。'},
{q:'CSS @media print用于？', level:'进阶', options:['屏幕显示','打印样式','投影仪','手机'], answer:1, explain:'@media print匹配打印场景，可设置打印时隐藏导航、调整字号、分页等。'},
{q:'CSS计数器counter需要配合哪两个属性？', level:'进阶', options:['counter-reset + counter-increment','counter-start + counter-add','count + number','index + step'], answer:0, explain:'counter-reset创建/重置计数器；counter-increment递增；counter()/counters()显示值。'},
{q:'CSS shape-outside的作用是？', level:'进阶', options:['绘制形状','让文字围绕非矩形（圆形/多边形/图片）形状环绕','创建梯形','裁剪元素'], answer:1, explain:'shape-outside定义浮动元素的文字环绕形状（非常规矩形），常配合clip-path。'},
{q:'CSS clip-path的作用是？', level:'进阶', options:['裁剪元素显示区域','背景裁剪','阴影裁剪','边框裁剪'], answer:0, explain:'clip-path创建裁剪区域，只有区域内的元素内容可见，可做各种几何形状。'},
{q:'CSS filter滤镜不包括以下哪个效果？', level:'进阶', options:['blur模糊','grayscale灰度','invert反色','rotate旋转'], answer:3, explain:'filter处理视觉效果：blur/grayscale/brightness等；rotate是transform的功能。'},
{q:'backdrop-filter与filter的区别是？', level:'进阶', options:['无区别','filter作用元素自身，backdrop-filter作用元素下方背景','语法不同','兼容相同'], answer:1, explain:'backdrop-filter对元素背后（下方）的内容应用滤镜，自身常配合半透明背景。'},
{q:'CSS will-change的作用是？', level:'进阶', options:['强制动画','提前告知浏览器元素将变化的属性，做好优化准备','定义动画时长','延迟变化'], answer:1, explain:'will-change提示浏览器提前为指定属性变化做GPU层等优化，但不可滥用。'},
{q:'CSS contain属性的目的是？', level:'进阶', options:['包含浮动','布局隔离，子元素变化不影响外部，提升渲染性能','内容裁剪','尺寸限制'], answer:1, explain:'contain告诉浏览器子元素的布局/绘制等不影响外部，浏览器可独立渲染优化。'},
{q:'Vue中computed与watch的区别是？', level:'进阶', options:['相同','computed有缓存依赖响应式数据，watch用于副作用异步操作','watch有缓存','computed不能get/set'], answer:1, explain:'computed：依赖变化才重算，有缓存，必须return；watch监听变化执行副作用，支持异步。'},
{q:'Vue nextTick的作用是？', level:'进阶', options:['下一秒执行','在下次DOM更新循环结束后执行回调，获取更新后DOM','异步请求','下一轮事件循环'], answer:1, explain:'Vue异步更新DOM，nextTick确保回调在DOM批量更新完毕后执行，可拿到最新DOM。'},
{q:'Vue3中defineProps的作用是？', level:'进阶', options:['定义方法','在<script setup>中声明组件接收的props','定义全局变量','定义emit'], answer:1, explain:'defineProps是<script setup>的编译宏，用于声明组件props；defineEmits声明事件。'},
{q:'虚拟DOM中key的作用是？', level:'进阶', options:['美观','diff算法中识别节点身份，最大化复用减少DOM操作','绑定事件','样式钩子'], answer:1, explain:'key给vnode打上唯一标识，diff时同层级同key才复用，避免不必要的创建/复用错误。'},
{q:'React useEffect、useMemo、useCallback的描述，错误的是？', level:'进阶', options:['useEffect副作用','useMemo缓存计算结果值','useCallback缓存函数引用','三者功能相同'], answer:3, explain:'三者不同：useEffect副作用；useMemo(fn,[])=fn()的值缓存；useCallback(fn,[])=fn函数引用缓存。'},
{q:'React类组件生命周期中，组件首次挂载完成后调用的是？', level:'进阶', options:['componentWillMount','componentDidMount','componentDidUpdate','componentWillUnmount'], answer:1, explain:'componentDidMount在组件挂载到DOM后执行一次，适合订阅、请求；WillMount已废弃。'},
{q:'Pinia相比Vuex的主要变化之一是？', level:'进阶', options:['无变化','去掉了mutations，更简洁，更好TS支持','多了modules','必须用namespaced'], answer:1, explain:'Pinia去掉mutations、更好TS支持、模块化更自然、devtools集成，是Vue官方推荐。'},
{q:'Redux三大原则不包括？', level:'进阶', options:['单一store','state只读','纯函数reducer修改','异步请求在reducer中'], answer:3, explain:'Redux三原则：单一数据源、state只读、纯函数reducer；异步用中间件thunk/saga，不在reducer。'},
{q:'TypeScript中interface和type别名的主要区别是？', level:'进阶', options:['完全相同','interface可声明合并，type不行；type可表达联合/交叉/映射类型等更多类型','type更优','interface不能扩展'], answer:1, explain:'interface支持合并声明、extends/implements；type支持联合、交叉、元组、条件类型、映射类型等。'},
{q:'TS泛型的主要作用是？', level:'进阶', options:['定义任意类型','在定义时不指定具体类型，使用时才确定，实现类型复用与约束','声明变量','类型检查关闭'], answer:1, explain:'泛型<T>提供类型层面的参数化，让函数/类/接口在多种类型下复用同时保持类型安全。'},
{q:'Webpack核心概念中loader的作用是？', level:'进阶', options:['打包输出','转换非JS模块（如TS/CSS/图片）为JS可处理的模块','插件扩展','入口文件'], answer:1, explain:'Webpack默认只认识JS/JSON；loader让它能处理其他资源；plugin处理更广的打包流程任务。'},
{q:'Webpack Plugin与Loader的区别是？', level:'进阶', options:['相同','Loader转换特定文件；Plugin基于钩子机制在打包各阶段做更广泛的任务','Plugin处理文件','Loader处理流程'], answer:1, explain:'Loader文件级转换（require时）；Plugin贯穿整个打包生命周期（打包优化、资源管理、注入等）。'},
{q:'webpack-dev-server proxy的作用是？', level:'进阶', options:['反向代理，解决开发环境跨域','部署','缓存','压缩'], answer:0, explain:'开发服务器代理：浏览器请求同源dev server，由它转发到真实后端，绕过浏览器CORS限制。'},
{q:'Tree Shaking的作用是？', level:'进阶', options:['删除代码','基于ES模块静态结构，移除未使用的导出代码（dead code）','压缩代码','拆分代码'], answer:1, explain:'Tree Shaking：标记未引用的export，打包时移除；需ES Module（import/export）+生产模式。'},
{q:'Code Splitting代码分割的目的是？', level:'进阶', options:['美化代码','按需加载/拆分成多个bundle，减少首屏加载体积','加密代码','合并文件'], answer:1, explain:'代码分割：按路由/动态import/公共依赖拆分包，首屏只加载必要的，性能优化。'},
{q:'HMR热模块替换的核心特点是？', level:'进阶', options:['刷新整页','不刷新整个页面，只替换变更的模块，保留应用状态','自动部署','热部署服务器'], answer:1, explain:'Hot Module Replacement：webpack-dev-server核心，修改代码局部更新，开发体验大幅提升。'},
{q:'Vite为什么启动快？', level:'进阶', options:['用了Webpack','开发时基于浏览器原生ES Module，按需编译，不打包','预打包依赖更快','用了缓存'], answer:1, explain:'Vite开发模式不打包全部源码，利用原生ESM按需请求即时编译；只有第三方依赖用esbuild预构建。'},
{q:'ESLint的作用是？', level:'进阶', options:['打包代码','代码静态检查，发现语法/风格问题并可自动修复','运行测试','编译TS'], answer:1, explain:'ESLint是JS/TS Linter，静态分析代码找问题，支持规则自定义和autofix；Prettier负责格式化。'},
{q:'Event Loop与浏览器渲染帧（60fps）的关系，正确的是？', level:'高级', options:['每轮事件循环必渲染','每轮宏任务+清空微任务后，浏览器自行决定是否渲染（通常与屏幕刷新同步）','渲染在微任务前','渲染在宏任务前'], answer:1, explain:'规范：每轮tick（宏任务+微任务队列清空）后，浏览器判断是否需要更新渲染，通常16.6ms一帧对齐刷新。'},
{q:'requestIdleCallback的执行时机是？', level:'高级', options:['每帧必须执行','浏览器一帧剩余空闲时间（deadline>0），优先级低可被推迟','宏任务','微任务'], answer:1, explain:'rIC利用帧间空闲时间执行低优先级任务，避免影响动画/输入；有timeout可兜底触发。'},
{q:'IntersectionObserver最适合用于？', level:'高级', options:['精确布局计算','异步监听目标元素与祖先/视口的交叉状态变化（懒加载、无限滚动）','动画','事件绑定'], answer:1, explain:'IO是高性能异步监听相交比，不用循环getBoundingClientRect，适合懒加载、曝光统计、吸顶等。'},
{q:'MutationObserver监听的是？', level:'高级', options:['事件','DOM树变化（属性/子节点/文本）','滚动','尺寸'], answer:1, explain:'MO异步监听DOM变动（属性增减、子节点增删、文本变化等），微任务级别触发。'},
{q:'ResizeObserver的作用是？', level:'高级', options:['监听window resize','监听单个元素的content box/border box尺寸变化','监听字体大小','监听滚动'], answer:1, explain:'RO监听特定元素尺寸变化，比window resize精准，不冒泡，处理响应式组件边界情况。'},
{q:'PerformanceObserver的作用是？', level:'高级', options:['发送性能数据','订阅不同的性能指标条目（如LCP/FCP/LongTask等）并异步回调处理','测量时间','监控内存'], answer:1, explain:'PO通过observe(entryTypes)订阅PerformanceEntry，集中处理各类性能指标，是RUM采集核心API。'},
{q:'Long Task的定义是？', level:'高级', options:['>50ms','>100ms','超过50ms占用主线程且不可中断的任务，会阻塞交互响应','网络请求长'], answer:2, explain:'RAIL模型：>50ms的任务视为Long Task，应chunk拆分，否则用户感知卡顿。'},
{q:'Svelte的核心编译原理是？', level:'高级', options:['运行时Virtual DOM','编译期将组件转换为命令式DOM操作代码，无runtime虚拟DOM开销','JIT编译','解释执行'], answer:1, explain:'Svelte是编译器框架，构建时分析模板生成直接操作DOM的极小JS，无VD运行时负担。'},
{q:'Virtual DOM真正的开销在于？', level:'高级', options:['创建JS对象','diff比较本身+可能多余的DOM操作，以及内存中VD树的维护成本','渲染图像','CSS计算'], answer:1, explain:'VD好处是跨平台/心智模型简单；开销：组件render重新创建VD、diff递归对比、不可避免仍会有DOM操作。'},
{q:'React Fiber架构的核心目标是？', level:'高级', options:['更快diff','将渲染工作分片（时间切片），可被中断，让浏览器高优先级任务（输入/动画）不被阻塞','服务端渲染','简化组件'], answer:1, explain:'Fiber链表结构+优先级调度，实现协调阶段可中断/可恢复，避免长时间阻塞主线程造成的掉帧。'},
{q:'React Server Components（RSC）的核心是？', level:'高级', options:['SSR','部分组件仅在服务器渲染，不打包到客户端bundle，直接序列化结果+可能流式传输','CSR','SPA'], answer:1, explain:'RSC：标记为Server的组件不在客户端执行，服务器渲染输出（非HTML而是特殊格式），减少客户端JS体积。'},
{q:'Streaming SSR的核心优势？', level:'高级', options:['一次性发送完整HTML','服务器边渲染边分块（chunked transfer）发送HTML，客户端逐步显示减少TTFB和FCP','节省带宽','缓存容易'], answer:1, explain:'流式SSR：渲染一点flush一点，浏览器不用等全量HTML就可解析渲染首屏，交互也更早。'},
{q:'Hydration（注水）的正确理解是？', level:'高级', options:['再次渲染HTML','客户端接管SSR已生成的静态HTML DOM，附加事件监听器和状态，使页面变为交互式','压缩HTML','缓存DOM'], answer:1, explain:'脱水（服务端生成HTML+数据序列化）→注水（客户端匹配DOM树、绑定事件、恢复Vine状态，让页面可交互）。'},
{q:'Qwik的核心思想可恢复性（Resumability）是？', level:'高级', options:['直接Hydration','不做全量Hydration，通过序列化框架状态+懒加载处理程序，点击时才执行对应代码，实现0 JS启动','离线优先','缓存优先'], answer:1, explain:'Qwik打破传统Hydration模式：首屏HTML携带序列化状态，交互时按需恢复执行对应组件代码，极致减少启动JS。'},
{q:'Stale-While-Revalidate缓存策略是指？', level:'高级', options:['直接用缓存','先返回过期但新鲜的缓存给用户，同时后台异步重新验证更新缓存，下次生效','每次都请求','永不更新'], answer:1, explain:'SWR（HTTP Cache-Control扩展/前端库名）：优先读取缓存立即响应，异步请求更新，兼顾速度与新鲜度。'},
{q:'Cache-Control: no-store与no-cache区别是？', level:'高级', options:['相同','no-store完全禁止任何缓存；no-cache可存但每次使用前必须向源站验证（304）','no-store存中间缓存','no-cache不存'], answer:1, explain:'no-store不写入也不读取；no-cache可本地存储但须先与服务器验证（with ETag/Last-Modified），不是不缓存。'},
{q:'ETag相比Last-Modified做304的优势是？', level:'高级', options:['相同','ETag是内容指纹（字节级变化）精度高；Last-Modified只到秒且文件内容改回旧时间戳不变会误判','ETag更大','Last-Modified更准'], answer:1, explain:'ETag基于内容哈希，不受修改时间、服务器集群差异影响；但有强弱ETag之分，计算有开销。'},
{q:'Critical CSS的核心思想是？', level:'高级', options:['把所有CSS内联','提取首屏渲染必需的CSS内联到HTML，剩余CSS异步加载，避免外部CSS阻塞渲染','压缩CSS','拆分CSS'], answer:1, explain:'首屏关键路径：内嵌首屏必要样式，减少外部CSS请求阻塞，加快FCP/LCP；非首屏CSS延迟加载。'},
{q:'字体FOIT vs FOUT的区别是？', level:'高级', options:['相同','FOIT：字体加载完前文本不可见空白；FOUT：先用系统字体显示后再切换为webfont闪烁','FOIT更好','FOUT不显示'], answer:1, explain:'FOIT(Flash Of Invisible Text) 空白→字体；FOUT(Flash Of Unstyled Text) 替代字体→webfont；font-display控制策略。'},
{q:'font-display: swap的作用是？', level:'高级', options:['立即不显示','先用fallback字体立即显示文本（无空白），webfont加载完再交换，避免FOIT','不加载字体','系统字体'], answer:1, explain:'swap策略：极短阻塞期后如未加载好，先显示后备字体，字体就绪后替换，提升用户感知性能。'},
{q:'Brotli与gzip压缩相比，正确的是？', level:'高级', options:['完全相同','Brotli在常见级别下压缩率更高（-11级最大），浏览器端解压快，需HTTPS且服务器支持','gzip永远更好','Brotli慢'], answer:1, explain:'Brotli对文本文件（HTML/CSS/JS）压缩比gzip高15-25%左右，现代浏览器已普遍支持；级别要平衡CPU。'},
{q:'HTTP/3 QUIC的0-RTT特点是？', level:'高级', options:['无延迟','连接复用时，之前协商好密钥，首个数据包就可携带HTTP数据，减少握手RTT；有重放攻击风险需谨慎','0安全','0数据'], answer:1, explain:'QUIC 0-RTT在会话复用时消除握手往返；但可能被重放，仅用于幂等请求（GET），非幂等POST需禁用。'},
{q:'Preload、Prefetch、Preconnect、DNS-Prefetch按优先级从高到低？', level:'高级', options:['都一样','Preload(当前页必需高优) > Preconnect(提前连) > DNS-Prefetch > Prefetch(下页闲时)','Prefetch最高','Preconnect最高'], answer:1, explain:'Preload当前导航必须资源，立即下载；Preconnect提前DNS/TCP/TLS握手；DNS-Prefetch只DNS；Prefetch下页资源闲时拉取。'},
{q:'Service Worker缓存策略Cache-First适合？', level:'高级', options:['所有请求','构建产物（带hash）等稳定不常变的静态资源，命中缓存即用否则回源网络','API请求','HTML文档'], answer:1, explain:'Cache-First：尽可能从缓存取，极快；适合有指纹（版本hash）的资源；HTML/API通常用Network-First或SWR。'},
{q:'子资源完整性SRI（Subresource Integrity）是？', level:'高级', options:['签名','通过<script integrity="sha256-xxx">对CDN等第三方资源做哈希校验，被篡改则拒绝执行，防供应链攻击','压缩','缓存'], answer:1, explain:'SRI=算法(hash内容base64)，浏览器下载资源后重新哈希对比，不匹配拒绝执行，是重要的第三方依赖防护措施。'}
]